Repository haskell/cabal, pull requests merged in 2018-03, with the labels that each got.

#5175 cross compile exe extension
  Cabal/Distribution/Simple/Bench.hs
  Cabal/Distribution/Simple/Build.hs
  Cabal/Distribution/Simple/BuildPaths.hs
  Cabal/Distribution/Simple/GHC.hs
  Cabal/Distribution/Simple/GHCJS.hs
  Cabal/Distribution/Simple/JHC.hs
  Cabal/Distribution/Simple/LHC.hs
  Cabal/Distribution/Simple/Test/ExeV10.hs
  Cabal/Distribution/Simple/Test/LibV09.hs
  cabal-install/Distribution/Client/Install.hs
  cabal-install/Distribution/Client/Run.hs
  cabal-install/Distribution/Client/SetupWrapper.hs
  cabal-testsuite/PackageTests/InternalLibraries/Executable/setup-static.test.hs
Labels: blocked: action-required

#5188 Fix new-install symlink location
  cabal-install/Distribution/Client/CmdInstall.hs
  cabal-install/Distribution/Client/Config.hs
  cabal-install/changelog
Labels: cabal-install: nix-local-build

#5117 Add more lenses for PackageDescription and GenericPackageDescription
  Cabal/Distribution/PackageDescription/Check.hs
  Cabal/Distribution/PackageDescription/Configuration.hs
  Cabal/Distribution/Types/BuildInfo/Lens.hs
  Cabal/Distribution/Types/CondTree.hs
  Cabal/Distribution/Types/GenericPackageDescription.hs
  Cabal/Distribution/Types/GenericPackageDescription/Lens.hs
  Cabal/Distribution/Types/PackageDescription.hs
Labels: after-2.2-release, blocked: action-required

#5197 Fix powershell transport
  appveyor.yml
  cabal-install/Distribution/Client/HttpUtils.hs
Labels: platform: windows, type: bug

#5166 Enforce the backjump limit before creating the solver log.
  cabal-install/Distribution/Solver/Modular.hs
  cabal-install/Distribution/Solver/Modular/Explore.hs
  cabal-install/Distribution/Solver/Modular/Log.hs
  cabal-install/Distribution/Solver/Modular/Message.hs
  cabal-install/Distribution/Solver/Modular/Solver.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL/TestCaseUtils.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
  cabal-testsuite/PackageTests/BuildTargets/UseLocalPackage/use-local-version-of-package.out
  cabal-testsuite/PackageTests/InternalVersions/BuildDependsBad/setup.cabal.out
Labels: after-2.2-release, cabal-install: solver

#5221 add support for the aarch64 architecture
  Cabal/Distribution/Simple/PreProcess.hs
  Cabal/Distribution/System.hs
Labels: type: enhancement

#5246 new-install docs
  Cabal/doc/nix-local-build.rst
Labels: cabal-install: nix-local-build, documentation

#5244 Use GHC 8.2.2 and new-build for solver-debug-flags Travis job
  .travis.yml
  travis-solver-debug-flags.sh
Labels: continuous-integration
