Repository haskell/cabal, pull requests merged in 2020-09, with the labels that each got.

#7023 Fix #7019: GHC-8.12 is GHC-9.0
  Cabal/src/Distribution/Simple/GHC.hs
  Cabal/src/Distribution/Simple/Program/GHC.hs
  Cabal/tests/UnitTests/Distribution/Simple/Program/GHC.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
Labels: attention: needs-backport

#7024 Use optparse-applicative-0.16
  Cabal/Cabal.cabal
  cabal-dev-scripts/cabal-dev-scripts.cabal
  cabal-testsuite/cabal-testsuite.cabal
Labels: attention: needs-backport

#7004 Bump process version required for job support to 1.6.9
  Cabal/src/Distribution/Compat/Process.hs
Labels: attention: needs-backport

#7025 Fix #7007: RemoteSourceRepoPackage location is of .tar.gz
  cabal-install/src/Distribution/Client/CmdSdist.hs
Labels: attention: needs-backport, cabal-install: cmd/sdist

#7030 Fix #7028. Use cwd when looking for data-files in sdist
  Cabal/src/Distribution/Simple/SrcDist.hs
  cabal-testsuite/PackageTests/SDist/T7028/cabal.out
  cabal-testsuite/PackageTests/SDist/T7028/cabal.project
  cabal-testsuite/PackageTests/SDist/T7028/cabal.test.hs
  cabal-testsuite/PackageTests/SDist/T7028/pkg/Main.hs
  cabal-testsuite/PackageTests/SDist/T7028/pkg/data.txt
  cabal-testsuite/PackageTests/SDist/T7028/pkg/t7028.cabal
Labels: attention: needs-backport

#7032 Improve Arbitrary VersionRange
  Cabal/Cabal-QuickCheck/src/Test/QuickCheck/Instances/Cabal.hs
Labels: attention: needs-backport

#7037 Simpler prettyVersionRange
  Cabal/src/Distribution/Types/VersionRange/Internal.hs
Labels: attention: needs-backport

#7041 Fix #7039: Use flagIgnoreProject in CmdRepl
  cabal-install/src/Distribution/Client/CmdRepl.hs
Labels: attention: needs-backport

#7049 Data.ByteString.Lazy.Builder -> Data.ByteString.Builder
  Cabal/src/Distribution/Utils/Structured.hs
Labels: attention: needs-backport

#7050 Fix #6998. Mark ghc-bignum as non-upgradable package
  cabal-install/src/Distribution/Client/Dependency.hs
Labels: attention: needs-backport

#7072 Pass -optcxx for GHC >= 8.10
  Cabal/src/Distribution/Simple/Program/GHC.hs
  cabal-testsuite/PackageTests/FFI/ForeignOptsC/Main.hs
  cabal-testsuite/PackageTests/FFI/ForeignOptsC/README.md
  cabal-testsuite/PackageTests/FFI/ForeignOptsC/cabal.out
  cabal-testsuite/PackageTests/FFI/ForeignOptsC/cabal.project
  cabal-testsuite/PackageTests/FFI/ForeignOptsC/cabal.test.hs
  cabal-testsuite/PackageTests/FFI/ForeignOptsC/cbits/clib.c
  cabal-testsuite/PackageTests/FFI/ForeignOptsC/cbits/clib.h
  cabal-testsuite/PackageTests/FFI/ForeignOptsC/foreign-opts-c.cabal
  cabal-testsuite/PackageTests/FFI/ForeignOptsCxx/Main.hs
  cabal-testsuite/PackageTests/FFI/ForeignOptsCxx/README.md
  cabal-testsuite/PackageTests/FFI/ForeignOptsCxx/cabal.out
  cabal-testsuite/PackageTests/FFI/ForeignOptsCxx/cabal.project
  cabal-testsuite/PackageTests/FFI/ForeignOptsCxx/cabal.test.hs
  cabal-testsuite/PackageTests/FFI/ForeignOptsCxx/cxxbits/cxxlib.cpp
  cabal-testsuite/PackageTests/FFI/ForeignOptsCxx/cxxbits/cxxlib.h
  cabal-testsuite/PackageTests/FFI/ForeignOptsCxx/foreign-opts-cxx.cabal
Labels: attention: needs-backport 3.2, attention: needs-backport 3.4

#7093 Resolve #7091: Require custom-setup for cabal-version: 1.24 and later
  Cabal/src/Distribution/PackageDescription/Parsec.hs
  Cabal/tests/ParserTests/regressions/mixin-1.cabal
  Cabal/tests/ParserTests/regressions/mixin-1.expr
  Cabal/tests/ParserTests/regressions/mixin-1.format
Labels: attention: needs-backport 3.2, attention: needs-backport 3.4
