Repository haskell/cabal, pull requests merged in 2020-05, with the labels that each got.

#6745 Make NixStyleOptions
  cabal-install/Distribution/Client/CmdHaddock.hs
  cabal-install/Distribution/Client/CmdInstall.hs
  cabal-install/Distribution/Client/CmdRepl.hs
  cabal-install/Distribution/Client/CmdRun.hs
  cabal-install/Distribution/Client/NixStyleOptions.hs
  cabal-install/cabal-install.cabal
  cabal-install/cabal-install.cabal.pp
Labels: cabal-install: other, type: refactor

#6746 Internal refactorings to install command.
  cabal-install/Distribution/Client/CmdInstall.hs
Labels: cabal-install: cmd/install, type: refactor

#6761 cabal init not interactive by default in 3.0
  Cabal/doc/developing-packages.rst
Labels: documentation

#6826 Prepend hs-source-dir to match-component
  Cabal/doc/cabal-commands.rst
  cabal-install/Distribution/Client/TargetSelector.hs
  cabal-install/cabal-install.cabal
  cabal-install/cabal-install.cabal.pp
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/IntegrationTests2/targets/simple/app/Main.hs
  cabal-install/tests/IntegrationTests2/targets/simple/p.cabal
  cabal-install/tests/IntegrationTests2/targets/simple/q/Q.hs
  cabal-install/tests/IntegrationTests2/targets/simple/q/q.cabal
Labels: attention: needs-backport

#6827 Update dependency bounds
  Cabal/Cabal-QuickCheck/Cabal-QuickCheck.cabal
  Cabal/Cabal.cabal
  cabal-install/cabal-install.cabal
  cabal-install/cabal-install.cabal.pp
  cabal-install/tests/UnitTests/Distribution/Client/GenericInstances.hs
  cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
  cabal-install/tests/UnitTests/Distribution/Client/TreeDiffInstances.hs
Labels: attention: needs-backport
