Repository haskell/cabal, pull requests merged in 2021-08, with the labels that each got.

#7503 set package index asserts expensive
  cabal-install-solver/src/Distribution/Solver/Types/PackageIndex.hs
Labels: type: performance

#7508 Bump Project Versions to 3.6
  .docker/validate-8.10.4.dockerfile
  .docker/validate-8.8.4.dockerfile
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
  Cabal-QuickCheck/Cabal-QuickCheck.cabal
  Cabal-described/Cabal-described.cabal
  Cabal-tests/Cabal-tests.cabal
  Cabal-tree-diff/Cabal-tree-diff.cabal
  Cabal/Cabal.cabal
  Cabal/Makefile
  Makefile
  appveyor.yml
  bootstrap/linux-8.10.4.json
  bootstrap/linux-8.10.4.plan.json
  bootstrap/linux-8.6.5.json
  bootstrap/linux-8.6.5.plan.json
  bootstrap/linux-8.8.4.json
  bootstrap/linux-8.8.4.plan.json
  cabal-benchmarks/cabal-benchmarks.cabal
  cabal-dev-scripts/src/GenValidate.hs
  cabal-dev-scripts/src/GenValidateDockerfile.hs
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/Utils.hs
  cabal-testsuite/cabal-testsuite.cabal
  doc/conf.py
  templates/ci-windows.template.yml
  vendor/cabal-doctest-1.0.8/cabal-doctest.cabal
Labels: priority: high :fire:, continuous-integration, release

#7516 lazily decode cache files for checking invalidation
  Cabal/src/Distribution/Utils/Structured.hs
  cabal-install/src/Distribution/Client/FileMonitor.hs
Labels: type: performance

#7490 Attempt to speed solving when test is enable projectwide
  cabal-install-solver/src/Distribution/Solver/Modular/Preference.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
Labels: cabal-install: solver

#7486 Mention that multiple changelog entries per pr are fine
  CONTRIBUTING.md
Labels: documentation, merge me

#7533 add traverseWithKey to cabal-install-solver
  cabal-install-solver/src/Distribution/Solver/Modular/WeightedPSQ.hs
Labels: merge me

#7519 solver: swap catas with recursion, fuse travs
  cabal-install-solver/src/Distribution/Solver/Modular/Cycles.hs
  cabal-install-solver/src/Distribution/Solver/Modular/Explore.hs
  cabal-install-solver/src/Distribution/Solver/Modular/Linking.hs
  cabal-install-solver/src/Distribution/Solver/Modular/Preference.hs
  cabal-install-solver/src/Distribution/Solver/Modular/Solver.hs
  cabal-install-solver/src/Distribution/Solver/Modular/Tree.hs
  cabal-install-solver/src/Distribution/Solver/Modular/Validate.hs
  cabal-install-solver/src/Distribution/Solver/Modular/WeightedPSQ.hs
Labels: cabal-install: solver, type: performance, merge me

#7470 Suppress warnings for verbosity
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  Cabal/src/Distribution/PackageDescription/Check.hs
  Cabal/src/Distribution/Simple/Utils.hs
  Cabal/src/Distribution/Verbosity.hs
  Cabal/src/Distribution/Verbosity/Internal.hs
  cabal-testsuite/PackageTests/Backpack/Includes2/cabal-internal.out
  cabal-testsuite/PackageTests/BuildDeps/InternalLibrary1/cabal.out
  cabal-testsuite/PackageTests/BuildTools/Internal/cabal.out
  cabal-testsuite/PackageTests/CmmSources/cabal.out
  cabal-testsuite/PackageTests/CmmSourcesDyn/cabal.out
  cabal-testsuite/PackageTests/InternalLibraries/cabal.out
  cabal-testsuite/PackageTests/InternalVersions/BuildDependsExtra/setup.test.hs
  cabal-testsuite/PackageTests/InternalVersions/BuildToolDependsExtra/setup.test.hs
  cabal-testsuite/PackageTests/InternalVersions/BuildToolsExtra/setup.test.hs
  cabal-testsuite/PackageTests/MultipleLibraries/T6083Post/cabal.out
  cabal-testsuite/PackageTests/MultipleLibraries/T6083PostMixin/cabal.out
  cabal-testsuite/PackageTests/MultipleLibraries/T6894/cabal.out
  cabal-testsuite/PackageTests/Regression/T5213/cabal.out
  cabal-testsuite/PackageTests/Regression/T5213ExeCoverage/cabal.out
  cabal-testsuite/PackageTests/Regression/T5309/cabal.out
  cabal-testsuite/PackageTests/Regression/T5677/cabal.out
  cabal-testsuite/PackageTests/TestSuiteTests/ExeV10/cabal.out
  changelog.d/pr-7470
  changelog.d/pr-7470-backport
Labels: merge me

#7453 Wordier explanation of the "active-repositories:" configuration field.
  doc/cabal-project.rst
Labels: merge me

#7479 Properly link filename compatibility checks into `cabal check`
  Cabal-tests/tests/ParserTests/regressions/assoc-cpp-options.check
  Cabal-tests/tests/ParserTests/regressions/denormalised-paths.cabal
  Cabal-tests/tests/ParserTests/regressions/denormalised-paths.check
  Cabal-tests/tests/ParserTests/regressions/extensions-paths-5054.check
  Cabal/src/Distribution/PackageDescription/Check.hs
  cabal-testsuite/PackageTests/AutogenModules/Package/setup.cabal.out
  cabal-testsuite/PackageTests/AutogenModules/Package/setup.out
  changelog.d/path-validation
  changelog.d/rel-path-check
Labels: merge me

#7552 add baseDep to simple project generation
  cabal-install/src/Distribution/Client/Init/FlagExtractors.hs
  cabal-install/src/Distribution/Client/Init/Interactive/Command.hs
  cabal-install/src/Distribution/Client/Init/Simple.hs
  cabal-install/src/Distribution/Client/Init/Utils.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/Simple.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/Utils.hs
Labels: type: bug, cabal-install: cmd/init, priority: high :fire:, attention: needs-review, merge me

#7553 Adding comment to further explain the meaning of cabal-version
  cabal-install/src/Distribution/Client/Init/Format.hs
  cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-and-exe-with-comments.golden
  cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-with-comments.golden
  cabal-install/tests/fixtures/init/golden/cabal/cabal-test-suite-with-comments.golden
  cabal-install/tests/fixtures/init/golden/pkg-desc/pkg-old-cabal-with-flags.golden
  cabal-install/tests/fixtures/init/golden/pkg-desc/pkg-with-comments.golden
  cabal-install/tests/fixtures/init/golden/pkg-desc/pkg-with-flags.golden
  cabal-install/tests/fixtures/init/golden/pkg-desc/pkg.golden
Labels: merge me

#7550 Add --open flag to `cabal haddock`
  cabal-install/src/Distribution/Client/CmdHaddock.hs
  cabal-install/src/Distribution/Client/ProjectBuilding.hs
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Types.hs
  cabal-install/src/Distribution/Client/Utils.hs
  changelog.d/pr-7550
  doc/cabal-project.rst
Labels: cabal-install: cmd/haddock, merge me

#7563 add changelog for cabal-install-3.6.0.0
  cabal-install/changelog
  release-notes/cabal-install-3.6.0.0.md
Labels: attention: needs-review, 3.6

#7578 Add '--repl-no-load' option to skip module load in REPL
  Cabal/src/Distribution/Simple/Build.hs
  Cabal/src/Distribution/Simple/GHC.hs
  Cabal/src/Distribution/Simple/Setup.hs
  cabal-install/src/Distribution/Client/CmdRepl.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/ProjectPlanning/Types.hs
  cabal-testsuite/PackageTests/ReplNoLoad/ModuleA.hs
  cabal-testsuite/PackageTests/ReplNoLoad/ModuleB.hs
  cabal-testsuite/PackageTests/ReplNoLoad/ModuleC.hs
  cabal-testsuite/PackageTests/ReplNoLoad/cabal-repl-no-load.cabal
  cabal-testsuite/PackageTests/ReplNoLoad/cabal.exec-no-load.out
  cabal-testsuite/PackageTests/ReplNoLoad/cabal.exec-normal.out
  cabal-testsuite/PackageTests/ReplNoLoad/cabal.lib-no-load.out
  cabal-testsuite/PackageTests/ReplNoLoad/cabal.lib-normal.out
  cabal-testsuite/PackageTests/ReplNoLoad/cabal.project
  cabal-testsuite/PackageTests/ReplNoLoad/cabal.test.hs
  cabal-testsuite/src/Test/Cabal/Monad.hs
  changelog.d/issue-7541
  doc/cabal-commands.rst
Labels: merge me

#7586 Fix #7469: broken link to "prefix independence" in docs
  doc/cabal-package.rst
Labels: documentation, merge me

#7585 Fix #7582: add Ord to the derived instances of SymbolicPath
  Cabal/src/Distribution/Utils/Path.hs
Labels: attention: needs-review

#7591 Change mentions of "overwrite" to "backup"
  changelog.d/pr-7402
  doc/cabal-commands.rst
Labels: merge me

#7588 README: replace broken travis badge by representative GHA badge
  README.md
Labels: documentation, merge me

#7592 ci(Mergify): use rebase+merge queue
  .github/mergify.yml
Labels: continuous-integration

#7584 Fix #7583: updated text for Setup.hs test/bench --help
  Cabal/src/Distribution/Simple/Setup.hs
Labels: attention: needs-review, squash+merge me, help-text
