Repository haskell/cabal, pull requests merged in 2021-11, with the labels that each got.

#7779 Re #7777 #7778: check requirements.txt for security advisory
  .github/workflows/users-guide.yml
  .gitignore
  Makefile
  doc/Makefile
  doc/pyproject.toml
  doc/requirements.in
  doc/requirements.txt
Labels: continuous-integration, merge me, re: readthedocs

#7795 Remove code duplication and unify definition of 'trim' function.
  Cabal/Cabal.cabal
  Cabal/src/Distribution/Compat/Prelude.hs
  Cabal/src/Distribution/FieldGrammar/FieldDescrs.hs
  Cabal/src/Distribution/FieldGrammar/Parsec.hs
  Cabal/src/Distribution/Simple/Configure.hs
  Cabal/src/Distribution/Simple/UHC.hs
  Cabal/src/Distribution/Utils/String.hs
  cabal-install/src/Distribution/Client/HttpUtils.hs
  cabal-install/src/Distribution/Client/Init/Utils.hs
  cabal-install/src/Distribution/Client/Upload.hs
Labels: squash+merge me

#7823 Warn about needing to opt in to overwrite-policy for install.
  doc/cabal-commands.rst
Labels: documentation, attention: needs-review, merge me

#7822 Enable TypeOperators to use (~)
  Cabal/src/Distribution/Compat/Graph.hs
  Cabal/src/Distribution/Utils/IOData.hs
Labels: merge me

#7839 Prepend library to executable deps in cabal init
  cabal-install/src/Distribution/Client/Init/Interactive/Command.hs
  cabal-install/src/Distribution/Client/Init/NonInteractive/Command.hs
  cabal-install/src/Distribution/Client/Init/Utils.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/NonInteractive.hs
Labels: merge me

#7793 Make the deps' test for `cabal init` ignore unspecified versions
  cabal-install/tests/UnitTests/Distribution/Client/Init/NonInteractive.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/Utils.hs
Labels: attention: needs-review

#7841 Update Cabal/README.md (see #7391)
  Cabal/README.md
Labels: documentation, merge me

#5672 Prompt overwrite policy
  cabal-install/src/Distribution/Client/CmdInstall.hs
  cabal-install/src/Distribution/Client/CmdInstall/ClientInstallFlags.hs
  cabal-install/src/Distribution/Client/Init/Prompt.hs
  cabal-install/src/Distribution/Client/Init/Types.hs
  cabal-install/src/Distribution/Client/InstallSymlink.hs
  cabal-install/src/Distribution/Client/Types/OverwritePolicy.hs
  changelog.d/pr-5672
Labels: attention: needs-review, cabal-install: cmd/install
