Repository haskell/cabal, pull requests merged in 2021-09, with the labels that each got.

#7564 more type annotations
  cabal-install/src/Distribution/Client/Dependency.hs
  cabal-install/src/Distribution/Client/Fetch.hs
  cabal-install/src/Distribution/Client/FetchUtils.hs
  cabal-install/src/Distribution/Client/Freeze.hs
  cabal-install/src/Distribution/Client/HttpUtils.hs
  cabal-install/src/Distribution/Client/ProjectBuilding.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/RebuildMonad.hs
  cabal-install/src/Distribution/Client/Reconfigure.hs
  cabal-install/src/Distribution/Client/SolverInstallPlan.hs
  cabal-install/src/Distribution/Client/SourceFiles.hs
  cabal-install/src/Distribution/Client/Targets.hs
  cabal-install/src/Distribution/Client/Upload.hs
  cabal-install/src/Distribution/Client/Utils.hs
  cabal-install/src/Distribution/Client/VCS.hs
  cabal-install/src/Distribution/Client/World.hs
Labels: merge me

#6474 [ci skip] Update installing-packages.rst
  doc/installing-packages.rst
Labels: attention: needs-review

#7614 don't consider test flags in reconfigure check
  cabal-install/src/Distribution/Client/ProjectBuilding.hs
Labels: type: enhancement, cabal-install: cmd/configure, merge me

#7617 remove unnecessary dotfiles, add to .gitignore
  .arcconfig
  .ghci
  .ghcid
  .gitignore
  .mention-bot
  .projectile
  .stylish-haskell.yaml
Labels: merge me

#7616 handle conditionals in duplicate module checks
  Cabal/src/Distribution/PackageDescription/Check.hs
  Cabal/src/Distribution/Types/CondTree.hs
  changelog.d/pr-7616
Labels: attention: needs-review, squash+merge me

#7624 change documented global flags
  cabal-install/src/Distribution/Client/Setup.hs
Labels: merge me

#7628 Allow text-2.0 in Cabal.cabal only
  Cabal/Cabal.cabal
Labels: merge me

#7621 Backtrack when no pkgconfigdb is present
  cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL/TestCaseUtils.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
  changelog.d/pr-7621
Labels: cabal-install: solver, attention: needs-review, squash+merge me

#7630 pipe auth into curl (v2)
  cabal-install/src/Distribution/Client/HttpUtils.hs
  changelog.d/pr-7630
Labels: attention: needs-review, squash+merge me

#7637 Fix docs
  doc/conf.py
  doc/developing-packages.rst
  doc/setup-commands.rst
Labels: attention: needs-review

#7567 handle build reports in v2-build
  cabal-install/src/Distribution/Client/BuildReports/Anonymous.hs
  cabal-install/src/Distribution/Client/ProjectOrchestration.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
Labels: cabal-install: nix-local-build, cabal-install: cmd/build, merge me

#7606 Fix mentions of overwrite and backup flags for v2-configure
  changelog.d/pr-7402
  doc/cabal-commands.rst
Labels: merge me

#7412 Pp order register
  Cabal/src/Distribution/Simple/PreProcess.hs
  cabal-testsuite/PackageTests/CustomPreProcess/Setup.hs
  changelog.d/pp-orders
Labels: attention: needs-review, squash+merge me

#7604 Additional examples in doc of `tested-with` (fix #4894)
  doc/cabal-package.rst
Labels: merge me

#7638 CI for building doc with sphinx
  .github/workflows/users-guide.yml
Labels: documentation, continuous-integration

#7310 Canonicalize path in TargetSelector to fix No Targets bug on Windows
  cabal-install/src/Distribution/Client/TargetSelector.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/IntegrationTests2/targets/symbolic-link-to-simple
Labels: platform: windows, merge me

#7572 Add file perm bits to current mode rather than overriding
  Cabal/src/Distribution/Compat/CopyFile.hs
  cabal-install/src/Distribution/Client/Compat/FilePerms.hs
  changelog.d/pr-7572
Labels: merge me

#7645 cabal-testsuite/README: typos, formatting
  cabal-testsuite/README.md
Labels: documentation, cabal-testsuite, merge me, devx

#7648 Change cabal-plan list-bin to cabal list-bin in Makefile
  Makefile
Labels: type: refactor, merge me

#7575 Restore GHCJS "-build-runner" option
  Cabal/src/Distribution/Simple/GHCJS.hs
  cabal-testsuite/PackageTests/GHCJS/BuildRunner/BuildRunner.cabal
  cabal-testsuite/PackageTests/GHCJS/BuildRunner/BuildRunner.hs
  cabal-testsuite/PackageTests/GHCJS/BuildRunner/README.md
  cabal-testsuite/PackageTests/GHCJS/BuildRunner/cabal.project
  cabal-testsuite/PackageTests/GHCJS/BuildRunner/cabal.test.hs
  cabal-testsuite/PackageTests/GHCJS/BuildRunner/scripts/fake-ghcjs.sh
  cabal-testsuite/PackageTests/GHCJS/BuildRunner/scripts/ghcjs-pkg
  changelog.d/pr-7575
Labels: attention: needs-review

#7651 Revert PR #7510 (which was "Set PATH_SEPARATOR=; when calling ./configure")
  Cabal/src/Distribution/Simple.hs
  changelog.d/pr-7510
Labels: attention: needs-review

#7650 Generate Paths_ module with qualified Data.List.last import
  Cabal/src/Distribution/Simple/Build/PathsModule/Z.hs
  templates/Paths_pkg.template.hs
Labels: attention: needs-review, merge me

#7657 Regenerate bootstrap/ with GHC updated from 8.10.4 to 8.10.7
  .github/workflows/bootstrap.yml
  Makefile
  bootstrap/linux-8.10.4.plan.json
  bootstrap/linux-8.10.7.json
  bootstrap/linux-8.10.7.plan.json
  bootstrap/linux-8.6.5.json
  bootstrap/linux-8.6.5.plan.json
  bootstrap/linux-8.8.4.json
  bootstrap/linux-8.8.4.plan.json
  templates/ci-bootstrap.template.yml
Labels: attention: pr-welcome

#7658 Regenerate bootstrap/ with GHC updated from 8.10.4 to 8.10.7 (forwardport of #7657)
  .github/workflows/bootstrap.yml
  Makefile
  bootstrap/linux-8.10.4.plan.json
  bootstrap/linux-8.10.7.json
  bootstrap/linux-8.10.7.plan.json
  bootstrap/linux-8.6.5.json
  bootstrap/linux-8.6.5.plan.json
  bootstrap/linux-8.8.4.json
  bootstrap/linux-8.8.4.plan.json
  templates/ci-bootstrap.template.yml
Labels: attention: needs-review

#7659 Try to fix CI/Meta-checks failure
  .github/workflows/quick-jobs.yml
  cabal-dev-scripts/cabal-dev-scripts.cabal
  templates/ci-quick-jobs.template.yml
Labels: attention: needs-review, merge me

#7652 Windows: rewrite paths to configure
  Cabal/src/Distribution/Simple.hs
Labels: merge me

#7662 Try to fix CI/Meta-checks failure (backport of #7659)
  .github/workflows/quick-jobs.yml
  cabal-dev-scripts/cabal-dev-scripts.cabal
  templates/ci-quick-jobs.template.yml
Labels: attention: needs-review, merge me

#7665 Bring back cabal-install-dev call removed by backport of #7653
  .github/workflows/windows.yml
  templates/ci-windows.template.yml
Labels: attention: needs-review

#7668 Windows: rewrite paths to configure (backport #7652)
  Cabal/src/Distribution/Simple.hs
Labels: attention: needs-review

#7675 Revert "Change cabal-plan list-bin to cabal list-bin in Makefile"
  Makefile
Labels: merge me

#7558 `cabal init` common stanzas and default flags
  cabal-install/src/Distribution/Client/Init/FileCreators.hs
  cabal-install/src/Distribution/Client/Init/Format.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/Golden.hs
  cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-and-exe-no-comments.golden
  cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-and-exe-with-comments.golden
  cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-no-comments.golden
  cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-with-comments.golden
  cabal-install/tests/fixtures/init/golden/cabal/cabal-test-suite-no-comments.golden
  cabal-install/tests/fixtures/init/golden/cabal/cabal-test-suite-with-comments.golden
  cabal-install/tests/fixtures/init/golden/exe/exe-build-tools-with-comments.golden
  cabal-install/tests/fixtures/init/golden/exe/exe-minimal-no-comments.golden
  cabal-install/tests/fixtures/init/golden/exe/exe-simple-minimal-with-comments.golden
  cabal-install/tests/fixtures/init/golden/exe/exe-with-comments.golden
  cabal-install/tests/fixtures/init/golden/exe/exe.golden
  cabal-install/tests/fixtures/init/golden/lib/lib-build-tools-with-comments.golden
  cabal-install/tests/fixtures/init/golden/lib/lib-minimal-no-comments.golden
  cabal-install/tests/fixtures/init/golden/lib/lib-simple-minimal-with-comments.golden
  cabal-install/tests/fixtures/init/golden/lib/lib-simple.golden
  cabal-install/tests/fixtures/init/golden/lib/lib-with-comments.golden
  cabal-install/tests/fixtures/init/golden/lib/lib.golden
  cabal-install/tests/fixtures/init/golden/test/standalone-test-with-comments.golden
  cabal-install/tests/fixtures/init/golden/test/standalone-test.golden
  cabal-install/tests/fixtures/init/golden/test/test-build-tools-with-comments.golden
  cabal-install/tests/fixtures/init/golden/test/test-minimal-no-comments.golden
  cabal-install/tests/fixtures/init/golden/test/test-simple-minimal-with-comments.golden
  cabal-install/tests/fixtures/init/golden/test/test-with-comments.golden
  cabal-install/tests/fixtures/init/golden/test/test.golden
Labels: merge me

#7683 Fix #7569 for cabal-install: bump to 3.7
  cabal-install/cabal-install.cabal
  cabal-install/main/Main.hs
  cabal-install/src/Distribution/Client/BuildReports/Anonymous.hs
  cabal-install/src/Distribution/Client/Config.hs
  cabal-install/src/Distribution/Client/HttpUtils.hs
  cabal-install/src/Distribution/Client/ProjectPlanOutput.hs
  cabal-install/src/Distribution/Client/Utils.hs
  cabal-install/src/Distribution/Client/Version.hs
Labels: cabal-install: other, attention: needs-review, merge me, version

#7687 Add changelogs for the three non-internal changes in cabal 3.6.2
  changelog.d/pr-7650
  changelog.d/pr-7652
  changelog.d/pr-7657
Labels: attention: needs-review, merge me

#7672 Add links to irc/matrix chat to readme
  README.md
Labels: documentation, merge me

#7681 Option to place comments after the cabal file field declaration
  Cabal-tests/tests/HackageTests.hs
  Cabal/src/Distribution/Fields.hs
  Cabal/src/Distribution/Fields/Pretty.hs
  Cabal/src/Distribution/InstalledPackageInfo.hs
  Cabal/src/Distribution/PackageDescription/PrettyPrint.hs
  cabal-install/src/Distribution/Client/BuildReports/Anonymous.hs
  cabal-install/src/Distribution/Client/Init/Format.hs
  cabal-install/src/Distribution/Client/Init/Types.hs
  cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-and-exe-with-comments.golden
  cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-with-comments.golden
  cabal-install/tests/fixtures/init/golden/cabal/cabal-test-suite-with-comments.golden
  cabal-install/tests/fixtures/init/golden/pkg-desc/pkg-old-cabal-with-flags.golden
  cabal-install/tests/fixtures/init/golden/pkg-desc/pkg-with-comments.golden
  cabal-install/tests/fixtures/init/golden/pkg-desc/pkg-with-flags.golden
  cabal-install/tests/fixtures/init/golden/pkg-desc/pkg.golden
Labels: attention: needs-review, squash+merge me

#7692 Convert chat links in badges
  README.md
Labels: squash+merge me
