Repository haskell/cabal, pull requests merged in 2021-03, with the labels that each got.

#7319 Fix containerless CI jobs by upgrading to ghc 8.10
  .github/workflows/bootstrap.yml
  .github/workflows/quick-jobs.yml
  bootstrap/linux-8.10.4.json
  bootstrap/linux-8.10.4.plan.json
  templates/ci-bootstrap.template.yml
  templates/ci-quick-jobs.template.yml
Labels: continuous-integration

#7195 Allow base16-bytestring 1.0 and newer
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/HashValue.hs
  cabal-install/src/Distribution/Client/HttpUtils.hs
  cabal-testsuite/cabal-testsuite.cabal
Labels: attention: needs-backport 3.4

#7318 Add ghc 9.0 to ci
  .github/workflows/linux.yml
  Cabal-described/Cabal-described.cabal
  Cabal-tests/Cabal-tests.cabal
  cabal-dev-scripts/src/GenValidate.hs
  cabal-testsuite/PackageTests/CmmSources/demo/Main.hs
  cabal-testsuite/PackageTests/TemplateHaskell/dynamic/TH.hs
  cabal-testsuite/PackageTests/TemplateHaskell/profiling/TH.hs
  cabal-testsuite/PackageTests/TemplateHaskell/vanilla/TH.hs
  cabal-testsuite/cabal-testsuite.cabal
  cabal-testsuite/src/Test/Cabal/OutputNormalizer.hs
  cabal.project.validate.libonly
Labels: continuous-integration

#7317 Suggest command on spelling mistakes
  Cabal/src/Distribution/Simple/Command.hs
  changelog.d/spelling-suggestion
Labels: Cabal: other, type: enhancement
