Repository haskell/cabal, pull requests merged in 2021-12, with the labels that each got.

#7408 Set exe as default component for `cabal run` and `cabal list-bin`
  cabal-install/src/Distribution/Client/CmdListBin.hs
  cabal-install/src/Distribution/Client/CmdRun.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/IntegrationTests2/targets/one-of-each/cabal.project
  cabal-install/tests/IntegrationTests2/targets/one-of-each/p.cabal
  doc/cabal-commands.rst
Labels: cabal-install: cmd/run, merge me, cabal-install: cmd/list-bin

#7843 Fix #6679 : Warn about `v2-haddock` failure
  cabal-install/src/Distribution/Client/CmdHaddock.hs
  cabal-testsuite/PackageTests/HaddockWarn/Main.hs
  cabal-testsuite/PackageTests/HaddockWarn/cabal.out
  cabal-testsuite/PackageTests/HaddockWarn/cabal.project
  cabal-testsuite/PackageTests/HaddockWarn/cabal.test.hs
  cabal-testsuite/PackageTests/HaddockWarn/example.cabal
  changelog.d/issue-6679
Labels: merge me

#7831 Cabal init fileformat tests
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/Init/FileCreators.hs
  cabal-install/src/Distribution/Client/Init/Types.hs
  cabal-install/src/Distribution/Client/Init/Utils.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/FileCreators.hs
Labels: merge me

#7844 Fix cabal on Windows 7
  Cabal/src/Distribution/Compat/Process.hs
  changelog.d/pr-7844
Labels: platform: windows, attention: needs-review, merge me, attention: needs-backport 3.6

#7853 Backport: Add ghcup install call to boostrap script to be future safe
  .github/workflows/bootstrap.yml
  .github/workflows/quick-jobs.yml
  .github/workflows/windows.yml
  templates/ci-bootstrap.template.yml
  templates/ci-quick-jobs.template.yml
  templates/ci-windows.template.yml
Labels: attention: needs-review, merge me

#7848 Update contributing guide
  CONTRIBUTING.md
Labels: squash+merge me

#7863 Cabal: Bump time upper bound to allow 1.12
  Cabal/Cabal.cabal
Labels: Cabal: other, merge me

#7866 Haddockumentation fixes to Cabal::Distribution.Verbosity.
  Cabal/src/Distribution/Simple/Utils.hs
  Cabal/src/Distribution/Verbosity.hs
Labels: documentation, merge me

#7807 Disregard occurrences of "." while backing up
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/Init/FileCreators.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/FileCreators.hs
Labels: merge me

#7861 docs: move flags not supported by Setup.hs, fixes #7859
  doc/cabal-commands.rst
  doc/setup-commands.rst
Labels: attention: needs-review, merge me

#7868 Fix --repl-options parsing
  Cabal/src/Distribution/Simple/Setup.hs
Labels: attention: needs-review, merge me, 3.8

#7873 Extra argument for `cabal init` as starting dir
  cabal-install/main/Main.hs
  cabal-install/src/Distribution/Client/Setup.hs
  doc/getting-started.rst
Labels: merge me

#7878 Changelog for #7873
  changelog.d/pr-7873
Labels: squash+merge me

#7880 extraBundledLibs (fix typos in comments)
  Cabal/src/Distribution/Types/BuildInfo.hs
Labels: merge me

#7847 Fix #7641 : Fix `post-checkout-command` bug
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-testsuite/PackageTests/postCheckoutCommand/cabal.negative.project
  cabal-testsuite/PackageTests/postCheckoutCommand/cabal.out
  cabal-testsuite/PackageTests/postCheckoutCommand/cabal.positive.project
  cabal-testsuite/PackageTests/postCheckoutCommand/cabal.test.hs
  cabal-testsuite/PackageTests/postCheckoutCommand/example.cabal
  cabal-testsuite/PackageTests/postCheckoutCommand/src/Example.hs
  changelog.d/issue-7641
Labels: attention: needs-review, merge me
