Repository haskell/cabal, pull requests merged in 2022-02, with the labels that each got.

#7799 Split --repl-options on whitespace
  Cabal/src/Distribution/Simple/Setup.hs
  cabal-testsuite/PackageTests/ReplOptions/ModuleA.hs
  cabal-testsuite/PackageTests/ReplOptions/ModuleC.hs
  cabal-testsuite/PackageTests/ReplOptions/cabal-repl-options.cabal
  cabal-testsuite/PackageTests/ReplOptions/cabal.multiple-repl-options-multiple-flags.out
  cabal-testsuite/PackageTests/ReplOptions/cabal.multiple-repl-options.out
  cabal-testsuite/PackageTests/ReplOptions/cabal.project
  cabal-testsuite/PackageTests/ReplOptions/cabal.single-repl-options-multiple-flags-negative.out
  cabal-testsuite/PackageTests/ReplOptions/cabal.single-repl-options-multiple-flags.out
  cabal-testsuite/PackageTests/ReplOptions/cabal.single-repl-options.out
  cabal-testsuite/PackageTests/ReplOptions/cabal.test.hs
  changelog.d/issue-6190
Labels: merge me

#7686 addFileMode: Replace use of Posix.Internals module with public API
  Cabal/src/Distribution/Compat/CopyFile.hs
  cabal-install/src/Distribution/Client/Compat/FilePerms.hs
Labels: merge me

#7949 Simplify bootstrap generation
  .github/workflows/bootstrap.yml
  .gitignore
  Cabal-syntax/src/Distribution/Fields/Lexer.hs
  Makefile
  bootstrap/README.md
  bootstrap/linux-8.10.7.json
  bootstrap/linux-8.10.7.plan.json
  bootstrap/linux-8.6.5.json
  bootstrap/linux-8.6.5.plan.json
  bootstrap/linux-8.8.4.json
  bootstrap/linux-8.8.4.plan.json
  cabal.project.bootstrap
  changelog.d/pr-9749
  templates/Lexer.x
  templates/ci-bootstrap.template.yml
Labels: merge me

#7953 Reduce VCS QuickCheck count to 10 (from 100)
  cabal-install/tests/UnitTests/Distribution/Client/VCS.hs
Labels: merge me

#7962 Fix missing space in error message
  cabal-install-solver/src/Distribution/Solver/Modular/MessageUtils.hs
Labels: merge me, re: error-message

#7948 Remove dead module Distribution.Client.Compat.FilePerms
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/Compat/FilePerms.hs
  changelog.d/pr-7948
Labels: merge me

#7231 Removed obsolete warning about mixins in the doc
  doc/cabal-package.rst
Labels: documentation, merge me

#7980 Consistent starting capital letter, ending period in help text.
  cabal-install/src/Distribution/Client/CmdBench.hs
  cabal-install/src/Distribution/Client/CmdConfigure.hs
  cabal-install/src/Distribution/Client/CmdHaddock.hs
  cabal-install/src/Distribution/Client/CmdListBin.hs
  cabal-install/src/Distribution/Client/CmdOutdated.hs
  cabal-install/src/Distribution/Client/CmdTest.hs
Labels: merge me

#7983 Fix 7835 for 3.6
  cabal-install/cabal-install.cabal
  release-notes/Cabal-3.6.1.0.md
Labels: merge me

#7964 Add a doc section on cabal list-bin.
  doc/cabal-commands.rst
Labels: merge me

#7952 Avoid templating GitHub Actions workflow
  .github/workflows/bootstrap.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/quick-jobs.yml
  .github/workflows/windows.yml
  Makefile
  cabal-dev-scripts/cabal-dev-scripts.cabal
  cabal-dev-scripts/src/GenValidate.hs
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
  cabal-install/tests/IntegrationTests2.hs
  cabal-testsuite/cabal-testsuite.cabal
  cabal.project
  cabal.project.coverage
  cabal.project.libonly
  cabal.project.validate
  cabal.project.validate.libonly
  templates/ci-bootstrap.template.yml
  templates/ci-linux.template.yml
  templates/ci-macos.template.yml
  templates/ci-quick-jobs.template.yml
  templates/ci-windows.template.yml
  vendor/cabal-doctest-1.0.8/ChangeLog.md
  vendor/cabal-doctest-1.0.8/LICENSE
  vendor/cabal-doctest-1.0.8/README.md
  vendor/cabal-doctest-1.0.8/Setup.hs
  vendor/cabal-doctest-1.0.8/cabal-doctest.cabal
  vendor/cabal-doctest-1.0.8/src/Distribution/Extra/Doctest.hs
Labels: continuous-integration, attention: needs-review

#8008 Try to resolve unused-packages warnings
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
Labels: attention: needs-review, merge me

#7972 Better recovery from a few index/tar errors
  cabal-install/src/Distribution/Client/CmdUpdate.hs
  cabal-install/src/Distribution/Client/IndexUtils.hs
Labels: attention: needs-review, squash+merge me

#7929 Fix concurrency/exception bugs in asyncFetchPackages
  bootstrap/linux-8.10.7.json
  bootstrap/linux-8.6.5.json
  bootstrap/linux-8.8.4.json
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/FetchUtils.hs
  cabal-install/src/Distribution/Client/Types/RepoName.hs
  cabal-install/src/Distribution/Client/Utils.hs
  cabal-install/tests/UnitTests.hs
  cabal-install/tests/UnitTests/Distribution/Client/BuildReport.hs
  cabal-install/tests/UnitTests/Distribution/Client/FetchUtils.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Types/OptionalStanza.hs
  changelog.d/pr-7929
Labels: attention: needs-review, merge me

#7995 Cleanup around subprocess helpers
  Cabal/src/Distribution/Compat/Process.hs
  Cabal/src/Distribution/Simple/Test/LibV09.hs
  Cabal/src/Distribution/Simple/Utils.hs
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/Compat/Process.hs
  cabal-install/src/Distribution/Client/Init/Types.hs
  cabal-install/src/Distribution/Client/Manpage.hs
  cabal-install/src/Distribution/Client/SetupWrapper.hs
  cabal-testsuite/src/Test/Cabal/Server.hs
  changelog.d/pr-7995
Labels: attention: needs-review, merge me

#8012 Remove overlapping patterns
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
Labels: attention: needs-review, merge me

#8000 Post remove ci templates
  .github/workflows/bootstrap.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/quick-jobs.yml
  .github/workflows/users-guide.yml
  .github/workflows/windows.yml
Labels: attention: needs-review

#8013 Use ref instead head_ref to cancelling jobs
  .github/workflows/bootstrap.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/quick-jobs.yml
  .github/workflows/users-guide.yml
  .github/workflows/windows.yml
Labels: merge me

#7688 code-generators field in test stanza.
  Cabal-syntax/src/Distribution/PackageDescription/FieldGrammar.hs
  Cabal-syntax/src/Distribution/PackageDescription/Parsec.hs
  Cabal-syntax/src/Distribution/Types/TestSuite.hs
  Cabal-tests/tests/ParserTests/regressions/Octree-0.5.expr
  Cabal-tests/tests/ParserTests/regressions/common-conditional.expr
  Cabal-tests/tests/ParserTests/regressions/common.expr
  Cabal-tests/tests/ParserTests/regressions/common2.expr
  Cabal-tests/tests/ParserTests/regressions/common3.expr
  Cabal-tests/tests/ParserTests/regressions/generics-sop.expr
  Cabal-tests/tests/ParserTests/regressions/hasktorch.expr
  Cabal-tests/tests/ParserTests/regressions/issue-5055.expr
  Cabal-tests/tests/ParserTests/regressions/jaeger-flamegraph.expr
  Cabal-tests/tests/ParserTests/regressions/shake.expr
  Cabal-tests/tests/ParserTests/regressions/th-lift-instances.expr
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  Cabal/src/Distribution/Simple/Build.hs
  Cabal/src/Distribution/Simple/PreProcess.hs
  cabal-testsuite/PackageTests/TestCodeGenerator/Foo.hs
  cabal-testsuite/PackageTests/TestCodeGenerator/cabal.out
  cabal-testsuite/PackageTests/TestCodeGenerator/cabal.project
  cabal-testsuite/PackageTests/TestCodeGenerator/cabal.test.hs
  cabal-testsuite/PackageTests/TestCodeGenerator/my.cabal
  cabal-testsuite/PackageTests/TestCodeGenerator/test-code-gen/CHANGELOG.md
  cabal-testsuite/PackageTests/TestCodeGenerator/test-code-gen/LICENSE
  cabal-testsuite/PackageTests/TestCodeGenerator/test-code-gen/app/Main.hs
  cabal-testsuite/PackageTests/TestCodeGenerator/test-code-gen/test-code-gen.cabal
  cabal-testsuite/PackageTests/TestCodeGenerator/tests/blank
  changelog.d/pr-7688
  doc/cabal-package.rst
  doc/file-format-changelog.rst
Labels: Cabal: cmd/test, squash+merge me, re: doctest

#8015 [3.4] cabal-install.cabal: allow base-4.15 (ghc-9.0)
  cabal-install/cabal-install.cabal
Labels: re: dependencies

#7973 Remove local options from global program options
  cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/IntegrationTests2/regression/program-options/cabal.project
  cabal-install/tests/IntegrationTests2/regression/program-options/p-0.1.tar.gz
  cabal-install/tests/IntegrationTests2/regression/program-options/q/Q.hs
  cabal-install/tests/IntegrationTests2/regression/program-options/q/q.cabal
  cabal-install/tests/UnitTests/Distribution/Client/Configure.hs
  changelog.d/pr-7973
  doc/cabal-project.rst
Labels: merge me

#6200 Provide explanation for invalid license identifier
  cabal-install/src/Distribution/Client/Init/Interactive/Command.hs
Labels: squash+merge me
