Repository haskell/cabal, pull requests merged in 2022-05, with the labels that each got.

#8115 Make `type` field optional for tests and benchmarks
  Cabal-syntax/src/Distribution/PackageDescription/FieldGrammar.hs
  Cabal-syntax/src/Distribution/PackageDescription/Parsec.hs
  Cabal-syntax/src/Distribution/Types/BenchmarkInterface.hs
  Cabal-syntax/src/Distribution/Types/BenchmarkType.hs
  Cabal-syntax/src/Distribution/Types/TestSuiteInterface.hs
  Cabal-syntax/src/Distribution/Types/TestType.hs
  Cabal-tests/tests/ParserTests/errors/issue-5055-2.errors
  Cabal-tests/tests/ParserTests/errors/issue-5055.errors
  Cabal-tests/tests/ParserTests/regressions/issue-5055.expr
  Cabal-tests/tests/ParserTests/regressions/issue-5055.format
  Cabal/src/Distribution/PackageDescription/Check.hs
  cabal-install/tests/IntegrationTests2/targets/benchmarks-disabled/p.cabal
  cabal-install/tests/IntegrationTests2/targets/multiple-tests/p.cabal
  cabal-install/tests/IntegrationTests2/targets/variety/p.cabal
  cabal-testsuite/PackageTests/DuplicateModuleName/DuplicateModuleName.cabal
  cabal-testsuite/PackageTests/NewBuild/CmdBench/MultipleBenchmarks/MultipleBenchmarks.cabal
  changelog.d/pr-8115
  doc/cabal-package.rst
Labels: attention: needs-review

#8120 cabal-install.cabal: bump hashable, HTTP, time upper bounds
  cabal-install/cabal-install.cabal
Labels: merge me

#8112 fix more typos
  Cabal-QuickCheck/src/Test/QuickCheck/GenericArbitrary.hs
  Cabal-described/src/Distribution/Utils/CharSet.hs
  Cabal-syntax/README.md
  Cabal-syntax/src/Distribution/Compat/CharParsing.hs
  Cabal-syntax/src/Distribution/Compat/Newtype.hs
  Cabal-syntax/src/Distribution/FieldGrammar.hs
  Cabal-syntax/src/Distribution/Fields.hs
  Cabal-syntax/src/Distribution/PackageDescription/Parsec.hs
  Cabal-syntax/src/Distribution/System.hs
  Cabal-syntax/src/Distribution/Types/BuildInfo.hs
  Cabal-syntax/src/Distribution/Types/VersionInterval.hs
  Cabal-syntax/src/Distribution/Types/VersionInterval/Legacy.hs
  Cabal-syntax/src/Distribution/Utils/Structured.hs
  Cabal-tests/Cabal-tests.cabal
  Cabal-tests/tests/Test/Laws.hs
  Cabal-tests/tests/cbits/rpmvercmp.c
  Cabal/src/Distribution/PackageDescription/Check.hs
  Cabal/src/Distribution/Simple/Build/Macros.hs
  Cabal/src/Distribution/Simple/BuildToolDepends.hs
  Cabal/src/Distribution/Simple/Configure.hs
  Cabal/src/Distribution/Simple/Utils.hs
  Cabal/src/Distribution/Utils/NubList.hs
  Makefile
  cabal-dev-scripts/src/GenUtils.hs
  cabal-install-solver/src/Distribution/Solver/Modular/Dependency.hs
  cabal-install-solver/src/Distribution/Solver/Modular/Linking.hs
  cabal-install-solver/src/Distribution/Solver/Modular/MessageUtils.hs
  cabal-install-solver/src/Distribution/Solver/Types/PackageIndex.hs
  cabal-install-solver/tests/UnitTests/Distribution/Solver/Modular/MessageUtils.hs
  cabal-install/src/Distribution/Client/Check.hs
  cabal-install/src/Distribution/Client/CmdErrorMessages.hs
  cabal-install/src/Distribution/Client/Compat/Semaphore.hs
  cabal-install/src/Distribution/Client/Fetch.hs
  cabal-install/src/Distribution/Client/HashValue.hs
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/RebuildMonad.hs
  cabal-install/src/Distribution/Client/Setup.hs
  cabal-install/src/Distribution/Client/SrcDist.hs
  cabal-install/src/Distribution/Client/TargetSelector.hs
  cabal-install/src/Distribution/Client/Types/Repo.hs
  cabal-install/tests/UnitTests/Distribution/Client/VCS.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
  cabal-testsuite/PackageTests/CCompilerOverride/setup.test.hs
  cabal-testsuite/PackageTests/DeterministicAr/setup-default-ar.test.hs
  cabal-testsuite/PackageTests/DeterministicAr/setup-old-ar-without-at-args.test.hs
  cabal-testsuite/PackageTests/Regression/T5309/T5309.cabal
  cabal-testsuite/PackageTests/Regression/T5309/lib/Data/TCM/Memoized/FFI.hsc
  cabal-testsuite/cabal-testsuite.cabal
  doc/cabal-project.rst
  doc/developing-packages.rst
  doc/file-format-changelog.rst
  doc/getting-started.rst
  editors/vim/example.cabal
  stack.yaml
  validate.sh
Labels: merge me, re: typo

#8119 Doc: Fix command-line syntax for haddock options; add --haddock-quickjump
  doc/cabal-project.rst
Labels: documentation, Cabal: cmd/haddock, attention: needs-review, cabal-install: cmd/haddock, merge me

#8123 Remove >= from Cabal cabal-version
  Cabal/Cabal.cabal
Labels: merge me

#8125 Remove references to `new-build` in testsuite readme
  cabal-testsuite/README.md
Labels: merge me

#8117 Remove the Generic instance for LicenseId
  Cabal-syntax/src/Distribution/SPDX/LicenseId.hs
  Cabal-tests/tests/UnitTests/Distribution/SPDX.hs
  changelog.d/pr-8117
  templates/SPDX.LicenseId.template.hs
Labels: squash+merge me

#7934 Fix the timestamp shown during cabal update
  .github/workflows/validate.yml
  cabal-install/src/Distribution/Client/CmdUpdate.hs
  cabal-testsuite/PackageTests/NewUpdate/UpdateIndexState/repo/pkg-1.0/pkg.cabal
  cabal-testsuite/PackageTests/NewUpdate/UpdateIndexState/update-index-state.out
  cabal-testsuite/PackageTests/NewUpdate/UpdateIndexState/update-index-state.test.hs
  cabal-testsuite/cabal-testsuite.cabal
  cabal-testsuite/src/Test/Cabal/Monad.hs
  cabal-testsuite/src/Test/Cabal/Prelude.hs
  cabal-testsuite/src/Test/Cabal/Run.hs
  changelog.d/pr-7934
Labels: cabal-install: cmd/update, merge me

#8134 code-generators now marked to 3.8 spec
  Cabal-syntax/src/Distribution/PackageDescription/FieldGrammar.hs
  cabal-testsuite/PackageTests/TestCodeGenerator/my.cabal
Labels: attention: needs-review, squash+merge me

#8109 v2-sdist now respects --ignore-project
  cabal-install/src/Distribution/Client/CmdSdist.hs
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/src/Distribution/Client/ProjectFlags.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/IntegrationTests2/build/ignore-project/A.hs
  cabal-install/tests/IntegrationTests2/build/ignore-project/Setup.hs
  cabal-install/tests/IntegrationTests2/build/ignore-project/a.cabal
  cabal-install/tests/IntegrationTests2/build/ignore-project/cabal.project
  cabal-testsuite/PackageTests/Regression/T5318/cabal.project
  cabal-testsuite/PackageTests/Regression/T5318/sdist-list-sources.test.hs
  cabal-testsuite/PackageTests/SDist/T5195/cabal.project
  cabal-testsuite/PackageTests/SDist/T5195/cabal.test.hs
  cabal-testsuite/PackageTests/SDist/T7028/cabal.test.hs
  cabal-testsuite/PackageTests/SDist/T7124/cabal-list.test.hs
  cabal-testsuite/PackageTests/SDist/T7124/cabal.test.hs
  cabal-testsuite/PackageTests/SDist/T7698/cabal.test.hs
  changelog.d/issue-7965
  doc/cabal-project.rst
Labels: type: bug, Cabal: cmd/sdist, merge me

#8139 Clarify `runhaskell` in Cabal's guide
  doc/setup-commands.rst
Labels: documentation, merge me

#8131 Minor clean up after PR #7934
  cabal-install/src/Distribution/Client/CmdUpdate.hs
  cabal-testsuite/PackageTests/NewUpdate/UpdateIndexState/update-index-state.out
  cabal-testsuite/src/Test/Cabal/Prelude.hs
Labels: merge me

#8136 Mention file-format-changelog.rst in CONTRIBUTING
  CONTRIBUTING.md
Labels: documentation, squash+merge me

#8138 Require `type` field when spec < 3.8 (#8115)
  Cabal-syntax/src/Distribution/PackageDescription/FieldGrammar.hs
  Cabal-syntax/src/Distribution/PackageDescription/Parsec.hs
  Cabal-tests/tests/ParserTests/errors/issue-5055-2.errors
  Cabal-tests/tests/ParserTests/errors/issue-5055.errors
  Cabal-tests/tests/ParserTests/regressions/issue-5055.expr
  Cabal-tests/tests/ParserTests/regressions/issue-5055.format
  cabal-install/tests/IntegrationTests2/targets/benchmarks-disabled/p.cabal
  cabal-install/tests/IntegrationTests2/targets/multiple-tests/p.cabal
  cabal-install/tests/IntegrationTests2/targets/variety/p.cabal
  cabal-testsuite/PackageTests/DuplicateModuleName/DuplicateModuleName.cabal
  cabal-testsuite/PackageTests/NewBuild/CmdBench/MultipleBenchmarks/MultipleBenchmarks.cabal
  changelog.d/pr-8115
  doc/file-format-changelog.rst
Labels: attention: needs-review, merge me

#8140 Improve error message for empty --allow-newer= (fix #7740)
  Cabal/src/Distribution/ReadE.hs
  cabal-install/src/Distribution/Client/Setup.hs
  changelog.d/pr-8140
Labels: merge me

#8146 Typo missing closing parenthesis on license.
  README.md
Labels: attention: needs-review

#8135 Add SPDX List v3.16 to LicenseListVersion and the file format changelog
  Cabal-syntax/src/Distribution/SPDX/LicenseExceptionId.hs
  Cabal-syntax/src/Distribution/SPDX/LicenseId.hs
  Cabal-syntax/src/Distribution/SPDX/LicenseListVersion.hs
  doc/file-format-changelog.rst
  templates/SPDX.LicenseExceptionId.template.hs
  templates/SPDX.LicenseId.template.hs
Labels: attention: needs-review, attention: needs-backport 3.8

#8152 Re #7916: undeprecate Distribution.Types.VersionInterval.Legacy
  Cabal-syntax/src/Distribution/Types/VersionInterval.hs
  Cabal-syntax/src/Distribution/Types/VersionInterval/Legacy.hs
Labels: documentation, merge me, 3.8, re: API, attention: needs-backport 3.8

#8160 Bump cabal-version in the remaining .cabal files and update BSD3 name
  Cabal-syntax/Cabal-syntax.cabal
  Cabal-tests/Cabal-tests.cabal
  Cabal/Cabal.cabal
  cabal-benchmarks/cabal-benchmarks.cabal
  solver-benchmarks/solver-benchmarks.cabal
Labels: attention: needs-review, attention: needs-backport 3.8

#8157 Preparation for 3.8.0.20220526 pre-release up to and including release notes
  .gitlab-ci.yml
  Cabal-QuickCheck/Cabal-QuickCheck.cabal
  Cabal-described/Cabal-described.cabal
  Cabal-syntax/Cabal-syntax.cabal
  Cabal-syntax/LICENSE
  Cabal-tests/Cabal-tests.cabal
  Cabal-tests/LICENSE
  Cabal-tree-diff/Cabal-tree-diff.cabal
  Cabal/Cabal.cabal
  Cabal/ChangeLog.md
  Cabal/LICENSE
  Cabal/Makefile
  LICENSE
  cabal-benchmarks/LICENSE
  cabal-benchmarks/cabal-benchmarks.cabal
  cabal-dev-scripts/LICENSE
  cabal-install-solver/LICENSE
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/LICENSE
  cabal-install/cabal-install.cabal
  cabal-install/changelog
  cabal-testsuite/LICENSE
  cabal-testsuite/PackageTests/ShowBuildInfo/Complex/single.out
  cabal-testsuite/cabal-testsuite.cabal
  cabal-testsuite/src/Test/Cabal/OutputNormalizer.hs
  doc/conf.py
  release-notes/Cabal-3.8.0.0.md
  release-notes/Cabal-3.8.0.20220526.md
  release-notes/cabal-install-3.8.0.20220526.md
  solver-benchmarks/LICENSE
  solver-benchmarks/solver-benchmarks.cabal
Labels: attention: needs-review, merge me

#8164 Fix BSD-3-Clause not being recognized with cabal-version 2.0, too new cabal version for Cabal and Cabal-syntax (backward compat)
  Cabal-syntax/Cabal-syntax.cabal
  Cabal-syntax/ChangeLog.md
  Cabal-tests/Cabal-tests.cabal
  Cabal/Cabal.cabal
  Cabal/ChangeLog.md
  cabal-benchmarks/cabal-benchmarks.cabal
  cabal-install-solver/ChangeLog.md
  cabal-install/README.md
  cabal-install/src/Distribution/Client/Version.hs
  solver-benchmarks/solver-benchmarks.cabal
Labels: merge me

#8163 Forwardport 3.8.0
  .gitlab-ci.yml
  Cabal-QuickCheck/Cabal-QuickCheck.cabal
  Cabal-described/Cabal-described.cabal
  Cabal-syntax/Cabal-syntax.cabal
  Cabal-syntax/ChangeLog.md
  Cabal-syntax/LICENSE
  Cabal-tests/Cabal-tests.cabal
  Cabal-tests/LICENSE
  Cabal-tree-diff/Cabal-tree-diff.cabal
  Cabal/Cabal.cabal
  Cabal/ChangeLog.md
  Cabal/LICENSE
  Cabal/Makefile
  LICENSE
  bootstrap/linux-8.10.7.json
  bootstrap/linux-8.6.5.json
  bootstrap/linux-8.8.4.json
  cabal-benchmarks/LICENSE
  cabal-benchmarks/cabal-benchmarks.cabal
  cabal-dev-scripts/LICENSE
  cabal-install-solver/ChangeLog.md
  cabal-install-solver/LICENSE
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/LICENSE
  cabal-install/README.md
  cabal-install/cabal-install.cabal
  cabal-install/changelog
  cabal-install/src/Distribution/Client/Version.hs
  cabal-testsuite/LICENSE
  cabal-testsuite/PackageTests/ShowBuildInfo/Complex/single.out
  cabal-testsuite/cabal-testsuite.cabal
  cabal-testsuite/src/Test/Cabal/OutputNormalizer.hs
  doc/conf.py
  release-notes/Cabal-3.8.0.0.md
  release-notes/Cabal-3.8.0.20220526.md
  release-notes/cabal-install-3.8.0.20220526.md
  solver-benchmarks/LICENSE
  solver-benchmarks/solver-benchmarks.cabal
Labels: attention: needs-review, merge me

#8137 Fix typos in changelog entries
  .github/workflows/changelogs.yml
Labels: merge me

#8169 Update cabal to officially support GHC 9.2
  Cabal/src/Distribution/Simple/Program/GHC.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
Labels: priority: high :fire:, attention: needs-review, merge me, attention: needs-backport 3.8

#8167 All kinds of last touches before the 3.8.0 pre-release
  Cabal/ChangeLog.md
  Cabal/README.md
  cabal-install-solver/cabal-install-solver.cabal
Labels: attention: needs-review, merge me

#8176 Update repo URL in doc example and Drop outdated Hackage vs CPAN package counts
  doc/cabal-package.rst
  doc/intro.rst
Labels: documentation, attention: needs-review, merge me

#8170 Update the list of known GHC extensions to match GHC 9.2
  Cabal-syntax/src/Language/Haskell/Extension.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  changelog.d/pr-8170
Labels: merge me

#8184 Permit pre-releases in gitlab CI
  .gitlab-ci.yml
Labels: release, attention: needs-review
