Repository haskell/cabal, pull requests merged in 2022-12, with the labels that each got.

#8620 Switch to fgaz's changelog-d fork
  .github/workflows/changelogs.yml
  CONTRIBUTING.md
Labels: continuous-integration, merge me, re: changelog, merge delay passed

#8361 Add upper bound check to all
  Cabal-tests/tests/CheckTests.hs
  Cabal-tests/tests/ParserTests/regressions/all-upper-bound.cabal
  Cabal-tests/tests/ParserTests/regressions/all-upper-bound.check
  Cabal-tests/tests/ParserTests/regressions/public-multilib-2.cabal
  Cabal/src/Distribution/PackageDescription/Check.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs
  changelog.d/pr-8339
Labels: attention: needs-review, squash+merge me, merge delay passed

#8629 Downgrade ubuntu image to fix a CI linker failure to do with package resolve
  .github/workflows/validate.yml
Labels: attention: needs-review, squash+merge me, merge delay passed

#8622 add marked output to `cabal list-bin`
  cabal-install/src/Distribution/Client/CmdListBin.hs
Labels: merge me, cabal-install: cmd/list-bin, merge delay passed

#8565 Cabal: Expose flag assignment to configure script
  Cabal/src/Distribution/Simple.hs
  cabal-testsuite/PackageTests/Configure/cabal.out
  cabal-testsuite/PackageTests/Configure/configure.ac
  cabal-testsuite/PackageTests/Configure/setup.cabal.out
  cabal-testsuite/PackageTests/Configure/setup.out
  cabal-testsuite/PackageTests/Configure/zlib.cabal
  changelog.d/issue-8564
  doc/cabal-package.rst
Labels: Cabal: custom, attention: needs-review, squash+merge me, merge delay passed

#8633 Specify default exe extension on wasm32 to be .wasm
  Cabal/src/Distribution/Simple/BuildPaths.hs
  Cabal/src/Distribution/Simple/Utils.hs
  changelog.d/pr-8633
Labels: merge me, merge delay passed

#8582 [Backpack]: improve the error message in case of a mutually recursive unit
  Cabal/src/Distribution/Backpack/LinkedComponent.hs
  Cabal/src/Distribution/Backpack/UnifyM.hs
  cabal-testsuite/PackageTests/Backpack/T8582/Main.hs
  cabal-testsuite/PackageTests/Backpack/T8582/T8582.cabal
  cabal-testsuite/PackageTests/Backpack/T8582/cabal.project
  cabal-testsuite/PackageTests/Backpack/T8582/impl/ImplA.hs
  cabal-testsuite/PackageTests/Backpack/T8582/setup.cabal.out
  cabal-testsuite/PackageTests/Backpack/T8582/setup.out
  cabal-testsuite/PackageTests/Backpack/T8582/setup.test.hs
  cabal-testsuite/PackageTests/Backpack/T8582/sig/A.sig
  changelog.d/pr-8582
Labels: cabal-install: Backpack, attention: needs-review, re: error-message, squash+merge me, merge delay passed

#8623 Fix project-local flags being ignored
  cabal-install/src/Distribution/Client/Configure.hs
  cabal-install/src/Distribution/Client/Install.hs
  cabal-install/src/Distribution/Client/ProjectPlanOutput.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/SetupWrapper.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-testsuite/PackageTests/LinkerOptions/NonignoredConfigs/basic/basic/Basic.hs
  cabal-testsuite/PackageTests/LinkerOptions/NonignoredConfigs/basic/basic/basic.cabal
  cabal-testsuite/PackageTests/LinkerOptions/NonignoredConfigs/basic/cabal.project
  cabal-testsuite/PackageTests/LinkerOptions/NonignoredConfigs/cabal.out
  cabal-testsuite/PackageTests/LinkerOptions/NonignoredConfigs/cabal.test.hs
  changelog.d/pr-8623
Labels: type: enhancement, merge me, re: dynamic-linking, merge delay passed

#8607 no global packages auto written to env files
  cabal-install/src/Distribution/Client/CmdFreeze.hs
  cabal-install/src/Distribution/Client/CmdInstall.hs
  cabal-install/src/Distribution/Client/ProjectOrchestration.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/tests/IntegrationTests2.hs
  changelog.d/pr-8607
Labels: cabal-install: cmd/install, squash+merge me, re: install --lib, merge delay passed

#8500 redownload pkgs when source hash verification fails
  cabal-install/src/Distribution/Client/FetchUtils.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  changelog.d/pr-8500
Labels: attention: needs-review, squash+merge me, merge delay passed

#8642 Add example on how refer private libs in build-depends
  doc/file-format-changelog.rst
Labels: merge me, merge delay passed

#8588 Fix docs for running tests
  cabal-testsuite/README.md
  cabal-testsuite/src/Test/Cabal/Prelude.hs
Labels: squash+merge me, merge delay passed
