Repository haskell/cabal, pull requests merged in 2022-01, with the labels that each got.

#7886 Remove trailing spaces from empty comments in `cabal init`
  cabal-install/src/Distribution/Client/Init/Format.hs
  cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-and-exe-with-comments.golden
  cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-with-comments.golden
  cabal-install/tests/fixtures/init/golden/cabal/cabal-test-suite-with-comments.golden
  cabal-install/tests/fixtures/init/golden/pkg-desc/pkg-old-cabal-with-flags.golden
  cabal-install/tests/fixtures/init/golden/pkg-desc/pkg-with-comments.golden
  cabal-install/tests/fixtures/init/golden/pkg-desc/pkg-with-flags.golden
  cabal-install/tests/fixtures/init/golden/pkg-desc/pkg.golden
Labels: merge me

#7897 Update semigroups dep and bump time and text deps on Hackage
  Cabal/Cabal.cabal
Labels: merge me

#7900 Update #7874: Add test, fix changelog
  Cabal/src/Distribution/Simple/GHC/Internal.hs
  Cabal/src/Distribution/Simple/Program/GHC.hs
  cabal-testsuite/PackageTests/CCompilerOverride/Main.hs
  cabal-testsuite/PackageTests/CCompilerOverride/custom-cc
  cabal-testsuite/PackageTests/CCompilerOverride/custom-cc.bat
  cabal-testsuite/PackageTests/CCompilerOverride/foo.c
  cabal-testsuite/PackageTests/CCompilerOverride/my.cabal
  cabal-testsuite/PackageTests/CCompilerOverride/setup.cabal.out
  cabal-testsuite/PackageTests/CCompilerOverride/setup.out
  cabal-testsuite/PackageTests/CCompilerOverride/setup.test.hs
  changelog.d/issue-4439
Labels: attention: needs-review, merge me

#7876 Backing up only when overwritting to allow cabalisation
  cabal-install/src/Distribution/Client/Init/FileCreators.hs
  cabal-testsuite/PackageTests/Init/app/Main.hs
  cabal-testsuite/PackageTests/Init/init.out
  cabal-testsuite/PackageTests/Init/init.test.hs
  cabal-testsuite/src/Test/Cabal/Prelude.hs
Labels: merge me

#7902 Fix #7712 fix #7803: do not link to other .rst files by .html links
  doc/cabal-package.rst
  doc/cabal-project.rst
  doc/developing-packages.rst
  doc/getting-started.rst
  doc/intro.rst
  doc/nix-local-build.rst
  doc/setup-commands.rst
Labels: merge me

#7903 Silencing warning about unrecognised world-file field
  cabal-install/src/Distribution/Client/ParseUtils.hs
  changelog.d/pr-7903
Labels: merge me

#7726 Fix #7714: use `nroff -man | less` as backend for `cabal man`
  .github/workflows/linux.yml
  Cabal/Cabal.cabal
  Cabal/src/Distribution/Simple/Utils.hs
  cabal-dev-scripts/src/GenValidate.hs
  cabal-install/main/Main.hs
  cabal-install/src/Distribution/Client/Manpage.hs
  cabal-testsuite/PackageTests/Manpage/cabal.test.hs
  templates/ci-linux.template.yml
Labels: platform: mac, merge me, cabal-install: cmd/man

#7908 Testing cabal init for buildable output
  cabal-testsuite/PackageTests/Init/init.out
  cabal-testsuite/PackageTests/Init/init.test.hs
Labels: merge me

#7911 Haddockumentation fixes in Distribution.Types.VersionRange.Internal
  Cabal/src/Distribution/Types/VersionRange/Internal.hs
Labels: documentation, merge me, re: API

#7928 docs: typo
  doc/nix-local-build.rst
Labels: merge me

#7919 Re #7916: haddockumentation of Distribution.Types.VersionInterval.Legacy
  Cabal/src/Distribution/Types/VersionInterval/Legacy.hs
  Cabal/src/Distribution/Types/VersionRange/Internal.hs
Labels: documentation, attention: needs-review, re: API

#7935 Changelog for #7714 / #7726: cabal man
  changelog.d/issue-7714
Labels: squash+merge me

#7925 Add list-bin support for scripts.
  cabal-install/src/Distribution/Client/CmdListBin.hs
  cabal-testsuite/PackageTests/ListBin/Script/cabal.out
  cabal-testsuite/PackageTests/ListBin/Script/cabal.test.hs
  cabal-testsuite/PackageTests/ListBin/Script/script.hs
  changelog.d/pr-7851
Labels: attention: needs-review

#7922 Raise process lower bound to 1.2.1.0
  Cabal-tests/Cabal-tests.cabal
  Cabal-tests/tests/UnitTests.hs
  Cabal-tests/tests/UnitTests/Distribution/Compat/CreatePipe.hs
  Cabal/Cabal.cabal
  Cabal/src/Distribution/Compat/CreatePipe.hs
  Cabal/src/Distribution/Compat/Process.hs
  Cabal/src/Distribution/Simple/Test/ExeV10.hs
  Cabal/src/Distribution/Simple/Test/LibV09.hs
  Cabal/src/Distribution/Simple/Utils.hs
  cabal-testsuite/cabal-testsuite.cabal
  cabal-testsuite/main/cabal-tests.hs
  cabal-testsuite/src/Test/Cabal/Run.hs
  cabal-testsuite/src/Test/Cabal/Server.hs
  changelog.d/pr-7922
Labels: merge me, re: code quality, re: dependencies

#7936 Add Cabal-syntax creation commit to .git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: merge me

#7933 Adjusting cabal check warning for long synopses
  Cabal/src/Distribution/PackageDescription/Check.hs
  cabal-testsuite/PackageTests/Check/SynopsisLength/cabal.out
  cabal-testsuite/PackageTests/Check/SynopsisLength/cabal.test.hs
  cabal-testsuite/PackageTests/Check/SynopsisLength/pkg.cabal
  changelog.d/pr-7933
Labels: merge me

#7931 docs: cabal.project in parent directories
  doc/cabal-project.rst
Labels: merge me

#7676 Add package-db flag for v2 commands
  Cabal-QuickCheck/src/Test/QuickCheck/Instances/Cabal.hs
  Cabal/src/Distribution/Simple/Setup.hs
  cabal-install/src/Distribution/Client/PackageHash.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Types.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/ProjectPlanning/Types.hs
  cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
  cabal-install/tests/UnitTests/Distribution/Client/TreeDiffInstances.hs
  cabal-testsuite/PackageTests/PackageDB/cabal-fail-no-base.out
  cabal-testsuite/PackageTests/PackageDB/cabal-fail-no-base.test.hs
  cabal-testsuite/PackageTests/PackageDB/cabal-fail-no-p.out
  cabal-testsuite/PackageTests/PackageDB/cabal-fail-no-p.test.hs
  cabal-testsuite/PackageTests/PackageDB/cabal-fail-no-packagedbs.out
  cabal-testsuite/PackageTests/PackageDB/cabal-fail-no-packagedbs.test.hs
  cabal-testsuite/PackageTests/PackageDB/cabal-manual-packagedb.out
  cabal-testsuite/PackageTests/PackageDB/cabal-manual-packagedb.test.hs
  cabal-testsuite/PackageTests/PackageDB/cabal-packagedb.out
  cabal-testsuite/PackageTests/PackageDB/cabal-packagedb.test.hs
  cabal-testsuite/PackageTests/PackageDB/p-no-package-dbs/P.hs
  cabal-testsuite/PackageTests/PackageDB/p-no-package-dbs/cabal.project
  cabal-testsuite/PackageTests/PackageDB/p-no-package-dbs/p-no-package-dbs.cabal
  cabal-testsuite/PackageTests/PackageDB/p/P.hs
  cabal-testsuite/PackageTests/PackageDB/p/cabal.project
  cabal-testsuite/PackageTests/PackageDB/p/p.cabal
  cabal-testsuite/PackageTests/PackageDB/q/Main.hs
  cabal-testsuite/PackageTests/PackageDB/q/cabal.project
  cabal-testsuite/PackageTests/PackageDB/q/q.cabal
  changelog.d/pr-7676
  doc/cabal-project.rst
Labels: squash+merge me

#7827 Fix haddock via Setup.hs with internal libraries
  CONTRIBUTING.md
  Cabal-syntax/src/Distribution/Compat/Lens.hs
  Cabal-syntax/src/Distribution/Types/VersionInterval.hs
  Cabal/src/Distribution/Simple/Haddock.hs
  cabal-testsuite/PackageTests/InternalLibraries/Haddock/Foo.hs
  cabal-testsuite/PackageTests/InternalLibraries/Haddock/InternalAfter.hs
  cabal-testsuite/PackageTests/InternalLibraries/Haddock/InternalBefore.hs
  cabal-testsuite/PackageTests/InternalLibraries/Haddock/foo.cabal
  cabal-testsuite/PackageTests/InternalLibraries/Haddock/haddock.cabal.out
  cabal-testsuite/PackageTests/InternalLibraries/Haddock/haddock.out
  cabal-testsuite/PackageTests/InternalLibraries/Haddock/haddock.test.hs
  changelog.d/issue-1919
  doc/nix-local-build.rst
  stack.yaml
Labels: Cabal: cmd/haddock, merge me

#7938 Improve names of generated executables for scripts
  cabal-install/src/Distribution/Client/ScriptUtils.hs
  cabal-testsuite/PackageTests/ListBin/Script/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdBuild/Script/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdBuild/ScriptBuildRepl/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdBuild/ScriptBuildRun/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdBuild/ScriptRerun/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdClean/Keep/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdClean/Orphan/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdClean/Script/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRepl/Script/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRepl/ScriptRerun/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/Script/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptLiterate/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptNoExtention/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptNoExtention/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptNoExtention/with sp
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptRerun/cabal.out
  changelog.d/pr-7851
Labels: merge me
