Repository haskell/cabal, pull requests merged in 2022-06, with the labels that each got.

#8179 Simplify Language extension documentation
  Cabal-syntax/src/Language/Haskell/Extension.hs
Labels: merge me

#8193 Improve documentation formatting of some cabal command flags
  doc/cabal-commands.rst
  doc/cabal-project.rst
Labels: documentation, merge me

#8182 docs: move Configuration chapter to cabal-install reference
  doc/cabal-commands.rst
  doc/cabal-config-and-commands.rst
  doc/cabal-package.rst
  doc/config-and-install.rst
  doc/config.rst
  doc/developing-packages.rst
  doc/index.rst
  doc/intro.rst
  doc/setup-commands.rst
Labels: documentation, merge me, attention: needs-backport 3.8

#8191 Fix win release ext
  .gitlab/ci.sh
Labels: squash+merge me, attention: needs-backport 3.8

#8195 Exclude broken 'Validate windows-latest ghc-8.6.5' job that cancels CI
  .github/workflows/validate.yml
Labels: platform: windows, continuous-integration, attention: needs-review, merge me

#8199 Remove Cabal version check that applied to already not supported <1.19.2
  cabal-install/src/Distribution/Client/Configure.hs
Labels: merge me

#8194 bootstrap: generate missing Setup.hs in dependencies
  bootstrap/bootstrap.py
Labels: merge me, attention: needs-backport 3.8

#8196 docs: allow TOC navigation
  doc/conf.py
  doc/requirements.in
  doc/requirements.txt
Labels: merge me, re: readthedocs

#8205 Drop >= in suggestions to cabal-version (rebase #7104)
  Cabal/src/Distribution/PackageDescription/Check.hs
Labels: merge me

#8162 Haddocks command
  Cabal/src/Distribution/Simple/Haddock.hs
  Cabal/src/Distribution/Simple/Setup.hs
  cabal-install/cabal-install.cabal
  cabal-install/main/Main.hs
  cabal-install/src/Distribution/Client/CmdHaddock.hs
  cabal-install/src/Distribution/Client/CmdHaddockProject.hs
  cabal-install/src/Distribution/Client/Config.hs
  cabal-install/src/Distribution/Client/Haddock.hs
  cabal-install/src/Distribution/Client/PackageHash.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Types.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/ProjectPlanning/Types.hs
  cabal-install/src/Distribution/Client/Setup.hs
  cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
  changelog.d/pr-8162
  doc/cabal-commands.rst
Labels: merge me

#8217 Add strikethrough text support
  doc/cabal-project.rst
  doc/conf.py
  doc/requirements.in
  doc/requirements.txt
Labels: merge me

#8212 Add command line options tests for 9.2
  Cabal-tests/tests/UnitTests/Distribution/Simple/Program/GHC.hs
Labels: merge me

#8223 Future compat for liftA2 being exported from Prelude
  Cabal-syntax/src/Distribution/Fields/ParseResult.hs
  Cabal-syntax/src/Distribution/System.hs
  Cabal-syntax/src/Distribution/Types/VersionInterval.hs
Labels: attention: needs-review, merge me, attention: needs-backport 3.8

#8214 Some cosmetics on the 3.8 changelogs
  release-notes/cabal-install-3.8.0.20220526.md
Labels: release, squash+merge me, attention: needs-backport 3.8

#8228 Add changelog for future proofing liftA2 export from Prelude
  changelog.d/pr-8223
Labels: attention: needs-review, merge me

#8237 Document `cabal check` in the user guide
  changelog.d/pr-8237
  doc/cabal-commands.rst
Labels: merge me

#8252 Fix Haddocks for `unAbiHash` and `mkAbiHash`
  Cabal-syntax/src/Distribution/Types/AbiHash.hs
Labels: merge me
