Repository haskell/cabal, pull requests merged in 2022-11, with the labels that each got.

#8496 build pkgconfig db individually when bulk fails
  cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs
  changelog.d/pr-8496
Labels: attention: needs-review, squash+merge me, attention: needs-backport 3.8, merge delay passed

#8576 Set urllib.request.urlopen timeout in bootstrap.py to fix CI
  bootstrap/bootstrap.py
Labels: continuous-integration, cabal-install: bootstrap, attention: needs-review

#8573 Document internal library syntax changes
  doc/cabal-package.rst
Labels: merge me, merge delay passed

#8501 `ghc`, `ghc-boot`, `ghci` packages should be non-upgradable (#8489)
  cabal-install-solver/src/Distribution/Solver/Modular/Solver.hs
  cabal-install/src/Distribution/Client/Dependency.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
  changelog.d/issue-8489
Labels: squash+merge me, merge delay passed

#8593 Increase urllib.request.urlopen timeout in bootstrap.py to fix CI
  bootstrap/bootstrap.py
Labels: continuous-integration, cabal-install: bootstrap, attention: needs-review, merge me

#8570 Update Makefile
  Makefile
Labels: merge me, merge delay passed

#8595 Cache whole of ~/.cabal in bootstrap.yml to fix CI
  .github/workflows/bootstrap.yml
Labels: continuous-integration, cabal-install: bootstrap, attention: needs-review

#8596 Hardwire a different CI cache path, to fix CI
  .github/workflows/bootstrap.yml
Labels: continuous-integration, cabal-install: bootstrap

#8559 add documentation for single-file Haskell scripts
  doc/cabal-commands.rst
  doc/getting-started.rst
Labels: squash+merge me, merge delay passed

#8592 Add dependabot for github workflows
  .github/dependabot.yml
Labels: merge me, merge delay passed

#8590 Use GHC.Conc.Sync.getNumProcessors instead of C
  cabal-install/src/Distribution/Client/Utils.hs
Labels: type: refactor, squash+merge me, merge delay passed

#8610 Support transformers-0.6 and mtl-2.3
  Cabal-syntax/Cabal-syntax.cabal
  Cabal/Cabal.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install-solver/src/Distribution/Solver/Modular/Linking.hs
  cabal-install-solver/src/Distribution/Solver/Modular/Validate.hs
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-testsuite/cabal-testsuite.cabal
  solver-benchmarks/solver-benchmarks.cabal
Labels: merge me, merge delay passed

#8608 Avoid `Data.List.{head,tail}`
  Cabal-syntax/src/Language/Haskell/Extension.hs
  Cabal/src/Distribution/Simple/Configure.hs
Labels: merge me, merge delay passed

#8602 Fix typo in import feature documentation
  doc/nix-local-build.rst
Labels: merge me, merge delay passed

#8604 Change exitcode-stdio-1.0 description to match current status quo
  Cabal-syntax/src/Distribution/Types/BenchmarkInterface.hs
  Cabal-syntax/src/Distribution/Types/TestSuiteInterface.hs
Labels: type: enhancement, documentation, Cabal: cmd/test, Cabal: stanza/test-suite/detailed-0.9, Cabal: stanza/test-suite/exitcode-stdio-1.0, merge me, merge delay passed
