Repository haskell/cabal, pull requests merged in 2022-03, with the labels that each got.

#7997 Add support for cabal.project fields to scripts
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/src/Distribution/Client/ScriptUtils.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptWithProjectBlock/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptWithProjectBlock/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptWithProjectBlock/s.hs
  changelog.d/pr-7851
  doc/cabal-commands.rst
Labels: merge me

#7942 Update old cabal examples to version 3.0
  doc/cabal-package.rst
Labels: documentation, merge me

#8022 Mark failing tests as expected failures, or fix them
  cabal-install/cabal-install.cabal
  cabal-testsuite/PackageTests/Backpack/Includes2/setup-external.test.hs
  cabal-testsuite/PackageTests/Backpack/Includes2/setup-per-component.test.hs
  cabal-testsuite/PackageTests/Backpack/Includes3/setup-external-ok.test.hs
  cabal-testsuite/PackageTests/CmmSourcesDyn/setup.test.hs
  cabal-testsuite/PackageTests/CustomPlain/setup.test.hs
  cabal-testsuite/PackageTests/ForeignLibs/setup.test.hs
  cabal-testsuite/PackageTests/NewBuild/T3827/cabal.test.hs
  cabal-testsuite/PackageTests/Regression/T4025/setup.test.hs
  cabal-testsuite/PackageTests/Regression/T4270/setup.test.hs
  cabal-testsuite/PackageTests/SPDX/cabal-old-build.test.hs
  cabal-testsuite/PackageTests/TestSuiteTests/ExeV10/cabal-with-hpc.multitest.hs
  cabal-testsuite/README.md
  cabal-testsuite/src/Test/Cabal/Prelude.hs
Labels: attention: needs-review

#8033 backticks (markdown files)
  CONTRIBUTING.md
  README.md
Labels: merge me

#8034 Add release notes for 3.6.3 and move release checklist to the wiki and update some
  Cabal/ChangeLog.md
  release-checklist.md
  release-notes/Cabal-3.6.3.0.md
Labels: documentation, release, attention: needs-review, merge me

#8020 Rebased version of #6703: Remove v2- prefix from command, package, and project docs.
  doc/cabal-commands.rst
  doc/cabal-package.rst
  doc/cabal-project.rst
Labels: attention: needs-review

#8006 allow trailing whitespace after flags
  Cabal-syntax/src/Distribution/Compat/CharParsing.hs
  Cabal-syntax/src/Distribution/Types/Flag.hs
Labels: merge me

#8041 Add changelog for #7279 and #8006
  changelog.d/issue-7279
Labels: merge me

#8042 Bootstrap generation fix for exe-only dependencies
  bootstrap/src/Main.hs
Labels: merge me

#7967 Use the cli flags in fetching packages in building a project config
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
Labels: merge me

#8046 fix typos
  Cabal-syntax/src/Distribution/Fields/Parser.hs
  Cabal-tests/tests/custom-setup/IdrisSetup.hs
  Cabal/src/Distribution/Compat/Process.hs
  Cabal/src/Distribution/Simple/Compiler.hs
  cabal-install-solver/src/Distribution/Solver/Modular/PSQ.hs
  cabal-install-solver/src/Distribution/Solver/Modular/Validate.hs
  cabal-install/src/Distribution/Client/CmdInstall.hs
  cabal-install/src/Distribution/Client/InstallPlan.hs
  cabal-install/src/Distribution/Client/PackageHash.hs
  cabal-install/src/Distribution/Client/ProjectBuilding.hs
  cabal-install/src/Distribution/Client/Targets.hs
  cabal-install/src/Distribution/Client/Types/ConfiguredId.hs
Labels: documentation, merge me

#8051 Rework gitlab ci config
  .gitlab-ci.yml
  .gitlab/brew.sh
  .gitlab/ci.sh
  .gitlab/shell.nix
Labels: attention: needs-review

#8045 Merge workflows
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/validate.yml
  .github/workflows/windows.yml
  .gitignore
  cabal-install/cabal-install.cabal
  cabal-install/tests/UnitTests/Distribution/Client/FileMonitor.hs
  cabal-install/tests/UnitTests/Distribution/Client/VCS.hs
  cabal-testsuite/PackageTests/ForeignLibs/setup.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptNoExtension/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptNoExtension/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptNoExtension/with sp
  cabal-testsuite/PackageTests/NewBuild/T3827/cabal.test.hs
  cabal-testsuite/PackageTests/Regression/T6906/cabal.test.hs
  cabal-testsuite/src/Test/Cabal/Prelude.hs
  cabal-testsuite/src/Test/Cabal/Server.hs
  doc/cabal-commands.rst
  validate.sh
Labels: attention: needs-review

#7921 Handle SIGTERM properly, on unix systems
  Cabal/src/Distribution/Simple/Program/Run.hs
  Cabal/src/Distribution/Simple/Utils.hs
  cabal-install/cabal-install.cabal
  cabal-install/main/Main.hs
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/src/Distribution/Client/Signal.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/Terminate/Main.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/Terminate/RunKill.cabal
  cabal-testsuite/PackageTests/NewBuild/CmdRun/Terminate/cabal.project
  cabal-testsuite/PackageTests/NewBuild/CmdRun/Terminate/cabal.test.hs
  cabal-testsuite/src/Test/Cabal/Run.hs
  changelog.d/pr-7921
Labels: merge me

#7959 Making the user aware of an unchanged .cabal file in cabal init
  cabal-install/src/Distribution/Client/Init/FileCreators.hs
  cabal-install/src/Distribution/Client/Init/Interactive/Command.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/Golden.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/Interactive.hs
  cabal-testsuite/PackageTests/Init/init-backup.out
  cabal-testsuite/PackageTests/Init/init-backup.test.hs
  cabal-testsuite/PackageTests/Init/init-interactive-legacy.test.hs
  cabal-testsuite/PackageTests/Init/init-interactive.test.hs
Labels: merge me

#8050 Update stack.yaml resolver and fix cabal-testsuite stack build
  cabal-testsuite/cabal-testsuite.cabal
  stack.yaml
Labels: merge me

#8054 Make enable/disable nix flag easier to read
  cabal-install/src/Distribution/Client/Setup.hs
  cabal-install/tests/IntegrationTests2.hs
  changelog.d/issue-8036
Labels: cabal-install: nix integration, re: help-text

#8056 #7776 regression tests
  Cabal-tests/Cabal-tests.cabal
  Cabal-tests/tests/CheckTests.hs
  Cabal-tests/tests/ParserTests/regressions/issue-7776-a.cabal
  Cabal-tests/tests/ParserTests/regressions/issue-7776-a.check
  Cabal-tests/tests/ParserTests/regressions/issue-7776-b.cabal
  Cabal-tests/tests/ParserTests/regressions/issue-7776-b.check
  Cabal-tests/tests/ParserTests/regressions/issue-7776-c.cabal
  Cabal-tests/tests/ParserTests/regressions/issue-7776-c.check
Labels: attention: needs-review, merge me

#8061 Derive Eq on DependencyMap
  Cabal-syntax/src/Distribution/Types/Dependency.hs
  Cabal-syntax/src/Distribution/Types/DependencyMap.hs
  changelog.d/pr-8061
Labels: merge me

#7970 ensure range headers are only sent when from < to
  cabal-install/src/Distribution/Client/Security/HTTP.hs
  changelog.d/pr-7970
Labels: attention: needs-review, squash+merge me

#8010 don't suggest 'all' target for run action
  cabal-install/src/Distribution/Client/TargetSelector.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/MultiplePackages/cabal.out
Labels: attention: needs-review

#7966 Fix the duplicate modules check
  Cabal-tests/tests/CheckTests.hs
  Cabal/src/Distribution/PackageDescription/Check.hs
Labels: Cabal: cmd/check, attention: needs-review, cabal-install: cmd/build

#8055 Enable hackage tests for windows
  Cabal-tests/Cabal-tests.cabal
  Cabal-tests/tests/HackageTests.hs
  validate.sh
Labels: merge me

#8065 Add support for the 64-bit S390X architecture
  Cabal-syntax/src/Distribution/System.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  Cabal/src/Distribution/Simple/PreProcess.hs
  changelog.d/pr-8065
Labels: merge me

#8070 fix spelling errors
  Cabal/src/Distribution/Backpack/Id.hs
  Cabal/src/Distribution/GetOpt.hs
  cabal-install-solver/src/Distribution/Solver/Modular/Dependency.hs
  cabal-install/src/Distribution/Client/FileMonitor.hs
  cabal-install/src/Distribution/Client/GlobalFlags.hs
  cabal-install/src/Distribution/Client/HttpUtils.hs
  cabal-install/src/Distribution/Client/IndexUtils.hs
  cabal-install/src/Distribution/Client/InstallPlan.hs
  cabal-install/src/Distribution/Client/ProjectBuilding.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  changelog.d/pr-7349
  changelog.d/pr-7407
Labels: merge me
