Repository haskell/cabal, pull requests merged in 2022-04, with the labels that each got.

#8081 Fix race condition in PackageTests/NewBuild/CmdRun/Terminate
  cabal-testsuite/PackageTests/NewBuild/CmdRun/Terminate/Main.hs
Labels: merge me

#8079 Drop build and CI support for GHC < 8.0
  .docker/validate-7.10.3.dockerfile
  .docker/validate-7.6.3.dockerfile
  .docker/validate-7.8.4.dockerfile
  Cabal-QuickCheck/Cabal-QuickCheck.cabal
  Cabal-described/Cabal-described.cabal
  Cabal-syntax/Cabal-syntax.cabal
  Cabal-syntax/src/Distribution/Compat/Binary.hs
  Cabal-syntax/src/Distribution/Compat/Binary/Class.hs
  Cabal-syntax/src/Distribution/Compat/Binary/Generic.hs
  Cabal-syntax/src/Distribution/Compat/Exception.hs
  Cabal-syntax/src/Distribution/Compat/Prelude.hs
  Cabal-syntax/src/Distribution/FieldGrammar/Class.hs
  Cabal-syntax/src/Distribution/Utils/Structured.hs
  Cabal-tests/Cabal-tests.cabal
  Cabal-tree-diff/src/Data/TreeDiff/Instances/Cabal.hs
  Cabal-tree-diff/src/Data/TreeDiff/Instances/CabalLanguage.hs
  Cabal-tree-diff/src/Data/TreeDiff/Instances/CabalSPDX.hs
  Cabal-tree-diff/src/Data/TreeDiff/Instances/CabalVersion.hs
  Cabal/Cabal.cabal
  Cabal/src/Distribution/Compat/Environment.hs
  Cabal/src/Distribution/Simple/Utils.hs
  Cabal/src/Distribution/Utils/MapAccum.hs
  Makefile
  bootstrap/linux-8.10.7.json
  bootstrap/linux-8.6.5.json
  bootstrap/linux-8.8.4.json
  cabal-dev-scripts/src/GenValidateDockerfile.hs
  cabal-testsuite/cabal-testsuite.cabal
Labels: merge me

#8085 Bootstrapping fix
  Makefile
  bootstrap/README.md
  bootstrap/cabal.project
  bootstrap/src/Main.hs
Labels: merge me

#8071 Changes to support new GHC 9.4's new Windows toolchain
  Cabal/src/Distribution/Simple/Compiler.hs
  Cabal/src/Distribution/Simple/Configure.hs
  Cabal/src/Distribution/Simple/Program/Ar.hs
  Cabal/src/Distribution/Simple/Setup.hs
  changelog.d/pr-8062
Labels: merge me

#8005 allow glob matches of the form dir/**/FileNoExtension
  Cabal-tests/tests/CheckTests.hs
  Cabal-tests/tests/ParserTests/regressions/globstar-literal.cabal
  Cabal-tests/tests/ParserTests/regressions/globstar-literal.check
  Cabal-tests/tests/ParserTests/regressions/pre-3.8-globstar-literal.cabal
  Cabal-tests/tests/ParserTests/regressions/pre-3.8-globstar-literal.check
  Cabal/src/Distribution/Simple/Glob.hs
  changelog.d/pr-8005
  doc/cabal-package.rst
  doc/file-format-changelog.rst
Labels: squash+merge me

#7425 Docs: add 'gen-bounds' and 'outdated' to the list of commands.
  doc/cabal-commands.rst
  doc/cabal-package.rst
Labels: squash+merge me

#8096 Add wasm32-wasi to recognized arch/os
  .github/workflows/validate.yml
  Cabal-syntax/src/Distribution/System.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  Cabal/src/Distribution/Simple/GHC.hs
  Cabal/src/Distribution/Simple/GHCJS.hs
  Cabal/src/Distribution/Simple/PreProcess.hs
  changelog.d/pr-8096
Labels: attention: needs-review, squash+merge me

#8101 Correct url to package properties
  Cabal/src/Distribution/PackageDescription/Check.hs
Labels: squash+merge me

#7764 Cabal: Use -flink-rts when available
  Cabal/src/Distribution/Simple/GHC.hs
  Cabal/src/Distribution/Simple/Program/GHC.hs
Labels: attention: needs-review, merge me

#8106 Update stale docs for configure
  cabal-install/src/Distribution/Client/CmdConfigure.hs
Labels: Cabal: cmd/configure, cabal-install: cmd/(re)configure, attention: needs-review, cabal-install: cmd/configure, squash+merge me

#8105 add explanation for what -w does in init context
  cabal-install/src/Distribution/Client/Setup.hs
Labels: cabal-install: cmd/init, merge me

#8111 Unmark foreign lib test as broken for win and ghc >= 9.0
  cabal-testsuite/PackageTests/ForeignLibs/setup.test.hs
  changelog.d/pr-7764
Labels: squash+merge me

#8116 Exclude broken 'Validate windows-latest ghc-8.4.4' job that cancels CI
  .github/workflows/validate.yml
Labels: merge me
