Repository haskell/cabal, pull requests merged in 2022-09, with the labels that each got.

#8448 [ mergify ] fix condition of 'merge delay passed' label
  .github/mergify.yml
Labels: attention: needs-review

#8445 Make validate.sh show the output of cabal-plan
  .github/workflows/validate.yml
  validate.sh
Labels: merge me, merge delay passed

#8449 Fixed changelog entry for haddock-package command
  changelog.d/pr-8162
Labels: merge me, merge delay passed

#8460 Revert "Revert "Turn off DeterministicTrivial test (see #8356)""
  cabal-testsuite/PackageTests/NewSdist/DeterministicTrivial/deterministic.test.hs
Labels: attention: needs-review

#8414 Pass some haddock flags to dependencies
  cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
  cabal-testsuite/PackageTests/HaddockArgs/cabal.project
  cabal-testsuite/PackageTests/HaddockArgs/example.cabal
  cabal-testsuite/PackageTests/HaddockArgs/hoogle.out
  cabal-testsuite/PackageTests/HaddockArgs/hoogle.test.hs
  cabal-testsuite/PackageTests/HaddockArgs/quickjump.out
  cabal-testsuite/PackageTests/HaddockArgs/quickjump.test.hs
  cabal-testsuite/PackageTests/HaddockArgs/repo/exe-0.1.0.0/Main.hs
  cabal-testsuite/PackageTests/HaddockArgs/repo/exe-0.1.0.0/exe.cabal
  cabal-testsuite/PackageTests/HaddockArgs/repo/indef-0.1.0.0/Foo.hs
  cabal-testsuite/PackageTests/HaddockArgs/repo/indef-0.1.0.0/indef.cabal
  cabal-testsuite/PackageTests/HaddockArgs/repo/sigs-0.1.0.0/Data/Map.hsig
  cabal-testsuite/PackageTests/HaddockArgs/repo/sigs-0.1.0.0/sigs.cabal
  cabal-testsuite/PackageTests/HaddockArgs/src/Lib.hs
  cabal-testsuite/src/Test/Cabal/Prelude.hs
  changelog.d/pr-8414
Labels: squash+merge me, merge delay passed

#8470 drop ci support for GHC 8.0.2
  .docker/validate-8.0.2.dockerfile
  .github/workflows/validate.yml
  Makefile
  cabal-dev-scripts/src/GenValidateDockerfile.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/Utils.hs
Labels: continuous-integration, merge me, merge delay passed

#8368 Allow offline bootstrapping of cabal-install
  .github/workflows/bootstrap.yml
  bootstrap/README.md
  bootstrap/bootstrap.py
  changelog.d/pr-8368
Labels: continuous-integration, cabal-install: bootstrap, merge me, merge delay passed

#8407 cabal man handles $PAGER with more than one word now
  cabal-install/src/Distribution/Client/Manpage.hs
  changelog.d/issue-8405
Labels: merge me, merge delay passed

#8384 gitlab CI generates deb11 images
  .gitlab-ci.yml
Labels: merge me, merge delay passed

#8358 only check for compiler when project file has conditionals
  cabal-install/src/Distribution/Client/CmdOutdated.hs
  cabal-install/src/Distribution/Client/CmdSdist.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/ScriptUtils.hs
  changelog.d/pr-8358
  doc/cabal-project.rst
Labels: squash+merge me, merge delay passed

#8433 Reorder `cabal help` commands
  cabal-install/src/Distribution/Client/Setup.hs
Labels: merge me, merge delay passed

#8485 Bump unix bound to allow unix-2.8
  Cabal-syntax/Cabal-syntax.cabal
  Cabal/Cabal.cabal
Labels: merge me, merge delay passed

#6566 [ci skip] Enable opensearch in Cabal documentation
  doc/conf.py
Labels: documentation, merge me, re: readthedocs, merge delay passed

#8420 Support GHC 9.4
  .github/workflows/validate.yml
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
  cabal-testsuite/PackageTests/Backpack/Includes2/setup-external.test.hs
  cabal-testsuite/PackageTests/Backpack/Includes2/setup-per-component.test.hs
  cabal-testsuite/PackageTests/Backpack/Includes3/setup-external-ok.test.hs
  cabal-testsuite/PackageTests/CCompilerOverride/setup.test.hs
  cabal-testsuite/PackageTests/CustomPreProcess/cabal.test.hs
  cabal-testsuite/PackageTests/FFI/ForeignOptsC/cabal.test.hs
  cabal-testsuite/PackageTests/FFI/ForeignOptsCxx/cabal.test.hs
  cabal-testsuite/PackageTests/ForeignLibs/UseLib.c
  cabal-testsuite/PackageTests/ForeignLibs/setup.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdBench/OptionsFlag/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdBuild/Script/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdBuild/ScriptBuildRepl/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdBuild/ScriptBuildRun/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdBuild/ScriptRerun/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdClean/Keep/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdClean/Orphan/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdClean/Script/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/Script/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptLiterate/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptNoExtension/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptRerun/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptWithProjectBlock/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdTest/OptionsFlag/cabal.test.hs
  cabal-testsuite/cabal-testsuite.cabal
Labels: merge me, merge delay passed

#8503 Work around CI problem from ghcup switch to GHC 9.2
  .github/workflows/quick-jobs.yml
  cabal-dev-scripts/cabal-dev-scripts.cabal
Labels: attention: needs-review

#8505 Stick to GHC 8.10.7 in CI until changelog-d is updated and update CI job names to permit making them mandatory in Settings
  .github/workflows/changelogs.yml
  .github/workflows/users-guide.yml
  .github/workflows/whitespace.yml
Labels: attention: needs-review

#8493 add DeepSubsumption and TypeData language extensions (ghc proposals 511 & 106)
  Cabal-syntax/src/Language/Haskell/Extension.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  changelog.d/pr-8493
  editors/vim/syntax/cabal.vim
Labels: squash+merge me, attention: needs-backport 3.8, merge delay passed
