Repository haskell/cabal, pull requests merged in 2022-08, with the labels that each got.

#8333 Give an example for `--enable-nix` flag
  doc/nix-integration.rst
Labels: documentation, cabal-install: nix integration, squash+merge me

#8338 Turn off T3827 for Linux and OSX due to heisenbugs not caused by cabal
  cabal-testsuite/PackageTests/NewBuild/T3827/cabal.test.hs
Labels: continuous-integration, attention: needs-review, cabal-testsuite

#8220 When generating `Paths` modules, define functions when used
  Cabal/src/Distribution/Simple/Build/PathsModule/Z.hs
  cabal-testsuite/PackageTests/PathsModule/Executable-Relocatable/Main.hs
  cabal-testsuite/PackageTests/PathsModule/Executable-Relocatable/my.cabal
  cabal-testsuite/PackageTests/PathsModule/Executable-Relocatable/setup.cabal.out
  cabal-testsuite/PackageTests/PathsModule/Executable-Relocatable/setup.out
  cabal-testsuite/PackageTests/PathsModule/Executable-Relocatable/setup.test.hs
  changelog.d/pr-8220
  templates/Paths_pkg.template.hs
Labels: merge me

#8362 Clean up 3.8.1.0 changelogs
  release-notes/Cabal-3.8.1.0.md
  release-notes/cabal-install-3.8.1.0.md
Labels: documentation, release

#8364 Document multiple public libraries
  doc/buildinfo-fields-reference.rst
  doc/cabal-package.rst
  doc/file-format-changelog.rst
Labels: documentation, attention: needs-backport 3.8

#8373 Fix compilation on old GHCs (fixes #8371)
  Cabal-syntax/Cabal-syntax.cabal
  Cabal/Cabal.cabal
Labels: attention: needs-review, attention: needs-backport 3.8

#8342 Bump package process dependency version to 1.6.15.0 and move from Cabal to cabal-install
  Cabal/Cabal.cabal
  bootstrap/linux-8.10.7.json
  bootstrap/linux-8.6.5.json
  bootstrap/linux-8.8.4.json
  bootstrap/linux-9.0.2.json
  bootstrap/linux-9.2.3.json
  cabal-install/cabal-install.cabal
Labels: attention: needs-review, merge me, attention: needs-backport 3.8

#8353 Expose BuildFlags and ClientHaddockFlags
  cabal-install/src/Distribution/Client/CmdBuild.hs
  cabal-install/src/Distribution/Client/CmdHaddock.hs
  changelog.d/issue-8351
Labels: cabal-install: other, attention: needs-review, squash+merge me

#8388 Exclude CI job 8.10.7 on Windows that corrupts all CI
  .github/workflows/validate.yml
  cabal-testsuite/PackageTests/NewSdist/DeterministicTrivial/deterministic.test.hs
Labels: continuous-integration, attention: needs-review

#8346 [ docs ] fix typo in cabal update’s help
  cabal-install/src/Distribution/Client/CmdUpdate.hs
Labels: documentation, newcomer: 1-one-line-change, merge me, attention: needs-backport 3.8

#8344 Fix optional test-suite/benchmark type docs
  doc/cabal-package.rst
Labels: merge me, attention: needs-backport 3.8

#8330 unbreak cabal haddock --disable-documentation
  cabal-install/src/Distribution/Client/CmdHaddock.hs
  cabal-testsuite/PackageTests/NewHaddock/DisableDoc/B/B.cabal
  cabal-testsuite/PackageTests/NewHaddock/DisableDoc/B/B.hs
  cabal-testsuite/PackageTests/NewHaddock/DisableDoc/cabal.out
  cabal-testsuite/PackageTests/NewHaddock/DisableDoc/cabal.project
  cabal-testsuite/PackageTests/NewHaddock/DisableDoc/cabal.test.hs
  cabal-testsuite/PackageTests/NewHaddock/DisableDoc/repo/A-0.1.0.0/A.cabal
  cabal-testsuite/PackageTests/NewHaddock/DisableDoc/repo/A-0.1.0.0/A.hs
Labels: merge me, regression on master, attention: needs-backport in the future

#8415 CI: bump fix-whitespace to 0.0.10
  .github/workflows/whitespace.yml
Labels: continuous-integration

#8403 Bump cabal-bootstrap-gen to GHC 9.2.4 ecosystem.
  bootstrap/README.md
  bootstrap/cabal-bootstrap-gen.cabal
  bootstrap/src/Main.hs
Labels: cabal-install: bootstrap, merge me

#8417 Add some debugging to CmdRun/Terminate test
  cabal-testsuite/PackageTests/NewBuild/CmdRun/Terminate/Main.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/Terminate/RunKill.cabal
  cabal-testsuite/PackageTests/NewBuild/CmdRun/Terminate/cabal.test.hs
Labels: attention: needs-review, merge me

#8396 Updated warning message to output on stderr
  cabal-install/main/Main.hs
Labels: squash+merge me, re: warnings

#8375 facelift for README
  README.md
Labels: documentation, merge me

#8398 Fix #8377: allow text-2.0 and time-1.12 in cabal-install
  cabal-install/cabal-install.cabal
  cabal-testsuite/cabal-testsuite.cabal
  cabal-testsuite/src/Test/Cabal/Prelude.hs
  cabal.project
Labels: merge me, attention: needs-backport 3.8

#8311 Add PackageCheck pretty print
  Cabal/src/Distribution/PackageDescription/Check.hs
  Cabal/src/Distribution/Simple/Configure.hs
  Cabal/src/Distribution/Simple/SrcDist.hs
  changelog.d/pr-8311
Labels: cabal-install: cmd/check, merge me, re: code quality

#8332 Organise cabal commands into subsections
  doc/cabal-commands.rst
Labels: merge me

#8381 Add test summary
  cabal-testsuite/main/cabal-tests.hs
Labels: merge me

#7611 testsuite: remove file generated by autoheader
  cabal-testsuite/PackageTests/Configure/include/.gitkeep
  cabal-testsuite/PackageTests/Configure/include/HsZlibConfig.h.in
Labels: squash+merge me, re: devx

#8432 Remove warning on option -threaded when building libraries
  Cabal-tests/tests/ParserTests/regressions/issue-774.check
  Cabal/src/Distribution/PackageDescription/Check.hs
  changelog.d/pr-8432
Labels: squash+merge me
