Repository haskell/cabal, pull requests merged in 2022-10, with the labels that each got.

#8488 "Build profile" now reflects optimization level set in global config
  cabal-install/src/Distribution/Client/ProjectOrchestration.hs
  cabal-testsuite/PackageTests/ConfigFile/T8487/cabal.out
  cabal-testsuite/PackageTests/ConfigFile/T8487/cabal.project
  cabal-testsuite/PackageTests/ConfigFile/T8487/cabal.test.hs
  cabal-testsuite/PackageTests/ConfigFile/T8487/config.file
  cabal-testsuite/PackageTests/ConfigFile/T8487/src/MyLib.hs
  cabal-testsuite/PackageTests/ConfigFile/T8487/test.cabal
  changelog.d/issue-8487
Labels: merge me, merge delay passed

#8336 Don't warn about 'prepositive-qualified-module' in Paths_pkgs
  Cabal/src/Distribution/Simple/Build/PathsModule/Z.hs
  cabal-testsuite/PackageTests/PathsModule/ImportQualifiedPost/Main.hs
  cabal-testsuite/PackageTests/PathsModule/ImportQualifiedPost/my.cabal
  cabal-testsuite/PackageTests/PathsModule/ImportQualifiedPost/setup.cabal.out
  cabal-testsuite/PackageTests/PathsModule/ImportQualifiedPost/setup.out
  cabal-testsuite/PackageTests/PathsModule/ImportQualifiedPost/setup.test.hs
  templates/Paths_pkg.template.hs
Labels: merge me, re: warnings, attention: needs-backport 3.8, merge delay passed

#8508 Use munch1 to parse Language
  Cabal-syntax/src/Language/Haskell/Extension.hs
  cabal-testsuite/PackageTests/Regression/T8507/Foo.hs
  cabal-testsuite/PackageTests/Regression/T8507/cabal.out
  cabal-testsuite/PackageTests/Regression/T8507/cabal.project
  cabal-testsuite/PackageTests/Regression/T8507/cabal.test.hs
  cabal-testsuite/PackageTests/Regression/T8507/pkg.cabal
  fix-whitespace.yaml
Labels: squash+merge me, merge delay passed

#8296 print out dependency build failure during cabal build / repl
  cabal-install/src/Distribution/Client/CmdBuild.hs
  cabal-install/src/Distribution/Client/CmdHaddockProject.hs
  cabal-install/src/Distribution/Client/CmdListBin.hs
  cabal-install/src/Distribution/Client/CmdRepl.hs
  cabal-install/src/Distribution/Client/CmdRun.hs
  cabal-install/src/Distribution/Client/ProjectOrchestration.hs
  cabal-install/src/Distribution/Client/ScriptUtils.hs
  cabal-testsuite/PackageTests/CustomWithoutCabal/cabal.out
  cabal-testsuite/PackageTests/CustomWithoutCabalDefaultMain/cabal.out
  cabal-testsuite/PackageTests/NewBuild/MonitorCabalFiles/cabal.out
  cabal-testsuite/PackageTests/NewHaddock/Fails/cabal.out
  cabal-testsuite/PackageTests/ShowBuildInfo/CompileFail/compile-fail.out
Labels: merge me, merge delay passed

#8516 CI: mergify should label automatic backports as such
  .github/mergify.yml
Labels: merge me

#8350 *.project.* files use program-options to specify -fno-ignore-asserts
  cabal.project
  cabal.project.coverage
  cabal.project.libonly
  cabal.project.validate
  cabal.project.validate.libonly
Labels: attention: needs-review, merge me, merge delay passed

#8546 Work around git problem with file transport
  .github/workflows/validate.yml
Labels: continuous-integration

#8499 ordNub for extra stanzas
  Cabal/src/Distribution/Simple/Build.hs
  changelog.d/pr-8499
Labels: attention: needs-review, squash+merge me, merge delay passed

#8522 Fix nix config option
  cabal-install/src/Distribution/Client/Setup.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/IntegrationTests2/nix-config/default-config
  cabal-install/tests/IntegrationTests2/nix-config/nix-false
  cabal-install/tests/IntegrationTests2/nix-config/nix-true
  changelog.d/issue-8452
Labels: squash+merge me, merge delay passed

#8545 Elaborate on XDG directories in users guide.
  doc/config.rst
Labels: documentation, attention: needs-review, merge me, merge delay passed, xdg
