Repository haskell/cabal, pull requests merged in 2022-07, with the labels that each got.

#8258 Simplify -Werror warning
  Cabal/src/Distribution/PackageDescription/Check.hs
  cabal-testsuite/PackageTests/Check/DifferentGhcOptions/cabal.out
Labels: merge me

#8240 Print a warning when assertions are enabled
  cabal-install/main/Main.hs
  changelog.d/pr-8240
Labels: attention: needs-review

#8259 cabal haddock imply enable-documentation
  cabal-install/src/Distribution/Client/CmdHaddock.hs
  cabal-testsuite/PackageTests/NewHaddock/ImplyDependencies/B/B.cabal
  cabal-testsuite/PackageTests/NewHaddock/ImplyDependencies/B/B.hs
  cabal-testsuite/PackageTests/NewHaddock/ImplyDependencies/cabal.out
  cabal-testsuite/PackageTests/NewHaddock/ImplyDependencies/cabal.project
  cabal-testsuite/PackageTests/NewHaddock/ImplyDependencies/cabal.test.hs
  cabal-testsuite/PackageTests/NewHaddock/ImplyDependencies/repo/A-0.1.0.0/A.cabal
  cabal-testsuite/PackageTests/NewHaddock/ImplyDependencies/repo/A-0.1.0.0/A.hs
  changelog.d/issue-7462
  doc/cabal-project.rst
Labels: merge me

#8272 Build release archives (and validate) with GHC 9.2.3
  .github/workflows/bootstrap.yml
  .github/workflows/validate.yml
  .gitlab-ci.yml
  changelog.d/pr-8272
Labels: attention: needs-review, merge me, attention: needs-backport 3.8

#8267 cabal init -i should autodetect author name and maintainer email
  cabal-install/src/Distribution/Client/Init/Interactive/Command.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/Golden.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/Interactive.hs
  changelog.d/issue-8255
Labels: squash+merge me, attention: needs-backport 3.8

#8277 cabal init -i: add the GHC2021 language option
  cabal-install/src/Distribution/Client/Init/Interactive/Command.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/Interactive.hs
  cabal-testsuite/PackageTests/Init/init-interactive-ghc2021.out
  cabal-testsuite/PackageTests/Init/init-interactive-ghc2021.test.hs
  changelog.d/issue-8265
Labels: merge me, attention: needs-backport 3.8

#8279 Bump dependency on process
  Cabal/Cabal.cabal
  bootstrap/linux-8.10.7.json
  bootstrap/linux-8.6.5.json
  bootstrap/linux-8.8.4.json
  bootstrap/linux-9.0.2.json
  bootstrap/linux-9.2.3.json
Labels: attention: needs-review, merge me, attention: needs-backport 3.8

#6293 Improve --test/benchmark-options test accuracy
  cabal-testsuite/PackageTests/NewBuild/CmdBench/OptionsFlag/OptionsFlag.hs
  cabal-testsuite/PackageTests/NewBuild/CmdTest/OptionsFlag/OptionsFlag.hs
Labels: merge me

#8260 bump known ghc versions in cabal library
  Cabal/src/Distribution/Simple/GHC.hs
Labels: squash+merge me, attention: needs-backport 3.8

#8261 Implement --prefer-oldest
  cabal-install-solver/src/Distribution/Solver/Modular/Preference.hs
  cabal-install-solver/src/Distribution/Solver/Types/InstalledPreference.hs
  cabal-install-solver/src/Distribution/Solver/Types/Settings.hs
  cabal-install/src/Distribution/Client/Config.hs
  cabal-install/src/Distribution/Client/Dependency.hs
  cabal-install/src/Distribution/Client/Dependency/Types.hs
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Types.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/Setup.hs
  cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
  cabal-install/tests/UnitTests/Distribution/Client/TreeDiffInstances.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL/TestCaseUtils.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
  changelog.d/pr-8261
  doc/cabal-project.rst
Labels: squash+merge me, attention: needs-backport in the future

#8290 Clarify assertionsEnabledMsg
  cabal-install/main/Main.hs
Labels: merge me, re: warnings, attention: needs-backport in the future

#8292 cabal init -n: avoid extra blank lines
  Cabal-syntax/src/Distribution/Fields/Pretty.hs
  cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-and-exe-no-comments.golden
  cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-and-exe-with-comments.golden
  cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-no-comments.golden
  cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-with-comments.golden
  changelog.d/issue-8236
Labels: attention: needs-review, merge me, attention: needs-backport 3.8

#8297 Fix cabal-version 3.4 description in cabal init
  cabal-install/src/Distribution/Client/Init/Interactive/Command.hs
Labels: squash+merge me

#8269 `cabal check`: add typed errors
  Cabal-syntax/src/Distribution/Compiler.hs
  Cabal-syntax/src/Distribution/License.hs
  Cabal-syntax/src/Distribution/Parsec/Warning.hs
  Cabal-syntax/src/Distribution/Types/Benchmark.hs
  Cabal-syntax/src/Distribution/Types/BenchmarkInterface.hs
  Cabal-syntax/src/Distribution/Types/BenchmarkType.hs
  Cabal-syntax/src/Distribution/Types/BuildInfo.hs
  Cabal-syntax/src/Distribution/Types/BuildType.hs
  Cabal-syntax/src/Distribution/Types/Dependency.hs
  Cabal-syntax/src/Distribution/Types/ExeDependency.hs
  Cabal-syntax/src/Distribution/Types/Executable.hs
  Cabal-syntax/src/Distribution/Types/ExecutableScope.hs
  Cabal-syntax/src/Distribution/Types/ForeignLib.hs
  Cabal-syntax/src/Distribution/Types/ForeignLibOption.hs
  Cabal-syntax/src/Distribution/Types/ForeignLibType.hs
  Cabal-syntax/src/Distribution/Types/LegacyExeDependency.hs
  Cabal-syntax/src/Distribution/Types/Library.hs
  Cabal-syntax/src/Distribution/Types/LibraryVisibility.hs
  Cabal-syntax/src/Distribution/Types/ModuleReexport.hs
  Cabal-syntax/src/Distribution/Types/PackageDescription.hs
  Cabal-syntax/src/Distribution/Types/PkgconfigDependency.hs
  Cabal-syntax/src/Distribution/Types/PkgconfigVersionRange.hs
  Cabal-syntax/src/Distribution/Types/SetupBuildInfo.hs
  Cabal-syntax/src/Distribution/Types/TestSuite.hs
  Cabal-syntax/src/Distribution/Types/TestSuiteInterface.hs
  Cabal-syntax/src/Distribution/Types/TestType.hs
  Cabal-syntax/src/Distribution/Types/VersionRange/Internal.hs
  Cabal-syntax/src/Language/Haskell/Extension.hs
  Cabal/src/Distribution/PackageDescription/Check.hs
  Cabal/src/Distribution/Simple/Configure.hs
  Cabal/src/Distribution/Simple/SrcDist.hs
  cabal-install/src/Distribution/Client/Check.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs
  cabal-testsuite/PackageTests/BuildToolDependsInternalMissing/setup.cabal.out
  cabal-testsuite/PackageTests/BuildToolDependsInternalMissing/setup.out
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Paths/DistPoint/cabal.out
  cabal-testsuite/PackageTests/Check/MissingGlobDirectory2/cabal.out
Labels: attention: needs-review, squash+merge me

#8285 [ mergify ] require 2 days to pass after last update of PR to merge it
  .github/mergify.yml
  CONTRIBUTING.md
Labels: squash+merge me

#8310 Accept unknown future GHCs in the argument filtering code
  Cabal/src/Distribution/Simple/Program/GHC.hs
  changelog.d/pr-8310
Labels: attention: needs-review, squash+merge me, re: ghc-options, attention: needs-backport 3.8

#8321 Temporarily revert #7995 and #7921 due to #8208
  Cabal/src/Distribution/Compat/Process.hs
  Cabal/src/Distribution/Simple/Program/Run.hs
  Cabal/src/Distribution/Simple/Test/LibV09.hs
  Cabal/src/Distribution/Simple/Utils.hs
  cabal-install/cabal-install.cabal
  cabal-install/main/Main.hs
  cabal-install/src/Distribution/Client/Compat/Process.hs
  cabal-install/src/Distribution/Client/Init/Types.hs
  cabal-install/src/Distribution/Client/Manpage.hs
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/src/Distribution/Client/SetupWrapper.hs
  cabal-install/src/Distribution/Client/Signal.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/Terminate/Main.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/Terminate/RunKill.cabal
  cabal-testsuite/PackageTests/NewBuild/CmdRun/Terminate/cabal.project
  cabal-testsuite/PackageTests/NewBuild/CmdRun/Terminate/cabal.test.hs
  cabal-testsuite/src/Test/Cabal/Run.hs
  cabal-testsuite/src/Test/Cabal/Server.hs
  changelog.d/pr-7921
  changelog.d/pr-7995
Labels: attention: needs-review, merge me

#8322 Prepare 3.8.1.0 release (or at least a legitimate tag)
  Cabal-QuickCheck/Cabal-QuickCheck.cabal
  Cabal-described/Cabal-described.cabal
  Cabal-syntax/Cabal-syntax.cabal
  Cabal-tree-diff/Cabal-tree-diff.cabal
  Cabal/Cabal.cabal
  Cabal/Makefile
  bootstrap/linux-8.10.7.json
  bootstrap/linux-8.6.5.json
  bootstrap/linux-8.8.4.json
  bootstrap/linux-9.0.2.json
  bootstrap/linux-9.2.3.json
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/Version.hs
  doc/conf.py
Labels: release, attention: needs-review, merge me

#8327 Fixup headers of 3.8.1.0 release notes
  release-notes/Cabal-3.8.1.0.md
  release-notes/cabal-install-3.8.1.0.md
Labels: release, merge me, attention: needs-backport 3.8

#8309 Document missing commands
  changelog.d/pr-8309
  doc/cabal-commands.rst
  doc/developing-packages.rst
Labels: documentation, attention: needs-review
