Repository haskell/cabal, pull requests merged in 2023-03, with the labels that each got.

#8454 Add --project-dir flag
  cabal-install/src/Distribution/Client/CmdClean.hs
  cabal-install/src/Distribution/Client/CmdOutdated.hs
  cabal-install/src/Distribution/Client/Config.hs
  cabal-install/src/Distribution/Client/DistDirLayout.hs
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Types.hs
  cabal-install/src/Distribution/Client/ProjectFlags.hs
  cabal-install/src/Distribution/Client/ProjectOrchestration.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/UnitTests/Distribution/Client/Configure.hs
  cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
  cabal-install/tests/fixtures/project-root/cabal.project
  cabal-install/tests/fixtures/project-root/cabal.project.other
  cabal-install/tests/fixtures/project-root/lib/.gitkeep
  cabal-install/tests/fixtures/project-root/nix/cabal.project
  cabal-install/tests/fixtures/project-root/nix/cabal.project.other
  cabal-testsuite/PackageTests/ConditionalAndImport/cabal.test.hs
  cabal-testsuite/PackageTests/Outdated/outdated-project-file.out
  cabal-testsuite/PackageTests/ProjectDir/app/App.hs
  cabal-testsuite/PackageTests/ProjectDir/app/app.cabal
  cabal-testsuite/PackageTests/ProjectDir/cabal.test.hs
  cabal-testsuite/PackageTests/ProjectDir/proj/App.hs
  cabal-testsuite/PackageTests/ProjectDir/proj/Lib.hs
  cabal-testsuite/PackageTests/ProjectDir/proj/cabal.project
  cabal-testsuite/PackageTests/ProjectDir/proj/nix/cabal.project
  cabal-testsuite/PackageTests/ProjectDir/proj/proj.cabal
  changelog.d/pr-8454
  doc/cabal-project.rst
Labels: merge me, re: project-file, merge delay passed

#8821 Disable everfailing assertion
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
Labels: squash+merge me, merge delay passed

#8755 Return empty default when git fails
  cabal-install/src/Distribution/Client/Init/Interactive/Command.hs
  cabal-install/src/Distribution/Client/Init/NonInteractive/Command.hs
  cabal-install/src/Distribution/Client/Init/NonInteractive/Heuristics.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/FileCreators.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/NonInteractive.hs
Labels: attention: needs-review, merge me, merge delay passed, attention: needs-backport 3.10

#8834 Add 3.10.1.0 changelogs and remove the used up tiny changlog files
  Cabal/ChangeLog.md
  cabal-install/changelog
  changelog.d/issue-1954
  changelog.d/issue-4255
  changelog.d/issue-4994
  changelog.d/issue-7462
  changelog.d/issue-8189
  changelog.d/issue-8351
  changelog.d/issue-8405
  changelog.d/issue-8452
  changelog.d/issue-8487
  changelog.d/issue-8489
  changelog.d/issue-8564
  changelog.d/issue-8637
  changelog.d/issue-8646
  changelog.d/pr-7386
  changelog.d/pr-7794
  changelog.d/pr-8162
  changelog.d/pr-8220
  changelog.d/pr-8237
  changelog.d/pr-8240
  changelog.d/pr-8261
  changelog.d/pr-8281
  changelog.d/pr-8309
  changelog.d/pr-8311
  changelog.d/pr-8339
  changelog.d/pr-8358
  changelog.d/pr-8368
  changelog.d/pr-8414
  changelog.d/pr-8432
  changelog.d/pr-8441
  changelog.d/pr-8493
  changelog.d/pr-8496
  changelog.d/pr-8498
  changelog.d/pr-8499
  changelog.d/pr-8500
  changelog.d/pr-8506
  changelog.d/pr-8510
  changelog.d/pr-8528
  changelog.d/pr-8534
  changelog.d/pr-8556
  changelog.d/pr-8561
  changelog.d/pr-8582
  changelog.d/pr-8607
  changelog.d/pr-8633
  changelog.d/pr-8636
  changelog.d/pr-8640
  changelog.d/pr-8647
  changelog.d/pr-8648
  changelog.d/pr-8657
  changelog.d/pr-8663
  changelog.d/pr-8686
  changelog.d/pr-8732
  changelog.d/pr-8794
  release-notes/Cabal-3.10.1.0.md
  release-notes/cabal-install-3.10.1.0.md
Labels: release, attention: needs-review, merge me, backport

#8836 Stabilize use of brew in GitLab CI
  .gitlab-ci.yml
  .gitlab/brew.sh
Labels: continuous-integration, release, merge me, merge delay passed

#8676 Fix --offline flag
  cabal-install/src/Distribution/Client/BuildReports/Anonymous.hs
  cabal-install/src/Distribution/Client/Install.hs
  cabal-install/src/Distribution/Client/ProjectBuilding.hs
  cabal-install/src/Distribution/Client/ProjectBuilding/Types.hs
  cabal-install/src/Distribution/Client/ProjectOrchestration.hs
  cabal-install/src/Distribution/Client/Types/BuildResults.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-testsuite/PackageTests/OfflineFlag/Main.hs
  cabal-testsuite/PackageTests/OfflineFlag/cabal.repo.project
  cabal-testsuite/PackageTests/OfflineFlag/main.cabal
  cabal-testsuite/PackageTests/OfflineFlag/offlineFlag.out
  cabal-testsuite/PackageTests/OfflineFlag/offlineFlag.test.hs
  cabal-testsuite/PackageTests/OfflineFlag/repo/remote-0.1.0.0/P.hs
  cabal-testsuite/PackageTests/OfflineFlag/repo/remote-0.1.0.0/remote.cabal
  changelog.d/pr-8676
Labels: cabal-install: other, squash+merge me, merge delay passed, attention: needs-backport 3.10

#8844 Bump versions and deps on master branch to 3.11 and regenerate bootstrap files
  .github/workflows/bootstrap.yml
  .github/workflows/validate.yml
  Cabal-QuickCheck/Cabal-QuickCheck.cabal
  Cabal-described/Cabal-described.cabal
  Cabal-syntax/Cabal-syntax.cabal
  Cabal-syntax/src/Distribution/CabalSpecVersion.hs
  Cabal-tree-diff/Cabal-tree-diff.cabal
  Cabal/Cabal.cabal
  Cabal/Makefile
  Makefile
  bootstrap/cabal-bootstrap-gen.cabal
  bootstrap/cabal.project
  bootstrap/linux-8.10.7.json
  bootstrap/linux-8.6.5.json
  bootstrap/linux-8.8.4.json
  bootstrap/linux-9.2.3.json
  bootstrap/linux-9.2.7.json
  bootstrap/linux-9.4.4.json
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/Version.hs
  cabal-testsuite/cabal-testsuite.cabal
  doc/conf.py
  solver-benchmarks/solver-benchmarks.cabal
Labels: release, attention: needs-review, squash+merge me, merge delay passed

#8852 CI: disable prerelease validation
  .github/workflows/validate.yml
Labels: continuous-integration, attention: needs-review, merge delay passed

#8839 Allow no-comments, quiet, simple, minimal in init section of config
  cabal-install/src/Distribution/Client/Config.hs
  cabal-testsuite/PackageTests/ConfigFile/InitSectionFields/cabal.out
  cabal-testsuite/PackageTests/ConfigFile/InitSectionFields/cabal.test.hs
  changelog.d/issue-8835
Labels: cabal-install: cmd/init, merge me, merge delay passed

#8816 Pull revision onto 3.8 branch: Cabal: allow mtl-2.3 and transformers-0.6
  Cabal/Cabal.cabal
Labels: merge me, re: dependencies, merge delay passed

#8851 GitLab CI: Add aarch64-linux-deb{10,11}
  .gitlab-ci.yml
Labels: continuous-integration, merge me, merge delay passed

#8871 Fix a typo in the split-objs/split-sections warning message
  Cabal/src/Distribution/Simple/Configure.hs
Labels: merge me, merge delay passed
