Repository haskell/cabal, pull requests merged in 2023-08, with the labels that each got.

#9143 Subsequent Cabal Exceptions
  Cabal/src/Distribution/Simple/BuildTarget.hs
  Cabal/src/Distribution/Simple/ConfigureScript.hs
  Cabal/src/Distribution/Simple/Errors.hs
  Cabal/src/Distribution/Simple/GHC.hs
  Cabal/src/Distribution/Simple/GHCJS.hs
  Cabal/src/Distribution/Simple/PackageDescription.hs
  Cabal/src/Distribution/Simple/PreProcess.hs
  Cabal/src/Distribution/Simple/PreProcess/Unlit.hs
  cabal-testsuite/PackageTests/BuildTargetErrors/setup.out
  cabal-testsuite/PackageTests/GhcPkgGuess/SameDirectory/setup.cabal.out
  cabal-testsuite/PackageTests/GhcPkgGuess/SameDirectory/setup.out
  cabal-testsuite/PackageTests/GhcPkgGuess/SameDirectoryGhcVersion/setup.cabal.out
  cabal-testsuite/PackageTests/GhcPkgGuess/SameDirectoryGhcVersion/setup.out
  cabal-testsuite/PackageTests/GhcPkgGuess/SameDirectoryVersion/setup.cabal.out
  cabal-testsuite/PackageTests/GhcPkgGuess/SameDirectoryVersion/setup.out
  cabal-testsuite/PackageTests/GhcPkgGuess/Symlink/setup.cabal.out
  cabal-testsuite/PackageTests/GhcPkgGuess/Symlink/setup.out
  cabal-testsuite/PackageTests/GhcPkgGuess/SymlinkGhcVersion/setup.cabal.out
  cabal-testsuite/PackageTests/GhcPkgGuess/SymlinkGhcVersion/setup.out
  cabal-testsuite/PackageTests/GhcPkgGuess/SymlinkVersion/setup.cabal.out
  cabal-testsuite/PackageTests/GhcPkgGuess/SymlinkVersion/setup.out
Labels: squash+merge me, merge delay passed

#8980 Add alex to build-tool-depends remove separate code gen
  Cabal-syntax/Cabal-syntax.cabal
  Cabal-syntax/src/Distribution/Fields/Lexer.x
  Makefile
  bootstrap/bootstrap.py
  bootstrap/cabal.project
  bootstrap/linux-8.10.7.json
  bootstrap/linux-9.0.2.json
  bootstrap/linux-9.2.7.json
  bootstrap/linux-9.4.4.json
  bootstrap/src/Main.hs
Labels: squash+merge me, merge delay passed

#9167 Address CVE-2023-37920
  doc/requirements.in
  doc/requirements.txt
Labels: merge me, merge delay passed

#9162 Successive Cabal Package Errors
  Cabal/src/Distribution/PackageDescription/Check.hs
  Cabal/src/Distribution/Simple.hs
  Cabal/src/Distribution/Simple/Build.hs
  Cabal/src/Distribution/Simple/Configure.hs
  Cabal/src/Distribution/Simple/Errors.hs
  Cabal/src/Distribution/Simple/Program/Run.hs
  cabal-testsuite/PackageTests/AutogenModules/Package/setup.cabal.out
  cabal-testsuite/PackageTests/AutogenModules/Package/setup.out
  cabal-testsuite/PackageTests/AutogenModules/Package/setup.test.hs
  cabal-testsuite/PackageTests/Backpack/Reexport2/setup.cabal.out
  cabal-testsuite/PackageTests/Backpack/Reexport2/setup.out
  cabal-testsuite/PackageTests/BuildDeps/InternalLibrary0/setup.cabal.out
  cabal-testsuite/PackageTests/BuildDeps/InternalLibrary0/setup.out
  cabal-testsuite/PackageTests/BuildToolDependsInternalMissing/setup.cabal.out
  cabal-testsuite/PackageTests/BuildToolDependsInternalMissing/setup.out
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Sanity/AutogenExposedOther/cabal.out
  cabal-testsuite/PackageTests/ConfigureComponent/SubLib/setup-explicit-fail.out
  cabal-testsuite/PackageTests/InternalVersions/BuildDependsBad/setup.cabal.out
  cabal-testsuite/PackageTests/InternalVersions/BuildDependsBad/setup.out
  cabal-testsuite/PackageTests/InternalVersions/BuildToolDependsBad/setup.cabal.out
  cabal-testsuite/PackageTests/InternalVersions/BuildToolDependsBad/setup.out
  cabal-testsuite/PackageTests/InternalVersions/BuildToolsBad/setup.cabal.out
  cabal-testsuite/PackageTests/InternalVersions/BuildToolsBad/setup.out
  cabal-testsuite/PackageTests/PackageDB/cabal-fail-no-packagedbs.out
Labels: type: enhancement, attention: needs-review, re: error-message, squash+merge me, merge delay passed

#9164 Remove RPATH workaround
  Cabal/src/Distribution/Simple/GHC.hs
  Cabal/src/Distribution/Simple/GHCJS.hs
Labels: merge me, merge delay passed

#9153 Fix incorrect conditional block documentation
  doc/cabal-package.rst
Labels: documentation, merge me, merge delay passed

#9187 Fix two dead links in the users guide
  doc/cabal-package.rst
Labels: documentation, merge me, merge delay passed

#9179 Make users-guide buildable from within doc/ subdirectory
  Makefile
  doc/Makefile
  doc/README.md
Labels: documentation, attention: needs-review, merge me, re: devx, merge delay passed

#9200 Filter out files that are not ending in .c from c-sources
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  Cabal/src/Distribution/Simple/GHC.hs
  cabal-testsuite/PackageTests/CSourcesSanitisation/Main.hs
  cabal-testsuite/PackageTests/CSourcesSanitisation/build.out
  cabal-testsuite/PackageTests/CSourcesSanitisation/build.test.hs
  cabal-testsuite/PackageTests/CSourcesSanitisation/cabal.project
  cabal-testsuite/PackageTests/CSourcesSanitisation/cbits/gwinsz.c
  cabal-testsuite/PackageTests/CSourcesSanitisation/cbits/gwinsz.h
  cabal-testsuite/PackageTests/CSourcesSanitisation/repro.cabal
Labels: attention: needs-review, attention: needs-manual-qa

#9193 Add a config path on Windows in a message
  cabal-install/src/Distribution/Client/Setup.hs
Labels: squash+merge me, merge delay passed

#9207 Add changelogs for 3.10.2.0
  Cabal-syntax/ChangeLog.md
  Cabal/ChangeLog.md
  cabal-install-solver/ChangeLog.md
  cabal-install/changelog
  release-notes/Cabal-3.10.2.0.md
  release-notes/cabal-install-3.10.2.0.md
Labels: release, attention: needs-review, re: changelog

#9209 Add changelogs for 3.10.2.0 (#9207)
  Cabal-syntax/ChangeLog.md
  Cabal/ChangeLog.md
  cabal-install-solver/ChangeLog.md
  cabal-install/changelog
  release-notes/Cabal-3.10.2.0.md
  release-notes/cabal-install-3.10.2.0.md
Labels: squash+merge me, merge delay passed

#9191 Remaining Cabal Package Exceptions
  Cabal/src/Distribution/Simple/Errors.hs
  Cabal/src/Distribution/Simple/GHC/Internal.hs
  Cabal/src/Distribution/Simple/Haddock.hs
  Cabal/src/Distribution/Simple/Program/Db.hs
  Cabal/src/Distribution/Simple/Register.hs
  Cabal/src/Distribution/Simple/Test.hs
  Cabal/src/Distribution/Simple/Test/ExeV10.hs
  Cabal/src/Distribution/Simple/Test/LibV09.hs
  Cabal/src/Distribution/Simple/Utils.hs
  cabal-install/src/Distribution/Client/Install.hs
  cabal-testsuite/PackageTests/Check/PackageFiles/Missing/cabal.out
Labels: type: enhancement, squash+merge me, merge delay passed

#9213 haddock-packages fixes
  .gitignore
  Cabal/src/Distribution/Simple/Haddock.hs
  Cabal/src/Distribution/Simple/Setup/Haddock.hs
  cabal-install/src/Distribution/Client/CmdHaddockProject.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/IntegrationTests2/haddock-project/dependencies/a.cabal
  cabal-install/tests/IntegrationTests2/haddock-project/dependencies/cabal.project
  cabal-install/tests/IntegrationTests2/haddock-project/dependencies/src/MyLib.hs
  cabal-testsuite/PackageTests/Backpack/Includes2/setup-external.cabal.out
  cabal-testsuite/PackageTests/Backpack/Includes2/setup-external.out
  cabal-testsuite/PackageTests/Backpack/Includes2/setup-per-component.out
  cabal-testsuite/PackageTests/Backpack/Includes3/setup-external-explicit.out
  cabal-testsuite/PackageTests/Backpack/Includes3/setup-external-ok.cabal.out
  cabal-testsuite/PackageTests/Backpack/Includes3/setup-external-ok.out
  cabal-testsuite/PackageTests/Backpack/Reexport1/setup.cabal.out
  cabal-testsuite/PackageTests/Backpack/Reexport1/setup.out
  cabal-testsuite/PackageTests/Haddock/setup.cabal.out
  cabal-testsuite/PackageTests/Haddock/setup.out
  cabal-testsuite/PackageTests/HaddockArgs/quickjump.out
  cabal-testsuite/PackageTests/HaddockNewline/setup.cabal.out
  cabal-testsuite/PackageTests/HaddockNewline/setup.out
  cabal-testsuite/PackageTests/HaddockProject/a.cabal
  cabal-testsuite/PackageTests/HaddockProject/cabal.project
  cabal-testsuite/PackageTests/HaddockProject/haddock-project.out
  cabal-testsuite/PackageTests/HaddockProject/haddock-project.test.hs
  cabal-testsuite/PackageTests/HaddockProject/repo/async-2.2.4/Control/Concurrent/Async.hs
  cabal-testsuite/PackageTests/HaddockProject/repo/async-2.2.4/LICENSE
  cabal-testsuite/PackageTests/HaddockProject/repo/async-2.2.4/Setup.hs
  cabal-testsuite/PackageTests/HaddockProject/repo/async-2.2.4/async.cabal
  cabal-testsuite/PackageTests/HaddockProject/src/MyLib.hs
  cabal-testsuite/PackageTests/InternalLibraries/Haddock/haddock.cabal.out
  cabal-testsuite/PackageTests/InternalLibraries/Haddock/haddock.out
  cabal-testsuite/PackageTests/NewHaddock/DisableDoc/cabal.out
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockOutputCmd/cabal.out
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockOutputConfig/cabal.out
  cabal-testsuite/PackageTests/NewHaddock/ImplyDependencies/cabal.out
  cabal-testsuite/src/Test/Cabal/Prelude.hs
  changelog.d/issue-8843
  doc/cabal-commands.rst
  doc/requirements.txt
Labels: squash+merge me, merge delay passed

#9180 Fix inconsistent indentation
  cabal-install/cabal-install.cabal
Labels: merge me, merge delay passed
