Repository haskell/cabal, pull requests merged in 2023-12, with the labels that each got.

#9330 GHC 9.8 compat and CI
  .github/workflows/validate.yml
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  Cabal/src/Distribution/Simple/GHC.hs
  cabal-dev-scripts/cabal-dev-scripts.cabal
  cabal-install/src/Distribution/Client/Dependency.hs
  cabal-install/src/Distribution/Client/Init/NonInteractive/Command.hs
  cabal-install/src/Distribution/Client/Init/NonInteractive/Heuristics.hs
  cabal-install/src/Distribution/Client/InstallPlan.hs
  cabal-install/src/Distribution/Client/Upload.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/UnitTests/Distribution/Client/FileMonitor.hs
  cabal-install/tests/UnitTests/Distribution/Client/InstallPlan.hs
  cabal-install/tests/UnitTests/Distribution/Client/Targets.hs
  cabal-testsuite/src/Test/Cabal/Prelude.hs
  cabal.project
  cabal.project.latest-ghc
  cabal.project.validate
Labels: merge me, merge delay passed, re: ghc 9.8

#9386 add more breadcrumbs for how to use remote packages. documentation change only.
  doc/cabal-project-description-file.rst
Labels: documentation, squash+merge me, merge delay passed

#9346 Fix #9151 (cabal init logs at loglevel "Log")
  cabal-install/src/Distribution/Client/Init/FileCreators.hs
  cabal-install/src/Distribution/Client/Init/Types.hs
  cabal-install/src/Distribution/Client/Init/Utils.hs
  changelog.d/pr-9346
Labels: squash+merge me, merge delay passed

#9123 Remove --cabal-file option
  cabal-install/src/Distribution/Client/NixStyleOptions.hs
  cabal-testsuite/PackageTests/Backpack/Includes2/Includes2-fail/Includes2.cabal
  cabal-testsuite/PackageTests/Backpack/Includes2/Includes2-fail/mylib
  cabal-testsuite/PackageTests/Backpack/Includes2/Includes2-fail/mysql
  cabal-testsuite/PackageTests/Backpack/Includes2/Includes2-fail/postgresql
  cabal-testsuite/PackageTests/Backpack/Includes2/Includes2-fail/src
  cabal-testsuite/PackageTests/Backpack/Includes2/Includes2/Includes2.cabal
  cabal-testsuite/PackageTests/Backpack/Includes2/Includes2/exe
  cabal-testsuite/PackageTests/Backpack/Includes2/Includes2/mylib
  cabal-testsuite/PackageTests/Backpack/Includes2/Includes2/mysql
  cabal-testsuite/PackageTests/Backpack/Includes2/Includes2/postgresql
  cabal-testsuite/PackageTests/Backpack/Includes2/Includes2/src
  cabal-testsuite/PackageTests/Backpack/Includes2/cabal.internal.project
  cabal-testsuite/PackageTests/Backpack/Includes2/setup-internal-fail.test.hs
  cabal-testsuite/PackageTests/Backpack/Includes2/setup-internal.test.hs
  cabal-testsuite/PackageTests/Backpack/Includes2/setup-per-component.out
  cabal-testsuite/PackageTests/Backpack/Includes2/setup-per-component.test.hs
  cabal-testsuite/PackageTests/ReexportedModules/p-fail-ambiguous/p.cabal
  cabal-testsuite/PackageTests/ReexportedModules/p-fail-missing/p.cabal
  cabal-testsuite/PackageTests/ReexportedModules/p-fail-other/Private.hs
  cabal-testsuite/PackageTests/ReexportedModules/p-fail-other/Public.hs
  cabal-testsuite/PackageTests/ReexportedModules/p-fail-other/p.cabal
  cabal-testsuite/PackageTests/ReexportedModules/setup-fail-ambiguous.test.hs
  cabal-testsuite/PackageTests/ReexportedModules/setup-fail-missing.test.hs
  cabal-testsuite/PackageTests/ReexportedModules/setup-fail-other.test.hs
  cabal-testsuite/PackageTests/ReexportedModules/setup.test.hs
  cabal-testsuite/PackageTests/Regression/HadrianT634/setup.test.hs
  changelog.d/pr-9123
Labels: merge me, merge delay passed

#9504 Make `check` recognise `TypeAbstractions`
  Cabal/src/Distribution/PackageDescription/Check.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Fields/KnownTypeAbstractions/cabal.out
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Fields/KnownTypeAbstractions/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Fields/KnownTypeAbstractions/pkg.cabal
  changelog.d/pr-9503
  editors/vim/syntax/cabal.vim
Labels: cabal-install: cmd/check, merge me, backport

#9497 Separate setup policy from the rest of project planning
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/ProjectPlanning/SetupPolicy.hs
Labels: type: refactor, attention: needs-review, merge me, merge delay passed

#9502 Add `TypeAbstractions` extension
  Cabal-syntax/src/Language/Haskell/Extension.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  changelog.d/pr-9502
  editors/vim/syntax/cabal.vim
Labels: merge me, merge delay passed

#9475 Refactor buildComponent and replComponent
  Cabal/src/Distribution/Simple/Build.hs
Labels: attention: needs-review, squash+merge me, merge delay passed

#9515 Warn about project conditional blocks
  doc/cabal-package-description-file.rst
  doc/cabal-project-description-file.rst
Labels: documentation, merge delay passed, merge+no rebase

#9506 Warn early overwrite expanded
  cabal-install/src/Distribution/Client/CmdInstall.hs
  cabal-install/src/Distribution/Client/InstallSymlink.hs
  cabal-testsuite/PackageTests/WarnEarlyOverwrite/WarnEarlyOverwrite.cabal
  cabal-testsuite/PackageTests/WarnEarlyOverwrite/app/Main.hs
  cabal-testsuite/PackageTests/WarnEarlyOverwrite/cabal.project
  cabal-testsuite/PackageTests/WarnEarlyOverwrite/clean-install-by-copy.out
  cabal-testsuite/PackageTests/WarnEarlyOverwrite/clean-install-by-copy.test.hs
  cabal-testsuite/PackageTests/WarnEarlyOverwrite/clean-install-by-symlink.out
  cabal-testsuite/PackageTests/WarnEarlyOverwrite/clean-install-by-symlink.test.hs
  cabal-testsuite/PackageTests/WarnEarlyOverwrite/dirty-install.out
  cabal-testsuite/PackageTests/WarnEarlyOverwrite/dirty-install.test.hs
  changelog.d/issue-5993
Labels: merge delay passed, merge+no rebase

#9370 Rework material on library components in Cabal Users Guide
  doc/cabal-package-description-file.rst
Labels: documentation, merge me, merge delay passed, re: internal library

#9411 [Rel-Eng]: Adds script to automatically generate GHCup metadata for Cabal releases
  .gitignore
  scripts/release/create-release-metadata-for-ghcup.sh
  scripts/release/download-cabal-install-release-binaries.sh
Labels: attention: needs-review, squash+merge me, merge delay passed

#9523 Relax upper bounds on filepath
  Cabal-syntax/Cabal-syntax.cabal
  Cabal/Cabal.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
  cabal-testsuite/cabal-testsuite.cabal
Labels: merge me, merge delay passed

#9481 Guard PackageInfo behind `cabal-version` ≥ 3.12
  Cabal-syntax/src/Distribution/CabalSpecVersion.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  Cabal/src/Distribution/PackageDescription/Check/Target.hs
  Cabal/src/Distribution/PackageDescription/Check/Warning.hs
  cabal-install/src/Distribution/Client/Init/Interactive/Command.hs
  cabal-testsuite/PackageTests/AutogenModules/Package/my.cabal
  cabal-testsuite/PackageTests/AutogenModules/SrcDist/AutogenModules.cabal
  cabal-testsuite/PackageTests/BuildAutogenPackageGuard/cabal.out
  cabal-testsuite/PackageTests/BuildAutogenPackageGuard/cabal.project
  cabal-testsuite/PackageTests/BuildAutogenPackageGuard/cabal.test.hs
  cabal-testsuite/PackageTests/BuildAutogenPackageGuard/pkg.cabal
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/CabalVersion/AutoGenMods/pkg.cabal
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Sanity/AutogenVersion/cabal.out
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Sanity/AutogenVersion/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Sanity/AutogenVersion/pkg.cabal
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Sanity/AutogenVersionOk/cabal.out
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Sanity/AutogenVersionOk/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Sanity/AutogenVersionOk/pkg.cabal
  cabal-testsuite/PackageTests/Check/NonConfCheck/PathsExtensions/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/Datafiles/foo/foo.cabal
  cabal-testsuite/PackageTests/NewBuild/T5164/setup-lib/setup-lib.cabal
  cabal-testsuite/PackageTests/PackageInfoModule/Executable/my.cabal
  cabal-testsuite/PackageTests/PackageInfoModule/ImportQualifiedPost/my.cabal
  cabal-testsuite/PackageTests/PackageInfoModule/Library/my.cabal
  cabal-testsuite/PackageTests/PathsModule/Executable-Relocatable/my.cabal
  cabal-testsuite/PackageTests/PathsModule/Executable/my.cabal
  cabal-testsuite/PackageTests/PathsModule/ImportQualifiedPost/my.cabal
  cabal-testsuite/PackageTests/PathsModule/Library/my.cabal
  cabal-testsuite/PackageTests/PathsModule/MissingSafeHaskellMode/my.cabal
  changelog.d/pr-9481
Labels: squash+merge me, merge delay passed

#9525 `check`: add PackageInfo warning
  Cabal/src/Distribution/PackageDescription/Check.hs
  cabal-testsuite/PackageTests/AutogenModules/Package/setup.cabal.out
  cabal-testsuite/PackageTests/AutogenModules/Package/setup.out
  cabal-testsuite/PackageTests/AutogenModules/SrcDist/setup.cabal.out
  cabal-testsuite/PackageTests/AutogenModules/SrcDist/setup.out
  cabal-testsuite/PackageTests/AutogenModules/SrcDist/setup.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/CabalVersion/AutoGenMods/cabal.out
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Sanity/AutogenVersion/cabal.out
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Sanity/AutogenVersion/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Sanity/AutogenVersion/pkg.cabal
  cabal-testsuite/PackageTests/Check/NonConfCheck/PathsExtensions/cabal.out
  changelog.d/pr-9525
Labels: merge me, merge delay passed, backport

#9549 Fix #9548 Improve accuracy of docs for condition `arch(name)`
  doc/cabal-package-description-file.rst
Labels: merge me, merge delay passed

#9488 Satisfy `-Werror=unused-top-binds`
  Cabal-tests/tests/UnitTests/Distribution/SPDX.hs
  Cabal-tests/tests/UnitTests/Distribution/Simple/Program/GHC.hs
Labels: merge delay passed, merge+no rebase

#9572 Add Cabal-described and cabal-install to doctests
  Cabal-described/src/Distribution/Utils/CharSet.hs
  Makefile
  cabal-install/src/Distribution/Client/IndexUtils/ActiveRepos.hs
  cabal-install/src/Distribution/Client/IndexUtils/IndexState.hs
  cabal-install/src/Distribution/Client/Types/RepoName.hs
Labels: merge delay passed, merge+no rebase
