Repository haskell/cabal, pull requests merged in 2023-01, with the labels that each got.

#8640 root relative glob expansion of extra source files
  cabal-install/src/Distribution/Client/SourceFiles.hs
  changelog.d/pr-8640
Labels: attention: needs-review

#8648 Tiny refactor of how Cabal handles configure scripts
  Cabal/Cabal.cabal
  Cabal/src/Distribution/Simple.hs
  Cabal/src/Distribution/Simple/ConfigureScript.hs
  changelog.d/pr-8648
Labels: type: refactor, merge me

#8650 Fix typo in cabal.test.hs
  cabal-testsuite/PackageTests/LinkerOptions/NonignoredConfigs/cabal.test.hs
Labels: merge me, merge delay passed

#8498 improve install target handling logic
  cabal-install/src/Distribution/Client/CmdInstall.hs
  changelog.d/pr-8498
Labels: squash+merge me, merge delay passed

#8556 Add installDirs (datadir, etc) to new-build and remove them from new-install
  Cabal-tree-diff/src/Data/TreeDiff/Instances/Cabal.hs
  cabal-install/src/Distribution/Client/CmdInstall.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Types.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
  changelog.d/pr-8556
Labels: squash+merge me, merge delay passed

#8627 don't create a cache directory when the compiler isn't configured
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  changelog.d/pr-8358
Labels: attention: needs-test, squash+merge me, merge delay passed

#8647 Fix #8645: no assertion warning on special modes (help, version, etc.)
  cabal-install/main/Main.hs
  changelog.d/pr-8647
Labels: attention: needs-review, squash+merge me, re: devx, re: warnings, merge delay passed

#8651 Remove "'-main-is' is not portable" check
  Cabal-tests/tests/CheckTests.hs
  Cabal-tests/tests/ParserTests/regressions/issue-8646.cabal
  Cabal-tests/tests/ParserTests/regressions/issue-8646.check
  Cabal/src/Distribution/PackageDescription/Check.hs
  changelog.d/issue-8646
Labels: squash+merge me, merge delay passed

#8510 Don't send non-existent extra-lib-dirs to ghc
  Cabal/src/Distribution/Simple/GHC.hs
  changelog.d/pr-8510
Labels: Cabal: cmd/build, squash+merge me, re: ghc-options, merge delay passed

#8506 prepend rather than append extra prog path
  Cabal/src/Distribution/Simple/Configure.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-testsuite/PackageTests/ExtraProgPath/MyLibrary.hs
  cabal-testsuite/PackageTests/ExtraProgPath/cabal.project
  cabal-testsuite/PackageTests/ExtraProgPath/my.cabal
  cabal-testsuite/PackageTests/ExtraProgPath/pkg-config
  cabal-testsuite/PackageTests/ExtraProgPath/setup.out
  cabal-testsuite/PackageTests/ExtraProgPath/setup.test.hs
  changelog.d/pr-8506
Labels: attention: needs-review, squash+merge me, merge delay passed

#8661 Add since pragma for ppOrdering
  Cabal/src/Distribution/Simple/PreProcess.hs
Labels: merge me, merge delay passed

#8665 Re #6125: document that glob dirs are buggy in Cabal 2.4
  doc/cabal-package.rst
  doc/file-format-changelog.rst
Labels: documentation, merge me, data-files, merge delay passed, re: globbing

#8670 Fix #8400 by marking output of `cabal list-bin`
  cabal-install/src/Distribution/Client/CmdListBin.hs
  cabal-testsuite/PackageTests/ListBin/Script/cabal.out
  cabal-testsuite/PackageTests/ListBin/SelectedComponent/cabal.out
  cabal-testsuite/PackageTests/ListBin/SelectedComponent/cabal.test.hs
Labels: squash+merge me, cabal-install: cmd/list-bin, regression on master, merge delay passed

#8672 cabal-testsuite #8401: communicate better the need for `--with-cabal`
  cabal-testsuite/README.md
  cabal-testsuite/main/cabal-tests.hs
  cabal-testsuite/src/Test/Cabal/Monad.hs
Labels: attention: needs-review, cabal-testsuite, merge me, re: devx, merge delay passed

#8441 Add check for recursive glob in root directory
  Cabal/src/Distribution/PackageDescription/Check.hs
  Cabal/src/Distribution/Simple/Glob.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Paths/RecursiveGlobInRoot/a.dat
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Paths/RecursiveGlobInRoot/a.md
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Paths/RecursiveGlobInRoot/cabal.out
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Paths/RecursiveGlobInRoot/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Paths/RecursiveGlobInRoot/pkg.cabal
  changelog.d/pr-8441
Labels: cabal-install: cmd/check, squash+merge me, merge delay passed

#8628 TargetSelector: Include a hint in the error message for internal error
  cabal-install/src/Distribution/Client/TargetSelector.hs
Labels: merge me, merge delay passed

#8671 Fix build instructions in CONTRIBUTING.md for people with old cabal
  CONTRIBUTING.md
Labels: documentation, merge me, merge delay passed

#8686 Fix project relative imports
  cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
  cabal-testsuite/PackageTests/LinkerOptions/NonignoredConfigs/cabal.test.hs
  cabal-testsuite/PackageTests/RelativePathProjectImports/Lib.hs
  cabal-testsuite/PackageTests/RelativePathProjectImports/cabal.out
  cabal-testsuite/PackageTests/RelativePathProjectImports/cabal.project
  cabal-testsuite/PackageTests/RelativePathProjectImports/cabal.test.hs
  cabal-testsuite/PackageTests/RelativePathProjectImports/dep/Dep.hs
  cabal-testsuite/PackageTests/RelativePathProjectImports/dep/cabal.project
  cabal-testsuite/PackageTests/RelativePathProjectImports/dep/dep.cabal
  cabal-testsuite/PackageTests/RelativePathProjectImports/dep2/Dep2.hs
  cabal-testsuite/PackageTests/RelativePathProjectImports/dep2/dep2.cabal
  cabal-testsuite/PackageTests/RelativePathProjectImports/main.cabal
  cabal-testsuite/src/Test/Cabal/CheckArMetadata.hs
  changelog.d/pr-8686
Labels: squash+merge me, re: project root, merge delay passed

#8666 Bump known ghc versions in cabal library to < 9.8
  Cabal/src/Distribution/Simple/GHC.hs
Labels: release, merge me, merge delay passed

#8636 Add support for js-sources
  Cabal/src/Distribution/Simple/Build.hs
  Cabal/src/Distribution/Simple/GHC.hs
  Cabal/src/Distribution/Simple/GHC/Internal.hs
  Cabal/src/Distribution/Simple/Register.hs
  cabal-testsuite/PackageTests/JS/JsSources/cabal.project
  cabal-testsuite/PackageTests/JS/JsSources/cabal.test.hs
  cabal-testsuite/PackageTests/JS/JsSources/demo/Main.hs
  cabal-testsuite/PackageTests/JS/JsSources/jsbits/lib.js
  cabal-testsuite/PackageTests/JS/JsSources/jssources.cabal
  cabal-testsuite/PackageTests/JS/JsSources/src/Lib.hs
  cabal-testsuite/src/Test/Cabal/Prelude.hs
  changelog.d/pr-8636
Labels: compiler: ghcjs, squash+merge me, merge delay passed, re: ghc 9.6, js backend

#8678 Improve docs for 'option' and 'reqArg'
  Cabal/src/Distribution/Simple/Command.hs
Labels: documentation, squash+merge me, merge delay passed

#8691 Fix #8664 redux: add EOL character to list-bin output
  cabal-install/src/Distribution/Client/CmdListBin.hs
Labels: merge me, cabal-install: cmd/list-bin, merge delay passed

#8657 cabal check: Warn if readmes or changelogs are omitted from extra-doc-files
  Cabal/src/Distribution/PackageDescription/Check.hs
  cabal-testsuite/PackageTests/Check/PackageFiles/MissingExpectedDocFiles/ChangeLog/NotExisting/cabal.out
  cabal-testsuite/PackageTests/Check/PackageFiles/MissingExpectedDocFiles/ChangeLog/NotExisting/cabal.test.hs
  cabal-testsuite/PackageTests/Check/PackageFiles/MissingExpectedDocFiles/ChangeLog/NotExisting/pkg.cabal
  cabal-testsuite/PackageTests/Check/PackageFiles/MissingExpectedDocFiles/ChangeLog/NotIncluded/V1.12/ChangeLog.md
  cabal-testsuite/PackageTests/Check/PackageFiles/MissingExpectedDocFiles/ChangeLog/NotIncluded/V1.12/LICENSE
  cabal-testsuite/PackageTests/Check/PackageFiles/MissingExpectedDocFiles/ChangeLog/NotIncluded/V1.12/cabal.out
  cabal-testsuite/PackageTests/Check/PackageFiles/MissingExpectedDocFiles/ChangeLog/NotIncluded/V1.12/cabal.test.hs
  cabal-testsuite/PackageTests/Check/PackageFiles/MissingExpectedDocFiles/ChangeLog/NotIncluded/V1.12/pkg.cabal
  cabal-testsuite/PackageTests/Check/PackageFiles/MissingExpectedDocFiles/ChangeLog/NotIncluded/V3.0/ChangeLog.md
  cabal-testsuite/PackageTests/Check/PackageFiles/MissingExpectedDocFiles/ChangeLog/NotIncluded/V3.0/cabal.out
  cabal-testsuite/PackageTests/Check/PackageFiles/MissingExpectedDocFiles/ChangeLog/NotIncluded/V3.0/cabal.test.hs
  cabal-testsuite/PackageTests/Check/PackageFiles/MissingExpectedDocFiles/ChangeLog/NotIncluded/V3.0/pkg.cabal
  cabal-testsuite/PackageTests/Check/PackageFiles/MissingExpectedDocFiles/ChangeLog/WrongField/V1.12/ChangeLog.md
  cabal-testsuite/PackageTests/Check/PackageFiles/MissingExpectedDocFiles/ChangeLog/WrongField/V1.12/LICENSE
  cabal-testsuite/PackageTests/Check/PackageFiles/MissingExpectedDocFiles/ChangeLog/WrongField/V1.12/cabal.out
  cabal-testsuite/PackageTests/Check/PackageFiles/MissingExpectedDocFiles/ChangeLog/WrongField/V1.12/cabal.test.hs
  cabal-testsuite/PackageTests/Check/PackageFiles/MissingExpectedDocFiles/ChangeLog/WrongField/V1.12/pkg.cabal
  cabal-testsuite/PackageTests/Check/PackageFiles/MissingExpectedDocFiles/ChangeLog/WrongField/V3.0/ChangeLog.md
  cabal-testsuite/PackageTests/Check/PackageFiles/MissingExpectedDocFiles/ChangeLog/WrongField/V3.0/cabal.out
  cabal-testsuite/PackageTests/Check/PackageFiles/MissingExpectedDocFiles/ChangeLog/WrongField/V3.0/cabal.test.hs
  cabal-testsuite/PackageTests/Check/PackageFiles/MissingExpectedDocFiles/ChangeLog/WrongField/V3.0/pkg.cabal
  changelog.d/pr-8657
Labels: cabal-install: cmd/check, squash+merge me, merge delay passed

#8663 Fix and improve list parser of cabal init cli
  cabal-install/src/Distribution/Client/Init/Simple.hs
  cabal-install/src/Distribution/Client/Setup.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/NonInteractive.hs
  changelog.d/pr-8663
Labels: type: enhancement, cabal-install: cmd/init, re: options, squash+merge me, merge delay passed

#8697 elim warning spam from #8500
  cabal-install/src/Distribution/Client/FetchUtils.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
Labels: attention: needs-backport 3.10

#8700 Fix cabal init should not suggest Cabal < 2.0
  cabal-install/src/Distribution/Client/Init/Interactive/Command.hs
  changelog.d/issue-8680
Labels: squash+merge me, merge delay passed
