Repository haskell/cabal, pull requests merged in 2023-05, with the labels that each got.

#8903 add base to cabal install --lib default env file
  cabal-install/src/Distribution/Client/CmdInstall.hs
  changelog.d/pr-8903
Labels: squash+merge me, merge delay passed, attention: needs-backport 3.10, attention: needs-manual-qa

#8942 Make --test-show-details=direct the default
  Cabal/src/Distribution/Simple/Setup/Test.hs
  changelog.d/issue-7817
  doc/README.md
  doc/cabal-commands.rst
  doc/setup-commands.rst
Labels: merge me, merge delay passed

#8916 Avoid using to-be-deprecated Data.List.NonEmpty.unzip
  Cabal/src/Distribution/Simple/BuildTarget.hs
Labels: merge me, merge delay passed

#8878 Fix default Nix configuration option in generated ~/.cabal/config file
  cabal-install/src/Distribution/Client/Config.hs
  cabal-install/src/Distribution/Client/Setup.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/IntegrationTests2/config/default-config
  changelog.d/pr-8878
  tests/IntegrationTests2/config/default-config
  tests/IntegrationTests2/nix-config/default-config
Labels: squash+merge me, merge delay passed

#8819 use with compiler flags in key of cached project config
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  changelog.d/pr-8819
Labels: attention: needs-review, squash+merge me, merge delay passed, attention: needs-backport 3.10, attention: needs-manual-qa

#8914 CI: add automated GitHub prereleases
  .github/workflows/validate.yml
  README.md
Labels: attention: needs-review, squash+merge me, merge delay passed

#8898 Shorten script-builds paths
  Cabal/src/Distribution/PackageDescription/Check.hs
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/CmdListBin.hs
  cabal-install/src/Distribution/Client/CmdRun.hs
  cabal-install/src/Distribution/Client/HashValue.hs
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/src/Distribution/Client/ScriptUtils.hs
  cabal-testsuite/PackageTests/ListBin/Script/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdBuild/Script/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdBuild/ScriptBuildRepl/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdBuild/ScriptBuildRepl/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdBuild/ScriptBuildRun/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdBuild/ScriptBuildRun/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdBuild/ScriptRerun/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdClean/Keep/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdClean/Orphan/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdClean/Script/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRepl/Script/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRepl/ScriptRerun/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/Script/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptLiterate/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptLiterate/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptNoExtension/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptRerun/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptWithProjectBlock/cabal.out
  cabal-testsuite/cabal-testsuite.cabal
  cabal-testsuite/src/Test/Cabal/Prelude.hs
  changelog.d/issue-8841
Labels: platform: windows, squash+merge me, merge delay passed, attention: needs-backport 3.10, attention: needs-manual-qa

#8877 Ignore ~/.cabal if $XDG_CONFIG_HOME/cabal/config exists.
  cabal-install/src/Distribution/Client/Config.hs
  changelog.d/issue-8577
  doc/config.rst
Labels: attention: needs-review, squash+merge me, merge delay passed, attention: needs-backport 3.10, attention: needs-manual-qa

#8959 Clarify `check` documentation
  cabal-install/src/Distribution/Client/Setup.hs
  doc/cabal-commands.rst
Labels: documentation, cabal-install: cmd/check, merge me, merge delay passed

#8960 Future-proof against potential Prelude.foldl'
  Cabal-syntax/src/Distribution/Compat/Prelude.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/CharSet.hs
Labels: merge me, merge delay passed

#8969 Put back docs for code-generators (fix #8887)
  doc/cabal-package.rst
Labels: merge me, merge delay passed

#8964 allow building cabal-install-3.10 with ghc-9.6
  Cabal-tests/Cabal-tests.cabal
  Cabal-tree-diff/Cabal-tree-diff.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
  cabal-testsuite/cabal-testsuite.cabal
Labels: merge me, merge delay passed

#8949 Warn if builddir is going to be ignored
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-testsuite/PackageTests/Project/WarnBuilddir/cabal.out
  cabal-testsuite/PackageTests/Project/WarnBuilddir/cabal.project
  cabal-testsuite/PackageTests/Project/WarnBuilddir/cabal.test.hs
  cabal-testsuite/PackageTests/Project/WarnBuilddir/main.cabal
  changelog.d/pr-8949
  doc/cabal-project.rst
Labels: squash+merge me, re: project-file, re: builddir, merge delay passed

#8974 docs: dependabot security suggestion
  .readthedocs.yml
  doc/README.md
  doc/requirements.txt
Labels: merge me, merge delay passed
