Repository haskell/cabal, pull requests merged in 2023-07, with the labels that each got.

#9068 Add new root keys
  cabal-install/src/Distribution/Client/Config.hs
  changelog.d/pr-9068
Labels: merge me, merge delay passed

#8972 Fix precedence for PATH for build-tools-depends
  Cabal/src/Distribution/Simple/Configure.hs
  cabal-install/src/Distribution/Client/Check.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/tests/UnitTests/Distribution/Client/ArbitraryInstances.hs
  changelog.d/pr-8972
Labels: squash+merge me, attention: needs-rebase, merge delay passed

#9062 Add support for the 64-bit RISC-V architecture
  Cabal-syntax/src/Distribution/System.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  Cabal/src/Distribution/Simple/PreProcess.hs
  changelog.d/pr-9062
Labels: squash+merge me, merge delay passed

#9069 cabal-install: update resolv to 0.2.0.2
  cabal-install/cabal-install.cabal
  cabal-testsuite/PackageTests/NewUpdate/UpdateIndexState/update-index-state.out
  cabal-testsuite/PackageTests/NewUpdate/UpdateIndexState/update-index-state.test.hs
Labels: merge me, merge delay passed

#8919 haddock-project fixes
  .gitignore
  Cabal/src/Distribution/Simple/Haddock.hs
  Cabal/src/Distribution/Simple/Setup/Haddock.hs
  cabal-install/src/Distribution/Client/CmdHaddockProject.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/IntegrationTests2/haddock-project/dependencies/a.cabal
  cabal-install/tests/IntegrationTests2/haddock-project/dependencies/cabal.project
  cabal-install/tests/IntegrationTests2/haddock-project/dependencies/src/MyLib.hs
  cabal-testsuite/PackageTests/Backpack/Includes2/setup-external.cabal.out
  cabal-testsuite/PackageTests/Backpack/Includes2/setup-external.out
  cabal-testsuite/PackageTests/Backpack/Includes2/setup-per-component.out
  cabal-testsuite/PackageTests/Backpack/Includes3/setup-external-explicit.out
  cabal-testsuite/PackageTests/Backpack/Includes3/setup-external-ok.cabal.out
  cabal-testsuite/PackageTests/Backpack/Includes3/setup-external-ok.out
  cabal-testsuite/PackageTests/Backpack/Reexport1/setup.cabal.out
  cabal-testsuite/PackageTests/Backpack/Reexport1/setup.out
  cabal-testsuite/PackageTests/Haddock/setup.cabal.out
  cabal-testsuite/PackageTests/Haddock/setup.out
  cabal-testsuite/PackageTests/HaddockArgs/quickjump.out
  cabal-testsuite/PackageTests/HaddockNewline/setup.cabal.out
  cabal-testsuite/PackageTests/HaddockNewline/setup.out
  cabal-testsuite/PackageTests/HaddockProject/a.cabal
  cabal-testsuite/PackageTests/HaddockProject/cabal.project
  cabal-testsuite/PackageTests/HaddockProject/haddock-project.out
  cabal-testsuite/PackageTests/HaddockProject/haddock-project.test.hs
  cabal-testsuite/PackageTests/HaddockProject/repo/async-2.2.4/Control/Concurrent/Async.hs
  cabal-testsuite/PackageTests/HaddockProject/repo/async-2.2.4/LICENSE
  cabal-testsuite/PackageTests/HaddockProject/repo/async-2.2.4/Setup.hs
  cabal-testsuite/PackageTests/HaddockProject/repo/async-2.2.4/async.cabal
  cabal-testsuite/PackageTests/HaddockProject/src/MyLib.hs
  cabal-testsuite/PackageTests/InternalLibraries/Haddock/haddock.cabal.out
  cabal-testsuite/PackageTests/InternalLibraries/Haddock/haddock.out
  cabal-testsuite/PackageTests/NewHaddock/DisableDoc/cabal.out
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockOutputCmd/cabal.out
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockOutputConfig/cabal.out
  cabal-testsuite/PackageTests/NewHaddock/ImplyDependencies/cabal.out
  cabal-testsuite/src/Test/Cabal/Prelude.hs
  changelog.d/issue-8843
  doc/cabal-commands.rst
Labels: cabal-install: cmd/haddock, merge me, merge delay passed, attention: needs-backport 3.10

#9085 README: update Matrix chat link
  README.md
Labels: merge me, merge delay passed

#9078 Bump deepseq bounds to allow 1.5
  Cabal-syntax/Cabal-syntax.cabal
  Cabal/Cabal.cabal
Labels: merge me, merge delay passed

#9087 Remove v2-prefix from Quickstart guide
  doc/nix-local-build.rst
Labels: merge me, merge delay passed

#9104 workaround for #9103: skip test failing on Windows
  cabal-testsuite/PackageTests/MultiRepl/EnabledSucc/cabal.test.hs
Labels: merge me, merge delay passed

#9041 Add HLint configuraton.
  .github/workflows/format.yml
  .github/workflows/lint.yml
  .hlint.yaml
Labels: blocked: action-required, continuous-integration, merge me, merge delay passed

#9090 Remove v2-prefix from other documentation where appropriate
  .github/ISSUE_TEMPLATE/bug_report.md
  CONTRIBUTING.md
  Makefile
  bootstrap/bootstrap.py
  cabal-dev-scripts/src/GenCabalInstallCabal.hs
  cabal-dev-scripts/src/GenCabalMacros.hs
  cabal-dev-scripts/src/GenPathsModule.hs
  cabal-dev-scripts/src/GenValidateDockerfile.hs
  solver-benchmarks/HackageBenchmark.hs
  validate.sh
Labels: documentation, meta: easy, squash+merge me, merge delay passed, re: v1-vs-v2

#9096 facelift bootstrap/README.md
  bootstrap/README.md
Labels: meta: easy, squash+merge me, merge delay passed

#9105 Bring the command help up to date
  doc/cabal-commands.rst
Labels: merge me

#9100 Revamp issue/PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/user_question.md
  .github/PULL_REQUEST_TEMPLATE/full_pr.md
  .github/PULL_REQUEST_TEMPLATE/simple_pr.md
Labels: squash+merge me, re: devx, merge delay passed

#9117 Fix issue/PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/user_question.md
  .github/PULL_REQUEST_TEMPLATE/full_pr.md
  .github/PULL_REQUEST_TEMPLATE/simple_pr.md
  .github/pull_request_template.md
Labels: squash+merge me, re: devx

#9102 Add user-oriented resources in README.md
  README.md
Labels: documentation, merge me, merge delay passed

#9118 Remove labels from template PR
  .github/pull_request_template.md
Labels: attention: needs-review, re: devx

#9034 Add 'mkVersionIntervals' for creating a VersionIntervals from a list
  Cabal-syntax/src/Distribution/Types/VersionInterval.hs
  changelog.d/pr-9034
Labels: squash+merge me, merge delay passed

#9095 Fix fourmolu
  .github/workflows/format.yml
  Cabal-syntax/src/Distribution/Fields/Lexer.hs
  Cabal-syntax/src/Distribution/SPDX/LicenseExceptionId.hs
  Cabal-syntax/src/Distribution/SPDX/LicenseId.hs
  Cabal-syntax/src/Distribution/Types/InstalledPackageInfo/FieldGrammar.hs
  Cabal/src/Distribution/Simple/Build/Macros/Z.hs
  Cabal/src/Distribution/Simple/Build/PathsModule/Z.hs
  Makefile
  cabal-dev-scripts/src/GenCabalMacros.hs
  cabal-dev-scripts/src/GenPathsModule.hs
  cabal-install/src/Distribution/Client/CmdHaddockProject.hs
  cabal-install/tests/UnitTests/Distribution/Client/FetchUtils.hs
  cabal-install/tests/UnitTests/Distribution/Client/Get.hs
  fourmolu.yaml
  templates/SPDX.LicenseExceptionId.template.hs
  templates/SPDX.LicenseId.template.hs
Labels: squash+merge me, merge delay passed

#9043 Render short option with arg.
  Cabal/src/Distribution/GetOpt.hs
  Cabal/src/Distribution/Simple/Command.hs
  Cabal/src/Distribution/Simple/Setup/Common.hs
  Cabal/src/Distribution/Simple/Setup/Config.hs
  cabal-install/src/Distribution/Client/CmdOutdated.hs
  cabal-install/src/Distribution/Client/Setup.hs
  changelog.d/issue-8785
  doc/cabal-commands.rst
  doc/cabal-project.rst
  doc/setup-commands.rst
Labels: attention: needs-review, squash+merge me, merge delay passed

#9120 Mergify: rebase as Mikolaj (fix #8462)
  .github/mergify.yml
Labels: merge me, merge delay passed

#9111 Follow hlint suggestion: redundant list comprehension
  .hlint.yaml
  Cabal/src/Distribution/Simple/PreProcess.hs
  Cabal/src/Distribution/Simple/Program/GHC.hs
Labels: merge me, merge delay passed

#9061 Support asm/cmm/js sources in executable components (#8639)
  Cabal/src/Distribution/Simple/GHC.hs
  cabal-testsuite/PackageTests/CmmSourcesExe/cabal.out
  cabal-testsuite/PackageTests/CmmSourcesExe/cabal.project
  cabal-testsuite/PackageTests/CmmSourcesExe/cabal.test.hs
  cabal-testsuite/PackageTests/CmmSourcesExe/cbits/HeapPrim.cmm
  cabal-testsuite/PackageTests/CmmSourcesExe/cmmexperiment.cabal
  cabal-testsuite/PackageTests/CmmSourcesExe/demo/Main.hs
  cabal-testsuite/PackageTests/CmmSourcesExe/setup.out
  cabal-testsuite/PackageTests/CmmSourcesExe/setup.test.hs
  cabal-testsuite/PackageTests/CmmSourcesExe/src/Demo.hs
  cabal-testsuite/PackageTests/JS/JsSourcesExe/cabal.project
  cabal-testsuite/PackageTests/JS/JsSourcesExe/demo/Main.hs
  cabal-testsuite/PackageTests/JS/JsSourcesExe/js-arch.test.hs
  cabal-testsuite/PackageTests/JS/JsSourcesExe/jsbits/lib.js
  cabal-testsuite/PackageTests/JS/JsSourcesExe/jssources-exe.cabal
  cabal-testsuite/PackageTests/JS/JsSourcesExe/other-arch.out
  cabal-testsuite/PackageTests/JS/JsSourcesExe/other-arch.test.hs
  cabal-testsuite/PackageTests/JS/JsSourcesExe/src/Lib.hs
  cabal-testsuite/PackageTests/JS/JsSourcesExe/srcJS/Lib.hs
  changelog.d/issue-8639
Labels: squash+merge me, merge delay passed, attention: needs-backport 3.10

#9116 Use case insensitive match on ETag headers
  cabal-install/src/Distribution/Client/HttpUtils.hs
Labels: merge me, merge delay passed, attention: needs-backport 3.10

#9129 Fix fourmolu
  cabal-install/src/Distribution/Client/List.hs
  cabal-install/src/Distribution/Client/ProjectPlanOutput.hs
Labels: attention: needs-review

#9128 Follow hlint suggestion: redundant where (dead code)
  .hlint.yaml
  Cabal-syntax/src/Distribution/Fields/ParseResult.hs
  Cabal-syntax/src/Distribution/Types/Mixin.hs
  cabal-testsuite/src/Test/Cabal/Monad.hs
Labels: merge me, merge delay passed

#9108 Mergify: add no-rebase rule
  .github/mergify.yml
Labels: merge me, merge delay passed

#9139 Add support for using GHC's -jsem option
  Cabal/Cabal.cabal
  Cabal/src/Distribution/Simple/Build.hs
  Cabal/src/Distribution/Simple/Compiler.hs
  Cabal/src/Distribution/Simple/GHC.hs
  Cabal/src/Distribution/Simple/GHCJS.hs
  Cabal/src/Distribution/Simple/Program/GHC.hs
  Cabal/src/Distribution/Simple/Setup.hs
  Cabal/src/Distribution/Simple/Setup/Build.hs
  Cabal/src/Distribution/Types/ParStrat.hs
  bootstrap/linux-8.10.7.json
  bootstrap/linux-9.0.2.json
  bootstrap/linux-9.2.7.json
  bootstrap/linux-9.4.4.json
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/Config.hs
  cabal-install/src/Distribution/Client/JobControl.hs
  cabal-install/src/Distribution/Client/ProjectBuilding.hs
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Types.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/Setup.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
  cabal-testsuite/PackageTests/NewBuild/Semaphore/C.hs
  cabal-testsuite/PackageTests/NewBuild/Semaphore/Semaphore.cabal
  cabal-testsuite/PackageTests/NewBuild/Semaphore/Setup.hs
  cabal-testsuite/PackageTests/NewBuild/Semaphore/cabal.out
  cabal-testsuite/PackageTests/NewBuild/Semaphore/cabal.project
  cabal-testsuite/PackageTests/NewBuild/Semaphore/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/Semaphore/sub-package-A/A.hs
  cabal-testsuite/PackageTests/NewBuild/Semaphore/sub-package-A/Setup.hs
  cabal-testsuite/PackageTests/NewBuild/Semaphore/sub-package-A/sub-package-A.cabal
  cabal-testsuite/PackageTests/NewBuild/Semaphore/sub-package-B/B.hs
  cabal-testsuite/PackageTests/NewBuild/Semaphore/sub-package-B/Setup.hs
  cabal-testsuite/PackageTests/NewBuild/Semaphore/sub-package-B/sub-package-B.cabal
  changelog.d/pr-8557
  changelog.d/pr-8557-2
  doc/cabal-project.rst
Labels: merge me, merge delay passed

#9018 Cabal Error Refactor
  Cabal/Cabal.cabal
  Cabal/src/Distribution/Simple/Bench.hs
  Cabal/src/Distribution/Simple/Build.hs
  Cabal/src/Distribution/Simple/BuildPaths.hs
  Cabal/src/Distribution/Simple/Errors.hs
  Cabal/src/Distribution/Simple/GHCJS.hs
  Cabal/src/Distribution/Simple/Glob.hs
  Cabal/src/Distribution/Simple/Haddock.hs
  Cabal/src/Distribution/Simple/HaskellSuite.hs
  Cabal/src/Distribution/Simple/Install.hs
  Cabal/src/Distribution/Simple/Program.hs
  Cabal/src/Distribution/Simple/Program/HcPkg.hs
  Cabal/src/Distribution/Simple/SrcDist.hs
  Cabal/src/Distribution/Simple/Utils.hs
  cabal-install/src/Distribution/Client/CmdSdist.hs
  cabal-install/src/Distribution/Client/SrcDist.hs
  cabal-testsuite/PackageTests/AutogenModules/Package/setup.cabal.out
  cabal-testsuite/PackageTests/AutogenModules/Package/setup.out
  cabal-testsuite/PackageTests/SDist/T5195/cabal.out
  cabal-testsuite/PackageTests/SDist/T7124/cabal-list.out
  cabal-testsuite/PackageTests/SDist/T7124/cabal.out
  changelog.d/pr-9018
Labels: type: enhancement, re: error-message, squash+merge me, merge delay passed

#9152 Add changelog for #9113
  changelog.d/issue-9113
Labels: merge me, merge delay passed

#9155 Do not ask overwrite questions for empty dirs
  cabal-install/src/Distribution/Client/Init/Interactive/Command.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/Golden.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/Interactive.hs
  cabal-testsuite/PackageTests/Init/init-interactive-empty-folder.out
  cabal-testsuite/PackageTests/Init/init-interactive-empty-folder.test.hs
  changelog.d/pr-9155
Labels: cabal-install: cmd/init, squash+merge me, merge delay passed
