Repository haskell/cabal, pull requests merged in 2023-11, with the labels that each got.

#9361 doc: render math with HTML to make it selectable (fix #8453)
  doc/conf.py
Labels: squash+merge me, merge delay passed

#9376 Avoid double space in "Executing install plan ..."
  cabal-install/src/Distribution/Client/ProjectBuilding.hs
  changelog.d/pr-9376
Labels: merge delay passed, merge+no rebase

#9189 Have hlint ignore CmmSourcesExe Demo
  .hlint.yaml
Labels: merge delay passed, merge+no rebase

#9063 [cabal-7825] Implement external command system
  Cabal/src/Distribution/Make.hs
  Cabal/src/Distribution/Simple.hs
  Cabal/src/Distribution/Simple/Command.hs
  cabal-install/src/Distribution/Client/Main.hs
  cabal-install/src/Distribution/Client/SavedFlags.hs
  doc/external-commands.rst
  doc/index.rst
Labels: merge me, merge delay passed

#9372 Bump dependencies for GHC 9.8
  Cabal-tests/Cabal-tests.cabal
  cabal-benchmarks/cabal-benchmarks.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
  cabal-testsuite/cabal-testsuite.cabal
  cabal.project
Labels: merge me, merge delay passed, re: ghc 9.8

#9384 Revert #3639 (Don't pass -package-db and -package flags to --abi-hash)
  Cabal/src/Distribution/Simple/GHC.hs
  Cabal/src/Distribution/Simple/GHCJS.hs
Labels: squash+merge me, merge delay passed

#9381 Use the newer haskell-actions organisation
  .github/workflows/lint.yml
Labels: merge delay passed, merge+no rebase

#9379 Restructure user guide into top-level guides, reference and explanation parts
  .gitignore
  doc/_templates/layout.html
  doc/bugs-and-stability.rst
  doc/cabal-context.rst
  doc/cabal-interface-stability.rst
  doc/cabal-package-description-file.rst
  doc/cabal-project-description-file.rst
  doc/cabaldomain.py
  doc/concepts-and-development.rst
  doc/conf.py
  doc/getting-started.rst
  doc/how-to-build-like-nix.rst
  doc/how-to-package-haskell-code.rst
  doc/how-to-report-bugs.rst
  doc/index.rst
  doc/nix-integration.rst
  doc/nix-local-build.rst
  doc/package-concepts.rst
Labels: documentation, merge me, re: devx, re: readthedocs, merge delay passed

#9387 Add instance Ord for Field, FieldLine, SectionArg and Name
  Cabal-syntax/src/Distribution/Fields/Field.hs
Labels: merge me, merge delay passed

#9355 Do not run CI for documentation changes
  .github/workflows/lint.yml
  .github/workflows/validate.skip.yml
  .github/workflows/validate.yml
Labels: documentation, merge me, re: devx, merge delay passed

#9400 Move documentation about how to use backpack
  doc/buildinfo-fields-reference.rst
  doc/cabal-package-description-file.rst
  doc/how-to-use-backpack.rst
  doc/index.rst
Labels: documentation, merge me, merge delay passed

#9377 Add reinstall test to LinkerOptions/NonignoredConfigs
  cabal-testsuite/PackageTests/LinkerOptions/NonignoredConfigs/cabal.out
  cabal-testsuite/PackageTests/LinkerOptions/NonignoredConfigs/cabal.test.hs
Labels: Cabal: tests/package-tests, merge delay passed, merge+no rebase

#8944 Reject index-states after last known index-state
  .gitignore
  cabal-install/src/Distribution/Client/CmdUpdate.hs
  cabal-install/src/Distribution/Client/Errors.hs
  cabal-install/src/Distribution/Client/IndexUtils.hs
  cabal-install/src/Distribution/Client/IndexUtils/Timestamp.hs
  cabal-install/tests/UnitTests/Distribution/Client/ArbitraryInstances.hs
  cabal-install/tests/UnitTests/Distribution/Client/IndexUtils/Timestamp.hs
  cabal-testsuite/PackageTests/Get/OnlyDescription/cabal.test.hs
  cabal-testsuite/PackageTests/Get/T7248/cabal.out
  cabal-testsuite/PackageTests/NewUpdate/RejectFutureIndexStates/cabal.out.in
  cabal-testsuite/PackageTests/NewUpdate/RejectFutureIndexStates/cabal.project
  cabal-testsuite/PackageTests/NewUpdate/RejectFutureIndexStates/cabal.test.hs
  cabal-testsuite/PackageTests/NewUpdate/RejectFutureIndexStates/fake-pkg/Main.hs
  cabal-testsuite/PackageTests/NewUpdate/RejectFutureIndexStates/fake-pkg/fake-pkg.cabal
  cabal-testsuite/PackageTests/NewUpdate/RejectFutureIndexStates/repo/pkg-1.0/Foo.hs
  cabal-testsuite/PackageTests/NewUpdate/RejectFutureIndexStates/repo/pkg-1.0/pkg.cabal
  changelog.d/die-on-missing-pkg-list
  changelog.d/index-state-cabal-update
Labels: attention: needs-review, squash+merge me, merge delay passed, attention: needs-manual-qa

#9380 Note how to do "not equal" with constraints
  doc/cabal-package-description-file.rst
Labels: documentation, merge delay passed, merge+no rebase

#9407 Fix AutogenModulesToggling test
  cabal-testsuite/PackageTests/AutogenModulesToggling/cabal.out
  cabal-testsuite/PackageTests/AutogenModulesToggling/cabal.test.hs
Labels: merge me, merge delay passed

#9221 Require version 3,11 of Cabal to support --semaphore flag
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
Labels: merge me, merge delay passed

#9397 Add dependencies used by `PackageTests` to exe:cabal-tests
  cabal-testsuite/cabal-testsuite.cabal
Labels: merge me, merge delay passed

#9421 Use Paths_cabal_install for cabal-install version number
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/Version.hs
Labels: squash+merge me, merge delay passed, attention: needs-manual-qa

#9388 Document --profiling-detail in setup-commands.
  doc/setup-commands.rst
Labels: documentation, merge me, merge delay passed

#9413 Add test requirement to PR template
  .github/pull_request_template.md
Labels: merge me, merge delay passed

#8879 A 'cabal path' command.
  cabal-install/src/Distribution/Client/Main.hs
  cabal-install/src/Distribution/Client/Setup.hs
  cabal-testsuite/PackageTests/Path/All/cabal.out
  cabal-testsuite/PackageTests/Path/All/cabal.test.hs
  cabal-testsuite/PackageTests/Path/Single/cabal.out
  cabal-testsuite/PackageTests/Path/Single/cabal.test.hs
  cabal-testsuite/src/Test/Cabal/Prelude.hs
  changelog.d/pr-8879
  doc/cabal-commands.rst
  doc/config.rst
Labels: squash+merge me, merge delay passed, cabal-install: cmd/path

#9425 CI: Attempt to enable tests for 9.6.3 windows
  .github/workflows/validate.yml
  cabal-testsuite/PackageTests/CCompilerOverride/custom-cc-clang.bat
  cabal-testsuite/PackageTests/CCompilerOverride/setup.test.hs
  cabal-testsuite/PackageTests/ForeignLibs/setup.test.hs
Labels: merge me, merge delay passed

#9439 testsuite: Be explicit about runtime test dependencies
  cabal-testsuite/README.md
  cabal-testsuite/Setup.hs
  cabal-testsuite/cabal-testsuite.cabal
  cabal-testsuite/src/Test/Cabal/Script.hs
  cabal-testsuite/static/Main.hs
Labels: merge me, merge delay passed

#9441 hurd: Enable using $ORIGIN in RPATH
  Cabal/src/Distribution/Simple/GHC.hs
  Cabal/src/Distribution/Simple/GHCJS.hs
  changelog.d/pr-9441
Labels: merge me, merge delay passed

#9434 Fix the platform string for GNU/Hurd
  Cabal/src/Distribution/Simple/GHC/Internal.hs
  changelog.d/pr-9434
Labels: merge me, merge delay passed

#9443 Use linker capability detection to improve linker use
  Cabal/src/Distribution/Simple/Configure.hs
  Cabal/src/Distribution/Simple/GHC/Internal.hs
  Cabal/src/Distribution/Simple/Program/Builtin.hs
  Cabal/src/Distribution/Simple/Program/Db.hs
  changelog.d/pr-9443
Labels: merge me, merge delay passed

#9445 Add support for 64-bit SPARC as a separate architecture
  Cabal-syntax/src/Distribution/System.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  Cabal/src/Distribution/Simple/PreProcess.hs
  changelog.d/pr-9445
Labels: merge me, merge delay passed

#9432 Remove debug-conflict-sets flag from solver package
  bootstrap/linux-8.10.7.json
  bootstrap/linux-9.0.2.json
  bootstrap/linux-9.2.7.json
  bootstrap/linux-9.4.4.json
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install-solver/src/Distribution/Solver/Modular/ConflictSet.hs
  cabal-install-solver/src/Distribution/Solver/Modular/Validate.hs
Labels: cabal-install: solver, merge me, merge delay passed

#9429 formatting: Add style-commit makefile target
  CONTRIBUTING.md
  Makefile
Labels: merge me, merge delay passed

#9446 Fix assertion failure when combining build-tool-depends and --enable-documentation
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-testsuite/PackageTests/HaddockBuildDepends/a.cabal
  cabal-testsuite/PackageTests/HaddockBuildDepends/cabal.out
  cabal-testsuite/PackageTests/HaddockBuildDepends/cabal.project
  cabal-testsuite/PackageTests/HaddockBuildDepends/cabal.test.hs
  cabal-testsuite/PackageTests/HaddockBuildDepends/repo/exe-1/Main.hs
  cabal-testsuite/PackageTests/HaddockBuildDepends/repo/exe-1/exe.cabal
  cabal-testsuite/PackageTests/HaddockBuildDepends/repo/lib-1/Lib.hs
  cabal-testsuite/PackageTests/HaddockBuildDepends/repo/lib-1/lib.cabal
  cabal-testsuite/PackageTests/HaddockBuildDepends/src/MyLib.hs
  cabal-testsuite/src/Test/Cabal/Prelude.hs
Labels: merge me, merge delay passed

#9409 Only move code to Simple/GHC/Build*
  Cabal/Cabal.cabal
  Cabal/src/Distribution/Simple/GHC.hs
  Cabal/src/Distribution/Simple/GHC/Build.hs
  Cabal/src/Distribution/Simple/GHC/BuildGeneric.hs
  Cabal/src/Distribution/Simple/GHC/BuildOrRepl.hs
Labels: merge delay passed, merge+no rebase

#9391 cabal-install-solver: fix pkgconf 1.9 --modversion regression
  cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs
  changelog.d/pr-9391
Labels: cabal-install: solver, merge me, merge delay passed, attention: needs-manual-qa

#9412 Finish off external commands feature
  Cabal/src/Distribution/Make.hs
  Cabal/src/Distribution/Simple.hs
  Cabal/src/Distribution/Simple/Command.hs
  cabal-install/src/Distribution/Client/Main.hs
  cabal-install/src/Distribution/Client/SavedFlags.hs
  cabal-testsuite/PackageTests/ExternalCommand/cabal.out
  cabal-testsuite/PackageTests/ExternalCommand/cabal.project
  cabal-testsuite/PackageTests/ExternalCommand/cabal.test.hs
  cabal-testsuite/PackageTests/ExternalCommand/setup-test/AAAA.hs
  cabal-testsuite/PackageTests/ExternalCommand/setup-test/CHANGELOG.md
  cabal-testsuite/PackageTests/ExternalCommand/setup-test/LICENSE
  cabal-testsuite/PackageTests/ExternalCommand/setup-test/setup-test.cabal
  cabal-testsuite/PackageTests/ExternalCommandEnv/cabal.out
  cabal-testsuite/PackageTests/ExternalCommandEnv/cabal.project
  cabal-testsuite/PackageTests/ExternalCommandEnv/cabal.test.hs
  cabal-testsuite/PackageTests/ExternalCommandEnv/setup-test/AAAA.hs
  cabal-testsuite/PackageTests/ExternalCommandEnv/setup-test/CHANGELOG.md
  cabal-testsuite/PackageTests/ExternalCommandEnv/setup-test/LICENSE
  cabal-testsuite/PackageTests/ExternalCommandEnv/setup-test/setup-test.cabal
  cabal-testsuite/PackageTests/ExternalCommandHelp/cabal.out
  cabal-testsuite/PackageTests/ExternalCommandHelp/cabal.project
  cabal-testsuite/PackageTests/ExternalCommandHelp/cabal.test.hs
  cabal-testsuite/PackageTests/ExternalCommandHelp/setup-test/AAAA.hs
  cabal-testsuite/PackageTests/ExternalCommandHelp/setup-test/CHANGELOG.md
  cabal-testsuite/PackageTests/ExternalCommandHelp/setup-test/LICENSE
  cabal-testsuite/PackageTests/ExternalCommandHelp/setup-test/setup-test.cabal
  cabal-testsuite/PackageTests/ExternalCommandSetup/aaaa/LICENSE
  cabal-testsuite/PackageTests/ExternalCommandSetup/aaaa/Main.hs
  cabal-testsuite/PackageTests/ExternalCommandSetup/aaaa/aaaa.cabal
  cabal-testsuite/PackageTests/ExternalCommandSetup/custom/CHANGELOG.md
  cabal-testsuite/PackageTests/ExternalCommandSetup/custom/LICENSE
  cabal-testsuite/PackageTests/ExternalCommandSetup/custom/Setup.hs
  cabal-testsuite/PackageTests/ExternalCommandSetup/custom/custom.cabal
  cabal-testsuite/PackageTests/ExternalCommandSetup/setup.cabal.hs
  cabal-testsuite/PackageTests/ExternalCommandSetup/setup.out
  cabal-testsuite/src/Test/Cabal/Prelude.hs
  doc/external-commands.rst
Labels: merge me, merge delay passed, cabal-install: cmd/external-cmd

#9459 Use Base16 hash for script path.
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/HashValue.hs
  cabal-install/src/Distribution/Client/ScriptUtils.hs
  cabal-testsuite/cabal-testsuite.cabal
  cabal-testsuite/src/Test/Cabal/Prelude.hs
  changelog.d/base16-script-cache
Labels: platform: windows, merge me, merge delay passed, attention: needs-manual-qa

#9463 Migrate to haskell-actions/setup
  .github/workflows/validate.yml
Labels: continuous-integration, merge me, merge delay passed

#9454 testsuite: Introduce Cabal-tests library for common testsuite functions
  Cabal-tests/Cabal-tests.cabal
  Cabal-tests/lib/Test/Utils/TempTestDir.hs
  Cabal/Cabal.cabal
  cabal-install/cabal-install.cabal
  cabal-install/tests/UnitTests/Distribution/Client/FetchUtils.hs
  cabal-install/tests/UnitTests/Distribution/Client/Get.hs
  cabal-install/tests/UnitTests/Distribution/Client/VCS.hs
  cabal-testsuite/cabal-testsuite.cabal
  cabal-testsuite/src/Test/Cabal/Monad.hs
  cabal-testsuite/src/Test/Cabal/Prelude.hs
  changelog.d/issue-9453
Labels: attention: needs-review, merge me, merge delay passed
