Repository haskell/cabal, pull requests merged in 2023-04, with the labels that each got.

#8886 Add instructions to the PR template for manual QA
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: squash+merge me, type: testing, merge delay passed

#8873 Fix typo in Pretty.hs
  Cabal-syntax/src/Distribution/Fields/Pretty.hs
Labels: merge me, merge delay passed

#8662 Support for alternative GHC backends: extra-compilation-artifacts directory installation
  Cabal/src/Distribution/Simple/GHC.hs
  cabal-testsuite/PackageTests/ExtraCompilationArtifacts/Lib.hs
  cabal-testsuite/PackageTests/ExtraCompilationArtifacts/lib.cabal
  cabal-testsuite/PackageTests/ExtraCompilationArtifacts/test.hs
  changelog.d/pr-8662
  doc/setup-commands.rst
Labels: type: enhancement, attention: needs-review, squash+merge me, re: ghc-plugins, merge delay passed

#8860 Prepends >= to cabal versions older than 1.12
  cabal-install/src/Distribution/Client/Init/Format.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/Golden.hs
  cabal-install/tests/fixtures/init/golden/pkg-desc/pkg-with-flags.golden
  changelog.d/issue-8206
Labels: squash+merge me, merge delay passed

#8897 Make `check` comply with Hackage requirements
  Cabal/src/Distribution/PackageDescription/Check.hs
  Cabal/src/Distribution/Simple/SrcDist.hs
  cabal-install/src/Distribution/Client/Check.hs
  cabal-install/src/Distribution/Client/Setup.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/COptions/CxxOs/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/CabalVersion/DefaultExtension/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/CabalVersion/DefaultLanguage/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/CabalVersion/ExtraDynamicLibraryFlavour/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/CabalVersion/Mixins/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/CabalVersion/Sources/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/CabalVersion/VirtualModules/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Fields/DeprecatedExtension/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Fields/NoCategory/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Fields/NoDescription/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Fields/NoMaintainer/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Fields/NoSynopsis/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Fields/ShortDescription/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/GHCOptions/GHCSharedOptions/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/License/NoFileSpecified/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/License/SuspiciousLicense/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/License/SuspiciousVersion/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/License/WarnAllRightsReserved/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Sanity/VersionSignatures/cabal.test.hs
  cabal-testsuite/PackageTests/Check/NonConfCheck/DevOnlyFlags/Profiling/cabal.test.hs
  cabal-testsuite/PackageTests/Check/NonConfCheck/UnusedFlags/cabal.test.hs
  cabal-testsuite/PackageTests/Check/PackageFiles/VCSInfo/cabal.test.hs
  changelog.d/pr-8897
  doc/cabal-commands.rst
Labels: cabal-install: cmd/check, squash+merge me, merge delay passed, Manual QA

#8893 CI: remove dependency on cabal-plan (#8891)
  .github/workflows/validate.yml
  Makefile
  validate.sh
Labels: merge me, merge delay passed

#8788 Add --haddock-output-dir flag to cabal haddock.
  Cabal/src/Distribution/Simple/Flag.hs
  Cabal/src/Distribution/Simple/Haddock.hs
  Cabal/src/Distribution/Simple/Setup/Haddock.hs
  cabal-install/src/Distribution/Client/CmdClean.hs
  cabal-install/src/Distribution/Client/CmdHaddock.hs
  cabal-install/src/Distribution/Client/CmdHaddockProject.hs
  cabal-install/src/Distribution/Client/CmdOutdated.hs
  cabal-install/src/Distribution/Client/Config.hs
  cabal-install/src/Distribution/Client/DistDirLayout.hs
  cabal-install/src/Distribution/Client/NixStyleOptions.hs
  cabal-install/src/Distribution/Client/PackageHash.hs
  cabal-install/src/Distribution/Client/ProjectBuilding.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Types.hs
  cabal-install/src/Distribution/Client/ProjectOrchestration.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/ProjectPlanning/Types.hs
  cabal-install/src/Distribution/Client/Setup.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
  cabal-testsuite/.gitignore
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockOutputCmd/A/A.cabal
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockOutputCmd/A/A.hs
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockOutputCmd/cabal.out
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockOutputCmd/cabal.project
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockOutputCmd/cabal.test.hs
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockOutputCmd/repo/Dummy.hs
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockOutputConfig/A/A.cabal
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockOutputConfig/A/A.hs
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockOutputConfig/cabal.out
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockOutputConfig/cabal.project
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockOutputConfig/cabal.test.hs
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockOutputConfig/repo/Dummy.hs
  changelog.d/issue-8270
  doc/cabal-project.rst
Labels: type: enhancement, cabal-install: cmd/haddock, merge me, merge delay passed

#8907 docs: cabal repl fresh-up
  doc/cabal-commands.rst
Labels: merge me, merge delay passed

#8904 Fix `prefer-oldest` documentation
  doc/cabal-project.rst
Labels: documentation, merge me, merge delay passed

#8910 CI: ubuntu 20.04 -> latest
  .github/workflows/validate.yml
Labels: merge me, merge delay passed

#8896 Regenerate Lexer.hs with latest Alex (fix #8892)
  .github/workflows/quick-jobs.yml
  Cabal-syntax/src/Distribution/Fields/Lexer.hs
  Cabal-syntax/src/Distribution/Fields/LexerMonad.hs
  Cabal-tests/tests/ParserTests/regressions/Octree-0.5.format
  Cabal-tests/tests/ParserTests/regressions/monad-param.format
  Cabal-tests/tests/ParserTests/regressions/th-lift-instances.format
  cabal-testsuite/PackageTests/Check/PackageFiles/BOM/cabal.out
  changelog.d/issue-8892
  templates/Lexer.x
Labels: merge me, merge delay passed, attention: needs-backport 3.10
