Repository haskell/cabal, pull requests merged in 2023-02, with the labels that each got.

#8690 For ghc calls pass Cabal's build/ directory after user's src/ directory so that contents of src/ takes precedence
  Cabal/src/Distribution/Simple/GHC/Internal.hs
  cabal-testsuite/PackageTests/AutogenModulesToggling/Main.hs
  cabal-testsuite/PackageTests/AutogenModulesToggling/Setup.hs
  cabal-testsuite/PackageTests/AutogenModulesToggling/cabal.out
  cabal-testsuite/PackageTests/AutogenModulesToggling/cabal.project
  cabal-testsuite/PackageTests/AutogenModulesToggling/cabal.test.hs
  cabal-testsuite/PackageTests/AutogenModulesToggling/gen/Generated.hs
  cabal-testsuite/PackageTests/AutogenModulesToggling/src-inputs/Generated.hgen
  cabal-testsuite/PackageTests/AutogenModulesToggling/src/Lib.hs
  cabal-testsuite/PackageTests/AutogenModulesToggling/test.cabal
  cabal-testsuite/PackageTests/ShowBuildInfo/Complex/single.out
  changelog.d/issue-8689
Labels: attention: needs-review, squash+merge me, merge delay passed

#8738 Document the `remote-repo-cache` option as is implemented (it is).
  changelog.d/issue-8737
  doc/cabal-project.rst
Labels: merge me, merge delay passed

#8732 Fix repl discarding --build-depends
  Cabal-syntax/src/Distribution/Types/GenericPackageDescription.hs
  cabal-install/src/Distribution/Client/CmdRepl.hs
  cabal-testsuite/PackageTests/ReplBuildDepends/Foo.hs
  cabal-testsuite/PackageTests/ReplBuildDepends/cabal.allow-newer.out
  cabal-testsuite/PackageTests/ReplBuildDepends/cabal.allow-older.out
  cabal-testsuite/PackageTests/ReplBuildDepends/cabal.normal.out
  cabal-testsuite/PackageTests/ReplBuildDepends/cabal.project
  cabal-testsuite/PackageTests/ReplBuildDepends/cabal.test.hs
  cabal-testsuite/PackageTests/ReplBuildDepends/pkg.cabal
  changelog.d/pr-8732
Labels: attention: needs-review, cabal-install: cmd/repl, squash+merge me, merge delay passed

#8748 Ensure js-sources are used only with JavaScript arch
  Cabal/src/Distribution/Simple/GHC.hs
  Cabal/src/Distribution/Simple/Register.hs
  cabal-testsuite/PackageTests/JS/JsSources/js-arch.test.hs
  cabal-testsuite/PackageTests/JS/JsSources/jssources.cabal
  cabal-testsuite/PackageTests/JS/JsSources/other-arch.out
  cabal-testsuite/PackageTests/JS/JsSources/other-arch.test.hs
  cabal-testsuite/PackageTests/JS/JsSources/src/Lib.hs
  cabal-testsuite/PackageTests/JS/JsSources/srcJS/Lib.hs
Labels: attention: needs-review, merge me, merge delay passed, attention: needs-backport 3.10

#8669 Update bootstrap root keys
  cabal-install/src/Distribution/Client/Config.hs
Labels: attention: needs-review, merge me, merge delay passed

#8709 cabal run +RTS warning
  cabal-install/src/Distribution/Client/CmdBench.hs
  cabal-install/src/Distribution/Client/CmdRun.hs
  cabal-install/src/Distribution/Client/CmdTest.hs
  cabal-install/src/Distribution/Client/Utils.hs
  cabal-testsuite/PackageTests/NewBuild/CmdBench/WarningRTS/Main.hs
  cabal-testsuite/PackageTests/NewBuild/CmdBench/WarningRTS/WarningRTS.cabal
  cabal-testsuite/PackageTests/NewBuild/CmdBench/WarningRTS/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdBench/WarningRTS/cabal.project
  cabal-testsuite/PackageTests/NewBuild/CmdBench/WarningRTS/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/WarningRTS/Main.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/WarningRTS/WarningRTS.cabal
  cabal-testsuite/PackageTests/NewBuild/CmdRun/WarningRTS/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/WarningRTS/cabal.project
  cabal-testsuite/PackageTests/NewBuild/CmdRun/WarningRTS/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdTest/WarningRTS/Main.hs
  cabal-testsuite/PackageTests/NewBuild/CmdTest/WarningRTS/WarningRTS.cabal
  cabal-testsuite/PackageTests/NewBuild/CmdTest/WarningRTS/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdTest/WarningRTS/cabal.project
  cabal-testsuite/PackageTests/NewBuild/CmdTest/WarningRTS/cabal.test.hs
  changelog.d/pr-8709
Labels: type: enhancement, attention: needs-review, merge me, re: warnings, re: user experience, merge delay passed

#8744 Revert "Fix project-local build flags being ignored."
  cabal-install/src/Distribution/Client/Configure.hs
  cabal-install/src/Distribution/Client/Install.hs
  cabal-install/src/Distribution/Client/ProjectPlanOutput.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/SetupWrapper.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-testsuite/PackageTests/LinkerOptions/NonignoredConfigs/cabal.test.hs
  changelog.d/pr-8623
Labels: attention: needs-review, merge me, re: dynamic-linking, merge delay passed, attention: needs-backport 3.10

#8735 doctests: switch to the preffered method of calling the tool
  .github/workflows/quick-jobs.yml
  Makefile
  cabal-testsuite/README.md
Labels: merge me, re: doctest, merge delay passed

#8720 Bump cabal-bootstrap-gen to GHC 9.4.4 ecosystem
  .github/workflows/bootstrap.yml
  Makefile
  bootstrap/cabal-bootstrap-gen.cabal
  bootstrap/linux-9.4.4.json
  bootstrap/src/Main.hs
Labels: cabal-install: bootstrap, merge me, merge delay passed

#8764 (cabal init) Suggest BSD-3-Clause as default
  cabal-install/src/Distribution/Client/Init/Interactive/Command.hs
  cabal-testsuite/PackageTests/Init/init-interactive.test.hs
  changelog.d/issue-8757
Labels: cabal-install: cmd/init, squash+merge me, re: license, merge delay passed

#8769 don't auto-download in hash validation phase
  cabal-install/src/Distribution/Client/FetchUtils.hs
Labels: attention: needs-test, merge me, merge delay passed, attention: needs-backport 3.10

#8775 Update © year to 2023
  Cabal-syntax/Cabal-syntax.cabal
  Cabal-syntax/LICENSE
  Cabal-tests/Cabal-tests.cabal
  Cabal-tests/LICENSE
  Cabal/Cabal.cabal
  Cabal/LICENSE
  LICENSE
  cabal-benchmarks/LICENSE
  cabal-benchmarks/cabal-benchmarks.cabal
  cabal-dev-scripts/LICENSE
  cabal-install-solver/LICENSE
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/LICENSE
  cabal-install/cabal-install.cabal
  cabal-testsuite/LICENSE
  cabal-testsuite/cabal-testsuite.cabal
  doc/conf.py
  solver-benchmarks/LICENSE
  solver-benchmarks/solver-benchmarks.cabal
Labels: squash+merge me, merge delay passed, attention: needs-backport 3.10

#8783 Fix `config` format docs.
  doc/nix-local-build.rst
Labels: merge me, merge delay passed

#8794 Disallow GHC <8.0 for Cabal{,-syntax} & cabal-install-solver
  Cabal-syntax/Cabal-syntax.cabal
  Cabal-tests/Cabal-tests.cabal
  Cabal/Cabal.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-testsuite/cabal-testsuite.cabal
  changelog.d/pr-8794
Labels: squash+merge me, re: dependencies, merge delay passed

#8799 Bump cabal version numbers and bounds to 3.10 for release
  .github/workflows/bootstrap.yml
  Cabal-QuickCheck/Cabal-QuickCheck.cabal
  Cabal-described/Cabal-described.cabal
  Cabal-syntax/Cabal-syntax.cabal
  Cabal-syntax/src/Distribution/CabalSpecVersion.hs
  Cabal-tree-diff/Cabal-tree-diff.cabal
  Cabal/Cabal.cabal
  Cabal/Makefile
  Makefile
  bootstrap/cabal-bootstrap-gen.cabal
  bootstrap/linux-8.10.7.json
  bootstrap/linux-8.6.5.json
  bootstrap/linux-8.8.4.json
  bootstrap/linux-9.0.2.json
  bootstrap/linux-9.2.3.json
  bootstrap/linux-9.2.6.json
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/Version.hs
  cabal-testsuite/cabal-testsuite.cabal
  doc/conf.py
  solver-benchmarks/solver-benchmarks.cabal
Labels: release, attention: needs-review, merge me, merge delay passed

#8754 CI: add GHC pre-release
  .github/workflows/changelogs.yml
  .github/workflows/quick-jobs.yml
  .github/workflows/validate.yml
  Cabal-syntax/src/Distribution/Utils/Structured.hs
  cabal-install/src/Distribution/Client/VCS.hs
  cabal-testsuite/PackageTests/Backpack/Includes2/setup-external.test.hs
  cabal-testsuite/PackageTests/Backpack/Includes2/setup-per-component.test.hs
  cabal-testsuite/PackageTests/Backpack/Includes3/setup-external-ok.test.hs
  cabal-testsuite/PackageTests/JS/JsSources/js-arch.test.hs
Labels: continuous-integration, merge me, merge delay passed, re: ghc 9.6, attention: needs-backport 3.10

#8779 Apply command line flags to install packages (#8637)
  cabal-install/src/Distribution/Client/CmdInstall.hs
  cabal-testsuite/PackageTests/LinkerOptions/NonignoredConfigs/cabal.test.hs
  changelog.d/issue-8637
Labels: squash+merge me, merge delay passed, attention: needs-backport 3.10

#8789 Doc: bump to Python 3.10; Sphinx 5.3.0. Remove `--constraint: foo -none` & some polishing
  .github/workflows/users-guide.yml
  doc/Makefile
  doc/requirements.in
  doc/requirements.txt
  doc/setup-commands.rst
Labels: documentation, merge me, re: readthedocs, re: constraint, merge delay passed

#8765 Fix #8756: doc: `extra-source-files` are tracked by `cabal build`
  doc/cabal-package.rst
Labels: documentation, attention: needs-review, squash+merge me, merge delay passed, re: extra-source-files

#8784 Add traceM and traceShowM
  Cabal-syntax/src/Distribution/Compat/Prelude.hs
Labels: merge me, re: devx, merge delay passed

#8793 Add `Distribution.Client.Main`
  cabal-install/cabal-install.cabal
  cabal-install/main/Main.hs
  cabal-install/src/Distribution/Client/Main.hs
Labels: merge me, re: API, merge delay passed

#8712 Combine non-installable & non-upgradable packages
  cabal-install-solver/src/Distribution/Solver/Modular.hs
  cabal-install-solver/src/Distribution/Solver/Modular/Solver.hs
  cabal-install/src/Distribution/Client/Dependency.hs
Labels: cabal-install: solver, squash+merge me, merge delay passed
