Repository haskell/cabal, pull requests merged in 2023-06, with the labels that each got.

#8979 Revert workaround to filter JavaScriptFFI out on GHC versions where G…
  Cabal/src/Distribution/Simple/GHC.hs
Labels: squash+merge me, merge delay passed, attention: needs-backport 3.10

#8985 Ignore more formatting commits
  .git-blame-ignore-revs
Labels: merge me, merge delay passed

#8987 Fix QuickCheck instance of PackageName to not produce 'all' (fix #8986)
  Cabal-QuickCheck/src/Test/QuickCheck/Instances/Cabal.hs
Labels: cabal-testsuite, merge me, merge delay passed

#8728 Deduplicate `LD_LIBRARY_PATH` when running tests
  Cabal/src/Distribution/Simple/LocalBuildInfo.hs
  changelog.d/pr-8728
Labels: squash+merge me, merge delay passed

#9007 Generate cabal-testsuite modules at configure time
  cabal-testsuite/Setup.hs
  changelog.d/pr-9007
Labels: attention: needs-review, merge me, merge delay passed

#8992 Add the ExtendedLiterals extension
  Cabal-syntax/src/Language/Haskell/Extension.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  changelog.d/pr-8992
  editors/vim/syntax/cabal.vim
Labels: merge me, merge delay passed

#9004 Do not check PVP on internal targets
  Cabal/src/Distribution/PackageDescription/Check.hs
  cabal-testsuite/PackageTests/Check/NonConfCheck/PackageVersionsNoCheck/cabal.out
  cabal-testsuite/PackageTests/Check/NonConfCheck/PackageVersionsNoCheck/cabal.test.hs
  cabal-testsuite/PackageTests/Check/NonConfCheck/PackageVersionsNoCheck/pkg.cabal
  changelog.d/pr-9004
Labels: cabal-install: cmd/check, squash+merge me, merge delay passed, attention: needs-backport 3.10

#8996 Specify Fourmolu version
  CONTRIBUTING.md
Labels: documentation, merge me, re: devx, merge delay passed

#9011 CONTRIBUTING.md: more description of changelogs
  CONTRIBUTING.md
Labels: squash+merge me, merge delay passed

#9006 haiku: add as known platform
  Cabal-syntax/src/Distribution/System.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  Cabal/src/Distribution/Simple/GHC.hs
  Cabal/src/Distribution/Simple/GHCJS.hs
  Cabal/src/Distribution/Simple/InstallDirs.hs
  Cabal/src/Distribution/Simple/PreProcess.hs
  changelog.d/pr-9006
Labels: squash+merge me, merge delay passed

#9001 Show how to install cabal-head via GHCup
  README.md
Labels: documentation, merge me, merge delay passed

#9013 Do not check PVP on internal targets (backport of #9004 to 3.10)
  Cabal/src/Distribution/PackageDescription/Check.hs
  cabal-install/cabal-install.cabal
  cabal-install/tests/UnitTests/Distribution/Client/ArbitraryInstances.hs
  cabal-testsuite/PackageTests/Check/NonConfCheck/PackageVersionsNoCheck/cabal.out
  cabal-testsuite/PackageTests/Check/NonConfCheck/PackageVersionsNoCheck/cabal.test.hs
  cabal-testsuite/PackageTests/Check/NonConfCheck/PackageVersionsNoCheck/pkg.cabal
  changelog.d/pr-9004
Labels: merge me, merge delay passed

#9002 Fix parsing of password-command option (#6268)
  cabal-install/src/Distribution/Client/Setup.hs
  cabal-install/src/Distribution/Deprecated/ParseUtils.hs
  cabal-testsuite/PackageTests/UserConfig/cabal.out
  cabal-testsuite/PackageTests/UserConfig/cabal.test.hs
  changelog.d/issue-6268
  doc/cabal-commands.rst
Labels: cabal-install: other, cabal-install: cmd/upload, cabal-install: cmd/user-config, merge me, merge delay passed, attention: needs-manual-qa

#8982 Documentation cleanup around sublibraries
  doc/cabal-package.rst
Labels: merge me, merge delay passed

#9036 Update CONTRIBUTING.md to be clearer about the location of the QA notes
  CONTRIBUTING.md
Labels: squash+merge me, merge delay passed

#8952 Don't add `extra-prog-path` to `~/.config/cabal/config` (#8951)
  cabal-install/src/Distribution/Client/Config.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/IntegrationTests2/config/default-config
  changelog.d/issue-8951
Labels: merge me, merge delay passed, regression in 3.10

#9024 Add documentation for default-language field
  doc/cabal-package.rst
Labels: merge me, merge delay passed

#8957 Show full config file contents when option test fails
  cabal-install/tests/IntegrationTests2.hs
Labels: merge me, merge delay passed

#9055 testsuite: use removeDirectoryRecursiveHack to cleanup
  Cabal/Cabal.cabal
  Cabal/src/Distribution/Utils/TempTestDir.hs
  cabal-install/cabal-install.cabal
  cabal-install/tests/UnitTests/Distribution/Client/FetchUtils.hs
  cabal-install/tests/UnitTests/Distribution/Client/Get.hs
  cabal-install/tests/UnitTests/Distribution/Client/VCS.hs
  cabal-testsuite/src/Test/Cabal/Monad.hs
  cabal-testsuite/src/Test/Cabal/Prelude.hs
Labels: merge me, merge delay passed

#9051 #8975, #8981, #8983 rebased
  CONTRIBUTING.md
  Cabal-syntax/src/Distribution/Fields/Lexer.hs
  Cabal-syntax/src/Distribution/Fields/LexerMonad.hs
  Cabal-syntax/src/Distribution/Fields/Parser.hs
  Cabal-syntax/src/Distribution/Parsec/Warning.hs
  Cabal-tests/tests/CheckTests.hs
  Cabal-tests/tests/ParserTests/regressions/decreasing-indentation.cabal
  Cabal-tests/tests/ParserTests/regressions/decreasing-indentation.check
  Makefile
  cabal-testsuite/PackageTests/Check/NonConfCheck/DuplicatedModules/pkg.cabal
  cabal.project
  changelog.d/inconsistent-indentation
  templates/Lexer.x
Labels: merge me, merge delay passed

#9015 Document the pkg: prefix for package targets
  doc/cabal-commands.rst
Labels: merge me, attention: needs-help, merge delay passed

#9033 Update Cabal{,-install,-syntax} to 3.10.2.0
  .github/workflows/bootstrap.yml
  .github/workflows/validate.yml
  Cabal-syntax/Cabal-syntax.cabal
  Cabal/Cabal.cabal
  Cabal/Makefile
  Makefile
  bootstrap/cabal-bootstrap-gen.cabal
  bootstrap/linux-8.10.7.json
  bootstrap/linux-9.0.2.json
  bootstrap/linux-9.2.8.json
  bootstrap/linux-9.4.5.json
  cabal-install/cabal-install.cabal
  cabal-testsuite/PackageTests/CustomPreProcess/cabal.test.hs
  cabal-testsuite/PackageTests/FFI/ForeignOptsC/cabal.test.hs
  cabal-testsuite/PackageTests/FFI/ForeignOptsCxx/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdBench/OptionsFlag/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdBuild/ScriptBuildRepl/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdBuild/ScriptBuildRun/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptLiterate/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptNoExtension/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptWithProjectBlock/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdTest/OptionsFlag/cabal.test.hs
  cabal-testsuite/cabal-testsuite.cabal
  doc/conf.py
Labels: merge me, merge delay passed

#9019 Store hie files
  Cabal/src/Distribution/Simple/GHC.hs
  Cabal/src/Distribution/Simple/GHC/ImplInfo.hs
  Cabal/src/Distribution/Simple/GHC/Internal.hs
  Cabal/src/Distribution/Simple/Program/GHC.hs
  Cabal/src/Distribution/Simple/Setup/Common.hs
  cabal-testsuite/PackageTests/CopyHie/HieLocal.hs
  cabal-testsuite/PackageTests/CopyHie/cabal.out
  cabal-testsuite/PackageTests/CopyHie/cabal.project
  cabal-testsuite/PackageTests/CopyHie/cabal.test.hs
  cabal-testsuite/PackageTests/CopyHie/hie-local.cabal
  cabal-testsuite/PackageTests/CopyHie/hie/Hie.hs
  cabal-testsuite/PackageTests/CopyHie/hie/hie.cabal
  cabal-testsuite/PackageTests/CopyHie/repo/hie-dependency-0.1.0.0/HieDependency.hs
  cabal-testsuite/PackageTests/CopyHie/repo/hie-dependency-0.1.0.0/hie-dependency.cabal
  cabal-testsuite/PackageTests/CopyHie/setup.cabal.out
  cabal-testsuite/PackageTests/CopyHie/setup.out
  cabal-testsuite/PackageTests/CopyHie/setup.test.hs
  cabal-testsuite/PackageTests/ShowBuildInfo/Complex/single.out
  cabal-testsuite/src/Test/Cabal/Monad.hs
  changelog.d/pr-9019
Labels: squash+merge me, merge delay passed

#9044 Remove SandboxIndex
  cabal-install/src/Distribution/Client/IndexUtils.hs
Labels: merge me, merge delay passed

#9049 Do not always pass `--quickjump` to haddock
  Cabal/src/Distribution/Simple/Haddock.hs
  changelog.d/pr-9049
Labels: merge me, attention: needs-backport 3.10

#9071 Avoid dodgy Rep (..) import in Cabal-syntax
  Cabal-syntax/src/Distribution/Compat/Prelude.hs
Labels: merge me, merge delay passed, attention: needs-backport 3.10
