Repository haskell/cabal, pull requests merged in 2023-10, with the labels that each got.

#9285 Relax extension `.c` requirement for c-sources
  Cabal/src/Distribution/Simple/GHC.hs
  cabal-testsuite/PackageTests/CSourcesSanitisation/build.out
  cabal-testsuite/PackageTests/CSourcesSanitisation/cbits/gwinsz.cc
  cabal-testsuite/PackageTests/CSourcesSanitisation/repro.cabal
Labels: merge me, merge delay passed

#9287 README of testsuite: fix formatting in `doctest` section
  cabal-testsuite/README.md
Labels: documentation, merge me, re: devx, merge delay passed

#9282 Removing `chooseSolver` and inline `Modular` solver as default choice
  cabal-install/src/Distribution/Client/Configure.hs
  cabal-install/src/Distribution/Client/Dependency.hs
  cabal-install/src/Distribution/Client/Fetch.hs
  cabal-install/src/Distribution/Client/Freeze.hs
  cabal-install/src/Distribution/Client/Install.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs
Labels: merge me, merge delay passed

#9134 Try each pkg-config query separatedly
  Cabal/src/Distribution/Simple/Program/Builtin.hs
  cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs
  changelog.d/pkgconfig-envvars
  changelog.d/pkgconfig-once
Labels: merge me, merge delay passed, re: pkg-config

#9276 Subsequent Cabal-install package errors
  cabal-install/src/Distribution/Client/CmdBench.hs
  cabal-install/src/Distribution/Client/CmdBuild.hs
  cabal-install/src/Distribution/Client/CmdClean.hs
  cabal-install/src/Distribution/Client/CmdInstall/ClientInstallTargetSelector.hs
  cabal-install/src/Distribution/Client/CmdOutdated.hs
  cabal-install/src/Distribution/Client/CmdRepl.hs
  cabal-install/src/Distribution/Client/CmdRun.hs
  cabal-install/src/Distribution/Client/CmdUpdate.hs
  cabal-install/src/Distribution/Client/Config.hs
  cabal-install/src/Distribution/Client/Errors.hs
  cabal-install/src/Distribution/Client/Fetch.hs
  cabal-install/src/Distribution/Client/FetchUtils.hs
  cabal-install/src/Distribution/Client/List.hs
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/src/Distribution/Client/SetupWrapper.hs
  cabal-install/src/Distribution/Client/Targets.hs
  cabal-testsuite/PackageTests/ConditionalAndImport/cabal.out
  cabal-testsuite/PackageTests/ConfigFile/T7705/cabal.out
  cabal-testsuite/PackageTests/Get/T7248/cabal.out
  cabal-testsuite/PackageTests/MultiRepl/NotEnabledFail/cabal.multirepl-a.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ExeAndLib/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/MultipleExes/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/MultiplePackages/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/RunMainBad/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/Single/cabal.out
  cabal-testsuite/PackageTests/Outdated/outdated-project-file.out
  cabal-testsuite/PackageTests/Outdated/outdated_freeze.out
Labels: type: enhancement, attention: needs-review, merge me, merge delay passed

#9317 Fix `installCommand` description typo
  Cabal/src/Distribution/Simple/Setup/Install.hs
Labels: merge me, merge delay passed

#9297 Allow containers-0.7
  Cabal/Cabal.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
Labels: merge me, merge delay passed

#9319 Fix #9318 Avoid Haddock warning with `haddock --for-hackage`
  Cabal/src/Distribution/Simple/Haddock.hs
Labels: merge me, merge delay passed

#9306 Upgrade urllib3 due to CVE-2023-43804
  doc/requirements.in
  doc/requirements.txt
Labels: merge me, merge delay passed

#9332 Fix #5210 Don't refer to `index.html` when Haddock will not create it
  Cabal/src/Distribution/Simple/Haddock.hs
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockForHackageCmdOutput/A/A.cabal
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockForHackageCmdOutput/A/A.hs
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockForHackageCmdOutput/cabal.out
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockForHackageCmdOutput/cabal.project
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockForHackageCmdOutput/cabal.test.hs
  changelog.d/pr-9332
Labels: merge me, merge delay passed

#9340 Added or expanded 5 comments…
  Cabal/src/Distribution/Compat/ResponseFile.hs
  Cabal/src/Distribution/Simple.hs
  cabal-install/src/Distribution/Client/Main.hs
Labels: documentation, attention: needs-review, merge me, merge delay passed

#9324 Remaining Cabal-Install package errors
  cabal-install/src/Distribution/Client/CmdErrorMessages.hs
  cabal-install/src/Distribution/Client/CmdFreeze.hs
  cabal-install/src/Distribution/Client/CmdHaddock.hs
  cabal-install/src/Distribution/Client/CmdHaddockProject.hs
  cabal-install/src/Distribution/Client/CmdInstall.hs
  cabal-install/src/Distribution/Client/CmdSdist.hs
  cabal-install/src/Distribution/Client/Configure.hs
  cabal-install/src/Distribution/Client/Errors.hs
  cabal-install/src/Distribution/Client/Freeze.hs
  cabal-install/src/Distribution/Client/Get.hs
  cabal-install/src/Distribution/Client/HttpUtils.hs
  cabal-install/src/Distribution/Client/IndexUtils.hs
  cabal-install/src/Distribution/Client/Install.hs
  cabal-install/src/Distribution/Client/ProjectOrchestration.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/ScriptUtils.hs
  cabal-install/src/Distribution/Client/TargetSelector.hs
  cabal-install/src/Distribution/Client/Utils.hs
  cabal-install/src/Distribution/Client/Win32SelfUpgrade.hs
  cabal-testsuite/PackageTests/BuildTargets/UseLocalPackage/use-local-version-of-package.out
  cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/use-local-package-as-setup-dep.out
  cabal-testsuite/PackageTests/CustomSegfault/cabal.out
  cabal-testsuite/PackageTests/CustomWithoutCabal/cabal.out
  cabal-testsuite/PackageTests/CustomWithoutCabalDefaultMain/cabal.out
  cabal-testsuite/PackageTests/ExtraProgPath/setup.out
  cabal-testsuite/PackageTests/MultiRepl/CabalTooOld/cabal.out
  cabal-testsuite/PackageTests/MultipleLibraries/Failing/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/MultiplePackages/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptBad/cabal.out
  cabal-testsuite/PackageTests/NewBuild/MonitorCabalFiles/cabal.out
  cabal-testsuite/PackageTests/NewBuild/T3978/cabal.out
  cabal-testsuite/PackageTests/NewHaddock/Fails/cabal.out
  cabal-testsuite/PackageTests/NewSdist/MultiTarget/all-test-sute.out
  cabal-testsuite/PackageTests/NewSdist/MultiTarget/multi-archive-to-stdout.out
  cabal-testsuite/PackageTests/NewSdist/MultiTarget/target-remote-package.out
  cabal-testsuite/PackageTests/NewSdist/MultiTarget/valid-and-test-suite.out
  cabal-testsuite/PackageTests/OfflineFlag/offlineFlag.out
  cabal-testsuite/PackageTests/PackageDB/cabal-fail-no-base.out
  cabal-testsuite/PackageTests/PackageDB/cabal-fail-no-p.out
  cabal-testsuite/PackageTests/Regression/T6961/DepInternal/cabal.out
  cabal-testsuite/PackageTests/Regression/T7234/Fail/cabal.out
  cabal-testsuite/PackageTests/ReplOptions/cabal.single-repl-options-multiple-flags-negative.out
  cabal-testsuite/PackageTests/ShowBuildInfo/CompileFail/compile-fail.out
Labels: type: enhancement, attention: needs-review, merge me, re: error-message, merge delay passed

#9264 Add back reference from constraints to flags
  doc/cabal-project.rst
Labels: merge delay passed, merge+no rebase

#9358 Add 9 and revise 6 comments.
  Cabal/src/Distribution/Lex.hs
  Cabal/src/Distribution/Simple.hs
  Cabal/src/Distribution/Simple/Flag.hs
  Cabal/src/Distribution/Utils/IOData.hs
  cabal-install/src/Distribution/Client/Main.hs
Labels: merge me, merge delay passed

#9212 Restructure Getting Started documentation to be more compact and beginner friendly
  doc/getting-started.rst
Labels: documentation, squash+merge me, merge delay passed

#9356 Use ProjectFlags to define CleanCmd
  cabal-install/src/Distribution/Client/CmdClean.hs
Labels: squash+merge me, merge delay passed

#9371 Make “sublibrary” standard terminology in docs
  doc/cabal-package.rst
  doc/file-format-changelog.rst
  doc/setup-commands.rst
Labels: attention: needs-help

#9315 Simplify to avoid a typo
  cabal-testsuite/README.md
Labels: merge delay passed, merge+no rebase

#9369 Update format.yml
  .github/workflows/format.yml
Labels: merge me, merge delay passed

#9382 Create Cabal-3.10.2.1 release notes
  release-notes/Cabal-3.10.2.1.md
Labels: merge me, merge delay passed

#9383 Fix markdown syntax in changelog
  Cabal/ChangeLog.md
Labels: merge me, merge delay passed
