Repository haskell/cabal, pull requests merged in 2024-12, with the labels that each got.

#10610 Fix typo in constraint example
  doc/cabal-package-description-file.rst
Labels: merge me, merge delay passed, ready and waiting

#10603 Add typo checking for *.rst and *.md files
  .github/workflows/typos.yml
  .typos.toml
  Cabal/ChangeLog.md
  Makefile
  README.md
  doc/README.md
  doc/cabal-commands.rst
  doc/cabal-package-description-file.rst
  doc/file-format-changelog.rst
  doc/getting-started.rst
  doc/how-to-use-backpack.rst
  release-notes/Cabal-3.10.1.0.md
  release-notes/Cabal-3.12.0.0.md
  release-notes/cabal-install-3.10.3.0.md
  release-notes/cabal-install-3.12.1.0.md
Labels: merge delay passed, merge+no rebase, ready and waiting

#9890 Explicit export lists for Main
  cabal-install/src/Distribution/Client/Init/Defaults.hs
  changelog.d/pr-9890
Labels: squash+merge me, merge delay passed, ready and waiting

#10587 VCS tests: Quieter output
  cabal-install/src/Distribution/Client/VCS.hs
  cabal-install/tests/UnitTests/Distribution/Client/VCS.hs
  changelog.d/pr-10587
Labels: merge me, merge delay passed, ready and waiting

#10608 Add help target to the makefile
  Makefile
Labels: merge delay passed, merge+no rebase, ready and waiting

#10613 Fix typos in `*.hs` files
  Cabal-syntax/src/Distribution/Backpack.hs
  Cabal-syntax/src/Distribution/Fields/Field.hs
  Cabal-syntax/src/Distribution/Fields/LexerMonad.hs
  Cabal-syntax/src/Distribution/PackageDescription/Parsec.hs
  Cabal-syntax/src/Distribution/SPDX/LicenseId.hs
  Cabal-syntax/src/Distribution/Types/VersionInterval.hs
  Cabal-tests/tests/ParserTests.hs
  Cabal-tests/tests/UnitTests/Distribution/SPDX.hs
  Cabal/src/Distribution/GetOpt.hs
  Cabal/src/Distribution/PackageDescription/Check/Common.hs
  Cabal/src/Distribution/PackageDescription/Check/Monad.hs
  Cabal/src/Distribution/PackageDescription/Check/Warning.hs
  Cabal/src/Distribution/Simple/Build/PackageInfoModule.hs
  Cabal/src/Distribution/Simple/BuildToolDepends.hs
  Cabal/src/Distribution/Simple/Command.hs
  Cabal/src/Distribution/Simple/Compiler.hs
  Cabal/src/Distribution/Simple/Program/Types.hs
  Cabal/src/Distribution/Simple/Setup/Config.hs
  Cabal/src/Distribution/Simple/SetupHooks/Rule.hs
  Cabal/src/Distribution/Simple/Utils.hs
  Cabal/src/Distribution/Types/LocalBuildInfo.hs
  Cabal/src/Distribution/Utils/IOData.hs
  cabal-install-solver/tests/UnitTests/Distribution/Solver/Modular/MessageUtils.hs
  cabal-install/src/Distribution/Client/Check.hs
  cabal-install/src/Distribution/Client/CmdInstall.hs
  cabal-install/src/Distribution/Client/CmdRepl.hs
  cabal-install/src/Distribution/Client/IndexUtils/ActiveRepos.hs
  cabal-install/src/Distribution/Client/JobControl.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/ScriptUtils.hs
  cabal-install/tests/UnitTests/Distribution/Client/InstallPlan.hs
  templates/SPDX.LicenseId.template.hs
Labels: merge delay passed, merge+no rebase, ready and waiting

#10586 VCS: Fix weird tag creation
  cabal-install/src/Distribution/Client/VCS.hs
  cabal-testsuite/PackageTests/postCheckoutCommand/cabal.out
  cabal-testsuite/PackageTests/postCheckoutCommand/cabal.test.hs
Labels: merge me, merge delay passed, attention: needs-manual-qa, ready and waiting

#10579 3.14: make Cabal-hooks version track Cabal version
  Cabal-hooks/Cabal-hooks.cabal
  Cabal-hooks/changelog.md
  Cabal-hooks/src/Distribution/Simple/SetupHooks.hs
  bootstrap/linux-9.0.2.json
  bootstrap/linux-9.2.8.json
  bootstrap/linux-9.4.8.json
  bootstrap/linux-9.6.4.json
  bootstrap/linux-9.8.2.json
  cabal-testsuite/main/cabal-tests.hs
Labels: squash+merge me

#10590 VCS: Don't run submodule commands unless necessary
  Cabal/src/Distribution/Simple/Program/Run.hs
  cabal-install/src/Distribution/Client/VCS.hs
  cabal-install/tests/UnitTests/Distribution/Client/VCS.hs
  changelog.d/pr-10590
Labels: merge me, merge delay passed, ready and waiting

#10616 OpenBSD `--strip-unneeded` strips too much
  Cabal/src/Distribution/Simple/Program/Strip.hs
  changelog.d/pr-10616
Labels: merge me, merge delay passed, ready and waiting, attention: needs-backport 3.14

#10621 Have hlint ignore dist-*
  .hlint.yaml
Labels: merge delay passed, merge+no rebase, ready and waiting

#10625 `ProjectConfigPath` use haddock literal text for layout
  cabal-install-solver/src/Distribution/Solver/Types/ProjectConfigPath.hs
Labels: cabal-install: solver, merge delay passed, merge+no rebase, ready and waiting

#10518 Don't Glob if Glob Ain't Glob 2: The Globbening
  Cabal-tests/tests/UnitTests/Distribution/Simple/Glob.hs
  Cabal/src/Distribution/Simple/Glob.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Paths/AbsolutePath/cabal.out
Labels: squash+merge me, merge delay passed, ready and waiting

#10573 `cabal-validate`: Better output verbosity defaults
  .github/workflows/validate.yml
  cabal-validate/src/Cli.hs
  cabal-validate/src/Main.hs
  cabal-validate/src/ProcessUtil.hs
  cabal-validate/src/Step.hs
Labels: merge me, merge delay passed, attention: needs-manual-qa, ready and waiting, cabal-validate

#10546 Deduplicate "using config from" message
  cabal-install-solver/src/Distribution/Solver/Types/ProjectConfigPath.hs
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-testsuite/PackageTests/ConditionalAndImport/cabal.out
  cabal-testsuite/PackageTests/ConditionalAndImport/with-ghc.config
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/0.config
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/2.config
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/4.config
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/6.config
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/8.config
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/cabal.out
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/cabal.test.hs
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/cfg/1.config
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/cfg/3.config
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/cfg/5.config
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/cfg/7.config
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/cfg/9.config
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/no-pkg-1/README.md
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/no-pkg-3/README.md
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/no-pkgs.project
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/with-ghc.config
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromSimple/a-very-extra.config
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromSimple/an-extra.config
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromSimple/cabal.out
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromSimple/cabal.project
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromSimple/cabal.test.hs
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromSimple/with-ghc.config
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromSimple/z-empty.config
  changelog.d/pr-10546
Labels: merge delay passed, attention: needs-manual-qa, merge+no rebase, ready and waiting

#10637 Fix multi-package Haddock CSS handling
  Cabal/src/Distribution/Simple/Haddock.hs
  cabal-install/src/Distribution/Client/CmdHaddock.hs
  changelog.d/pr-10637
Labels: merge me, merge delay passed, ready and waiting

#10640 Include changelog.d/* files in fix-whitespace
  changelog.d/pr-10493
  changelog.d/pr-9367
  fix-whitespace.yaml
Labels: merge delay passed, merge+no rebase, ready and waiting

#10642 Fix whitespace issue in changelog
  changelog.d/pr-10546
Labels: priority: high :fire:, merge me, merge delay passed, ready and waiting

#10641 try to alert (via webhook) when Mergify is stuck
  .github/mergify.yml
Labels: continuous-integration, merge me, merge delay passed, ready and waiting

#10580 Master: make Cabal-hooks version track Cabal version
  Cabal-hooks/Cabal-hooks.cabal
  Cabal-hooks/changelog.md
  Cabal-hooks/readme.md
  Cabal-hooks/src/Distribution/Simple/SetupHooks.hs
  bootstrap/linux-9.0.2.json
  bootstrap/linux-9.2.8.json
  bootstrap/linux-9.4.8.json
  bootstrap/linux-9.6.4.json
  bootstrap/linux-9.8.2.json
  cabal-testsuite/main/cabal-tests.hs
Labels: squash+merge me, merge delay passed, ready and waiting

#10526 Convert display functions into `Pretty` instances
  cabal-install-solver/src/Distribution/Solver/Types/ConstraintSource.hs
  cabal-install-solver/src/Distribution/Solver/Types/PackageConstraint.hs
  cabal-install/src/Distribution/Client/Targets.hs
Labels: cabal-install: solver, merge me, merge delay passed, merge+no rebase, ready and waiting

#10459 sync `validate.yml` with `master`
  .github/workflows/validate.yml
Labels: squash+merge me, merge delay passed

#10654 CI: remove cabal-head before updating it (fix #10537)
  .github/workflows/validate.yml
Labels: priority: high :fire:, merge me, merge delay passed, ready and waiting

#10655 The release cleanup action requires a token
  .github/workflows/validate.yml
Labels: priority: high :fire:, continuous-integration, merge me, merge delay passed, ready and waiting

#10650 add ghc 9.12.1 to sdist check list
  .github/workflows/check-sdist.yml
Labels: continuous-integration, merge me, merge delay passed, ready and waiting, attention: needs-backport 3.14

#10656 Support `ghc-9.12.*`
  Cabal/src/Distribution/Simple/GHC.hs
Labels: merge delay passed, merge+no rebase, ready and waiting, attention: needs-backport 3.14

#10541 record Git revision in devel builds
  Cabal/Cabal.cabal
  Cabal/src/Distribution/Simple/Utils.hs
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/Main.hs
  cabal-install/src/Distribution/Client/Version.hs
  cabal.project
  cabal.release.project
  cabal.validate.project
Labels: merge me, merge delay passed, attention: needs-backport 3.12, ready and waiting, attention: needs-backport 3.14

#10606 Docs: guide on profiling: fix the title
  doc/how-to-enable-profiling.rst
  doc/index.rst
Labels: documentation, priority: high :fire:, squash+merge me, merge delay passed, ready and waiting

#10664 cabal.release.project: pick newer `unix` that fixes important bugs on i386 and arm
  cabal.release.project
Labels: priority: high :fire:, merge me, merge delay passed, ready and waiting, attention: needs-backport 3.14

#10662 CI: prerelease: fixup cleanup (again)
  .github/workflows/validate.yml
Labels: priority: high :fire:, continuous-integration, merge me, merge delay passed, ready and waiting

#10663 Minor refactor: spell out max supported GHC once
  Cabal/src/Distribution/Simple/GHC.hs
Labels: squash+merge me, merge delay passed, ready and waiting

#10629 Have projects import trimmed URIs
  Cabal/src/Distribution/Simple/Configure.hs
  cabal-install-solver/src/Distribution/Solver/Types/ProjectConfigPath.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
  cabal-testsuite/PackageTests/ProjectImport/UntrimmedImport/cabal.out
  cabal-testsuite/PackageTests/ProjectImport/UntrimmedImport/cabal.test.hs
  cabal-testsuite/PackageTests/ProjectImport/UntrimmedImport/my.cabal
  cabal-testsuite/PackageTests/ProjectImport/UntrimmedImport/tabs-and-spaces.project
  cabal-testsuite/PackageTests/ProjectImport/UntrimmedImport/trailing-space.project
  cabal-testsuite/PackageTests/ProjectImport/UntrimmedImport/with-ghc.config
  changelog.d/pr-10629
  fix-whitespace.yaml
Labels: type: bug, merge delay passed, merge+no rebase, ready and waiting

#10677 fix unix dependency correctly
  Cabal/Cabal.cabal
  bootstrap/linux-9.0.2.json
  bootstrap/linux-9.2.8.json
  bootstrap/linux-9.4.8.json
  bootstrap/linux-9.6.6.json
  bootstrap/linux-9.8.2.json
  cabal-install/cabal-install.cabal
  cabal.bootstrap.project
  cabal.release.project
Labels: priority: high :fire:, merge me, merge delay passed, ready and waiting

#10681 bump version numbers for 3.14.1.1
  Cabal-syntax/Cabal-syntax.cabal
  Cabal/Cabal.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
Labels: merge me

#10643 Comment optional post-install field in the ghcup metadata script and fix typos
  scripts/release/create-release-metadata-for-ghcup.sh
Labels: merge me, merge delay passed, ready and waiting
