Repository haskell/cabal, pull requests merged in 2024-05, with the labels that each got.

#9944 Update PR template
  .github/pull_request_template.md
Labels: merge me, re: devx, merge delay passed

#9946 Define a user-visible change
  CONTRIBUTING.md
Labels: documentation, merge delay passed, merge+no rebase

#9912 Correctly provision build tools in all situations
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  Cabal/src/Distribution/Simple/Bench.hs
  Cabal/src/Distribution/Simple/Build.hs
  Cabal/src/Distribution/Simple/Configure.hs
  Cabal/src/Distribution/Simple/ConfigureScript.hs
  Cabal/src/Distribution/Simple/Haddock.hs
  Cabal/src/Distribution/Simple/Program/Db.hs
  Cabal/src/Distribution/Simple/Program/Find.hs
  Cabal/src/Distribution/Simple/Program/Types.hs
  Cabal/src/Distribution/Simple/Test.hs
  Cabal/src/Distribution/Simple/Test/ExeV10.hs
  Cabal/src/Distribution/Simple/Test/LibV09.hs
  Cabal/src/Distribution/Simple/Utils.hs
  cabal-install/src/Distribution/Client/CmdExec.hs
  cabal-install/src/Distribution/Client/CmdInstall.hs
  cabal-install/src/Distribution/Client/CmdRun.hs
  cabal-install/src/Distribution/Client/HttpUtils.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/Run.hs
  cabal-install/src/Distribution/Client/SetupWrapper.hs
  cabal-install/src/Distribution/Client/VCS.hs
  cabal-testsuite/PackageTests/BuildToolPaths/bt/bt-data/PP1.txt
  cabal-testsuite/PackageTests/BuildToolPaths/bt/bt.cabal
  cabal-testsuite/PackageTests/BuildToolPaths/bt/exe/Main.hs
  cabal-testsuite/PackageTests/BuildToolPaths/bt/src/Tool.hs
  cabal-testsuite/PackageTests/BuildToolPaths/cabal.project
  cabal-testsuite/PackageTests/BuildToolPaths/cabal.test.hs
  cabal-testsuite/PackageTests/BuildToolPaths/pbts/SetupHooks.hs
  cabal-testsuite/PackageTests/BuildToolPaths/pbts/bench/Main.hs
  cabal-testsuite/PackageTests/BuildToolPaths/pbts/data/PP2.txt
  cabal-testsuite/PackageTests/BuildToolPaths/pbts/exe/Main.hs
  cabal-testsuite/PackageTests/BuildToolPaths/pbts/pbts.cabal
  cabal-testsuite/PackageTests/BuildToolPaths/pbts/src/Call.hs
  cabal-testsuite/PackageTests/BuildToolPaths/pbts/src/MyLib1.hs-pp1
  cabal-testsuite/PackageTests/BuildToolPaths/pbts/src/MyLib2.hs-pp2
  cabal-testsuite/PackageTests/BuildToolPaths/pbts/test/Main.hs
  cabal-testsuite/PackageTests/BuildToolPaths/pbts/tool/Main.hs
  cabal-testsuite/main/cabal-tests.hs
  doc/cabal-package-description-file.rst
Labels: merge me, re: build-tool, merge delay passed

#9958 Rename projects to have `.project` extension
  .github/workflows/quick-jobs.yml
  .github/workflows/validate.yml
  .gitlab/ci.sh
  CONTRIBUTING.md
  Makefile
  README.md
  bootstrap/generate_bootstrap_plans
  cabal-testsuite/README.md
  cabal.bootstrap.project
  cabal.meta.project
  cabal.release.project
  cabal.validate-libonly.project
  cabal.validate.project
  project-cabal/README.md
  project-cabal/ghc-latest.config
  validate.sh
Labels: merge delay passed, merge+no rebase

#9959 Bump to hlint-3.8
  .github/workflows/lint.yml
  .hlint.yaml
Labels: merge delay passed, merge+no rebase

#9951 Filter Setup flags: filter working dir on < 3.13
  cabal-install/src/Distribution/Client/Setup.hs
  cabal-testsuite/PackageTests/WorkingDir/Main.hs
  cabal-testsuite/PackageTests/WorkingDir/Setup.hs
  cabal-testsuite/PackageTests/WorkingDir/cabal.project
  cabal-testsuite/PackageTests/WorkingDir/dep/Dep.hs
  cabal-testsuite/PackageTests/WorkingDir/dep/Setup.hs
  cabal-testsuite/PackageTests/WorkingDir/dep/dep.cabal
  cabal-testsuite/PackageTests/WorkingDir/setup.test.hs
  cabal-testsuite/PackageTests/WorkingDir/working-dir-test.cabal
Labels: merge me, regression on master, merge delay passed

#9954 More consistently pass --package-db flag to tests
  cabal-testsuite/PackageTests/CustomTestCoverage/cabal.out
  cabal-testsuite/PackageTests/Regression/T9640/cabal.out
  cabal-testsuite/src/Test/Cabal/DecodeShowBuildInfo.hs
  cabal-testsuite/src/Test/Cabal/Prelude.hs
Labels: merge me, merge delay passed

#9964 update `base` bounds for desupported ghc 8.2
  Cabal-hooks/Cabal-hooks.cabal
  Cabal-syntax/Cabal-syntax.cabal
  Cabal-tests/Cabal-tests.cabal
  Cabal/Cabal.cabal
  cabal-dev-scripts/cabal-dev-scripts.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
  cabal-testsuite/cabal-testsuite.cabal
Labels: merge me, merge delay passed

#9970 Hackage as a proper noun, capitalized in docs
  doc/cabal-commands.rst
  doc/cabal-package-description-file.rst
Labels: documentation, merge delay passed, merge+no rebase

#9723 How to use Cabal in Windows
  doc/how-to-run-in-windows.rst
  doc/index.rst
Labels: platform: windows, documentation, merge me, merge delay passed

#9963 Touch up release notes for cabal-install 3.12.0.0 pre-release
  release-notes/WIP-cabal-install-3.12.x.0.md
Labels: documentation, release, attention: needs-review, merge me, re: changelog, merge delay passed, attention: needs-backport 3.12

#9926 Downgrade NoLibraryFound from an error to a warning
  Cabal/src/Distribution/Simple/Errors.hs
  Cabal/src/Distribution/Simple/Install.hs
  cabal-testsuite/PackageTests/OnlyTestSuite/OnlyTestSuite.cabal
  cabal-testsuite/PackageTests/OnlyTestSuite/cabal.cabal.out
  cabal-testsuite/PackageTests/OnlyTestSuite/cabal.out
  cabal-testsuite/PackageTests/OnlyTestSuite/cabal.test.hs
  cabal-testsuite/PackageTests/OnlyTestSuite/test/Main.hs
  changelog.d/issue-6750
Labels: merge me, re: error-message, re: warnings, merge delay passed

#9966 Haddock: use buildSettingKeepTempFiles
  cabal-install/src/Distribution/Client/ProjectBuilding/UnpackedPackage.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-testsuite/PackageTests/HaddockKeepsTmps/Simple.hs
  cabal-testsuite/PackageTests/HaddockKeepsTmps/cabal.project
  cabal-testsuite/PackageTests/HaddockKeepsTmps/cabal.test.hs
  cabal-testsuite/PackageTests/HaddockKeepsTmps/my.cabal
Labels: Cabal: cmd/haddock, merge me, merge delay passed

#9701 source-repository versus source-repository-package
  doc/cabal-commands.rst
  doc/cabal-package-description-file.rst
  doc/cabal-project-description-file.rst
  doc/how-to-source-packages.rst
  doc/index.rst
  doc/version-control-fields.rst
Labels: merge delay passed, merge+no rebase

#9989 Docs: update link to SetupHooks RFC
  doc/cabal-package-description-file.rst
Labels: merge me, merge delay passed

#9988 Add NoImplicitPrelude to buildTypeScript
  cabal-install/src/Distribution/Client/ProjectPlanning/SetupPolicy.hs
  cabal-install/src/Distribution/Client/SetupWrapper.hs
  cabal-testsuite/PackageTests/SetupHooks/SetupHooksNoBase/A.hs
  cabal-testsuite/PackageTests/SetupHooks/SetupHooksNoBase/SetupHooks.hs
  cabal-testsuite/PackageTests/SetupHooks/SetupHooksNoBase/cabal.project
  cabal-testsuite/PackageTests/SetupHooks/SetupHooksNoBase/cabal.test.hs
  cabal-testsuite/PackageTests/SetupHooks/SetupHooksNoBase/setup-hooks-no-base-test.cabal
Labels: merge me, merge delay passed

#10011 Bump index-state in the release project file
  cabal.project.release
Labels: merge me, backport

#10026 ci: Fix quick-jobs GHC version to 9.6
  .github/workflows/quick-jobs.yml
Labels: squash+merge me, merge delay passed

#10013 Recommend using latest cabal-install
  CONTRIBUTING.md
Labels: merge delay passed, attention: needs-backport 3.12, merge+no rebase

#9990 Use bootstrap project in bootstrapping
  bootstrap/generate_bootstrap_plans
Labels: merge me, merge delay passed

#9975 Add "no command line variant" for `source-repository-package`.
  doc/cabal-project-description-file.rst
Labels: documentation, merge delay passed, merge+no rebase

#10030 update jinja2 per CVE-2024-34064
  doc/requirements.in
  doc/requirements.txt
Labels: merge me, merge delay passed, attention: needs-backport 3.12

#10031 generate doc/requirements.txt
  .github/workflows/users-guide.yml
  .gitignore
  .readthedocs.yml
  doc/README.md
  doc/requirements.txt
Labels: squash+merge me, merge delay passed, attention: needs-backport 3.12

#10034 Add docs for list-bin support of scripts
  doc/cabal-commands.rst
Labels: merge me, merge delay passed

#10043 ci: Fix quick-jobs GHC version to 9.6
  .github/workflows/quick-jobs.yml
Labels: attention: needs-review, backport

#10035 PackageTests/NewUpdate: fix skipping flaky tests
  cabal-testsuite/PackageTests/NewUpdate/RejectFutureIndexStates/cabal.test.hs
  cabal-testsuite/PackageTests/NewUpdate/UpdateIndexState/update-index-state.test.hs
Labels: merge me, merge delay passed, attention: needs-backport 3.12

#10045 [3.12] PackageTests/NewUpdate: fix skipping flaky tests
  cabal-testsuite/PackageTests/NewUpdate/RejectFutureIndexStates/cabal.test.hs
  cabal-testsuite/PackageTests/NewUpdate/UpdateIndexState/update-index-state.test.hs
Labels: merge me, backport

#10048 CI: install changelog-d from bindist
  .github/workflows/changelogs.yml
Labels: continuous-integration, attention: needs-review, squash+merge me, merge delay passed, attention: needs-backport 3.12

#10033 Add comment clarifying disabling check for scripts
  Cabal/src/Distribution/PackageDescription/Check/Target.hs
Labels: merge me, merge delay passed

#10032 Allow whitespace in target selectors
  cabal-install/src/Distribution/Client/ScriptUtils.hs
  cabal-install/src/Distribution/Client/TargetSelector.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/IntegrationTests2/targets/simple/a p p/Main.hs
  cabal-install/tests/IntegrationTests2/targets/simple/p.cabal
  cabal-testsuite/PackageTests/NewBuild/T8875/T8875.cabal
  cabal-testsuite/PackageTests/NewBuild/T8875/a app/Main.hs
  cabal-testsuite/PackageTests/NewBuild/T8875/cabal.out
  cabal-testsuite/PackageTests/NewBuild/T8875/cabal.project
  cabal-testsuite/PackageTests/NewBuild/T8875/cabal.test.hs
  changelog.d/issue-8875
Labels: merge me, merge delay passed

#10044 Fix #10042 Don't recommend deprecated/removed 'extensions:' field
  Cabal/src/Distribution/PackageDescription/Check/Target.hs
  changelog.d/issue-10042
Labels: merge me, merge delay passed

#9914 CI: add GHC 9.10
  .github/workflows/validate.yml
  cabal-install/src/Distribution/Client/TargetSelector.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/NonInteractive.hs
  cabal-testsuite/PackageTests/CCompilerOverride/foo.c
  cabal-testsuite/PackageTests/CCompilerOverride/my.cabal
  cabal-testsuite/PackageTests/CCompilerOverride/setup.cabal.out
  cabal-testsuite/PackageTests/CCompilerOverride/setup.out
  cabal-testsuite/PackageTests/CCompilerOverride/setup.test.hs
  project-cabal/ghc-latest.config
Labels: squash+merge me, merge delay passed

#10055 fix: Make newSemaphoreJobControl respect verbosity
  cabal-install/src/Distribution/Client/JobControl.hs
  cabal-install/src/Distribution/Client/ProjectBuilding.hs
Labels: cabal-install: other, merge me, merge delay passed, attention: needs-backport 3.12

#9177 Haddock recompilation avoidance
  .gitignore
  Cabal/src/Distribution/Simple/Haddock.hs
  Cabal/src/Distribution/Simple/Setup/Haddock.hs
  Cabal/src/Distribution/Types/LocalBuildInfo.hs
  cabal-install/src/Distribution/Client/CmdHaddockProject.hs
  cabal-install/src/Distribution/Client/Config.hs
  cabal-install/src/Distribution/Client/PackageHash.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Types.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/ProjectPlanning/Types.hs
  cabal-install/src/Distribution/Client/Setup.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
  cabal-testsuite/PackageTests/NewHaddock/Fails/cabal.out
  changelog.d/pr-9177
  doc/cabal-project-description-file.rst
  release-notes/WIP-Cabal-3.12.x.0.md
  test/IntegrationTests2/config/default-config
  test/IntegrationTests2/nix-config/default-config
  tests/IntegrationTests2/config/default-config
  tests/IntegrationTests2/nix-config/default-config
Labels: Cabal: cmd/haddock, attention: needs-review, cabal-install: cmd/haddock, merge me, merge delay passed, attention: needs-manual-qa
