Repository haskell/cabal, pull requests merged in 2024-08, with the labels that each got.

#9476 clarify "configure" messages from Cabal
  Cabal/src/Distribution/Simple/Configure.hs
  Cabal/src/Distribution/Simple/Errors.hs
  changelog.d/configure-messages
Labels: squash+merge me, merge delay passed

#10226 reorder Haddock markup for dynprof constructor
  cabal-install-solver/src/Distribution/Solver/Types/ConstraintSource.hs
Labels: merge me, merge delay passed

#10192 Update cabal-install-solver synopsis (fix #10183)
  cabal-install-solver/cabal-install-solver.cabal
Labels: squash+merge me, merge delay passed

#10234 Add simple QuickCheck test for solver exceptions
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck.hs
Labels: cabal-install: solver, merge me, merge delay passed, attention: needs-backport 3.12

#10244 3.14 pre-flight checks: bump dependencies
  Cabal-described/Cabal-described.cabal
  Cabal-tests/Cabal-tests.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck/Utils.hs
Labels: squash+merge me, merge delay passed

#10251 use fixed cabal version per #10175
  .github/workflows/validate.yml
  cabal-testsuite/cabal-testsuite.cabal
Labels: merge me, merge delay passed, attention: needs-backport 3.12

#10257 CI: skip cli-suite on Windows due to #9571
  .github/workflows/validate.yml
Labels: priority: high :fire:, attention: needs-review, squash+merge me, merge delay passed

#10240 Filter out -dinitial-unique and -dunique-increment from hash flags
  Cabal/src/Distribution/Simple/Program/GHC.hs
  changelog.d/pr-10240
Labels: merge me, merge delay passed, attention: needs-backport 3.12

#10250 hpc: Don't cover non-dependency libraries
  Cabal/src/Distribution/Simple/Configure.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-testsuite/PackageTests/Regression/T10046/aa.cabal
  cabal-testsuite/PackageTests/Regression/T10046/app/Main.hs
  cabal-testsuite/PackageTests/Regression/T10046/cabal.project
  cabal-testsuite/PackageTests/Regression/T10046/cabal.test.hs
  cabal-testsuite/PackageTests/Regression/T10046/src/MyLib.hs
  cabal-testsuite/PackageTests/Regression/T10046/test/Main.hs
  cabal-testsuite/PackageTests/Regression/T10046/testbb/Main.hs
  changelog.d/issue-10046
Labels: merge me, merge delay passed, attention: needs-backport 3.12

#8717 Always pass `ghc-options`
  Cabal/src/Distribution/Simple/GHC.hs
  Cabal/src/Distribution/Simple/GHCJS.hs
  changelog.d/pr-8717
  doc/cabal-package-description-file.rst
Labels: squash+merge me, merge delay passed, attention: needs-backport 3.12

#10260 Mergify and actions upgrades
  .github/mergify.yml
  .github/workflows/bootstrap.yml
  .github/workflows/users-guide.yml
  .github/workflows/validate.yml
Labels: squash+merge me, merge delay passed, attention: needs-backport 3.12

#10261 Add git:// protocol check
  Cabal/src/Distribution/PackageDescription/Check.hs
  Cabal/src/Distribution/PackageDescription/Check/Warning.hs
  cabal-testsuite/PackageTests/Check/GitProtocol/cabal.out
  cabal-testsuite/PackageTests/Check/GitProtocol/cabal.test.hs
  cabal-testsuite/PackageTests/Check/GitProtocol/pkg.cabal
  changelog.d/pr-10261
  doc/cabal-commands.rst
Labels: merge me, merge delay passed, attention: needs-manual-qa

#10115 Let `cabal init` remember chosen language within current session
  cabal-install/src/Distribution/Client/Init.hs
  cabal-install/src/Distribution/Client/Init/Interactive/Command.hs
  cabal-install/src/Distribution/Client/Init/Types.hs
  cabal-install/src/Distribution/Client/InstallSymlink.hs
  cabal-install/src/Distribution/Client/ProjectBuilding/PackageFileMonitor.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/FileCreators.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/Golden.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/Interactive.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/NonInteractive.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/Simple.hs
  changelog.d/pr-10115
Labels: squash+merge me, merge delay passed, attention: needs-manual-qa

#10089 cabal-install: update curl transport to support Basic authentication
  cabal-install/src/Distribution/Client/HttpUtils.hs
  changelog.d/pr-10089
Labels: squash+merge me, merge delay passed

#10267 index Paths and Paths_ (resp. for PackageInfo)
  doc/cabal-package-description-file.rst
Labels: merge me, merge delay passed, attention: needs-backport 3.12

#10266 Update changelog-d to 1.0.1
  .github/workflows/changelogs.yml
  changelog.d/config
Labels: continuous-integration, squash+merge me, re: changelog, merge delay passed

#10268 Ignore VSCodium work directory
  .gitignore
Labels: merge me, merge delay passed, attention: needs-backport 3.12

#10135 implement mergify rules for release branches
  .github/mergify.yml
Labels: continuous-integration, squash+merge me, merge delay passed

#10271 validate dependabot configuration
  .github/dependabot.yml
  .github/workflows/dependabot.yml
Labels: merge me, merge delay passed

#10270 tests: Make structured hash tests invariant to GHC version
  Cabal-syntax/src/Distribution/Utils/Structured.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  cabal-install/tests/UnitTests/Distribution/Client/FileMonitor.hs
Labels: merge me, merge delay passed

#10103 Add check on project root file and fail if broken link
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
  cabal-install/tests/fixtures/project-root/cabal.project.dir.broken/.gitkeep
  cabal-install/tests/fixtures/project-root/cabal.project.symlink
  cabal-install/tests/fixtures/project-root/cabal.project.symlink.broken
  changelog.d/pr-10103
Labels: cabal-install: other, squash+merge me, re: project-file, merge delay passed, attention: needs-manual-qa, tested-on: windows

#10285 ci: Fix --index-state for hackage roundtrip tests
  Cabal-tests/Cabal-tests.cabal
  Cabal-tests/tests/HackageTests.hs
  validate.sh
Labels: merge me, merge delay passed

#10276 update the pinned index-state to get the new `rere`
  cabal.bootstrap.project
  cabal.release.project
Labels: merge me, merge delay passed, attention: needs-backport 3.12

#10223 add "ready and waiting" Mergify label
  .github/mergify.yml
Labels: merge me, merge delay passed

#10248 Include package version in --promised-dependency flag
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  Cabal/src/Distribution/Backpack/Configure.hs
  Cabal/src/Distribution/Backpack/PreExistingComponent.hs
  Cabal/src/Distribution/Simple/Configure.hs
  Cabal/src/Distribution/Simple/GHC/Internal.hs
  Cabal/src/Distribution/Simple/Setup/Config.hs
  Cabal/src/Distribution/Types/GivenComponent.hs
  Cabal/src/Distribution/Types/LocalBuildConfig.hs
  Cabal/src/Distribution/Types/LocalBuildInfo.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/Setup.hs
  cabal-testsuite/PackageTests/MultiRepl/CabalMacros/cabal.out
  cabal-testsuite/PackageTests/MultiRepl/CabalMacros/cabal.project
  cabal-testsuite/PackageTests/MultiRepl/CabalMacros/cabal.test.hs
  cabal-testsuite/PackageTests/MultiRepl/CabalMacros/pkg-a/Foo.hs
  cabal-testsuite/PackageTests/MultiRepl/CabalMacros/pkg-a/pkg-a.cabal
  cabal-testsuite/PackageTests/MultiRepl/CabalMacros/pkg-b/Bar.hs
  cabal-testsuite/PackageTests/MultiRepl/CabalMacros/pkg-b/pkg-b.cabal
  changelog.d/issue-10166
Labels: merge me, merge delay passed, ready and waiting
