Repository haskell/cabal, pull requests merged in 2024-03, with the labels that each got.

#9671 Use in-tree Cabal library for `cabal-install` tests with custom setup.
  cabal-testsuite/PackageTests/CustomDep/cabal.test.hs
  cabal-testsuite/PackageTests/CustomPlain/setup.test.hs
  cabal-testsuite/PackageTests/CustomPreProcess/cabal.test.hs
  cabal-testsuite/PackageTests/CustomPreProcess/setup.test.hs
  cabal-testsuite/PackageTests/CustomTestCoverage/setup.test.hs
  cabal-testsuite/PackageTests/DuplicateModuleName/setup.test.hs
  cabal-testsuite/PackageTests/MultiRepl/CabalTooOld/cabal.out
  cabal-testsuite/PackageTests/MultiRepl/CabalTooOld/cabal.test.hs
  cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/cabal.out
  cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/cabal.test.hs
  cabal-testsuite/PackageTests/PackageDB/cabal-fail-no-packagedbs.test.hs
  cabal-testsuite/PackageTests/Regression/T4270/setup.test.hs
  cabal-testsuite/PackageTests/TestNameCollision/setup.test.hs
  cabal-testsuite/PackageTests/TestSuiteTests/LibV09/setup-deadlock.test.hs
  cabal-testsuite/PackageTests/TestSuiteTests/LibV09/setup.test.hs
  cabal-testsuite/README.md
  cabal-testsuite/cabal-testsuite.cabal
  cabal-testsuite/main/cabal-tests.hs
  cabal-testsuite/src/Test/Cabal/Monad.hs
  cabal-testsuite/src/Test/Cabal/Prelude.hs
  validate.sh
Labels: merge me, merge delay passed

#9759 Add Issue/PR contributing guidelines
  CONTRIBUTING.md
Labels: merge me, merge delay passed

#9765 Fix `<more complex packages>` link lost in doc/cabal-package-description-file.rs
  doc/cabal-package-description-file.rst
Labels: merge me, merge delay passed

#9754 Improve bad cabal-version error message
  Cabal-syntax/src/Distribution/PackageDescription/Parsec.hs
  Cabal-tests/tests/ParserTests/errors/forward-compat.errors
  Cabal-tests/tests/ParserTests/errors/forward-compat2.errors
  Cabal-tests/tests/ParserTests/errors/forward-compat3.errors
Labels: squash+merge me, merge delay passed, attention: needs-backport 3.10

#9762 Find build-tool installed programs before programs in path
  Cabal/src/Distribution/Simple/Configure.hs
  Cabal/src/Distribution/Simple/ConfigureScript.hs
  Cabal/src/Distribution/Simple/Program/Db.hs
  Cabal/src/Distribution/Simple/Program/Types.hs
  cabal-install/src/Distribution/Client/CmdExec.hs
  cabal-install/src/Distribution/Client/CmdInstall.hs
  cabal-install/src/Distribution/Client/HttpUtils.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/SetupWrapper.hs
  cabal-install/src/Distribution/Client/VCS.hs
  cabal-testsuite/PackageTests/Regression/T9756/OK.hs
  cabal-testsuite/PackageTests/Regression/T9756/cabal-bug-build-tool.cabal
  cabal-testsuite/PackageTests/Regression/T9756/cabal.out
  cabal-testsuite/PackageTests/Regression/T9756/cabal.project
  cabal-testsuite/PackageTests/Regression/T9756/cabal.test.hs
  cabal-testsuite/PackageTests/Regression/T9756/repo/mybuilder-0.1.0.0/CHANGELOG.md
  cabal-testsuite/PackageTests/Regression/T9756/repo/mybuilder-0.1.0.0/app/Main.hs
  cabal-testsuite/PackageTests/Regression/T9756/repo/mybuilder-0.1.0.0/mybuilder.cabal
  cabal-testsuite/PackageTests/Regression/T9756/repo/mybuilder-0.2.0.0/CHANGELOG.md
  cabal-testsuite/PackageTests/Regression/T9756/repo/mybuilder-0.2.0.0/app/Main.hs
  cabal-testsuite/PackageTests/Regression/T9756/repo/mybuilder-0.2.0.0/mybuilder.cabal
Labels: merge me, merge delay passed, attention: needs-backport 3.12, attention: needs-backport 3.10

#9719 Fix cabal install in the presence of extra-packages
  cabal-install/src/Distribution/Client/CmdInstall.hs
  cabal-testsuite/PackageTests/Install/T8848/Main.hs
  cabal-testsuite/PackageTests/Install/T8848/cabal.project
  cabal-testsuite/PackageTests/Install/T8848/cabal.test.hs
  cabal-testsuite/PackageTests/Install/T8848/t8848.cabal
Labels: merge me, merge delay passed

#9761 Update .cabal files
  Cabal-syntax/Cabal-syntax.cabal
  Cabal/Cabal.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
Labels: merge me, merge delay passed, attention: needs-backport 3.12, attention: needs-backport 3.10

#9750 Remove stale see 'withSourceCopyDir'
  cabal-testsuite/src/Test/Cabal/Monad.hs
Labels: merge delay passed, merge+no rebase

#9770 Fix typo
  cabal-install/src/Distribution/Client/Setup.hs
Labels: merge me, merge delay passed

#9781 Add GitLab CI badge
  README.md
Labels: squash+merge me, merge delay passed

#9775 Tell zlib not to use pkg-config
  .gitlab/ci.sh
Labels: continuous-integration, release, merge me, merge delay passed, re: pkg-config

#9749 Remove skipIfGhcVersion "== 9.6.3"
  cabal-testsuite/PackageTests/VersionPriority/1-web.test.hs
  cabal-testsuite/PackageTests/VersionPriority/2-web.test.hs
  cabal-testsuite/PackageTests/VersionPriority/3-web.test.hs
Labels: merge delay passed, merge+no rebase

#9771 offline flag disables `source-repository-package` sync
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  changelog.d/issue-9641
Labels: merge me, merge delay passed

#9518 Testsuite: pass -i argument to runghc invocations
  cabal-testsuite/PackageTests/SetupDep/Setup.hs
  cabal-testsuite/PackageTests/SetupDep/SetupDep.hs
  cabal-testsuite/PackageTests/SetupDep/cabal.project
  cabal-testsuite/PackageTests/SetupDep/setup-dep.cabal
  cabal-testsuite/PackageTests/SetupDep/setup.out
  cabal-testsuite/PackageTests/SetupDep/setup.test.hs
  cabal-testsuite/src/Test/Cabal/Script.hs
  cabal-testsuite/src/Test/Cabal/Server.hs
Labels: merge me, merge delay passed

#9768 Make `check` recognise `main-is` in conditional branches
  Cabal-syntax/src/Distribution/Types/CondTree.hs
  Cabal/src/Distribution/PackageDescription/Check/Conditional.hs
  cabal-testsuite/PackageTests/Check/Cond/After/cabal.out
  cabal-testsuite/PackageTests/Check/Cond/After/cabal.test.hs
  cabal-testsuite/PackageTests/Check/Cond/After/pkg.cabal
  cabal-testsuite/PackageTests/Check/Cond/Before/cabal.out
  cabal-testsuite/PackageTests/Check/Cond/Before/cabal.test.hs
  cabal-testsuite/PackageTests/Check/Cond/Before/pkg.cabal
  cabal-testsuite/PackageTests/Check/Cond/Deep/cabal.out
  cabal-testsuite/PackageTests/Check/Cond/Deep/cabal.test.hs
  cabal-testsuite/PackageTests/Check/Cond/Deep/pkg.cabal
  cabal-testsuite/PackageTests/Check/Cond/DeepMissing/cabal.out
  cabal-testsuite/PackageTests/Check/Cond/DeepMissing/cabal.test.hs
  cabal-testsuite/PackageTests/Check/Cond/DeepMissing/pkg.cabal
Labels: squash+merge me, merge delay passed, attention: needs-backport 3.12

#9767 backport: Find build-tool installed programs before programs in path
  Cabal/src/Distribution/Simple/Configure.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-testsuite/PackageTests/Regression/T9756/OK.hs
  cabal-testsuite/PackageTests/Regression/T9756/cabal-bug-build-tool.cabal
  cabal-testsuite/PackageTests/Regression/T9756/cabal.out
  cabal-testsuite/PackageTests/Regression/T9756/cabal.project
  cabal-testsuite/PackageTests/Regression/T9756/cabal.test.hs
  cabal-testsuite/PackageTests/Regression/T9756/repo/mybuilder-0.1.0.0/CHANGELOG.md
  cabal-testsuite/PackageTests/Regression/T9756/repo/mybuilder-0.1.0.0/app/Main.hs
  cabal-testsuite/PackageTests/Regression/T9756/repo/mybuilder-0.1.0.0/mybuilder.cabal
  cabal-testsuite/PackageTests/Regression/T9756/repo/mybuilder-0.2.0.0/CHANGELOG.md
  cabal-testsuite/PackageTests/Regression/T9756/repo/mybuilder-0.2.0.0/app/Main.hs
  cabal-testsuite/PackageTests/Regression/T9756/repo/mybuilder-0.2.0.0/mybuilder.cabal
Labels: squash+merge me, merge delay passed, backport, regression in 3.10, re: extra-prog-path

#9791 Support GHC2024 (fixes #9736)
  Cabal-syntax/src/Language/Haskell/Extension.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  Cabal/src/Distribution/Simple/GHC/ImplInfo.hs
  Cabal/src/Distribution/Simple/GHC/Internal.hs
  cabal-install/src/Distribution/Client/Init/Interactive/Command.hs
  cabal-install/tests/UnitTests/Distribution/Client/Init/Interactive.hs
  changelog.d/issue-9736
  doc/buildinfo-fields-reference.rst
  doc/cabal-package-description-file.rst
  editors/vim/syntax/cabal.vim
Labels: merge me, merge delay passed, attention: needs-backport 3.12

#9610 Add a --dry-run build check of cabal.project.release
  .github/workflows/quick-jobs.yml
Labels: merge delay passed, merge+no rebase

#9813 Conform BSD-2-Clause and BSD-3-Clause text to SPDX
  cabal-install/src/Distribution/Client/Init/Licenses.hs
  changelog.d/pr-9813
Labels: merge me, merge delay passed, attention: needs-manual-qa

#9810 Add required-fields to changelog.d config
  .github/workflows/changelogs.yml
  changelog.d/config
  changelog.d/issue-8680
  changelog.d/issue-9098-lexbraces
  changelog.d/issue-9678
  changelog.d/issue-9736
  changelog.d/pkgconfig-once
Labels: continuous-integration, merge me, re: changelog, merge delay passed

#9822 Fix --project-file option for boostrap
  Makefile
Labels: merge me, merge delay passed

#9818 Update licence list
  Cabal-syntax/src/Distribution/SPDX/LicenseExceptionId.hs
  Cabal-syntax/src/Distribution/SPDX/LicenseId.hs
  Cabal-syntax/src/Distribution/SPDX/LicenseListVersion.hs
  Makefile
  cabal-dev-scripts/src/GenSPDX.hs
  cabal-dev-scripts/src/GenSPDXExc.hs
  cabal-dev-scripts/src/GenUtils.hs
  changelog.d/pr-spdx
  doc/file-format-changelog.rst
  license-list-data/exceptions-3.23.json
  license-list-data/licenses-3.23.json
  templates/SPDX.LicenseExceptionId.template.hs
  templates/SPDX.LicenseId.template.hs
Labels: attention: needs-review

#9565 Use package groups
  Cabal-QuickCheck/src/Test/QuickCheck/Instances/Cabal.hs
  Cabal-tests/tests/CheckTests.hs
  Cabal-tests/tests/UnitTests/Distribution/PackageDescription/Check.hs
  Makefile
  cabal-install/tests/UnitTests/Distribution/Client/Configure.hs
  cabal-testsuite/cabal.project
  cabal-testsuite/static/Main.hs
  cabal.project
  cabal.project.buildinfo
  cabal.project.doctest
  cabal.project.libonly
  cabal.project.meta
  cabal.project.release
  cabal.project.validate
  cabal.project.validate.libonly
  cabal.project.weeder
  project-cabal/README.md
  project-cabal/constraints.config
  project-cabal/ghc-latest.config
  project-cabal/ghc-options.config
  project-cabal/pkgs.config
  project-cabal/pkgs/benchmarks.config
  project-cabal/pkgs/buildinfo.config
  project-cabal/pkgs/cabal.config
  project-cabal/pkgs/install.config
  project-cabal/pkgs/integration-tests.config
  project-cabal/pkgs/tests.config
  solver-benchmarks/HackageBenchmark.hs
  weeder.dhall
Labels: merge delay passed, merge+no rebase

#9847 Ignore testdb/intree generated files
  .gitignore
Labels: merge delay passed, merge+no rebase

#9766 Add “Add default-language” suggestion
  Cabal-tests/tests/ParserTests/regressions/issue-6288-d.cabal
  Cabal-tests/tests/ParserTests/regressions/issue-6288-f.check
  Cabal-tests/tests/ParserTests/regressions/issue-7776-a.cabal
  Cabal-tests/tests/ParserTests/regressions/issue-7776-b.cabal
  Cabal-tests/tests/ParserTests/regressions/issue-7776-c.cabal
  Cabal/src/Distribution/PackageDescription/Check/Target.hs
  Cabal/src/Distribution/PackageDescription/Check/Warning.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/CabalVersion/DefaultLanguageSoft/cabal.out
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/CabalVersion/DefaultLanguageSoft/cabal.test.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/CabalVersion/DefaultLanguageSoft/pkg.cabal
  changelog.d/pr-9766
  doc/cabal-commands.rst
Labels: merge me, merge delay passed, attention: needs-manual-qa

#9859 CI validate-old-ghcs: pin to haskell-actions/setup@v2.6
  .github/workflows/validate.yml
Labels: priority: high :fire:, continuous-integration, attention: needs-review, merge me, merge delay passed, github_actions
