Repository haskell/cabal, pull requests merged in 2024-04, with the labels that each got.

#9845 Fix #9815: fix caching for quick-jobs CI (XDG, cache keys)
  .github/workflows/quick-jobs.yml
  Cabal/src/Distribution/Simple/Build/Macros/Z.hs
  Makefile
Labels: continuous-integration, merge me, merge delay passed, re: xdg

#9849 CI changelogs: switch to XDG, fix cache key
  .github/workflows/changelogs.yml
Labels: continuous-integration, merge me, merge delay passed

#9848 Bump time upper bound to acccomodate 1.14
  Cabal-syntax/Cabal-syntax.cabal
  Cabal/Cabal.cabal
Labels: merge me, merge delay passed, attention: needs-backport 3.12

#9837 Update licence list
  Cabal-syntax/src/Distribution/SPDX/LicenseExceptionId.hs
  Cabal-syntax/src/Distribution/SPDX/LicenseId.hs
  Cabal-syntax/src/Distribution/SPDX/LicenseListVersion.hs
  Makefile
  cabal-dev-scripts/src/GenSPDX.hs
  cabal-dev-scripts/src/GenSPDXExc.hs
  cabal-dev-scripts/src/GenUtils.hs
  changelog.d/pr-spdx
  doc/file-format-changelog.rst
  license-list-data/exceptions-3.23.json
  license-list-data/licenses-3.23.json
  templates/SPDX.LicenseExceptionId.template.hs
  templates/SPDX.LicenseId.template.hs
Labels: merge me, merge delay passed, backport

#9841 Update Cabal-syntax for bootstrap
  bootstrap/cabal-bootstrap-gen.cabal
Labels: merge me, re: devx, merge delay passed

#9468 testsuite: Add some unit tests for #9466 #9467
  cabal-install/cabal-install.cabal
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
Labels: cabal-install: solver, merge me, merge delay passed

#9855 Remove unused packages
  Cabal-described/Cabal-described.cabal
  Cabal-syntax/Cabal-syntax.cabal
  Cabal-tests/Cabal-tests.cabal
  Cabal/Cabal.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
  cabal-testsuite/cabal-testsuite.cabal
  project-cabal/ghc-options.config
Labels: merge delay passed, merge+no rebase

#9740 Registered the NamedDefaults language extension
  Cabal-syntax/src/Language/Haskell/Extension.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  changelog.d/pr-9740
  editors/vim/syntax/cabal.vim
Labels: squash+merge me, merge delay passed

#9882 Update setupMinCabalVersionConstraint for GHC 9.10
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
Labels: merge me, merge delay passed, attention: needs-backport 3.12

#9832 docs: correct references to location of global store
  doc/how-to-build-like-nix.rst
  doc/nix-local-build.rst
Labels: documentation, merge me, re: store-dir, merge delay passed

#9583 Redesign 'cabal path' command to account for projects
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/CmdPath.hs
  cabal-install/src/Distribution/Client/Config.hs
  cabal-install/src/Distribution/Client/Errors.hs
  cabal-install/src/Distribution/Client/Main.hs
  cabal-install/src/Distribution/Client/ScriptUtils.hs
  cabal-install/src/Distribution/Client/Setup.hs
  cabal-testsuite/PackageTests/Path/All/cabal.out
  cabal-testsuite/PackageTests/Path/All/cabal.test.hs
  cabal-testsuite/PackageTests/Path/Compiler/cabal.out
  cabal-testsuite/PackageTests/Path/Compiler/cabal.test.hs
  cabal-testsuite/PackageTests/Path/Config/cabal.out
  cabal-testsuite/PackageTests/Path/Config/cabal.test.hs
  cabal-testsuite/PackageTests/Path/Config/config.cabal
  cabal-testsuite/PackageTests/Path/Config/fake-cabal.config
  cabal-testsuite/PackageTests/Path/Config/fake.cabal.project
  cabal-testsuite/PackageTests/Path/Single/cabal.out
  cabal-testsuite/PackageTests/Path/Single/cabal.test.hs
  cabal-testsuite/src/Test/Cabal/Monad.hs
  cabal-testsuite/src/Test/Cabal/OutputNormalizer.hs
  cabal-testsuite/src/Test/Cabal/Prelude.hs
  changelog.d/pr-9583
  doc/cabal-commands.rst
Labels: squash+merge me, merge delay passed, attention: needs-backport 3.12

#9886 CI: stop validating GHC 7
  .github/workflows/validate.yml
  cabal-testsuite/PackageTests/ForeignLibs/setup.test.hs
Labels: continuous-integration, merge me, merge delay passed, re: old GHC versions

#9705 Add a warning when an env file is created
  cabal-install/src/Distribution/Client/CmdInstall.hs
Labels: cabal-install: environment-files, attention: needs-review, squash+merge me, re: install --lib, merge delay passed, attention: needs-backport 3.12

#9851 Update cabal-install to allow time 1.14
  cabal-install/cabal-install.cabal
Labels: merge me, merge delay passed, attention: needs-backport 3.12

#9824 Show abbreviated mixed versions with suffix
  cabal-install-solver/src/Distribution/Solver/Modular/Message.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
  changelog.d/pr-9824
Labels: cabal-install: solver, merge delay passed, merge+no rebase

#9805 Add tests for #9799
  cabal-testsuite/PackageTests/NewFreeze/T9799a/Setup.hs
  cabal-testsuite/PackageTests/NewFreeze/T9799a/T9799.cabal
  cabal-testsuite/PackageTests/NewFreeze/T9799a/cabal.test.hs
  cabal-testsuite/PackageTests/NewFreeze/T9799a/repo/libA-0.1.0.0/libA.cabal
  cabal-testsuite/PackageTests/NewFreeze/T9799a/repo/libA-0.1.0.0/src/MyLib.hs
  cabal-testsuite/PackageTests/NewFreeze/T9799a/repo/libA-0.2.0.0/libA.cabal
  cabal-testsuite/PackageTests/NewFreeze/T9799a/repo/libA-0.2.0.0/src/MyLib.hs
  cabal-testsuite/PackageTests/NewFreeze/T9799a/src/MyLib.hs
  cabal-testsuite/PackageTests/NewFreeze/T9799b/Setup.hs
  cabal-testsuite/PackageTests/NewFreeze/T9799b/T9799.cabal
  cabal-testsuite/PackageTests/NewFreeze/T9799b/cabal.test.hs
  cabal-testsuite/PackageTests/NewFreeze/T9799b/repo/libA-0.1.0.0/libA.cabal
  cabal-testsuite/PackageTests/NewFreeze/T9799b/repo/libA-0.1.0.0/src/MyLib.hs
  cabal-testsuite/PackageTests/NewFreeze/T9799b/repo/libA-0.2.0.0/libA.cabal
  cabal-testsuite/PackageTests/NewFreeze/T9799b/repo/libA-0.2.0.0/src/MyLib.hs
  cabal-testsuite/PackageTests/NewFreeze/T9799b/src/None.hs
Labels: cabal-install: solver, cabal-install: cmd/freeze, merge me, merge delay passed

#9879 add squash+merge for backports
  .github/mergify.yml
Labels: merge me, merge delay passed, attention: needs-backport 3.12, attention: needs-manual-qa, attention: needs-backport 3.10

#9908 3.12 changelogs updated
  changelog.d/issue-9578
  changelog.d/issue-9736
  changelog.d/pr-9583
  changelog.d/pr-9813
  changelog.d/pr-spdx
  release-notes/Cabal-3.12.0.0.md
  release-notes/WIP-cabal-install-3.12.x.0.md
Labels: squash+merge me

#9896 update idna per dependabot / CVE-2024-3651
  doc/requirements.in
  doc/requirements.txt
Labels: merge me, merge delay passed

#9905 Fix #8141 Don't refer to 'custom-setup' as 'optional'
  doc/cabal-package-description-file.rst
Labels: merge me, merge delay passed

#9922 3.12 changelog fixup
  release-notes/Cabal-3.12.0.0.md
  release-notes/WIP-cabal-install-3.12.x.0.md
Labels: squash+merge me, attention: needs-backport in the future

#9924 Fix release notes grammar
  release-notes/Cabal-3.12.0.0.md
  release-notes/WIP-cabal-install-3.12.x.0.md
Labels: squash+merge me

#9928 Support GHC 9.12
  Cabal/src/Distribution/Simple/GHC.hs
Labels: merge me, merge delay passed, attention: needs-backport 3.12

#9935 Fix changelog/readme
  Cabal-syntax/ChangeLog.md
  Cabal/ChangeLog.md
  Cabal/README.md
Labels: merge me, merge delay passed, attention: needs-backport 3.12

#9931 Use alice as username in cabal path examples
  doc/cabal-commands.rst
Labels: merge delay passed, merge+no rebase

#9943 Add `initialBuildSteps` removal notice
  release-notes/Cabal-3.12.0.0.md
Labels: documentation, squash+merge me

#9945 Add warning and note to cabal test [TARGETS]
  doc/cabal-commands.rst
Labels: documentation, merge delay passed, merge+no rebase

#9953 State supported GHC versions in release notes
  .github/workflows/validate.yml
  release-notes/Cabal-3.12.0.0.md
Labels: merge me, merge delay passed

#9950 Reinstate 'initialBuildSteps' function
  Cabal/src/Distribution/Simple/Build.hs
  changelog.d/pr-9950
Labels: merge me, merge delay passed, attention: needs-backport 3.12
