Repository haskell/cabal, pull requests merged in 2024-02, with the labels that each got.

#9635 Don't inherit package database to tests
  cabal-testsuite/PackageTests/PathsModule/Executable-Relocatable/setup.test.hs
  cabal-testsuite/main/cabal-tests.hs
  cabal-testsuite/src/Test/Cabal/Monad.hs
Labels: attention: needs-review, cabal-testsuite, merge me, type: testing, merge delay passed

#9649 Add static pre-release job
  .github/workflows/validate.yml
  CONTRIBUTING.md
  README.md
Labels: merge me, merge delay passed

#9676 Add instruction for CI patches
  .github/pull_request_template.md
Labels: merge me, merge delay passed

#9686 Bump a number of dependencies
  Cabal-tests/Cabal-tests.cabal
  cabal-install/cabal-install.cabal
  cabal-testsuite/cabal-testsuite.cabal
Labels: merge me, merge delay passed, attention: needs-backport 3.10

#9690 Revert "Drop sub-component targets (#8966)"
  Cabal/src/Distribution/Simple/BuildTarget.hs
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/CmdBench.hs
  cabal-install/src/Distribution/Client/CmdBuild.hs
  cabal-install/src/Distribution/Client/CmdErrorMessages.hs
  cabal-install/src/Distribution/Client/CmdHaddock.hs
  cabal-install/src/Distribution/Client/CmdInstall.hs
  cabal-install/src/Distribution/Client/CmdInstall/ClientInstallTargetSelector.hs
  cabal-install/src/Distribution/Client/CmdListBin.hs
  cabal-install/src/Distribution/Client/CmdRepl.hs
  cabal-install/src/Distribution/Client/CmdRun.hs
  cabal-install/src/Distribution/Client/CmdSdist.hs
  cabal-install/src/Distribution/Client/CmdTest.hs
  cabal-install/src/Distribution/Client/ProjectBuilding/PackageFileMonitor.hs
  cabal-install/src/Distribution/Client/ProjectBuilding/UnpackedPackage.hs
  cabal-install/src/Distribution/Client/ProjectOrchestration.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/ProjectPlanning/Types.hs
  cabal-install/src/Distribution/Client/TargetProblem.hs
  cabal-install/src/Distribution/Client/TargetSelector.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/UnitTests.hs
  cabal-install/tests/UnitTests/Distribution/Client/ProjectPlanning.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/RunMainBad/Main.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/RunMainBad/RunMainBad.cabal
  cabal-testsuite/PackageTests/NewBuild/CmdRun/RunMainBad/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/RunMainBad/cabal.project
  cabal-testsuite/PackageTests/NewBuild/CmdRun/RunMainBad/cabal.test.hs
  changelog.d/pr-8966
Labels: merge me, merge delay passed

#9697 Apply local configuration to install targets
  cabal-install/src/Distribution/Client/CmdInstall.hs
  cabal-testsuite/PackageTests/Install/T7297-8909-7236/Main.hs
  cabal-testsuite/PackageTests/Install/T7297-8909-7236/cabal.project
  cabal-testsuite/PackageTests/Install/T7297-8909-7236/cabal.test.hs
  cabal-testsuite/PackageTests/Install/T7297-8909-7236/t7297-89097236a.cabal
Labels: merge me, attention: needs-backport 3.6, attention: needs-backport 3.8, merge delay passed, attention: needs-backport 3.12, attention: needs-backport 3.10

#9699 Ignore test T7339 output, libhello.so
  cabal-testsuite/PackageTests/LinkerOptions/.gitignore
Labels: merge delay passed, merge+no rebase

#9703 Allow zlib-0.7
  cabal-install/cabal-install.cabal
Labels: merge me, merge delay passed, attention: needs-backport 3.10

#9663 Add -Wunused-packages to the packages
  Cabal-syntax/Cabal-syntax.cabal
  Cabal/Cabal.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
Labels: squash+merge me, merge delay passed

#9673 Merge two Globbing Modules and Fix #5349
  Cabal-tests/tests/UnitTests/Distribution/Simple/Glob.hs
  Cabal/Cabal.cabal
  Cabal/src/Distribution/PackageDescription/Check.hs
  Cabal/src/Distribution/PackageDescription/Check/Paths.hs
  Cabal/src/Distribution/Simple/Glob.hs
  Cabal/src/Distribution/Simple/Glob/Internal.hs
  Cabal/src/Distribution/Simple/Haddock.hs
  Cabal/src/Distribution/Simple/SrcDist.hs
  cabal-install/src/Distribution/Client/FileMonitor.hs
  cabal-install/src/Distribution/Client/Glob.hs
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/src/Distribution/Client/RebuildMonad.hs
  cabal-install/tests/UnitTests/Distribution/Client/ArbitraryInstances.hs
  cabal-install/tests/UnitTests/Distribution/Client/DescribedInstances.hs
  cabal-install/tests/UnitTests/Distribution/Client/FileMonitor.hs
  cabal-install/tests/UnitTests/Distribution/Client/Glob.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Paths/AbsolutePath/cabal.out
  cabal-testsuite/PackageTests/SDist/T5195/cabal.out
  cabal-testsuite/PackageTests/SDist/T5195/cabal.test.hs
  cabal-testsuite/PackageTests/SDist/T5195/t5195.cabal
  cabal-testsuite/PackageTests/SDist/T5195and5349/Main.hs
  cabal-testsuite/PackageTests/SDist/T5195and5349/actually-a-directory/some-file
  cabal-testsuite/PackageTests/SDist/T5195and5349/actually-a-file
  cabal-testsuite/PackageTests/SDist/T5195and5349/cabal.out
  cabal-testsuite/PackageTests/SDist/T5195and5349/cabal.project
  cabal-testsuite/PackageTests/SDist/T5195and5349/cabal.test.hs
  cabal-testsuite/PackageTests/SDist/T5195and5349/t5195and5349.cabal
  changelog.d/pr-9673
  doc/cabal-project-description-file.rst
Labels: merge me, merge delay passed

#9706 Refactor CmdInstall / fix bug in #9697
  cabal-install/src/Distribution/Client/CmdInstall.hs
  cabal-install/src/Distribution/Client/CmdInstall/ClientInstallTargetSelector.hs
  cabal-install/src/Distribution/Client/CmdSdist.hs
  cabal-install/src/Distribution/Client/CmdUpdate.hs
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/src/Distribution/Client/ProjectOrchestration.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/ScriptUtils.hs
  cabal-install/src/Distribution/Client/Types/PackageSpecifier.hs
Labels: merge me, merge delay passed

#9470 cabal-install: justify why legacy-fallback is used
  cabal-install/src/Distribution/Client/ProjectBuilding/UnpackedPackage.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/ProjectPlanning/Types.hs
Labels: merge me, merge delay passed

#9707 Add test cabal install remote-pkg for #9697
  cabal-testsuite/PackageTests/Install/T7297-8909-7236/cabal.test.hs
  cabal-testsuite/PackageTests/Install/T7297-8909-7236/repo/external-lib-0.1.0.0/CHANGELOG.md
  cabal-testsuite/PackageTests/Install/T7297-8909-7236/repo/external-lib-0.1.0.0/Main.hs
  cabal-testsuite/PackageTests/Install/T7297-8909-7236/repo/external-lib-0.1.0.0/external-lib.cabal
Labels: merge me, merge delay passed

#9543 Modularise writeAutogenFiles
  Cabal/Cabal.cabal
  Cabal/src/Distribution/Simple/Build.hs
  Cabal/src/Distribution/Simple/BuildPaths.hs
  Cabal/src/Distribution/Simple/Errors.hs
  Cabal/src/Distribution/Simple/GHC.hs
  Cabal/src/Distribution/Simple/GHC/Build/Link.hs
  Cabal/src/Distribution/Simple/GHCJS.hs
  Cabal/src/Distribution/Simple/PreProcess.hs
  Cabal/src/Distribution/Simple/PreProcess/Types.hs
  Cabal/src/Distribution/Simple/SrcDist.hs
  Cabal/src/Distribution/Simple/Utils.hs
  cabal-install/src/Distribution/Client/RebuildMonad.hs
  cabal-install/src/Distribution/Client/SourceFiles.hs
  cabal-testsuite/PackageTests/AutogenModulesToggling/Setup.hs
  cabal-testsuite/PackageTests/CustomPreProcess/Setup.hs
Labels: attention: needs-review, merge me, merge delay passed

#9720 Fix multi-repl closure computation with invalid Custom setup
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/cabal.out
  cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/cabal.project
  cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/cabal.test.hs
  cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/pkg-a/Foo.hs
  cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/pkg-a/pkg-a.cabal
  cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/pkg-b/Bar.hs
  cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/pkg-b/Setup.hs
  cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/pkg-b/pkg-b.cabal
  cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/pkg-c/Quu.hs
  cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/pkg-c/pkg-c.cabal
  cabal-testsuite/PackageTests/NewBuild/CmdRepl/CustomSetup/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRepl/CustomSetup/cabal.project
  cabal-testsuite/PackageTests/NewBuild/CmdRepl/CustomSetup/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRepl/CustomSetup/foo/CHANGELOG.md
  cabal-testsuite/PackageTests/NewBuild/CmdRepl/CustomSetup/foo/LICENSE
  cabal-testsuite/PackageTests/NewBuild/CmdRepl/CustomSetup/foo/Setup.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRepl/CustomSetup/foo/app/Main.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRepl/CustomSetup/foo/foo.cabal
Labels: merge me, merge delay passed

#8854 add the extension ListTuplePuns (GHC proposal 475)
  Cabal-syntax/src/Language/Haskell/Extension.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  changelog.d/pr-8854
  editors/vim/syntax/cabal.vim
Labels: merge me, merge delay passed

#9683 cabal-install: Clarify the semantics of package-db flag
  cabal-install/src/Distribution/Client/CmdInstall.hs
  cabal-install/src/Distribution/Client/DistDirLayout.hs
  cabal-install/src/Distribution/Client/ProjectBuilding/UnpackedPackage.hs
  cabal-install/src/Distribution/Client/ProjectOrchestration.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-testsuite/PackageTests/PackageDB/t9678/cabal.test.hs
  cabal-testsuite/PackageTests/PackageDB/t9678/p1/CHANGELOG.md
  cabal-testsuite/PackageTests/PackageDB/t9678/p1/p1.cabal
  cabal-testsuite/PackageTests/PackageDB/t9678/p1/src/MyLib.hs
  cabal-testsuite/PackageTests/PackageDB/t9678/p2/CHANGELOG.md
  cabal-testsuite/PackageTests/PackageDB/t9678/p2/cabal.project
  cabal-testsuite/PackageTests/PackageDB/t9678/p2/p2.cabal
  cabal-testsuite/PackageTests/PackageDB/t9678/p2/src/MyLib.hs
  cabal-testsuite/PackageTests/PackageDB/t9678/repo/p3-0.1.0.0/CHANGELOG.md
  cabal-testsuite/PackageTests/PackageDB/t9678/repo/p3-0.1.0.0/p3.cabal
  cabal-testsuite/PackageTests/PackageDB/t9678/repo/p3-0.1.0.0/src/MyLib.hs
  changelog.d/issue-9678
  doc/cabal-project-description-file.rst
Labels: attention: needs-review, merge me, merge delay passed

#9739 Download stackage.org/.../cabal.config locally
  cabal-testsuite/PackageTests/VersionPriority/1-web-constraints-import.project
  cabal-testsuite/PackageTests/VersionPriority/1-web-import-constraints.project
  cabal-testsuite/PackageTests/VersionPriority/1-web.out
  cabal-testsuite/PackageTests/VersionPriority/2-web.out
  cabal-testsuite/PackageTests/VersionPriority/3-web.out
  cabal-testsuite/PackageTests/VersionPriority/project-stackage/nightly-2023-12-07.config
  cabal-testsuite/PackageTests/VersionPriority/stackage-web.config
Labels: merge delay passed, merge+no rebase

#9751 update copyright for 2024
  Cabal-syntax/Cabal-syntax.cabal
  Cabal-syntax/LICENSE
  Cabal-tests/Cabal-tests.cabal
  Cabal-tests/LICENSE
  Cabal/Cabal.cabal
  Cabal/LICENSE
  LICENSE
  cabal-benchmarks/LICENSE
  cabal-benchmarks/cabal-benchmarks.cabal
  cabal-dev-scripts/LICENSE
  cabal-install-solver/LICENSE
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/LICENSE
  cabal-install/cabal-install.cabal
  cabal-testsuite/LICENSE
  cabal-testsuite/cabal-testsuite.cabal
  doc/conf.py
  solver-benchmarks/LICENSE
  solver-benchmarks/solver-benchmarks.cabal
Labels: merge me, merge delay passed
