Repository haskell/cabal, pull requests merged in 2024-10, with the labels that each got.

#10404 Prefer ErrorCall to ErrorCallWithLocation
  Cabal-syntax/src/Distribution/Compat/Binary.hs
  Cabal-syntax/src/Distribution/Utils/Structured.hs
Labels: merge me, merge delay passed, ready and waiting

#10314 Improve assertion messages in `IntegrationTests2` `testConfigOptionComments`
  cabal-install/tests/IntegrationTests2.hs
Labels: merge me, merge delay passed, ready and waiting

#10273 Show why configuring dependencies failed
  Cabal-syntax/Cabal-syntax.cabal
  Cabal-syntax/src/Distribution/Compat/NonEmptySet.hs
  Cabal-syntax/src/Distribution/PackageDescription/Configuration.hs
  Cabal-syntax/src/Distribution/Pretty.hs
  Cabal-syntax/src/Distribution/Types/Dependency.hs
  Cabal-syntax/src/Distribution/Types/DependencySatisfaction.hs
  Cabal-syntax/src/Distribution/Types/LibraryName.hs
  Cabal-syntax/src/Distribution/Types/MissingDependency.hs
  Cabal-syntax/src/Distribution/Types/MissingDependencyReason.hs
  Cabal-tests/tests/ParserTests/regressions/issue-5846.format
  Cabal/Cabal.cabal
  Cabal/src/Distribution/Simple/Configure.hs
  Cabal/src/Distribution/Simple/Errors.hs
  Cabal/src/Distribution/Simple/PackageIndex.hs
  cabal-install/src/Distribution/Client/CmdOutdated.hs
  cabal-install/src/Distribution/Client/Configure.hs
  cabal-install/src/Distribution/Client/Dependency.hs
  cabal-install/src/Distribution/Client/GenBounds.hs
  cabal-install/src/Distribution/Client/Install.hs
  cabal-install/src/Distribution/Client/InstallSymlink.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-testsuite/PackageTests/ConfigureComponent/MissingOrPrivate/Lib.cabal
  cabal-testsuite/PackageTests/ConfigureComponent/MissingOrPrivate/Lib.hs
  cabal-testsuite/PackageTests/ConfigureComponent/MissingOrPrivate/exe/Exe.hs
  cabal-testsuite/PackageTests/ConfigureComponent/MissingOrPrivate/setup-fail.out
  cabal-testsuite/PackageTests/ConfigureComponent/MissingOrPrivate/setup-fail.test.hs
  cabal-testsuite/PackageTests/ConfigureComponent/SubLib/setup-explicit-fail.out
  cabal-testsuite/src/Test/Cabal/OutputNormalizer.hs
  changelog.d/pr-10273
Labels: merge me, merge delay passed, attention: needs-backport 3.12, attention: needs-backport 3.10, ready and waiting

#10361 keep running tests even if earlier ones failed
  .github/workflows/validate.yml
Labels: continuous-integration, merge me, merge delay passed, attention: needs-backport 3.12, ready and waiting, attention: needs-backport 3.14

#10331 CI: cabal-head prerelease: move to a current GitHub Action
  .github/workflows/validate.yml
Labels: merge me, merge delay passed, ready and waiting

#10387 Fix Unicode output in `cabal-testsuite`
  cabal-testsuite/src/Test/Cabal/Monad.hs
  cabal-testsuite/src/Test/Cabal/Run.hs
Labels: merge me, merge delay passed, merge+no rebase, ready and waiting

#10403 avoid incomplete record selection warning
  Cabal/src/Distribution/Simple/GHC/Build/Link.hs
Labels: type: refactor, merge me, merge delay passed, attention: needs-backport 3.12, ready and waiting, attention: needs-backport 3.14

#10320 Convert `validate.sh` to a Haskell script
  .github/workflows/format.yml
  Makefile
  cabal-validate/README.md
  cabal-validate/cabal-validate.cabal
  cabal-validate/src/ANSI.hs
  cabal-validate/src/Cli.hs
  cabal-validate/src/ClockUtil.hs
  cabal-validate/src/Main.hs
  cabal-validate/src/OutputUtil.hs
  cabal-validate/src/ProcessUtil.hs
  cabal-validate/src/Step.hs
  project-cabal/pkgs/tests.config
  validate.sh
Labels: merge delay passed, merge+no rebase, ready and waiting

#10366 Create temp files in temp directory
  .github/workflows/validate.yml
  Cabal-syntax/src/Distribution/Utils/Generic.hs
  Cabal-tests/tests/UnitTests/Distribution/Simple/Utils.hs
  Cabal/src/Distribution/Simple/Configure.hs
  Cabal/src/Distribution/Simple/GHC/Internal.hs
  Cabal/src/Distribution/Simple/Haddock.hs
  Cabal/src/Distribution/Simple/PreProcess.hs
  Cabal/src/Distribution/Simple/Program/Ar.hs
  Cabal/src/Distribution/Simple/Program/Ld.hs
  Cabal/src/Distribution/Simple/Program/ResponseFile.hs
  Cabal/src/Distribution/Simple/Utils.hs
  cabal-install/src/Distribution/Client/HttpUtils.hs
  cabal-testsuite/PackageTests/Backpack/Includes2/cabal-internal.test.hs
  cabal-testsuite/PackageTests/Backpack/Includes3/cabal-external.test.hs
  cabal-testsuite/PackageTests/Backpack/Includes3/cabal-internal.test.hs
  cabal-testsuite/PackageTests/Backpack/T6385/cabal.test.hs
  cabal-testsuite/PackageTests/HaddockKeepsTmps/cabal.test.hs
Labels: merge me, merge delay passed, ready and waiting

#10409 Add `.editorconfig`
  .editorconfig
Labels: merge me, merge delay passed, ready and waiting

#10392 Add `haddock --keep-temp-files` test
  cabal-testsuite/PackageTests/HaddockKeepTmpsCustom/Setup.hs
  cabal-testsuite/PackageTests/HaddockKeepTmpsCustom/Simple.hs
  cabal-testsuite/PackageTests/HaddockKeepTmpsCustom/cabal.project
  cabal-testsuite/PackageTests/HaddockKeepTmpsCustom/cabal.test.hs
  cabal-testsuite/PackageTests/HaddockKeepTmpsCustom/my.cabal
Labels: merge delay passed, merge+no rebase, ready and waiting

#10419 Cabal: Take into account compilerBuildWay when computing final library ways
  Cabal/src/Distribution/Simple/GHC/Build.hs
  cabal-testsuite/PackageTests/BuildWays/p/CHANGELOG.md
  cabal-testsuite/PackageTests/BuildWays/p/p.cabal
  cabal-testsuite/PackageTests/BuildWays/p/src/MyLib.hs
  cabal-testsuite/PackageTests/BuildWays/q/CHANGELOG.md
  cabal-testsuite/PackageTests/BuildWays/q/app/Main.hs
  cabal-testsuite/PackageTests/BuildWays/q/q.cabal
  cabal-testsuite/PackageTests/BuildWays/setup.test.hs
  changelog.d/i10418
Labels: merge me, merge delay passed, ready and waiting

#10407 patchups to `changelog.d` file descriptions
  CONTRIBUTING.md
Labels: merge me, merge delay passed, ready and waiting

#10424 Fix `HaddockKeepTmpsCustom` test for merge skew
  cabal-testsuite/PackageTests/HaddockKeepTmpsCustom/cabal.test.hs
  cabal-testsuite/PackageTests/HaddockKeepsTmps/cabal.test.hs
  cabal-testsuite/src/Test/Cabal/Monad.hs
Labels: merge me, merge delay passed, ready and waiting

#10417 Fix ./setup install comand
  Cabal/src/Distribution/Simple.hs
  cabal-testsuite/PackageTests/Install/DistPrefInstall/CHANGELOG.md
  cabal-testsuite/PackageTests/Install/DistPrefInstall/DistPrefInstall.cabal
  cabal-testsuite/PackageTests/Install/DistPrefInstall/Setup.hs
  cabal-testsuite/PackageTests/Install/DistPrefInstall/setup.test.hs
  cabal-testsuite/PackageTests/Install/DistPrefInstall/src/MyLib.hs
  changelog.d/t10416
Labels: merge me, merge delay passed, attention: needs-backport 3.12, ready and waiting, attention: needs-backport 3.14

#10413 Add type signature and documentation to `toSavedConfig`
  cabal-install/src/Distribution/Client/Config.hs
Labels: merge me, merge delay passed, ready and waiting

#10356 Handle SPDX licences starting with a digit
  Cabal-syntax/src/Distribution/SPDX/LicenseExceptionId.hs
  Cabal-syntax/src/Distribution/SPDX/LicenseId.hs
  cabal-dev-scripts/src/GenUtils.hs
  changelog.d/pr-10356
Labels: squash+merge me, re: devx, merge delay passed, ready and waiting

#10433 Fix build ways for foreign libs
  Cabal/src/Distribution/Simple/GHC/Build.hs
  cabal-testsuite/PackageTests/ProfShared/setup.test.hs
Labels: merge me, merge delay passed, ready and waiting

#10434 README: add Cabal-hooks to the list of packages
  README.md
Labels: merge me, merge delay passed, ready and waiting

#10432 Avoid partial `Data.List.last` in autogenerated `Paths_<pkg>.hs`
  Cabal/src/Distribution/Simple/Build/PathsModule/Z.hs
  changelog.d/pr-10432
  templates/Paths_pkg.template.hs
Labels: merge me, merge delay passed, ready and waiting

#10445 switch validate to 22.04 for now
  .github/workflows/validate.yml
Labels: priority: high :fire:, continuous-integration, attention: needs-review, merge me, merge delay passed, attention: needs-backport 3.12, ready and waiting, attention: needs-backport 3.14

#10393 `haddock-project`: add `CommonSetupFlags`
  Cabal/src/Distribution/Simple/Setup/Haddock.hs
  cabal-install/src/Distribution/Client/CmdHaddockProject.hs
  cabal-install/src/Distribution/Client/Config.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
  cabal-install/tests/IntegrationTests2.hs
Labels: merge me, merge delay passed, merge+no rebase, ready and waiting

#10444 remove accidentally introduced `Cabal-hooks.cabal`
  Cabal-hooks/Cabal-hooks.cabal
Labels: merge me

#10429 try to fix LTS prerelease workflow
  .github/workflows/validate.yml
Labels: continuous-integration, merge me, merge delay passed, ready and waiting, re: long-term support branch

#10421 round out local Makefile checks
  CONTRIBUTING.md
  Makefile
Labels: merge me, re: devx, merge delay passed, ready and waiting

#10462 kill a `continue-on-error`
  .github/workflows/validate.yml
Labels: continuous-integration, merge me, merge delay passed, attention: needs-backport 3.12, ready and waiting, attention: needs-backport 3.14

#10458 sync `validate.yml` with `master`
  .github/workflows/validate.yml
Labels: merge me

#10465 Revert "have Mergify insist on all-green CI"
  .github/mergify.yml
Labels: priority: high :fire:, merge me, merge delay passed, ready and waiting

#10428 Add `--tasty-arg` to `validate.sh`
  cabal-validate/src/Cli.hs
Labels: merge me, merge delay passed, attention: needs-backport 3.12, ready and waiting, attention: needs-backport 3.14

#10464 Bump base bound to 4.21 for GHC 9.12
  buildinfo-reference-generator/buildinfo-reference-generator.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
  cabal-testsuite/cabal-testsuite.cabal
Labels: merge me, merge delay passed, ready and waiting, attention: needs-backport 3.14

#10463 change the backport label
  .github/mergify.yml
Labels: merge me, merge delay passed, ready and waiting

#10448 try to run check-sdist on the right ghcs
  .github/workflows/check-sdist.yml
Labels: continuous-integration, merge me, merge delay passed, ready and waiting

#10475 Clarify cabal check `no-doc` documentation
  doc/cabal-commands.rst
Labels: merge me, merge delay passed, ready and waiting

#10468 add new options for ghc 9.12
  Cabal/src/Distribution/Simple/Program/GHC.hs
  changelog.d/pr-10468
Labels: merge me, merge delay passed, ready and waiting

#10473 Add a note for contributors installing fourmolu
  CONTRIBUTING.md
Labels: merge delay passed, merge+no rebase, ready and waiting

#10481 Document `Setup.hs repl`
  doc/setup-commands.rst
Labels: squash+merge me, merge delay passed, ready and waiting

#10497 try to debug the LTS prerelease
  .github/workflows/validate.yml
Labels: merge me

#10488 Fix a incomplete selector warning
  Cabal/src/Distribution/Simple/Build/Macros.hs
  Cabal/src/Distribution/Simple/Register.hs
  Cabal/src/Distribution/Types/ComponentLocalBuildInfo.hs
Labels: merge me, merge delay passed, ready and waiting

#10499 Debug LTS prereleases, take 3
  .github/workflows/validate.yml
Labels: merge me
