Repository haskell/cabal, pull requests merged in 2024-06, with the labels that each got.

#10017 Two fixes to multi repl command
  Cabal/src/Distribution/Simple/GHC/Build/Link.hs
  cabal-install/src/Distribution/Client/CmdRepl.hs
  cabal-testsuite/PackageTests/MultiRepl/ExtraOptions/CHANGELOG.md
  cabal-testsuite/PackageTests/MultiRepl/ExtraOptions/LICENSE
  cabal-testsuite/PackageTests/MultiRepl/ExtraOptions/app/Main.hs
  cabal-testsuite/PackageTests/MultiRepl/ExtraOptions/cabal.out
  cabal-testsuite/PackageTests/MultiRepl/ExtraOptions/cabal.project
  cabal-testsuite/PackageTests/MultiRepl/ExtraOptions/cabal.test.hs
  cabal-testsuite/PackageTests/MultiRepl/ExtraOptions/extra-options.cabal
  cabal-testsuite/PackageTests/MultiRepl/ExtraOptions/src/MyLib.hs
  cabal-testsuite/PackageTests/MultiRepl/ExtraOptions/test/Main.hs
Labels: Cabal: cmd/repl, attention: needs-review, merge me, merge delay passed, attention: needs-backport 3.12

#10056 Fix --program-suffix resulting in invalid symlink
  cabal-install/src/Distribution/Client/CmdInstall.hs
  cabal-testsuite/PackageTests/Install/ProgramAffixes/Main.hs
  cabal-testsuite/PackageTests/Install/ProgramAffixes/cabal.project
  cabal-testsuite/PackageTests/Install/ProgramAffixes/cabal.test.hs
  cabal-testsuite/PackageTests/Install/ProgramAffixes/p.cabal
  changelog.d/issue-9919
Labels: cabal-install: cmd/install, merge me, merge delay passed, re: --program-suffix

#10082 Bump dependencies and cabal-version
  Cabal/Cabal.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
Labels: merge me, merge delay passed, attention: needs-backport 3.12

#10101 CI: dogfooding should run on the same Mac runner as validate
  .github/workflows/validate.yml
Labels: continuous-integration, squash+merge me, merge delay passed, attention: needs-backport 3.12

#10014 add the applicable new (version 9.10) GHC flags to normaliseGhcArgs
  Cabal/src/Distribution/Simple/Program.hs
  Cabal/src/Distribution/Simple/Program/GHC.hs
  changelog.d/pr-10014
Labels: attention: needs-review, squash+merge me, merge delay passed, attention: needs-backport 3.12

#10093 solver: Prevent ghc-internal from being reinstalled (see #10087)
  cabal-install/src/Distribution/Client/Dependency.hs
Labels: cabal-install: solver, squash+merge me, merge delay passed, attention: needs-backport 3.12

#10037 update requests per CVE-2024-35195
  doc/requirements.in
Labels: merge me, merge delay passed, attention: needs-backport 3.12

#10105 Fix recomp bug by invalidating cache on build exception
  cabal-install/src/Distribution/Client/ProjectBuilding/UnpackedPackage.hs
  cabal-testsuite/PackageTests/Recompilation/GHC24926/Repro.hs
  cabal-testsuite/PackageTests/Recompilation/GHC24926/cabal.test.hs
  cabal-testsuite/PackageTests/Recompilation/GHC24926/repro.cabal
  cabal-testsuite/PackageTests/Recompilation/GHC24926/src/Process.hs
Labels: merge me, merge delay passed

#9968 testsuite: Pass pkgdb of store used for intree Cabal
  cabal-testsuite/PackageTests/BuildToolPaths/cabal.test.hs
  cabal-testsuite/main/cabal-tests.hs
  cabal-testsuite/src/Test/Cabal/Monad.hs
  cabal-testsuite/src/Test/Cabal/Prelude.hs
Labels: merge me, merge delay passed

#10099 Change packages default to empty
  doc/cabal-project-description-file.rst
Labels: attention: needs-review

#9967 Be more careful in handling unconfigured programs in the program database
  Cabal/src/Distribution/Simple/Configure.hs
  Cabal/src/Distribution/Simple/Program/Builtin.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/SetupWrapper.hs
  cabal-testsuite/PackageTests/ExtraProgPath/setup.out
Labels: attention: needs-review, merge me, merge delay passed, attention: needs-backport 3.12, re: --program-suffix, attention: backport after release

#9878 Add MHS as a recognized compiler.
  Cabal-syntax/src/Distribution/Compiler.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  changelog.d/pr-9878
Labels: squash+merge me, merge delay passed, attention: needs-backport 3.12, re: --with-compiler

#10112 perf: Group together packages by repo when verifying tarballs
  .hlint.yaml
  cabal-install/src/Distribution/Client/FetchUtils.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/Utils.hs
Labels: merge me, merge delay passed

#10120 Depend on tar-0.6.3.0
  bootstrap/generate_bootstrap_plans
  bootstrap/linux-8.10.7.json
  bootstrap/linux-9.0.2.json
  bootstrap/linux-9.2.8.json
  bootstrap/linux-9.4.8.json
  bootstrap/linux-9.6.4.json
  bootstrap/linux-9.8.2.json
  cabal.bootstrap.project
  cabal.release.project
Labels: merge me, merge delay passed, attention: needs-backport 3.12

#10125 Use `msys2` shell on Windows GHA runners
  .github/workflows/validate.yml
Labels: platform: windows

#10124 Changelogs for 3.12.1.0
  changelog.d/issue-10042
  changelog.d/issue-10063
  changelog.d/issue-6750
  changelog.d/issue-8680
  changelog.d/issue-8875
  changelog.d/issue-9098-lexbraces
  changelog.d/issue-9641
  changelog.d/issue-9678
  changelog.d/issue-9736
  changelog.d/issue-9919
  changelog.d/issue-9971
  changelog.d/pkgconfig-once
  changelog.d/pr-10014
  changelog.d/pr-9766
  changelog.d/pr-9824
  changelog.d/pr-9878
  changelog.d/pr-9950
  release-notes/Cabal-3.12.0.0.md
  release-notes/Cabal-3.12.1.0.md
  release-notes/cabal-install-3.12.1.0.md
Labels: release, squash+merge me, attention: backport after release

#10134 one last changelog entry
  release-notes/Cabal-3.12.0.0.md
Labels: release, squash+merge me

#10130 Release 3.12.1.0 version bumps
  Cabal-QuickCheck/Cabal-QuickCheck.cabal
  Cabal-described/Cabal-described.cabal
  Cabal-syntax/Cabal-syntax.cabal
  Cabal-tree-diff/Cabal-tree-diff.cabal
  Cabal/Cabal.cabal
  Cabal/Makefile
  bootstrap/cabal-bootstrap-gen.cabal
  bootstrap/linux-9.0.2.json
  bootstrap/linux-9.2.8.json
  bootstrap/linux-9.4.8.json
  bootstrap/linux-9.6.4.json
  bootstrap/linux-9.8.2.json
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
  cabal-testsuite/cabal-testsuite.cabal
  cabal.bootstrap.project
  doc/conf.py
  solver-benchmarks/solver-benchmarks.cabal
Labels: release, squash+merge me

#10136 Skip tasty-quickcheck 0.11
  Cabal-described/Cabal-described.cabal
  Cabal-tests/Cabal-tests.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
Labels: priority: high :fire:, attention: needs-review, merge me, merge delay passed, attention: needs-backport 3.12

#10138 missed the two changelog pointers
  Cabal-syntax/ChangeLog.md
  Cabal/ChangeLog.md
  cabal-install-solver/ChangeLog.md
  cabal-install/changelog
Labels: release, squash+merge me

#10142 Disable arch-native flag when building releases that we distribute
  cabal.release.project
  cabal.validate.project
Labels: squash+merge me, merge delay passed

#10148 regenerate bootstrap files without arch-native
  bootstrap/linux-9.0.2.json
  bootstrap/linux-9.2.8.json
  bootstrap/linux-9.4.8.json
  bootstrap/linux-9.6.4.json
  bootstrap/linux-9.8.2.json
  cabal.bootstrap.project
Labels: cabal-install: bootstrap, release, merge me

#10114 Use `--io-manager=native` in `lib-suite` on Windows
  cabal-testsuite/cabal-testsuite.cabal
  validate.sh
Labels: merge me, merge delay passed

#10149 Remove a stray line from cabal-install changelog
  cabal-install/changelog
Labels: merge me, merge delay passed

#10128 Cabal: Add flag to ignore build tool dependencies
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  Cabal/src/Distribution/Simple/Configure.hs
  Cabal/src/Distribution/Simple/Setup/Config.hs
  cabal-install/src/Distribution/Client/Config.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/Setup.hs
  cabal-testsuite/PackageTests/IgnoreBuildTools/Hello.hs
  cabal-testsuite/PackageTests/IgnoreBuildTools/client.cabal
  cabal-testsuite/PackageTests/IgnoreBuildTools/setup.out
  cabal-testsuite/PackageTests/IgnoreBuildTools/setup.test.hs
  changelog.d/pr-10128
Labels: merge me, merge delay passed

#9821 haddock-project support public sublibraries
  Cabal/src/Distribution/Simple/BuildPaths.hs
  Cabal/src/Distribution/Simple/Haddock.hs
  Cabal/src/Distribution/Simple/Install.hs
  Cabal/src/Distribution/Simple/Register.hs
  Cabal/src/Distribution/Simple/Setup/Haddock.hs
  cabal-install/src/Distribution/Client/CmdHaddockProject.hs
  cabal-install/src/Distribution/Client/Config.hs
  cabal-install/src/Distribution/Client/PackageHash.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Types.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/ProjectPlanning/Types.hs
  cabal-install/src/Distribution/Client/Setup.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
  cabal-testsuite/PackageTests/Backpack/Includes2/setup-external.cabal.out
  cabal-testsuite/PackageTests/Backpack/Includes2/setup-external.out
  cabal-testsuite/PackageTests/Backpack/Includes2/setup-per-component.out
  cabal-testsuite/PackageTests/Backpack/Includes3/setup-external-explicit.out
  cabal-testsuite/PackageTests/Backpack/Includes3/setup-external-ok.cabal.out
  cabal-testsuite/PackageTests/Backpack/Includes3/setup-external-ok.out
  cabal-testsuite/PackageTests/Backpack/Reexport1/setup.cabal.out
  cabal-testsuite/PackageTests/Backpack/Reexport1/setup.out
  cabal-testsuite/PackageTests/Haddock/setup.cabal.out
  cabal-testsuite/PackageTests/Haddock/setup.out
  cabal-testsuite/PackageTests/HaddockArgs/quickjump.out
  cabal-testsuite/PackageTests/HaddockBuildDepends/cabal.out
  cabal-testsuite/PackageTests/HaddockNewline/setup.cabal.out
  cabal-testsuite/PackageTests/HaddockNewline/setup.out
  cabal-testsuite/PackageTests/HaddockProject/haddock-project.out
  cabal-testsuite/PackageTests/InternalLibraries/Haddock/haddock.cabal.out
  cabal-testsuite/PackageTests/InternalLibraries/Haddock/haddock.out
  cabal-testsuite/PackageTests/NewHaddock/DisableDoc/cabal.out
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockForHackageCmdOutput/cabal.out
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockOutputCmd/cabal.out
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockOutputCmd/cabal.test.hs
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockOutputConfig/cabal.out
  cabal-testsuite/PackageTests/NewHaddock/HaddockOutput/HaddockOutputConfig/cabal.test.hs
  cabal-testsuite/PackageTests/NewHaddock/ImplyDependencies/cabal.out
  changelog.d/pr-9821
  doc/cabal-project-description-file.rst
  test/IntegrationTests2/config/default-config
  test/IntegrationTests2/nix-config/default-config
  tests/IntegrationTests2/config/default-config
  tests/IntegrationTests2/nix-config/default-config
Labels: attention: needs-review, cabal-install: cmd/haddock, merge me, attention: needs-manual-qa, cabal-install: cmd/haddock-project
