Repository haskell/cabal, pull requests merged in 2024-11, with the labels that each got.

#10494 Update haddock example for recent changes.
  Cabal/src/Distribution/Simple/PreProcess/Types.hs
Labels: merge me, merge delay passed, ready and waiting

#10493 Remove text for sandbox in replCommand
  Cabal/src/Distribution/Simple/Setup/Repl.hs
  changelog.d/pr-10493
Labels: merge me, merge delay passed, attention: needs-backport 3.12, ready and waiting, attention: needs-backport 3.14

#10483 fix `cabal install --program-suffix/prefix` (fix #10290 and #10476)
  cabal-install/src/Distribution/Client/CmdInstall.hs
  cabal-testsuite/PackageTests/Install/ProgramAffixes/overwrite-policy.out
  cabal-testsuite/PackageTests/Install/ProgramAffixes/overwrite-policy.test.hs
Labels: cabal-install: cmd/install, squash+merge me, merge delay passed, attention: needs-backport 3.12, ready and waiting, attention: needs-backport 3.14

#10505 move ncommits check to correct place
  .github/mergify.yml
Labels: priority: high :fire:, continuous-integration, merge me, merge delay passed, ready and waiting

#10517 make sure downloaded artifacts are all in the same dir
  .github/workflows/validate.yml
Labels: priority: high :fire:, attention: needs-review, merge me, merge delay passed, ready and waiting

#10486 Catch exception if git is not installed
  cabal-install/src/Distribution/Client/Init/NonInteractive/Heuristics.hs
  cabal-install/src/Distribution/Client/Init/Types.hs
  cabal-testsuite/PackageTests/Init/init-without-git.out
  cabal-testsuite/PackageTests/Init/init-without-git.test.hs
  changelog.d/pr-10486
Labels: cabal-install: cmd/init, squash+merge me, merge delay passed, attention: needs-manual-qa, ready and waiting

#10316 Remove hashable dependency
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/FileMonitor.hs
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/tests/UnitTests/Distribution/Client/FileMonitor.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck/Utils.hs
  cabal.bootstrap.project
  cabal.release.project
  cabal.validate.project
  project-cabal/ghc-latest.config
Labels: cabal-install: solver, squash+merge me, merge delay passed, ready and waiting

#10521 Add “Significant change” guideline
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: merge me, merge delay passed, ready and waiting

#10292 Expand and unify `--keep-temp-files`
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  Cabal/src/Distribution/Simple/Haddock.hs
  Cabal/src/Distribution/Simple/Setup.hs
  Cabal/src/Distribution/Simple/Setup/Common.hs
  Cabal/src/Distribution/Simple/Setup/Haddock.hs
  cabal-install/src/Distribution/Client/CmdHaddockProject.hs
  cabal-install/src/Distribution/Client/CmdRepl.hs
  cabal-install/src/Distribution/Client/Config.hs
  cabal-install/src/Distribution/Client/ParseUtils.hs
  cabal-install/src/Distribution/Client/ProjectBuilding/UnpackedPackage.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
  cabal-install/src/Distribution/Client/ProjectOrchestration.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/ReplFlags.hs
  cabal-install/src/Distribution/Client/Setup.hs
  cabal-install/tests/IntegrationTests2.hs
Labels: merge me, merge delay passed, merge+no rebase, ready and waiting, API change

#10529 Format `IntegrationTests2`
  cabal-install/cabal-install.cabal
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/IntegrationTests2/CPP.hs
Labels: merge me, merge delay passed, ready and waiting

#10506 Don't error if package index is missing (fix #10504)
  cabal-install/src/Distribution/Client/IndexUtils.hs
  cabal-testsuite/PackageTests/Get/T7248/cabal.out
Labels: merge me, merge delay passed, ready and waiting, attention: needs-backport 3.14

#10427 Make `cabal-testsuite` filterable with `--pattern`
  cabal-testsuite/README.md
  cabal-testsuite/cabal-testsuite.cabal
  cabal-testsuite/main/cabal-tests.hs
Labels: merge me, merge delay passed, attention: needs-backport 3.12, attention: needs-manual-qa, ready and waiting, attention: needs-backport 3.14

#10508 Add Y-forking import project
  cabal-testsuite/PackageTests/ConditionalAndImport/cabal.out
  cabal-testsuite/PackageTests/ConditionalAndImport/cabal.test.hs
  cabal-testsuite/PackageTests/ConditionalAndImport/yops-0.project
  cabal-testsuite/PackageTests/ConditionalAndImport/yops-2.config
  cabal-testsuite/PackageTests/ConditionalAndImport/yops-4.config
  cabal-testsuite/PackageTests/ConditionalAndImport/yops-6.config
  cabal-testsuite/PackageTests/ConditionalAndImport/yops-8.config
  cabal-testsuite/PackageTests/ConditionalAndImport/yops/yops-1.config
  cabal-testsuite/PackageTests/ConditionalAndImport/yops/yops-3.config
  cabal-testsuite/PackageTests/ConditionalAndImport/yops/yops-5.config
  cabal-testsuite/PackageTests/ConditionalAndImport/yops/yops-7.config
  cabal-testsuite/PackageTests/ConditionalAndImport/yops/yops-9.config
Labels: merge delay passed, merge+no rebase, ready and waiting

#10548 Print info about current project file in use to stderr and ignore the imports by default
  cabal-install-solver/src/Distribution/Solver/Types/ProjectConfigPath.hs
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-testsuite/PackageTests/ConditionalAndImport/cabal.out
  cabal-testsuite/PackageTests/NewConfigure/LocalConfigOverwrite/cabal.out
  cabal-testsuite/PackageTests/NewFreeze/BuildTools/new_freeze.out
  cabal-testsuite/PackageTests/NewFreeze/Flags/new_freeze.out
  cabal-testsuite/PackageTests/NewFreeze/FreezeFile/new_freeze.out
  cabal-testsuite/PackageTests/RelativePathProjectImports/cabal.out
  cabal-testsuite/PackageTests/VersionPriority/1-local.out
  cabal-testsuite/PackageTests/VersionPriority/1-web.out
  cabal-testsuite/PackageTests/VersionPriority/2-local.out
  cabal-testsuite/PackageTests/VersionPriority/2-web.out
  cabal-testsuite/PackageTests/VersionPriority/3-web.out
Labels: squash+merge me, attention: needs-backport 3.14

#10545 Regen cabal help after #9583
  cabal-install/src/Distribution/Client/CmdPath.hs
  doc/cabal-commands.rst
Labels: merge delay passed, merge+no rebase, ready and waiting

#10513 Typo, Warning not Waring
  Cabal/src/Distribution/Simple/Utils.hs
Labels: merge delay passed, merge+no rebase, ready and waiting

#10549 Warn on cabal format invocation
  cabal-install/src/Distribution/Client/Main.hs
  changelog.d/pr-10549
Labels: merge me, merge delay passed, ready and waiting

#10254 Shallow and concurrent git clones
  cabal-install/src/Distribution/Client/CmdInstall.hs
  cabal-install/src/Distribution/Client/Install.hs
  cabal-install/src/Distribution/Client/JobControl.hs
  cabal-install/src/Distribution/Client/ProjectBuilding.hs
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/RebuildMonad.hs
  cabal-install/src/Distribution/Client/ScriptUtils.hs
  cabal-install/src/Distribution/Client/VCS.hs
  cabal-testsuite/PackageTests/ExtraProgPath/setup.out
  changelog.d/pr-10254
Labels: merge me, merge delay passed, ready and waiting

#10577 Bump versions of Cabal{,-syntax}, cabal-install{,-solver} to 3.14.1.0
  Cabal-syntax/Cabal-syntax.cabal
  Cabal/Cabal.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
Labels: squash+merge me

#10576 Create changelogs for 3.14.1.0
  Cabal-syntax/ChangeLog.md
  Cabal/ChangeLog.md
  cabal-install-solver/ChangeLog.md
  cabal-install/changelog
  changelog.d/i10418
  changelog.d/pr-10468
  changelog.d/pr-10486
  changelog.d/pr-10507
  changelog.d/t10416
  release-notes/Cabal-3.14.1.0.md
  release-notes/cabal-install-3.14.1.0.md
Labels: squash+merge me

#10558 end the `#commits-behind=0` experiment
  .github/mergify.yml
Labels: continuous-integration, merge me, merge delay passed, ready and waiting

#10530 cabal-validate: --no-hide-successes
  cabal-validate/src/Cli.hs
Labels: merge me, merge delay passed, ready and waiting

#10525 Make a trailing colon for stanzas a parse failure
  cabal-install/src/Distribution/Client/ParseUtils.hs
  cabal-install/src/Distribution/Deprecated/ParseUtils.hs
  cabal-testsuite/PackageTests/ProjectConfig/FieldStanzaConfusion/cabal.out
  cabal-testsuite/PackageTests/ProjectConfig/FieldStanzaConfusion/cabal.project
  cabal-testsuite/PackageTests/ProjectConfig/FieldStanzaConfusion/cabal.test.hs
  cabal-testsuite/PackageTests/ProjectConfig/FieldStanzaConfusion/src/MyLib.hs
  cabal-testsuite/PackageTests/ProjectConfig/FieldStanzaConfusion/test.cabal
  changelog.d/pr-10525
Labels: merge me, merge delay passed, ready and waiting

#10584 Add PHONY rules for lint and lint-json
  Makefile
Labels: merge delay passed, merge+no rebase, ready and waiting

#10539 Add a performance measuring top-level user guide page
  doc/cabal-project-description-file.rst
  doc/how-to-analyze-haskell-code-performance.rst
  doc/index.rst
  doc/setup-commands.rst
Labels: documentation, squash+merge me, merge delay passed, ready and waiting

#10553 Duplicate VCS content
  doc/cabal-package-description-file.rst
  doc/cabal-project-description-file.rst
  doc/vcs/branch.rst
  doc/vcs/fields.rst
  doc/vcs/kind.rst
  doc/vcs/location.rst
  doc/vcs/subdir.rst
  doc/vcs/tag.rst
  doc/version-control-fields.rst
Labels: documentation, merge delay passed, merge+no rebase, ready and waiting

#10592 Typo respositories
  doc/how-to-source-packages.rst
Labels: merge delay passed, merge+no rebase, ready and waiting

#10593 Typo prexif, reseved and unmatched (
  doc/cabal-commands.rst
Labels: merge delay passed, merge+no rebase, ready and waiting

#10591 Create changelogs for 3.14.1.0
  Cabal-syntax/ChangeLog.md
  Cabal/ChangeLog.md
  cabal-install-solver/ChangeLog.md
  cabal-install/changelog
  changelog.d/i10418
  changelog.d/pr-10468
  changelog.d/pr-10486
  changelog.d/pr-10507
  changelog.d/t10416
  release-notes/Cabal-3.14.1.0.md
  release-notes/cabal-install-3.14.1.0.md
Labels: squash+merge me, merge delay passed, ready and waiting

#10585 Make Git deterministic in `UnitTests.Distribution.Client.VCS`
  cabal-install/tests/UnitTests/Distribution/Client/VCS.hs
Labels: merge me, type: testing, merge delay passed, ready and waiting

#10582 Don't use redundant alias Prelude as Prelude
  Cabal-syntax/src/Distribution/Fields/Lexer.x
Labels: merge delay passed, merge+no rebase, ready and waiting

#10589 cabal-validate: Reorder cli-tests
  cabal-validate/src/Main.hs
Labels: merge me, merge delay passed, ready and waiting

#10588 VCS tests: Make smaller `Arbitrary` repositories to speed up `long-tests` 4.2x
  cabal-install/tests/UnitTests/Distribution/Client/VCS.hs
Labels: merge me, merge delay passed, ready and waiting

#10599 Typo depency
  Cabal-syntax/src/Distribution/Types/MissingDependencyReason.hs
Labels: merge delay passed, merge+no rebase, ready and waiting
