Repository haskell/cabal, pull requests merged in 2024-01, with the labels that each got.

#9574 Delete `cabal.project.coverage`
  cabal.project.coverage
Labels: merge delay passed, merge+no rebase

#9573 Generate doc/buildinfo-fields-reference.rst
  .github/workflows/quick-jobs.yml
  Cabal-described/src/Distribution/Described.hs
  Makefile
  buildinfo-reference-generator/buildinfo-reference-generator.cabal
  buildinfo-reference-generator/template.zinza
  cabal.project.buildinfo
  doc/buildinfo-fields-reference.rst
Labels: merge delay passed, merge+no rebase

#9580 Use knownLanguages for describing Language
  Cabal-described/src/Distribution/Described.hs
  Cabal-syntax/src/Language/Haskell/Extension.hs
Labels: merge delay passed, merge+no rebase

#9542 Update changelog for per-component with coverage #9464
  changelog.d/pr-9464
Labels: merge me, merge delay passed

#9593 Disable flaky index-state related tests, which often fail to `curl`
  cabal-testsuite/PackageTests/NewUpdate/RejectFutureIndexStates/cabal.test.hs
  cabal-testsuite/PackageTests/NewUpdate/UpdateIndexState/update-index-state.test.hs
Labels: merge me, merge delay passed

#9557 Relax `tar` upper bound
  Cabal-tests/Cabal-tests.cabal
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/Compat/Tar.hs
  cabal-install/src/Distribution/Client/Tar.hs
  cabal-install/tests/UnitTests/Distribution/Client/Tar.hs
Labels: merge me, merge delay passed

#9597 Relax `tar` upper bound
  Cabal-tests/Cabal-tests.cabal
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/Compat/Tar.hs
  cabal-install/src/Distribution/Client/Tar.hs
  cabal-install/tests/UnitTests/Distribution/Client/Tar.hs
Labels: merge me, merge delay passed, backport

#9524 Refactor ProjectBuilding into Package Phases
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/ProjectBuilding.hs
  cabal-install/src/Distribution/Client/ProjectBuilding/PackageFileMonitor.hs
  cabal-install/src/Distribution/Client/ProjectBuilding/UnpackedPackage.hs
Labels: merge me, merge delay passed

#9568 Use printf in validate.sh for proper coloring
  validate.sh
Labels: merge me, re: devx, merge delay passed

#9561 Add validate-revision workflow
  .github/workflows/validate.yml
  CONTRIBUTING.md
Labels: merge me, merge delay passed

#9594 Ignore generated cabal.out and cabal.out''
  .gitignore
  cabal-testsuite/PackageTests/NewUpdate/RejectFutureIndexStates/.gitignore
Labels: merge delay passed, merge+no rebase

#9202 Sort the unit order for --enable-multi-repl
  cabal-install/src/Distribution/Client/CmdRepl.hs
  cabal-testsuite/PackageTests/MultiRepl/EnabledClosure/cabal.test.hs
  cabal-testsuite/PackageTests/MultiRepl/EnabledSucc/cabal.test.hs
  doc/internal/multi-repl.md
Labels: merge me, merge delay passed

#9474 Small refactor of component pre-build
  Cabal/src/Distribution/Simple/Build.hs
  Cabal/src/Distribution/Simple/Haddock.hs
Labels: merge me, merge delay passed

#9600 Build cabal-dev-scripts with ghc-9.8.1
  cabal-dev-scripts/cabal-dev-scripts.cabal
  cabal-dev-scripts/src/GenSPDX.hs
  cabal-dev-scripts/src/GenSPDXExc.hs
Labels: merge delay passed, merge+no rebase

#9611 Workaround CI for XDG directories existence
  .github/workflows/bootstrap.yml
  .github/workflows/validate.yml
Labels: continuous-integration, merge me, merge delay passed

#9469 Modularise LocalBuildInfo and configure phase
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  Cabal/Cabal.cabal
  Cabal/src/Distribution/Backpack/Configure.hs
  Cabal/src/Distribution/Simple/BuildTarget.hs
  Cabal/src/Distribution/Simple/Configure.hs
  Cabal/src/Distribution/Simple/LocalBuildInfo.hs
  Cabal/src/Distribution/Simple/Test.hs
  Cabal/src/Distribution/Simple/Test/ExeV10.hs
  Cabal/src/Distribution/Types/LocalBuildConfig.hs
  Cabal/src/Distribution/Types/LocalBuildInfo.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/ProjectPlanning/Types.hs
  cabal-install/src/Distribution/Client/Run.hs
Labels: merge me, merge delay passed

#9607 Stop logging to file when build inplace
  cabal-install/src/Distribution/Client/ProjectBuilding/UnpackedPackage.hs
Labels: merge me, merge delay passed

#9440 Account for .buildinfo in repl when build-type: Configure
  Cabal/src/Distribution/Simple.hs
  changelog.d/issue-9401
Labels: attention: needs-review, attention: needs-backport 3.10

#9604 Fix italic in README.md
  README.md
Labels: documentation, merge me, merge delay passed

#9545 Fix wording of haddock-project help and curate list of commands
  Cabal/src/Distribution/Simple/Setup/Haddock.hs
  cabal-install/src/Distribution/Client/Setup.hs
Labels: merge me, re: user experience, merge delay passed

#9555 Fix Monoid instances for ForeignLib & Executable
  Cabal-syntax/src/Distribution/Types/Executable.hs
  Cabal-syntax/src/Distribution/Types/ForeignLib.hs
  Cabal-syntax/src/Distribution/Types/UnqualComponentName.hs
Labels: merge me, merge delay passed

#9560 Add a format rejections function
  Makefile
  cabal-install-solver/src/Distribution/Solver/Modular/Message.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
  changelog.d/pr-9560
Labels: cabal-install: solver, merge delay passed, merge+no rebase

#9599 Switch from criterion to tasty-bench
  cabal-benchmarks/bench/CabalBenchmarks.hs
  cabal-benchmarks/cabal-benchmarks.cabal
Labels: attention: needs-review, merge me, merge delay passed

#9614 Test that the last line `--help` is the name of the config file
  cabal-testsuite/PackageTests/Help/HelpPrintsConfigFile/help-prints-config-file.out
  cabal-testsuite/PackageTests/Help/HelpPrintsConfigFile/help-prints-config-file.test.hs
Labels: cabal-testsuite, merge me, merge delay passed

#9615 Sed-replace CRLF files
  Cabal-tests/tests/ParserTests/regressions/haddock-api-2.18.1-check.cabal
  Cabal-tests/tests/ParserTests/regressions/issue-7776-a.cabal
  Cabal-tests/tests/ParserTests/regressions/issue-7776-b.cabal
  Cabal-tests/tests/ParserTests/regressions/issue-7776-c.cabal
  cabal-testsuite/PackageTests/NewHaddock/Fails/Example.hs
  cabal-testsuite/PackageTests/NewSdist/ManyDataFiles/Main.hs
  cabal-testsuite/PackageTests/NewSdist/ManyDataFiles/cabal.project
  cabal-testsuite/PackageTests/NewSdist/ManyDataFiles/many-data-files.cabal
  cabal-testsuite/PackageTests/NewSdist/ManyDataFiles/many-data-files.out
  cabal-testsuite/PackageTests/NewSdist/ManyDataFiles/many-data-files.test.hs
  cabal-testsuite/PackageTests/ProfLate/cabal.out
  cabal-testsuite/PackageTests/ProfLate/setup.cabal.out
  cabal-testsuite/PackageTests/ProfLate/setup.out
  changelog.d/base16-script-cache
  changelog.d/pr-9018
  changelog.d/pr-9332
Labels: priority: low, merge me, merge delay passed

#9537 Fix haddock open on windows
  bootstrap/linux-8.10.7.json
  bootstrap/linux-9.0.2.json
  bootstrap/linux-9.2.7.json
  bootstrap/linux-9.4.4.json
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/ProjectBuilding/UnpackedPackage.hs
  cabal-install/src/Distribution/Client/Utils.hs
Labels: platform: windows, platform: mac, platform: linux, attention: needs-review, platform: freebsd, platform: openbsd, merge me, re: user experience, merge delay passed, attention: needs-manual-qa, tested-on: windows

#9527 Fix extra-prog-path propagation in the codebase.
  Cabal/src/Distribution/Simple/Configure.hs
  Cabal/src/Distribution/Simple/ConfigureScript.hs
  Cabal/src/Distribution/Simple/GHC.hs
  Cabal/src/Distribution/Simple/GHCJS.hs
  Cabal/src/Distribution/Simple/Program/Db.hs
  Cabal/src/Distribution/Simple/Program/Find.hs
  Cabal/src/Distribution/Simple/Program/GHC.hs
  Cabal/src/Distribution/Simple/Program/Run.hs
  Cabal/src/Distribution/Simple/Program/Types.hs
  cabal-install/src/Distribution/Client/CmdExec.hs
  cabal-install/src/Distribution/Client/CmdInstall.hs
  cabal-install/src/Distribution/Client/CmdRun.hs
  cabal-install/src/Distribution/Client/Config.hs
  cabal-install/src/Distribution/Client/Get.hs
  cabal-install/src/Distribution/Client/HttpUtils.hs
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/src/Distribution/Client/ProjectOrchestration.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/SetupWrapper.hs
  cabal-install/src/Distribution/Client/VCS.hs
  cabal-install/tests/UnitTests/Distribution/Client/Get.hs
  cabal-install/tests/UnitTests/Distribution/Client/VCS.hs
  changelog.d/pr-9341
  changelog.d/propagate-extra-prog-path
Labels: merge me, merge delay passed, attention: needs-manual-qa, attention: needs-backport 3.10

#9619 update jinja2 per CVE-2024-22195
  doc/requirements.in
  doc/requirements.txt
Labels: merge me, merge delay passed

#9618 Include the GHC "Project Unit Id" in the cabal store path
  Cabal/src/Distribution/Simple/GHC.hs
  cabal-install/src/Distribution/Client/CmdHaddockProject.hs
  cabal-install/src/Distribution/Client/CmdInstall.hs
  cabal-install/src/Distribution/Client/DistDirLayout.hs
  cabal-install/src/Distribution/Client/PackageHash.hs
  cabal-install/src/Distribution/Client/ProjectBuilding/UnpackedPackage.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/Store.hs
  cabal-install/tests/UnitTests/Distribution/Client/Store.hs
  cabal-testsuite/src/Test/Cabal/Monad.hs
  cabal-testsuite/src/Test/Cabal/OutputNormalizer.hs
  changelog.d/pr-9326
Labels: merge me, merge delay passed

#9554 Add extraLibDirs to runtime lib search paths of library
  Cabal/src/Distribution/Simple/GHC/BuildGeneric.hs
  Cabal/src/Distribution/Simple/GHC/BuildOrRepl.hs
  Cabal/src/Distribution/Simple/Program/GHC.hs
  cabal-testsuite/PackageTests/LinkerOptions/T7339/T19350.script
  cabal-testsuite/PackageTests/LinkerOptions/T7339/clib/lib.c
  cabal-testsuite/PackageTests/LinkerOptions/T7339/lib/Hello.hs
  cabal-testsuite/PackageTests/LinkerOptions/T7339/lib/Setup.hs
  cabal-testsuite/PackageTests/LinkerOptions/T7339/lib/T7339.cabal
  cabal-testsuite/PackageTests/LinkerOptions/T7339/setup.out
  cabal-testsuite/PackageTests/LinkerOptions/T7339/setup.test.hs
Labels: merge me, merge delay passed

#9633 Add cabal-testsuite git ignores for validate dangling files
  cabal-testsuite/PackageTests/Configure/.gitignore
  cabal-testsuite/PackageTests/MultipleLibraries/T7270/.gitignore
  cabal-testsuite/PackageTests/NewBuild/CmdRun/Terminate/.gitignore
Labels: merge delay passed, merge+no rebase

#9494 Solver Hackage benchmark: Explicitly initialize cabal config files
  solver-benchmarks/HackageBenchmark.hs
Labels: cabal-install: solver, attention: needs-review, merge me, merge delay passed

#9643 Relax `containers` upper bound in `Cabal-syntax`
  Cabal-syntax/Cabal-syntax.cabal
Labels: merge me

#9609 Ignore invalid Unicode in pkg-config descriptions
  Cabal/src/Distribution/Simple/Program/Run.hs
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs
  cabal-testsuite/PackageTests/ExtraProgPath/pkg-config
  cabal-testsuite/PackageTests/PkgConfigParse/MyLibrary.hs
  cabal-testsuite/PackageTests/PkgConfigParse/cabal.project
  cabal-testsuite/PackageTests/PkgConfigParse/my.cabal
  cabal-testsuite/PackageTests/PkgConfigParse/pkg-config
  cabal-testsuite/PackageTests/PkgConfigParse/setup.out
  cabal-testsuite/PackageTests/PkgConfigParse/setup.test.hs
  changelog.d/pr-9609
Labels: attention: needs-review, squash+merge me, merge delay passed

#9644 Ignore `IntegrationTests2/config/default-config`
  cabal-install/tests/IntegrationTests2/.gitignore
  cabal-install/tests/IntegrationTests2/config/default-config
Labels: merge delay passed, merge+no rebase

#9625 Add solver Hackage benchmarks to GitHub Actions (fixes #9495)
  .github/workflows/validate.yml
Labels: cabal-install: solver, continuous-integration, merge me, merge delay passed

#9662 Cabal-syntax: Drop dependencies on unix and Win32
  Cabal-syntax/Cabal-syntax.cabal
Labels: merge me, merge delay passed

#8966 Drop file and module targets
  Cabal/src/Distribution/Simple/BuildTarget.hs
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/CmdBench.hs
  cabal-install/src/Distribution/Client/CmdBuild.hs
  cabal-install/src/Distribution/Client/CmdErrorMessages.hs
  cabal-install/src/Distribution/Client/CmdHaddock.hs
  cabal-install/src/Distribution/Client/CmdInstall.hs
  cabal-install/src/Distribution/Client/CmdInstall/ClientInstallTargetSelector.hs
  cabal-install/src/Distribution/Client/CmdListBin.hs
  cabal-install/src/Distribution/Client/CmdRepl.hs
  cabal-install/src/Distribution/Client/CmdRun.hs
  cabal-install/src/Distribution/Client/CmdSdist.hs
  cabal-install/src/Distribution/Client/CmdTest.hs
  cabal-install/src/Distribution/Client/ProjectBuilding/PackageFileMonitor.hs
  cabal-install/src/Distribution/Client/ProjectBuilding/UnpackedPackage.hs
  cabal-install/src/Distribution/Client/ProjectOrchestration.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/ProjectPlanning/Types.hs
  cabal-install/src/Distribution/Client/TargetProblem.hs
  cabal-install/src/Distribution/Client/TargetSelector.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/UnitTests.hs
  cabal-install/tests/UnitTests/Distribution/Client/ProjectPlanning.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/RunMainBad/Main.hs
  cabal-testsuite/PackageTests/NewBuild/CmdRun/RunMainBad/RunMainBad.cabal
  cabal-testsuite/PackageTests/NewBuild/CmdRun/RunMainBad/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/RunMainBad/cabal.project
  cabal-testsuite/PackageTests/NewBuild/CmdRun/RunMainBad/cabal.test.hs
  changelog.d/pr-8966
Labels: attention: needs-review, squash+merge me, merge delay passed

#9650 Don't build unnecessary targets of legacy-fallback deps.
  cabal-install/src/Distribution/Client/ProjectBuilding/UnpackedPackage.hs
  cabal-testsuite/PackageTests/Regression/T9640/CHANGELOG.md
  cabal-testsuite/PackageTests/Regression/T9640/LICENSE
  cabal-testsuite/PackageTests/Regression/T9640/cabal.out
  cabal-testsuite/PackageTests/Regression/T9640/cabal.project
  cabal-testsuite/PackageTests/Regression/T9640/cabal.test.hs
  cabal-testsuite/PackageTests/Regression/T9640/depend-on-custom-with-exe.cabal
  cabal-testsuite/PackageTests/Regression/T9640/repo/one-custom-0.1.0.0/CHANGELOG.md
  cabal-testsuite/PackageTests/Regression/T9640/repo/one-custom-0.1.0.0/Main.hs
  cabal-testsuite/PackageTests/Regression/T9640/repo/one-custom-0.1.0.0/Setup.hs
  cabal-testsuite/PackageTests/Regression/T9640/repo/one-custom-0.1.0.0/cabal.project
  cabal-testsuite/PackageTests/Regression/T9640/repo/one-custom-0.1.0.0/one-custom.cabal
  cabal-testsuite/PackageTests/Regression/T9640/repo/one-custom-0.1.0.0/src/MyLib.hs
  cabal-testsuite/PackageTests/Regression/T9640/src/MyLib.hs
Labels: merge me, merge delay passed

#9602 Refactor the core component building logic: gbuild vs buildOrReplLib
  Cabal/Cabal.cabal
  Cabal/src/Distribution/Simple/Build.hs
  Cabal/src/Distribution/Simple/Build/Inputs.hs
  Cabal/src/Distribution/Simple/GHC.hs
  Cabal/src/Distribution/Simple/GHC/Build.hs
  Cabal/src/Distribution/Simple/GHC/Build/ExtraSources.hs
  Cabal/src/Distribution/Simple/GHC/Build/Link.hs
  Cabal/src/Distribution/Simple/GHC/Build/Modules.hs
  Cabal/src/Distribution/Simple/GHC/Build/Utils.hs
  Cabal/src/Distribution/Simple/GHC/BuildGeneric.hs
  Cabal/src/Distribution/Simple/GHC/BuildOrRepl.hs
  Cabal/src/Distribution/Simple/GHC/Internal.hs
  Cabal/src/Distribution/Simple/GHCJS.hs
  Cabal/src/Distribution/Simple/Setup.hs
  Cabal/src/Distribution/Simple/Utils.hs
  cabal-testsuite/PackageTests/FFI/CSourceDependsStub/Lib.hs
  cabal-testsuite/PackageTests/FFI/CSourceDependsStub/Main.hs
  cabal-testsuite/PackageTests/FFI/CSourceDependsStub/cabal.out
  cabal-testsuite/PackageTests/FFI/CSourceDependsStub/cabal.project
  cabal-testsuite/PackageTests/FFI/CSourceDependsStub/cabal.test.hs
  cabal-testsuite/PackageTests/FFI/CSourceDependsStub/cbits/clib.c
  cabal-testsuite/PackageTests/FFI/CSourceDependsStub/csourcedepsstub.cabal
Labels: merge me, merge delay passed

#9665 Add further tests of cyclical project imports
  cabal-testsuite/PackageTests/ConditionalAndImport/bad-conditional.project
  cabal-testsuite/PackageTests/ConditionalAndImport/cabal-cyclical.project
  cabal-testsuite/PackageTests/ConditionalAndImport/cabal.out
  cabal-testsuite/PackageTests/ConditionalAndImport/cabal.test.hs
  cabal-testsuite/PackageTests/ConditionalAndImport/cyclical-0-self.project
  cabal-testsuite/PackageTests/ConditionalAndImport/cyclical-1-out-back.config
  cabal-testsuite/PackageTests/ConditionalAndImport/cyclical-1-out-back.project
  cabal-testsuite/PackageTests/ConditionalAndImport/cyclical-1-out-self.config
  cabal-testsuite/PackageTests/ConditionalAndImport/cyclical-1-out-self.project
  cabal-testsuite/PackageTests/ConditionalAndImport/cyclical-2-out-out-back-a.config
  cabal-testsuite/PackageTests/ConditionalAndImport/cyclical-2-out-out-back-b.config
  cabal-testsuite/PackageTests/ConditionalAndImport/cyclical-2-out-out-back.project
  cabal-testsuite/PackageTests/ConditionalAndImport/cyclical-2-out-out-backback-a.config
  cabal-testsuite/PackageTests/ConditionalAndImport/cyclical-2-out-out-backback-b.config
  cabal-testsuite/PackageTests/ConditionalAndImport/cyclical-2-out-out-backback.project
  cabal-testsuite/PackageTests/ConditionalAndImport/cyclical-2-out-out-self-a.config
  cabal-testsuite/PackageTests/ConditionalAndImport/cyclical-2-out-out-self-b.config
  cabal-testsuite/PackageTests/ConditionalAndImport/cyclical-2-out-out-self.project
Labels: merge delay passed, merge+no rebase

#9667 Fixup #9614: make config file extraction from help text more robust
  cabal-install/src/Distribution/Client/Main.hs
  cabal-testsuite/PackageTests/Help/HelpPrintsConfigFile/help-prints-config-file.out
  cabal-testsuite/PackageTests/Help/HelpPrintsConfigFile/help-prints-config-file.test.hs
  cabal-testsuite/src/Test/Cabal/Monad.hs
Labels: cabal-testsuite, squash+merge me, re: config-file, merge delay passed

#9634 testsuite: Fix hardcoded /bin/bash in custom-cc wrapper
  cabal-testsuite/PackageTests/CCompilerOverride/custom-cc
Labels: merge me, merge delay passed

#9661 Generate changelogs for 3.10.3.0
  Cabal-syntax/ChangeLog.md
  Cabal/ChangeLog.md
  cabal-install-solver/ChangeLog.md
  cabal-install/changelog
  changelog.d/base16-script-cache
  changelog.d/issue-6268
  changelog.d/issue-8577
  changelog.d/issue-8841
  changelog.d/issue-8843
  changelog.d/issue-8892
  changelog.d/issue-8951
  changelog.d/issue-9122
  changelog.d/issue-9401
  changelog.d/pkgconfig-envvars
  changelog.d/pr-8819
  changelog.d/pr-8878
  changelog.d/pr-8903
  changelog.d/pr-9004
  changelog.d/pr-9049
  changelog.d/pr-9068
  changelog.d/pr-9242
  changelog.d/pr-9341
  changelog.d/pr-9391
  changelog.d/pr-9503
  changelog.d/pr-9525
  changelog.d/pr-9609
  changelog.d/propagate-extra-prog-path
  release-notes/Cabal-3.10.3.0.md
  release-notes/cabal-install-3.10.3.0.md
Labels: attention: needs-review

#9679 Cabal: Allow Win32-2.14
  Cabal/Cabal.cabal
Labels: merge me, merge delay passed
