Repository haskell/cabal, pull requests merged in 2024-07, with the labels that each got.

#10145 Improve online docs for `includes:` field
  doc/cabal-package-description-file.rst
Labels: documentation, merge me, merge delay passed

#10163 haddock-project: added `--all` switch
  CONTRIBUTING.md
  Cabal/src/Distribution/Simple/Setup/Haddock.hs
  changelog.d/issue-10051
Labels: cabal-install: cmd/haddock-project

#10167 copy: Take into account extra-dyn-lib-flavours when copying bundled library
  Cabal/src/Distribution/Simple/GHC.hs
Labels: merge me, merge delay passed

#10174 fix non-POSIX [[ ]]
  validate.sh
Labels: platform: windows, merge me, merge delay passed, attention: needs-backport 3.12

#10171 Lookup main-is C sources in hs-source-dirs
  Cabal/src/Distribution/Simple/GHC/Build.hs
  Cabal/src/Distribution/Simple/GHC/Build/ExtraSources.hs
  Cabal/src/Distribution/Simple/GHC/Build/Modules.hs
  Cabal/src/Distribution/Simple/GHC/Build/Utils.hs
  cabal-testsuite/PackageTests/CMain/10168/Setup.hs
  cabal-testsuite/PackageTests/CMain/10168/app/Main.hs
  cabal-testsuite/PackageTests/CMain/10168/c-app/main.c
  cabal-testsuite/PackageTests/CMain/10168/haskell-c-tests.cabal
  cabal-testsuite/PackageTests/CMain/10168/setup.out
  cabal-testsuite/PackageTests/CMain/10168/setup.test.hs
  cabal-testsuite/PackageTests/CMain/10168/src/Lib.hs
  cabal-testsuite/PackageTests/CMain/Simple/Bar.hs
  cabal-testsuite/PackageTests/CMain/Simple/foo.c
  cabal-testsuite/PackageTests/CMain/Simple/my.cabal
  cabal-testsuite/PackageTests/CMain/Simple/setup.cabal.out
  cabal-testsuite/PackageTests/CMain/Simple/setup.out
  cabal-testsuite/PackageTests/CMain/Simple/setup.test.hs
Labels: merge me, merge delay passed

#10194 CI: don't allow-newer for GHC 9.10
  buildinfo-reference-generator/buildinfo-reference-generator.cabal
  cabal-testsuite/cabal-testsuite.cabal
  project-cabal/ghc-latest.config
Labels: attention: needs-review, squash+merge me, merge delay passed, attention: needs-backport 3.12

#10197 Fix Haddock docs for `Distribution.Types.Dependency`
  Cabal-syntax/src/Distribution/Types/Dependency.hs
Labels: squash+merge me, merge delay passed

#10198 Update cabal-commands.rst
  doc/cabal-commands.rst
Labels: squash+merge me, merge delay passed

#10195 ci(validate.yml): Allow workflow_dispatch with no allow-newer or constraints
  .github/workflows/validate.yml
  CONTRIBUTING.md
Labels: merge me, merge delay passed

#10202 ghc-latest.config: rere is up to date with GHC 9.10 now
  project-cabal/ghc-latest.config
Labels: attention: needs-review, squash+merge me, merge delay passed, attention: needs-backport 3.12

#10173 Document `program-options`
  doc/cabal-package-description-file.rst
  doc/cabal-project-description-file.rst
  doc/cabaldomain.py
  doc/config.rst
Labels: merge me, merge delay passed

#10205 make cabal-install integration tests hermetic
  .gitignore
  cabal-install/cabal-install.cabal
  cabal-install/tests/IntegrationTests2.hs
Labels: merge me, merge delay passed, attention: needs-backport 3.12, attention: needs-manual-qa

#10212 Fix ForeignLibs test for Windows
  cabal-testsuite/PackageTests/ForeignLibs/MyForeignLib.def
  cabal-testsuite/PackageTests/ForeignLibs/my-foreign-lib.cabal
  cabal-testsuite/PackageTests/ForeignLibs/setup.test.hs
Labels: merge me, merge delay passed

#10214 Fix write-ghc-environment-files documentation
  doc/cabal-project-description-file.rst
Labels: merge me, merge delay passed

#10217 Die if dynamic executable is requested on Windows
  .gitignore
  Cabal/src/Distribution/Simple/Configure.hs
  Cabal/src/Distribution/Simple/Errors.hs
  cabal-testsuite/PackageTests/NoOSSupport/DynExe/Main.hs
  cabal-testsuite/PackageTests/NoOSSupport/DynExe/a.cabal
  cabal-testsuite/PackageTests/NoOSSupport/DynExe/cabal.out
  cabal-testsuite/PackageTests/NoOSSupport/DynExe/cabal.test.hs
  cabal-testsuite/PackageTests/NoOSSupport/RelocatableExe/Main.hs
  cabal-testsuite/PackageTests/NoOSSupport/RelocatableExe/a.cabal
  cabal-testsuite/PackageTests/NoOSSupport/RelocatableExe/cabal.out
  cabal-testsuite/PackageTests/NoOSSupport/RelocatableExe/cabal.test.hs
  cabal-testsuite/src/Test/Cabal/Prelude.hs
  changelog.d/pr-10217
Labels: merge me, merge delay passed

#10092 rm-old-base: remove ifdefs for pre-4.13 bases
  .github/workflows/validate.yml
  Cabal-QuickCheck/src/Test/QuickCheck/GenericArbitrary.hs
  Cabal-QuickCheck/src/Test/QuickCheck/Instances/Cabal.hs
  Cabal-hooks/Cabal-hooks.cabal
  Cabal-syntax/Cabal-syntax.cabal
  Cabal-syntax/src/Distribution/Compat/Graph.hs
  Cabal-syntax/src/Distribution/Compat/Newtype.hs
  Cabal-syntax/src/Distribution/Compat/NonEmptySet.hs
  Cabal-syntax/src/Distribution/Compat/Prelude.hs
  Cabal-syntax/src/Distribution/Compat/Typeable.hs
  Cabal-syntax/src/Distribution/Fields/ParseResult.hs
  Cabal-syntax/src/Distribution/Parsec.hs
  Cabal-syntax/src/Distribution/System.hs
  Cabal-syntax/src/Distribution/Utils/Structured.hs
  Cabal-tests/Cabal-tests.cabal
  Cabal-tests/tests/UnitTests/Distribution/Utils/CharSet.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  Cabal-tests/tests/UnitTests/Orphans.hs
  Cabal-tests/tests/custom-setup/IdrisSetup.hs
  Cabal/Cabal.cabal
  Cabal/src/Distribution/Compat/Async.hs
  Cabal/src/Distribution/Compat/ResponseFile.hs
  Cabal/src/Distribution/Compat/Stack.hs
  Cabal/src/Distribution/Compat/Time.hs
  Makefile
  cabal-dev-scripts/cabal-dev-scripts.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/Compat/Orphans.hs
  cabal-install/src/Distribution/Client/FileMonitor.hs
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/src/Distribution/Client/ProjectOrchestration.hs
  cabal-install/src/Distribution/Client/Security/HTTP.hs
  cabal-install/src/Distribution/Client/Store.hs
  cabal-install/src/Distribution/Deprecated/ParseUtils.hs
  cabal-install/src/Distribution/Deprecated/ReadP.hs
  cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
  cabal-install/tests/UnitTests/Distribution/Client/UserConfig.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Types/OptionalStanza.hs
  cabal-testsuite/main/cabal-tests.hs
  cabal-testsuite/src/Test/Cabal/TestCode.hs
  cabal-testsuite/src/Test/Cabal/Workdir.hs
  doc/cabal-package-description-file.rst
Labels: squash+merge me, merge delay passed

#10231 Makefile: Use `cabal doctest`
  Makefile
Labels: merge me, merge delay passed
