Repository haskell/cabal, pull requests merged in 2024-09, with the labels that each got.

#10264 make sure cabal-install is compatible with Cabal
  .github/workflows/check-sdist.yml
Labels: merge me, merge delay passed, attention: needs-backport 3.12, ready and waiting

#10282 Re-enable Windows CI
  .github/workflows/validate.yml
  cabal-testsuite/PackageTests/Backpack/Includes3/cabal-external.test.hs
  validate.sh
Labels: platform: windows, continuous-integration, merge me, merge delay passed, ready and waiting

#10306 Do not advertise `git://` in docs
  doc/version-control-fields.rst
Labels: merge me, merge delay passed, ready and waiting

#10293 Support ARM / M1 macOS in `validate.sh`
  validate.sh
Labels: merge me, merge delay passed, ready and waiting

#10311 Custom-build: Document breaking change on built comps.
  release-notes/Cabal-3.12.0.0.md
Labels: merge me, merge delay passed, ready and waiting

#10315 validate.sh: `--jobs` should default to `nproc`
  validate.sh
Labels: merge me, merge delay passed, ready and waiting

#10318 `validate.sh`: Use Bash explicitly
  validate.sh
Labels: merge me, merge delay passed, ready and waiting

#10329 Fix `cabal-install:long-tests` with Git >=2.38.1
  .github/workflows/validate.yml
  cabal-install/tests/UnitTests/Distribution/Client/VCS.hs
Labels: merge me, merge delay passed, ready and waiting

#10336 Changelogs 3.14
  Cabal/ChangeLog.md
  changelog.d/configure-messages
  changelog.d/issue-10046
  changelog.d/issue-10051
  changelog.d/issue-10166
  changelog.d/issue-4816
  changelog.d/issue-4816-2
  changelog.d/issue-8817
  changelog.d/issue-9702
  changelog.d/pr-10089
  changelog.d/pr-10103
  changelog.d/pr-10115
  changelog.d/pr-10122
  changelog.d/pr-10128
  changelog.d/pr-10217
  changelog.d/pr-10240
  changelog.d/pr-10245
  changelog.d/pr-10261
  changelog.d/pr-8717
  changelog.d/pr-9177
  changelog.d/pr-9551
  changelog.d/pr-9740
  changelog.d/pr-9821
  changelog.d/pr-9969
  release-notes/Cabal-3.14.0.0.md
  release-notes/cabal-install-3.16.0.0.md
Labels: release, squash+merge me

#10333 Bump deepseq bounds to allow 1.6
  Cabal-syntax/Cabal-syntax.cabal
  Cabal/Cabal.cabal
Labels: merge me, merge delay passed, ready and waiting

#10326 Warn that scripts cannot be package executables
  doc/getting-started.rst
Labels: documentation, merge delay passed, merge+no rebase, ready and waiting

#10310 [3.14] Bump version numbers to 3.14
  Cabal-QuickCheck/Cabal-QuickCheck.cabal
  Cabal-described/Cabal-described.cabal
  Cabal-hooks/Cabal-hooks.cabal
  Cabal-syntax/Cabal-syntax.cabal
  Cabal-tree-diff/Cabal-tree-diff.cabal
  Cabal/Cabal.cabal
  bootstrap/cabal-bootstrap-gen.cabal
  bootstrap/linux-9.0.2.json
  bootstrap/linux-9.2.8.json
  bootstrap/linux-9.4.8.json
  bootstrap/linux-9.6.4.json
  bootstrap/linux-9.8.2.json
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
  cabal-testsuite/cabal-testsuite.cabal
  cabal.bootstrap.project
  cabal.release.project
  solver-benchmarks/solver-benchmarks.cabal
Labels: release, merge me

#10190 Remove read-only mark on `dist-newstyle` when doing `cabal clean` on Windows
  cabal-install/src/Distribution/Client/CmdClean.hs
  cabal-install/src/Distribution/Client/VCS.hs
  cabal-testsuite/PackageTests/NewBuild/CmdClean/CleanSourceRepositoryPackage/a.cabal
  cabal-testsuite/PackageTests/NewBuild/CmdClean/CleanSourceRepositoryPackage/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdClean/CleanSourceRepositoryPackage/cabal.project
  cabal-testsuite/PackageTests/NewBuild/CmdClean/CleanSourceRepositoryPackage/cabal.test.hs
  changelog.d/pr-10190
Labels: platform: windows, merge me, merge delay passed, ready and waiting

#10351 remove references to git protocol
  doc/cabal-package-description-file.rst
Labels: merge me

#10355 remove recomp hack
  cabal-testsuite/cabal-testsuite.cabal
Labels: merge me

#10338 Changelogs 3.14
  release-notes/Cabal-3.14.0.0.md
  release-notes/cabal-install-3.14.0.0.md
Labels: squash+merge me

#10358 Add miscellaneous changelog fixes
  Cabal-syntax/ChangeLog.md
  cabal-install-solver/ChangeLog.md
  cabal-install/changelog
  release-notes/Cabal-3.14.0.0.md
Labels: release, merge me

#10339 Add OrPatterns extensions
  Cabal-syntax/src/Language/Haskell/Extension.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  editors/vim/syntax/cabal.vim
Labels: squash+merge me, merge delay passed, ready and waiting, attention: needs-backport 3.14

#10360 Add OrPatterns extension (backport #10339)
  Cabal-syntax/src/Language/Haskell/Extension.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  editors/vim/syntax/cabal.vim
Labels: release, merge me, backport

#10341 Update SPDX license list to version 3.25
  Cabal-syntax/src/Distribution/SPDX/LicenseExceptionId.hs
  Cabal-syntax/src/Distribution/SPDX/LicenseId.hs
  Cabal-syntax/src/Distribution/SPDX/LicenseListVersion.hs
  Makefile
  cabal-dev-scripts/src/GenSPDX.hs
  cabal-dev-scripts/src/GenSPDXExc.hs
  cabal-dev-scripts/src/GenUtils.hs
  doc/file-format-changelog.rst
  license-list-data/exceptions-3.25.json
  license-list-data/licenses-3.25.json
  templates/SPDX.LicenseExceptionId.template.hs
  templates/SPDX.LicenseId.template.hs
Labels: squash+merge me, merge delay passed, ready and waiting, attention: needs-backport 3.14

#10357 Add changelogs for 3.14 (backport #10336 #10338)
  Cabal-syntax/ChangeLog.md
  Cabal/ChangeLog.md
  cabal-install-solver/ChangeLog.md
  cabal-install/changelog
  changelog.d/configure-messages
  changelog.d/issue-10046
  changelog.d/issue-10051
  changelog.d/issue-10166
  changelog.d/issue-4816
  changelog.d/issue-4816-2
  changelog.d/issue-8817
  changelog.d/issue-9702
  changelog.d/pr-10089
  changelog.d/pr-10103
  changelog.d/pr-10115
  changelog.d/pr-10122
  changelog.d/pr-10128
  changelog.d/pr-10217
  changelog.d/pr-10240
  changelog.d/pr-10245
  changelog.d/pr-10261
  changelog.d/pr-8717
  changelog.d/pr-9177
  changelog.d/pr-9551
  changelog.d/pr-9740
  changelog.d/pr-9821
  changelog.d/pr-9969
  release-notes/Cabal-3.14.0.0.md
  release-notes/cabal-install-3.14.0.0.md
Labels: release, merge me, merge delay passed, ready and waiting

#10354 changelogs are docs
  .github/workflows/bootstrap.skip.yml
  .github/workflows/bootstrap.yml
  .github/workflows/check-sdist.yml
  .github/workflows/validate.skip.yml
  .github/workflows/validate.yml
Labels: continuous-integration, attention: needs-review, merge me, merge delay passed, attention: needs-backport 3.12, attention: backport after release, ready and waiting, attention: needs-backport 3.14

#10313 Gitignore `testdb/.../lx-*.lock` files
  .gitignore
Labels: merge me, re: devx, merge delay passed, ready and waiting

#10369 make LTS branch pre-releases
  .github/workflows/validate.yml
Labels: continuous-integration, merge me, merge delay passed, ready and waiting

#10374 CI: fix-whitespace: show violations (verbose mode)
  .github/workflows/whitespace.yml
Labels: continuous-integration, merge me, merge delay passed, ready and waiting

#10353 add Mergify config for high priority PRs
  .github/mergify.yml
Labels: continuous-integration, merge me, merge delay passed, ready and waiting

#10371 add missing sdist skip job
  .github/workflows/check-sdist.skip.yml
  .github/workflows/check-sdist.yml
Labels: continuous-integration, merge me, merge delay passed, attention: needs-backport 3.12, ready and waiting, attention: needs-backport 3.14

#10327 Add warning and note about cabal init and script
  doc/getting-started.rst
Labels: merge delay passed, merge+no rebase, ready and waiting

#10382 Fix `--accept` flag in `cabal-testsuite`
  cabal-testsuite/src/Test/Cabal/Monad.hs
Labels: merge me, merge delay passed, ready and waiting

#10363 try Apple AArch64 again
  .github/workflows/validate.yml
Labels: platform: mac, continuous-integration, merge me, merge delay passed, attention: needs-backport 3.12, ready and waiting, attention: needs-backport 3.14

#10330 Point out `validate.sh` more prominently in `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: merge me, merge delay passed, ready and waiting

#10376 add Makefile targets for fix-whitespace
  .github/workflows/whitespace.yml
  CONTRIBUTING.md
  Makefile
Labels: merge me, merge delay passed, ready and waiting

#10395 Filter `CommonSetupFlags` more consistently in `UnpackedPackage`
  cabal-install/src/Distribution/Client/ProjectBuilding/UnpackedPackage.hs
  cabal-install/src/Distribution/Client/Setup.hs
Labels: merge me, merge delay passed, merge+no rebase, ready and waiting

#10389 Fix `withFileContents` documentation (lazy IO strikes again)
  Cabal-syntax/src/Distribution/Utils/Generic.hs
Labels: merge me, merge delay passed, merge+no rebase, ready and waiting

#10383 update changelog.d format and Matrix link
  CONTRIBUTING.md
Labels: squash+merge me, merge delay passed, ready and waiting
