Repository haskell/cabal, pull requests merged in 2025-06, with the labels that each got.

#10976 test suite: mark DedupUsingConfigFromSimple as flaky
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromSimple/cabal.test.hs
Labels: priority: high :fire:, continuous-integration, attention: needs-review, cabal-testsuite, merge me, merge delay passed, ready and waiting

#10840 Implement v2-gen-bounds function
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/CmdGenBounds.hs
  cabal-install/src/Distribution/Client/Errors.hs
  cabal-install/src/Distribution/Client/GenBounds.hs
  cabal-install/src/Distribution/Client/Main.hs
  cabal-testsuite/PackageTests/GenBounds/Issue6290/cabal.out
  cabal-testsuite/PackageTests/GenBounds/Issue7504/cabal.project
  cabal-testsuite/PackageTests/GenBounds/Issue7504/cabal.test.hs
  cabal-testsuite/PackageTests/GenBounds/Issue7504/package-a/LICENSE
  cabal-testsuite/PackageTests/GenBounds/Issue7504/package-a/package-a.cabal
  cabal-testsuite/PackageTests/GenBounds/Issue7504/package-a/src/ModuleA.hs
  cabal-testsuite/PackageTests/GenBounds/Issue7504/package-b/LICENSE
  cabal-testsuite/PackageTests/GenBounds/Issue7504/package-b/exe/Main.hs
  cabal-testsuite/PackageTests/GenBounds/Issue7504/package-b/package-b.cabal
  cabal-testsuite/PackageTests/GenBounds/Issue7504/package-b/src/ModuleB.hs
  changelog.d/pr-10840.md
  doc/cabal-commands.rst
Labels: merge me, cabal-install: cmd/gen-bounds, merge delay passed, ready and waiting

#10880 multi-repl: Support module renaming for ghc-9.12 onwards
  Cabal/src/Distribution/Simple/Compiler.hs
  Cabal/src/Distribution/Simple/Errors.hs
  Cabal/src/Distribution/Simple/GHC/Build/Link.hs
  cabal-testsuite/PackageTests/MultiRepl/ReexportedModule/cabal.project
  cabal-testsuite/PackageTests/MultiRepl/ReexportedModule/cabal.test.hs
  cabal-testsuite/PackageTests/MultiRepl/ReexportedModule/package-a/CHANGELOG.md
  cabal-testsuite/PackageTests/MultiRepl/ReexportedModule/package-a/package-a.cabal
  cabal-testsuite/PackageTests/MultiRepl/ReexportedModule/package-a/src/PackageA.hs
  cabal-testsuite/PackageTests/MultiRepl/ReexportedModule/package-b/CHANGELOG.md
  cabal-testsuite/PackageTests/MultiRepl/ReexportedModule/package-b/package-b.cabal
  cabal-testsuite/PackageTests/MultiRepl/ReexportedModule/package-b/src/PackageB.hs
  changelog.d/pr-10880.md
Labels: merge me, merge delay passed, ready and waiting

#10688 Add cfgVerbosity
  cabal-install/src/Distribution/Client/CmdBench.hs
  cabal-install/src/Distribution/Client/CmdBuild.hs
  cabal-install/src/Distribution/Client/CmdConfigure.hs
  cabal-install/src/Distribution/Client/CmdExec.hs
  cabal-install/src/Distribution/Client/CmdFreeze.hs
  cabal-install/src/Distribution/Client/CmdGenBounds.hs
  cabal-install/src/Distribution/Client/CmdHaddock.hs
  cabal-install/src/Distribution/Client/CmdHaddockProject.hs
  cabal-install/src/Distribution/Client/CmdInstall.hs
  cabal-install/src/Distribution/Client/CmdListBin.hs
  cabal-install/src/Distribution/Client/CmdOutdated.hs
  cabal-install/src/Distribution/Client/CmdPath.hs
  cabal-install/src/Distribution/Client/CmdRepl.hs
  cabal-install/src/Distribution/Client/CmdRun.hs
  cabal-install/src/Distribution/Client/CmdTest.hs
  cabal-install/src/Distribution/Client/CmdUpdate.hs
  cabal-install/src/Distribution/Client/NixStyleOptions.hs
  cabal-install/src/Distribution/Client/ScriptUtils.hs
  cabal-testsuite/PackageTests/HaddockProject/haddock-project.out
Labels: merge delay passed, merge+no rebase, ready and waiting

#10979 Fix parsing AbiTag for development compilers
  Cabal/src/Distribution/Simple/GHC.hs
  Cabal/src/Distribution/Simple/Utils.hs
  changelog.d/pr-10979
Labels: merge me, merge delay passed, ready and waiting

#10999 bootstrap.py: fix incomplete reads when fetching from Hackage
  bootstrap/bootstrap.py
Labels: priority: high :fire:, continuous-integration, cabal-install: bootstrap, squash+merge me, merge delay passed, ready and waiting

#10990 Make ‘cabal exec’ not pass -package-env to called executable
  cabal-install/src/Distribution/Client/CmdExec.hs
  cabal-testsuite/PackageTests/ExecCommand/Main.hs
  cabal-testsuite/PackageTests/ExecCommand/cabal.out
  cabal-testsuite/PackageTests/ExecCommand/cabal.project
  cabal-testsuite/PackageTests/ExecCommand/cabal.test.hs
  cabal-testsuite/PackageTests/ExecCommand/my.cabal
  changelog.d/pr-10828.md
  changelog.d/pr-10830.md
  release-notes/Cabal-3.14.2.0.md
Labels: merge me, merge delay passed, ready and waiting

#11011 Preflight checks for 3.16
  Cabal-QuickCheck/Cabal-QuickCheck.cabal
  Cabal-hooks/Cabal-hooks.cabal
  Cabal-syntax/Cabal-syntax.cabal
  Cabal/Cabal.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
Labels: priority: high :fire:, release, merge me, merge delay passed, ready and waiting

#10985 Docs: fix the detailed-0.9 example
  doc/cabal-package-description-file.rst
Labels: newcomer: 1-one-line-change, merge me, merge delay passed, ready and waiting, waiting too long

#11014 add SPDX license data version 3.26
  Cabal-syntax/src/Distribution/SPDX/LicenseExceptionId.hs
  Cabal-syntax/src/Distribution/SPDX/LicenseId.hs
  Cabal-syntax/src/Distribution/SPDX/LicenseListVersion.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  Makefile
  cabal-dev-scripts/src/GenSPDX.hs
  cabal-dev-scripts/src/GenSPDXExc.hs
  cabal-dev-scripts/src/GenUtils.hs
  changelog.d/pr-11014
  license-list-data/exceptions-3.26.json
  license-list-data/licenses-3.26.json
  templates/SPDX.LicenseExceptionId.template.hs
  templates/SPDX.LicenseId.template.hs
Labels: priority: high :fire:, squash+merge me, merge delay passed, ready and waiting

#11024 bump index state to get new `hackage-security`
  cabal.bootstrap.project
  cabal.release.project
  cabal.validate.project
Labels: priority: high :fire:, merge me, merge delay passed, ready and waiting

#11015 try out merge queues
  .github/mergify.yml
Labels: merge me, merge delay passed, ready and waiting
