Repository haskell/cabal, pull requests merged in 2025-08, with the labels that each got.

#11093 Apply hlint suggestions with a single count
  .hlint.yaml
  Cabal-syntax/src/Distribution/Compat/Parsing.hs
  Cabal-tests/tests/UnitTests/Distribution/Version.hs
  Cabal/src/Distribution/Simple/BuildPaths.hs
  Cabal/src/Distribution/Simple/Configure.hs
  Cabal/src/Distribution/Simple/GHCJS.hs
  Cabal/src/Distribution/Simple/Haddock.hs
  cabal-install/src/Distribution/Client/BuildReports/Upload.hs
  cabal-install/src/Distribution/Client/CmdOutdated.hs
  cabal-install/src/Distribution/Client/CmdRepl.hs
  cabal-install/src/Distribution/Client/ProjectOrchestration.hs
  cabal-install/src/Distribution/Client/ProjectPlanOutput.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/Run.hs
  cabal-install/src/Distribution/Client/Utils.hs
  cabal-install/src/Distribution/Deprecated/ViewAsFieldDescr.hs
Labels: merge me, merge delay passed, ready and waiting

#11068 try Ubuntu 24.04 again
  .github/workflows/validate.yml
Labels: merge me, merge delay passed, ready and waiting

#11127 update `time` to 1.15
  Cabal-syntax/Cabal-syntax.cabal
  Cabal/Cabal.cabal
  cabal-install/cabal-install.cabal
Labels: merge me, merge delay passed, ready and waiting

#11072 Rewrite release CI
  .github/actions/download/action.yml
  .github/actions/upload/action.yml
  .github/scripts/build.bash
  .github/scripts/test.bash
  .github/workflows/release.yaml
  .github/workflows/reusable-release.yml
  cabal-install-solver/cabal-install-solver.cabal
  cabal.release.project
  scripts/release/create-release-metadata-for-ghcup.sh
  scripts/release/download-cabal-install-release-binaries.sh
  scripts/release/download-gh-artifacts.sh
  scripts/release/upload-artifacts.sh
Labels: continuous-integration, merge me, merge delay passed, ready and waiting, run release build

#11146 Only enable FreeBSD private runner on demand
  .github/workflows/reusable-release.yml
Labels: priority: high :fire:, merge me, merge delay passed, run release build

#11141 docs: explicitly list programs known to Cabal (fix #7899)
  Cabal/src/Distribution/Simple/Program/Builtin.hs
  doc/setup-commands.rst
Labels: documentation, merge me, merge delay passed, ready and waiting

#11150 HLint list literals
  .hlint.yaml
  Cabal-syntax/src/Distribution/ModuleName.hs
  Cabal-syntax/src/Distribution/Types/Version.hs
  Cabal-syntax/src/Distribution/Types/VersionRange.hs
  Cabal/src/Distribution/GetOpt.hs
  Cabal/src/Distribution/Simple/Program/GHC.hs
  Cabal/src/Distribution/Simple/Utils.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
  cabal-install/src/Distribution/Client/ProjectOrchestration.hs
  cabal-install/src/Distribution/Client/VCS.hs
Labels: merge me, merge delay passed, ready and waiting

#11171 Fix docs, `PackageInfo_*` modules and `cabal-version: 3.12`
  doc/file-format-changelog.rst
Labels: attention: needs-review, merge me, merge delay passed, ready and waiting, attention: needs-backport 3.16

#11181 Remove undesirable warnings about duplicate configs.
  cabal-install/src/Distribution/Client/CmdPath.hs
  cabal-install/src/Distribution/Client/Config.hs
  cabal-install/src/Distribution/Client/Main.hs
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
Labels: squash+merge me, merge delay passed, ready and waiting

#11190 Fix haddock typo: coversion
  cabal-testsuite/src/Test/Cabal/NeedleHaystack.hs
Labels: merge me, merge delay passed, ready and waiting

#11189 HLint: use first and use second
  .hlint.yaml
  Cabal-syntax/src/Distribution/Compat/Graph.hs
  Cabal/src/Distribution/Simple/BuildTarget.hs
  Cabal/src/Distribution/Utils/MapAccum.hs
  cabal-install/src/Distribution/Client/IndexUtils/ActiveRepos.hs
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/src/Distribution/Client/ProjectOrchestration.hs
  cabal-install/src/Distribution/Client/TargetSelector.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/Builder.hs
Labels: merge me, merge delay passed, ready and waiting

#10982 Support reinstalling more packages (including base and template-haskell) with GHC >=9.14
  Cabal-syntax/src/Distribution/Compiler.hs
  Cabal-tests/tests/UnitTests/Distribution/Simple/Program/GHC.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  Cabal/src/Distribution/Simple/Compiler.hs
  Cabal/src/Distribution/Simple/GHC.hs
  Cabal/src/Distribution/Simple/GHCJS.hs
  Cabal/src/Distribution/Simple/UHC.hs
  cabal-install-solver/src/Distribution/Solver/Modular/Message.hs
  cabal-install-solver/src/Distribution/Solver/Modular/Package.hs
  cabal-install-solver/src/Distribution/Solver/Modular/Preference.hs
  cabal-install-solver/src/Distribution/Solver/Modular/Tree.hs
  cabal-install-solver/src/Distribution/Solver/Types/PackageConstraint.hs
  cabal-install/src/Distribution/Client/Dependency.hs
  cabal-install/tests/UnitTests/Distribution/Client/Store.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL/TestCaseUtils.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
  cabal-testsuite/Setup.hs
  changelog.d/pr-10982
Labels: cabal-install: solver, merge me, merge delay passed, ready and waiting

#10609 Fix mistake in BuildInfo.Lens.hs
  Cabal-syntax/src/Distribution/Types/BuildInfo/Lens.hs
  changelog.d/pr-10609
Labels: priority: high :fire:, merge me, merge delay passed
