Repository haskell/cabal, pull requests merged in 2025-04, with the labels that each got.

#10873 exporting FileLike and PathLike
  Cabal-syntax/src/Distribution/Utils/Path.hs
Labels: merge me, merge delay passed, ready and waiting

#10895 Preflight checks
  Cabal-hooks/Cabal-hooks.cabal
  cabal-install/cabal-install.cabal
Labels: release, squash+merge me, ready and waiting

#10899 Backport #10895: Preflight checks
  Cabal-hooks/Cabal-hooks.cabal
  cabal-install/cabal-install.cabal
Labels: squash+merge me, backport

#10903 Backport #10895: Preflight checks
  cabal-install/cabal-install.cabal
Labels: merge me, backport

#10849 Switch cabal-install changelog to Markdown
  cabal-install/ChangeLog.md
  cabal-install/cabal-install.cabal
  cabal-install/changelog
Labels: squash+merge me, merge delay passed, ready and waiting, waiting too long

#10904 Bump version fields of main packages to 3.14.2.0
  Cabal-hooks/Cabal-hooks.cabal
  Cabal-syntax/Cabal-syntax.cabal
  Cabal/Cabal.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
  doc/conf.py
Labels: release, merge me, merge delay passed, don't backport

#10894 Add release notes for 3.14.2.0 release
  Cabal-hooks/CHANGELOG.md
  Cabal-syntax/ChangeLog.md
  Cabal/ChangeLog.md
  cabal-install-solver/ChangeLog.md
  cabal-install/changelog
  changelog.d/pr-10493
  changelog.d/pr-10546
  changelog.d/pr-10554
  changelog.d/pr-10616
  changelog.d/pr-10725
  changelog.d/pr-10728
  changelog.d/pr-10730
  changelog.d/pr-10731
  changelog.d/pr-10783
  changelog.d/pr-10800
  changelog.d/pr-10826
  changelog.d/pr-10827.md
  changelog.d/pr-10828.md
  changelog.d/pr-10841.md
  changelog.d/pr-9997
  changelog.d/solver-api-change-fixup-3.14
  release-notes/Cabal-3.14.0.0.md
  release-notes/Cabal-3.14.2.0.md
  release-notes/cabal-install-3.14.2.0.md
Labels: release, merge me, merge delay passed, attention: needs-backport master

#10892 Fix docs: extensions field was deprecated in Cabal 1.10, not 1.12
  doc/cabal-package-description-file.rst
Labels: merge me, merge delay passed, ready and waiting

#10896 Bump `cabal-version`
  Cabal-hooks/Cabal-hooks.cabal
  Cabal-syntax/Cabal-syntax.cabal
  Cabal/Cabal.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
Labels: merge me, merge delay passed, ready and waiting

#10830 Set <pkgname_datadir> to an absolute path
  Cabal/src/Distribution/Simple/Bench.hs
  Cabal/src/Distribution/Simple/Build.hs
  Cabal/src/Distribution/Simple/Haddock.hs
  Cabal/src/Distribution/Simple/Test.hs
  cabal-install/src/Distribution/Client/Run.hs
  cabal-testsuite/PackageTests/DataDirSetupTest/Setup.hs
  cabal-testsuite/PackageTests/DataDirSetupTest/cabal.cabal.out
  cabal-testsuite/PackageTests/DataDirSetupTest/cabal.out
  cabal-testsuite/PackageTests/DataDirSetupTest/cabal.test.hs
  cabal-testsuite/PackageTests/DataDirSetupTest/datadir-test.cabal
  cabal-testsuite/PackageTests/DataDirSetupTest/src/MyLib.hs
  cabal-testsuite/PackageTests/DataDirSetupTest/test/DataDirTest.hs
  cabal-testsuite/PackageTests/DataDirSetupTest/testdata/sample.txt
  changelog.d/pr-10830.md
Labels: merge me, merge delay passed, ready and waiting, regression in 3.14, don't backport

#10847 Take format specification history back to Cabal-1.0
  doc/file-format-changelog.rst
Labels: merge me, merge delay passed, ready and waiting

#10908 Drop the dead build-tool greencard
  Cabal/src/Distribution/Simple/BuildToolDepends.hs
  Cabal/src/Distribution/Simple/PreProcess.hs
  Cabal/src/Distribution/Simple/Program.hs
  Cabal/src/Distribution/Simple/Program/Builtin.hs
  cabal-install/src/Distribution/Client/Init/Utils.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-testsuite/PackageTests/AutogenModules/Package/setup.cabal.out
  cabal-testsuite/PackageTests/AutogenModules/Package/setup.out
  changelog.d/pr-10908.md
  doc/cabal-package-description-file.rst
  doc/config.rst
  test/IntegrationTests2/config/default-config
  test/IntegrationTests2/nix-config/default-config
  tests/IntegrationTests2/config/default-config
  tests/IntegrationTests2/nix-config/default-config
Labels: squash+merge me, re: build-tool, merge delay passed, ready and waiting

#10913 Add contributing instructions for gh users
  CONTRIBUTING.md
Labels: documentation, squash+merge me, re: devx, merge delay passed, ready and waiting

#10893 ci: Use ghc-9.12.2 and ghc-9.6.7
  .github/workflows/validate.yml
Labels: continuous-integration, merge me, merge delay passed, ready and waiting

#10844 Pass CXX and CXXFLAGS argument to ./configure scripts for build-type: Configure
  Cabal/src/Distribution/Simple/ConfigureScript.hs
  Cabal/src/Distribution/Simple/GHC/Internal.hs
  Cabal/src/Distribution/Simple/Program.hs
  Cabal/src/Distribution/Simple/Program/Builtin.hs
  cabal-testsuite/PackageTests/ConfigureCXX/CHANGELOG.md
  cabal-testsuite/PackageTests/ConfigureCXX/ConfigureCXX.cabal
  cabal-testsuite/PackageTests/ConfigureCXX/Setup.hs
  cabal-testsuite/PackageTests/ConfigureCXX/cabal.out
  cabal-testsuite/PackageTests/ConfigureCXX/cabal.test.hs
  cabal-testsuite/PackageTests/ConfigureCXX/configure
  cabal-testsuite/PackageTests/ConfigureCXX/hello.c
  cabal-testsuite/PackageTests/ConfigureCXX/hello.cpp
  cabal-testsuite/PackageTests/ConfigureCXX/src/MyLib.hs
  changelog.d/pr-10844.md
  doc/cabal-package-description-file.rst
Labels: attention: needs-review, merge me, merge delay passed, ready and waiting

#10816 Add module name validation in cabal check command
  Cabal/src/Distribution/PackageDescription/Check/Paths.hs
  Cabal/src/Distribution/PackageDescription/Check/Target.hs
  cabal-testsuite/PackageTests/Check/InvalidModuleName/InvalidModuleName.cabal
  cabal-testsuite/PackageTests/Check/InvalidModuleName/LICENSE
  cabal-testsuite/PackageTests/Check/InvalidModuleName/bench/.file
  cabal-testsuite/PackageTests/Check/InvalidModuleName/cabal.out
  cabal-testsuite/PackageTests/Check/InvalidModuleName/cabal.test.hs
  cabal-testsuite/PackageTests/Check/InvalidModuleName/exe/.file
  cabal-testsuite/PackageTests/Check/InvalidModuleName/src/.file
  cabal-testsuite/PackageTests/Check/InvalidModuleName/test/.file
  changelog.d/pr-10816.md
Labels: merge me, merge delay passed, ready and waiting

#10919 Fix call convention warnings for AArch64
  Cabal/src/Distribution/Compat/GetShortPathName.hs
  Cabal/src/Distribution/Compat/Time.hs
  Cabal/src/Distribution/Simple/InstallDirs.hs
  cabal-install/src/Distribution/Client/Win32SelfUpgrade.hs
Labels: merge me, merge delay passed, ready and waiting

#10907 Allow building foreign libraries on FreeBSD
  Cabal/src/Distribution/Simple/Configure.hs
Labels: merge me, merge delay passed, ready and waiting

#10837 testsuite: Supress stderr when running integration tests
  cabal-install/cabal-install.cabal
  cabal-install/tests/IntegrationTests2.hs
Labels: merge me, merge delay passed, ready and waiting

#10912 Remove knowledge about haskell-suite and hmake
  Cabal-syntax/src/Distribution/Compiler.hs
  Cabal-syntax/src/Language/Haskell/Extension.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  Cabal/Cabal.cabal
  Cabal/src/Distribution/Simple/Build.hs
  Cabal/src/Distribution/Simple/Configure.hs
  Cabal/src/Distribution/Simple/Errors.hs
  Cabal/src/Distribution/Simple/HaskellSuite.hs
  Cabal/src/Distribution/Simple/Install.hs
  Cabal/src/Distribution/Simple/PreProcess.hs
  Cabal/src/Distribution/Simple/Program.hs
  Cabal/src/Distribution/Simple/Program/Builtin.hs
  Cabal/src/Distribution/Simple/Register.hs
  Cabal/src/Distribution/Simple/Setup/Config.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/IntegrationTests2/nix-config/nix-false
  cabal-install/tests/IntegrationTests2/nix-config/nix-true
  changelog.d/pr-10912.md
  doc/cabal-project-description-file.rst
  doc/config.rst
  test/IntegrationTests2/config/default-config
  test/IntegrationTests2/nix-config/default-config
  tests/IntegrationTests2/config/default-config
  tests/IntegrationTests2/nix-config/default-config
Labels: squash+merge me, merge delay passed, ready and waiting, API change

#9695 Fix #9694 Don't imply that Haddock docs exist, when warning not installed
  Cabal/src/Distribution/Simple/Haddock.hs
  changelog.d/issue-9694
Labels: merge me, ready and waiting

#10091 Removes a smattering of, apparent, dead code
  Cabal-described/src/Distribution/Described.hs
  Cabal-described/src/Distribution/Utils/CharSet.hs
  Cabal-tests/Cabal-tests.cabal
  Cabal-tests/tests/Test/QuickCheck/Utils.hs
  cabal-benchmarks/bench/CabalBenchmarks.hs
Labels: merge me, merge delay passed, ready and waiting

#10932 Mark dedup complex test as flaky
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/cabal.test.hs
Labels: merge delay passed, merge+no rebase, ready and waiting

#10929 bootstrap/bootstrap.py: Added support for multithreaded builds
  bootstrap/bootstrap.py
Labels: merge me, merge delay passed, ready and waiting

#10936 Print out the "Created semaphore" message only in verbose mode
  cabal-install/src/Distribution/Client/JobControl.hs
  changelog.d/pr-10936.md
Labels: squash+merge me, merge delay passed, ready and waiting

#10792 Clarify splitting/passing behaviour for --*-option(s) arguments
  Cabal/src/Distribution/Simple/Setup/Benchmark.hs
  Cabal/src/Distribution/Simple/Setup/Common.hs
  Cabal/src/Distribution/Simple/Setup/Test.hs
  doc/cabal-commands.rst
  doc/setup-commands.rst
Labels: attention: needs-review, squash+merge me, merge delay passed, ready and waiting

#10735 Implement assert matches with assert on
  cabal-testsuite/AssertTests/cabal.out
  cabal-testsuite/AssertTests/cabal.test.hs
  cabal-testsuite/AssertTests/msg.expect.txt
  cabal-testsuite/PackageTests/CheckSetup/setup.test.hs
  cabal-testsuite/PackageTests/ConditionalAndImport/cabal.test.hs
  cabal-testsuite/PackageTests/NewBuild/T4288/cabal.test.hs
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/cabal.test.hs
  cabal-testsuite/PackageTests/ProjectImport/ParseErrorProvenance/cabal.out
  cabal-testsuite/PackageTests/ProjectImport/ParseErrorProvenance/cabal.test.hs
  cabal-testsuite/PackageTests/Regression/T5409/use-different-versions-of-dependency-for-library-and-build-tool.test.hs
  cabal-testsuite/src/Test/Cabal/NeedleHaystack.hs
  cabal-testsuite/src/Test/Cabal/Prelude.hs
Labels: merge delay passed, merge+no rebase, ready and waiting
