Repository haskell/cabal, pull requests merged in 2025-02, with the labels that each got.

#10776 Fix casing of extra-source-files in Cabal-hooks
  Cabal-hooks/Cabal-hooks.cabal
Labels: priority: high :fire:, merge delay passed, merge+no rebase, ready and waiting

#10793 Add PR size guidelines
  CONTRIBUTING.md
Labels: merge me, merge delay passed, ready and waiting

#10798 docs/conf.py: bump project development version
  doc/conf.py
Labels: documentation, priority: high :fire:, merge me, merge delay passed, ready and waiting

#10693 fix static builds lacking git info
  .github/workflows/validate.yml
  Cabal/src/Distribution/Simple/Utils.hs
  cabal-install/src/Distribution/Client/Version.hs
Labels: priority: high :fire:, merge me, merge delay passed, ready and waiting
