Repository haskell/cabal, pull requests merged in 2025-07, with the labels that each got.

#11037 adjust versions for 3.16.0.0 release
  Cabal-QuickCheck/Cabal-QuickCheck.cabal
  Cabal-described/Cabal-described.cabal
  Cabal-hooks/Cabal-hooks.cabal
  Cabal-syntax/Cabal-syntax.cabal
  Cabal-tree-diff/Cabal-tree-diff.cabal
  Cabal/Cabal.cabal
  Cabal/Makefile
  bootstrap/linux-9.10.2.json
  bootstrap/linux-9.12.2.json
  bootstrap/linux-9.2.8.json
  bootstrap/linux-9.4.8.json
  bootstrap/linux-9.6.7.json
  bootstrap/linux-9.8.4.json
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
  cabal-testsuite/cabal-testsuite.cabal
  doc/conf.py
  solver-benchmarks/solver-benchmarks.cabal
Labels: priority: high :fire:, merge me, merge delay passed

#11018 add paragraph mentioning stackage
  doc/cabal-project-description-file.rst
  doc/nix-local-build.rst
Labels: documentation, merge me, merge delay passed, ready and waiting

#11038 missed version bumps
  Cabal/Makefile
  doc/conf.py
Labels: merge me, merge delay passed, ready and waiting

#11039 adjust Mergify queue rules for release branches
  .github/mergify.yml
Labels: continuous-integration, merge me, merge delay passed, ready and waiting

#10854 Refactor cabal-install solver config log output
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install-solver/src/Distribution/Solver/Modular.hs
  cabal-install-solver/src/Distribution/Solver/Modular/Log.hs
  cabal-install-solver/src/Distribution/Solver/Modular/Message.hs
  cabal-install-solver/src/Distribution/Solver/Types/DependencyResolver.hs
  cabal-install-solver/src/Distribution/Solver/Types/SummarizedMessage.hs
  cabal-install/src/Distribution/Client/Dependency.hs
  changelog.d/pr-10854
Labels: cabal-install: solver, merge me, merge delay passed, ready and waiting

#11033 Add 3.16 changelogs
  Cabal-hooks/CHANGELOG.md
  Cabal-syntax/ChangeLog.md
  Cabal/ChangeLog.md
  cabal-install-solver/ChangeLog.md
  cabal-install/ChangeLog.md
  changelog.d/issue-9115.md
  changelog.d/issue-9694
  changelog.d/pr-10190
  changelog.d/pr-10254
  changelog.d/pr-10273
  changelog.d/pr-10356
  changelog.d/pr-10432
  changelog.d/pr-10525
  changelog.d/pr-10549
  changelog.d/pr-10587
  changelog.d/pr-10590
  changelog.d/pr-10629
  changelog.d/pr-10637
  changelog.d/pr-10644.md
  changelog.d/pr-10646.md
  changelog.d/pr-10647
  changelog.d/pr-10705
  changelog.d/pr-10805.md
  changelog.d/pr-10816.md
  changelog.d/pr-10817
  changelog.d/pr-10828.md
  changelog.d/pr-10830.md
  changelog.d/pr-10840.md
  changelog.d/pr-10844.md
  changelog.d/pr-10880.md
  changelog.d/pr-10908.md
  changelog.d/pr-10912.md
  changelog.d/pr-10936.md
  changelog.d/pr-10940
  changelog.d/pr-10941
  changelog.d/pr-10948.md
  changelog.d/pr-10949.md
  changelog.d/pr-10966.md
  changelog.d/pr-10967.md
  changelog.d/pr-10979
  changelog.d/pr-10991.md
  changelog.d/pr-10992.md
  changelog.d/pr-11003.md
  changelog.d/pr-11014
  changelog.d/pr-9367
  changelog.d/pr-9744.md
  changelog.d/pr-9890
  release-notes/Cabal-3.16.0.0.md
  release-notes/WIP-Cabal-3.16.x.0.md
  release-notes/cabal-install-3.16.0.0.md
Labels: release, squash+merge me, attention: needs-backport master

#11047 Capitalise “AArch” properly
  Cabal/src/Distribution/Simple/Build/PathsModule.hs
  Cabal/src/Distribution/Simple/Build/PathsModule/Z.hs
  cabal-dev-scripts/src/GenPathsModule.hs
  changelog.d/pr-10705
  templates/Paths_pkg.template.hs
Labels: release, merge me, merge delay passed, ready and waiting, attention: needs-backport 3.16

#11057 Backport #11047: Capitalise “AArch” properly
  Cabal/src/Distribution/Simple/Build/PathsModule.hs
  Cabal/src/Distribution/Simple/Build/PathsModule/Z.hs
  cabal-dev-scripts/src/GenPathsModule.hs
  templates/Paths_pkg.template.hs
Labels: release, merge me

#11042 Allow relocatable builds on FreeBSD
  Cabal/src/Distribution/Simple/Configure.hs
  changelog.d/pr-11042
Labels: merge me, merge delay passed, ready and waiting

#11061 missed updating all the copyrights in the cabal files
  Cabal-hooks/Cabal-hooks.cabal
  Cabal-syntax/Cabal-syntax.cabal
  Cabal-tests/Cabal-tests.cabal
  Cabal/Cabal.cabal
  cabal-benchmarks/cabal-benchmarks.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
  cabal-testsuite/cabal-testsuite.cabal
  cabal-validate/cabal-validate.cabal
  solver-benchmarks/solver-benchmarks.cabal
Labels: priority: high :fire:, attention: needs-review, merge me, merge delay passed, attention: needs-backport 3.16

#11006 First draft of the cabal-proposals process
  CONTRIBUTING.md
  README.md
  proposals.md
Labels: squash+merge me, merge delay passed, ready and waiting

#11067 cabal update: don't show comment with builddir in the default config
  cabal-install/src/Distribution/Client/Config.hs
  cabal-install/tests/IntegrationTests2.hs
  changelog.d/pr-11067
Labels: cabal-install: cmd/update, merge me, re: config-file, merge delay passed, ready and waiting

#11076 Fix typo exsting
  doc/cabaldomain.py
Labels: documentation, merge delay passed, merge+no rebase, ready and waiting

#11082 Bump to hlint-3.10
  .github/workflows/lint.yml
  .hlint.yaml
Labels: merge delay passed, merge+no rebase, ready and waiting

#11094 Typo in Makefile .PHONY target
  Makefile
Labels: merge me, merge delay passed, ready and waiting

#11095 Update Hackage root keys
  cabal-install/src/Distribution/Client/Config.hs
  changelog.d/pr-11095.md
Labels: merge me, merge delay passed, ready and waiting

#11110 Fix typos in release script comments
  scripts/release/create-release-metadata-for-ghcup.sh
  scripts/release/download-cabal-install-release-binaries.sh
Labels: merge me, merge delay passed, ready and waiting
