Repository haskell/cabal, pull requests merged in 2025-05, with the labels that each got.

#10941 Add Haddock documentation to Cabal's autogen modules
  Cabal/src/Distribution/Simple/Build/PackageInfoModule/Z.hs
  Cabal/src/Distribution/Simple/Build/PathsModule/Z.hs
  changelog.d/pr-10941
  doc/cabal-package-description-file.rst
  templates/Paths_pkg.template.hs
Labels: merge me, merge delay passed, ready and waiting

#10952 Mark untrimmed import test as flaky
  cabal-testsuite/PackageTests/ProjectImport/UntrimmedImport/cabal.test.hs
Labels: priority: high :fire:, merge me, merge delay passed, ready and waiting

#10948 Make `Flag a` a type synonym for `Last (Maybe a)`
  Cabal-QuickCheck/src/Test/QuickCheck/Instances/Cabal.hs
  Cabal-syntax/src/Distribution/Utils/Structured.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
  Cabal-tree-diff/src/Data/TreeDiff/Instances/Cabal.hs
  Cabal/src/Distribution/Backpack/Id.hs
  Cabal/src/Distribution/Simple/Flag.hs
  Cabal/src/Distribution/Simple/GHC/Internal.hs
  Cabal/src/Distribution/Simple/Setup.hs
  Cabal/src/Distribution/Simple/Setup/Common.hs
  cabal-install/src/Distribution/Client/CmdBuild.hs
  cabal-install/src/Distribution/Client/CmdClean.hs
  cabal-install/src/Distribution/Client/CmdFreeze.hs
  cabal-install/src/Distribution/Client/CmdHaddock.hs
  cabal-install/src/Distribution/Client/CmdHaddockProject.hs
  cabal-install/src/Distribution/Client/CmdInstall.hs
  cabal-install/src/Distribution/Client/CmdInstall/ClientInstallFlags.hs
  cabal-install/src/Distribution/Client/CmdOutdated.hs
  cabal-install/src/Distribution/Client/CmdPath.hs
  cabal-install/src/Distribution/Client/CmdRepl.hs
  cabal-install/src/Distribution/Client/CmdSdist.hs
  cabal-install/src/Distribution/Client/CmdTest.hs
  cabal-install/src/Distribution/Client/Config.hs
  cabal-install/src/Distribution/Client/Get.hs
  cabal-install/src/Distribution/Client/GlobalFlags.hs
  cabal-install/src/Distribution/Client/Init/FlagExtractors.hs
  cabal-install/src/Distribution/Client/Init/Interactive/Command.hs
  cabal-install/src/Distribution/Client/Init/NonInteractive/Command.hs
  cabal-install/src/Distribution/Client/Init/Simple.hs
  cabal-install/src/Distribution/Client/Init/Types.hs
  cabal-install/src/Distribution/Client/Init/Utils.hs
  cabal-install/src/Distribution/Client/Main.hs
  cabal-install/src/Distribution/Client/ManpageFlags.hs
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
  cabal-install/src/Distribution/Client/ProjectFlags.hs
  cabal-install/src/Distribution/Client/ReplFlags.hs
  cabal-install/src/Distribution/Client/Sandbox.hs
  cabal-install/src/Distribution/Client/Sandbox/PackageEnvironment.hs
  cabal-install/src/Distribution/Client/ScriptUtils.hs
  cabal-install/src/Distribution/Client/Setup.hs
  cabal-install/src/Distribution/Client/SetupWrapper.hs
  cabal-install/src/Distribution/Client/Utils.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/UnitTests/Distribution/Client/ArbitraryInstances.hs
  cabal-install/tests/UnitTests/Distribution/Client/UserConfig.hs
  cabal-testsuite/src/Test/Cabal/Script.hs
  changelog.d/pr-10948.md
  release-notes/WIP-Cabal-3.16.x.0.md
Labels: merge me, merge delay passed, ready and waiting

#10945 cabal-install.cabal: allow hashable-1.5
  cabal-install/cabal-install.cabal
Labels: merge me, re: dependencies

#10949 If ghc-options is not passed when compiling js, Cmm or asm, that's a bug
  Cabal/src/Distribution/Simple/GHC/Internal.hs
  cabal-testsuite/PackageTests/JS/GhcOptions/cabal.project
  cabal-testsuite/PackageTests/JS/GhcOptions/demo/Main.hs
  cabal-testsuite/PackageTests/JS/GhcOptions/js-arch.test.hs
  cabal-testsuite/PackageTests/JS/GhcOptions/jsbits/lib.js
  cabal-testsuite/PackageTests/JS/GhcOptions/jsghcoptions.cabal
  cabal-testsuite/PackageTests/JS/GhcOptions/other-arch.out
  cabal-testsuite/PackageTests/JS/GhcOptions/other-arch.test.hs
  cabal-testsuite/PackageTests/JS/GhcOptions/src/Lib.hs
  changelog.d/pr-10949.md
Labels: merge me, merge delay passed, ready and waiting

#10817 Fix PATH changes not triggering REPL reconfiguration (#2015)
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/ProjectPlanning/Types.hs
  cabal-testsuite/PackageTests/PathRecomp/PathRecomp.cabal
  cabal-testsuite/PackageTests/PathRecomp/Setup.hs
  cabal-testsuite/PackageTests/PathRecomp/cabal.test.hs
  cabal-testsuite/PackageTests/PathRecomp/src/Lib.hs
  changelog.d/pr-10817
Labels: merge me, merge delay passed, ready and waiting
