Repository haskell/cabal, pull requests merged in 2025-03, with the labels that each got.

#10805 Merge 'flags' stanzas in cabal.project (fix #10767)
  cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
  cabal-install/src/Distribution/Deprecated/ParseUtils.hs
  cabal-testsuite/PackageTests/ProjectConfig/FlagsSemigroup/cabal.out
  cabal-testsuite/PackageTests/ProjectConfig/FlagsSemigroup/cabal.project
  cabal-testsuite/PackageTests/ProjectConfig/FlagsSemigroup/cabal.test.hs
  cabal-testsuite/PackageTests/ProjectConfig/FlagsSemigroup/test.cabal
  changelog.d/pr-10805.md
Labels: merge me, re: flag, merge delay passed, ready and waiting, waiting too long

#10814 Allow containers-0.8
  Cabal-hooks/Cabal-hooks.cabal
  Cabal-syntax/Cabal-syntax.cabal
  Cabal/Cabal.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
Labels: merge me, merge delay passed, ready and waiting

#10516 Delete second `checkPackageDescription` call
  Cabal/src/Distribution/PackageDescription/Check.hs
Labels: cabal-install: cmd/check, merge me, merge delay passed, ready and waiting

#10781 Make wording re manual flag more explicit
  doc/cabal-package-description-file.rst
Labels: squash+merge me, merge delay passed, ready and waiting

#10783 Concat arguments when enabling haddock
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-testsuite/PackageTests/HaddockArgsCombine/CHANGELOG.md
  cabal-testsuite/PackageTests/HaddockArgsCombine/HaddockArgsCombine.cabal
  cabal-testsuite/PackageTests/HaddockArgsCombine/app/Main.hs
  cabal-testsuite/PackageTests/HaddockArgsCombine/cabal.out
  cabal-testsuite/PackageTests/HaddockArgsCombine/cabal.test.hs
  changelog.d/pr-10783
Labels: squash+merge me, merge delay passed, ready and waiting, regression in 3.14, attention: needs-backport 3.14

#10838 Backport: Set <pkgname_datadir> to an absolute path
  Cabal/src/Distribution/Simple/Bench.hs
  Cabal/src/Distribution/Simple/Build.hs
  Cabal/src/Distribution/Simple/Haddock.hs
  Cabal/src/Distribution/Simple/Test.hs
  cabal-install/src/Distribution/Client/Run.hs
  cabal-testsuite/PackageTests/DataDirSetupTest/Setup.hs
  cabal-testsuite/PackageTests/DataDirSetupTest/cabal.cabal.out
  cabal-testsuite/PackageTests/DataDirSetupTest/cabal.out
  cabal-testsuite/PackageTests/DataDirSetupTest/cabal.test.hs
  cabal-testsuite/PackageTests/DataDirSetupTest/datadir-test.cabal
  cabal-testsuite/PackageTests/DataDirSetupTest/src/MyLib.hs
  cabal-testsuite/PackageTests/DataDirSetupTest/test/DataDirTest.hs
  cabal-testsuite/PackageTests/DataDirSetupTest/testdata/sample.txt
  changelog.d/pr-10828.md
Labels: attention: needs-review, merge me

#10827 Fix environment variable handling when running executables
  Cabal/src/Distribution/Simple/Bench.hs
  Cabal/src/Distribution/Simple/Program/Run.hs
  Cabal/src/Distribution/Simple/Test/ExeV10.hs
  Cabal/src/Distribution/Simple/Test/LibV09.hs
  cabal-install/src/Distribution/Client/Run.hs
  cabal-testsuite/PackageTests/DuplicateEnvVars/cabal.out
  cabal-testsuite/PackageTests/DuplicateEnvVars/cabal.project
  cabal-testsuite/PackageTests/DuplicateEnvVars/cabal.test.hs
  cabal-testsuite/PackageTests/DuplicateEnvVars/p/Main.hs
  cabal-testsuite/PackageTests/DuplicateEnvVars/p/p.cabal
  changelog.d/pr-10827.md
Labels: attention: needs-review, merge me, merge delay passed, ready and waiting, regression in 3.14

#10822 Fix #10821 Clear 'to do' in format specification history
  doc/file-format-changelog.rst
Labels: attention: needs-review, merge me, merge delay passed, ready and waiting

#10823 Fix #10773 Document new `build-type: Hooks` in format specification history
  doc/file-format-changelog.rst
Labels: attention: needs-review, merge me, merge delay passed, ready and waiting

#10842 Fix typo: looses -> loses
  doc/setup-commands.rst
Labels: merge me, merge delay passed, ready and waiting

#10824 Fix #10819 Document that executables etc can depend on library in same package
  doc/cabal-package-description-file.rst
Labels: attention: needs-review, merge me, merge delay passed, ready and waiting

#10730 Create `noindex.cache` if missing
  cabal-install/src/Distribution/Client/IndexUtils.hs
  changelog.d/pr-10730
Labels: merge me, merge delay passed, ready and waiting, attention: needs-backport 3.14

#10828 Cabal: Always pass -package-env=- to supported GHC versions
  Cabal/src/Distribution/Simple/Program/Builtin.hs
  cabal-install/src/Distribution/Client/CmdExec.hs
  cabal-install/src/Distribution/Client/ProjectPlanOutput.hs
  cabal-testsuite/PackageTests/EnvironmentFile/CHANGELOG.md
  cabal-testsuite/PackageTests/EnvironmentFile/EnvironmentFile.cabal
  cabal-testsuite/PackageTests/EnvironmentFile/app/Main.hs
  cabal-testsuite/PackageTests/EnvironmentFile/cabal.test.hs
  cabal-testsuite/PackageTests/EnvironmentFile/ghc.environment
  changelog.d/pr-10828.md
Labels: attention: needs-review, merge me, merge delay passed, ready and waiting, regression in 3.14, don't backport

#10820 Re #10819 Take format specification history back to version 1.8
  doc/cabal-package-description-file.rst
  doc/file-format-changelog.rst
Labels: merge me, merge delay passed, ready and waiting

#10869 remove the *-skip workflows (fix #10868)
  .github/workflows/bootstrap.skip.yml
  .github/workflows/bootstrap.yml
  .github/workflows/check-sdist.skip.yml
  .github/workflows/check-sdist.yml
  .github/workflows/validate.skip.yml
  .github/workflows/validate.yml
Labels: priority: high :fire:, continuous-integration, merge me, merge delay passed, ready and waiting, attention: needs-backport 3.14

#10882 Cabal API change in 3.14 requires a lower bound bump in cabal-install
  Cabal/Cabal.cabal
  cabal-install/cabal-install.cabal
Labels: merge me

#10843 Use a newer ci-images for centos7
  .gitlab-ci.yml
  .gitlab/ci.sh
Labels: release, merge me, merge delay passed, ready and waiting, attention: needs-backport 3.14

#10841 Fix multi-repl when only building some internal library targets
  Cabal/src/Distribution/Backpack/Configure.hs
  cabal-testsuite/PackageTests/MultiRepl/InternalLibs/cabal.out
  cabal-testsuite/PackageTests/MultiRepl/InternalLibs/cabal.project
  cabal-testsuite/PackageTests/MultiRepl/InternalLibs/cabal.test.hs
  cabal-testsuite/PackageTests/MultiRepl/InternalLibs/components/x/X.hs
  cabal-testsuite/PackageTests/MultiRepl/InternalLibs/components/y/Y.hs
  cabal-testsuite/PackageTests/MultiRepl/InternalLibs/components/z/Z.hs
  cabal-testsuite/PackageTests/MultiRepl/InternalLibs/foo.cabal
  changelog.d/pr-10841.md
Labels: attention: needs-review, merge me, merge delay passed, ready and waiting, attention: needs-backport 3.14

#10861 Document deprecation of hugs- nhc98- jhc-options fields in format history
  doc/file-format-changelog.rst
Labels: merge me, merge delay passed, ready and waiting
