Repository haskell/cabal, pull requests merged in 2025-01, with the labels that each got.

#10647 Improve "Cannot read .cabal file inside ..." errors
  cabal-install/src/Distribution/Client/Errors.hs
  cabal-install/src/Distribution/Client/IndexUtils.hs
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/pkg/pkg.cabal
  cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/repo/setup-dep-1.0/setup-dep.cabal
  cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/setup-dep/setup-dep.cabal
  cabal-testsuite/PackageTests/IndexCabalFileParseError/cabal.out
  cabal-testsuite/PackageTests/IndexCabalFileParseError/cabal.test.hs
  cabal-testsuite/PackageTests/IndexCabalFileParseError/repo/my-lib-1.0/my-lib.cabal
  cabal-testsuite/PackageTests/NewBuild/CmdRun/Script/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptBad/cabal.out
  cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptLiterate/cabal.out
  cabal-testsuite/PackageTests/NewConfigure/ConfigFile/cabal.out
  cabal-testsuite/PackageTests/NewFreeze/BuildTools/new_freeze.out
  cabal-testsuite/PackageTests/Regression/T7234/Fail/cabal.out
  cabal-testsuite/PackageTests/Regression/T7234/Success/cabal.out
  cabal-testsuite/PackageTests/Regression/T9640/cabal.out
  cabal-testsuite/src/Test/Cabal/OutputNormalizer.hs
  cabal-testsuite/src/Test/Cabal/Prelude.hs
  changelog.d/pr-10647
Labels: merge me, merge delay passed, ready and waiting

#10699 Move cabal path to project configuration group
  doc/cabal-commands.rst
Labels: merge delay passed, merge+no rebase, ready and waiting

#10554 Additional version bound checks
  Cabal-syntax/src/Distribution/Types/VersionRange.hs
  Cabal-syntax/src/Distribution/Types/VersionRange/Internal.hs
  Cabal-syntax/src/Distribution/Version.hs
  Cabal-tests/tests/ParserTests/regressions/issue-8646.cabal
  Cabal/src/Distribution/PackageDescription/Check.hs
  Cabal/src/Distribution/PackageDescription/Check/Common.hs
  Cabal/src/Distribution/PackageDescription/Check/Target.hs
  Cabal/src/Distribution/PackageDescription/Check/Warning.hs
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Fields/ImpossibleVersionRangeLib/cabal.out
  cabal-testsuite/PackageTests/Check/ConfiguredPackage/Fields/ImpossibleVersionRangeLib/pkg.cabal
  cabal-testsuite/PackageTests/Check/DepVersionRange/BaseDep/cabal.out
  cabal-testsuite/PackageTests/Check/DepVersionRange/BaseDep/cabal.test.hs
  cabal-testsuite/PackageTests/Check/DepVersionRange/BaseDep/pkg.cabal
  cabal-testsuite/PackageTests/Check/DepVersionRange/CustomSetupBaseDep/Setup.hs
  cabal-testsuite/PackageTests/Check/DepVersionRange/CustomSetupBaseDep/cabal.out
  cabal-testsuite/PackageTests/Check/DepVersionRange/CustomSetupBaseDep/cabal.test.hs
  cabal-testsuite/PackageTests/Check/DepVersionRange/CustomSetupBaseDep/pkg.cabal
  cabal-testsuite/PackageTests/Check/DepVersionRange/InternalLibDep/cabal.out
  cabal-testsuite/PackageTests/Check/DepVersionRange/InternalLibDep/cabal.test.hs
  cabal-testsuite/PackageTests/Check/DepVersionRange/InternalLibDep/pkg.cabal
  cabal-testsuite/PackageTests/Check/DepVersionRange/UnboundedInternalDep/cabal.out
  cabal-testsuite/PackageTests/Check/DepVersionRange/UnboundedInternalDep/cabal.test.hs
  cabal-testsuite/PackageTests/Check/DepVersionRange/UnboundedInternalDep/pkg.cabal
  cabal-testsuite/PackageTests/Check/DepVersionRange/VersionConstraintOperators/cabal.out
  cabal-testsuite/PackageTests/Check/DepVersionRange/VersionConstraintOperators/cabal.test.hs
  cabal-testsuite/PackageTests/Check/DepVersionRange/VersionConstraintOperators/pkg.cabal
  cabal-testsuite/PackageTests/Check/NonConfCheck/PackageVersionsInternal/pkg.cabal
  cabal-testsuite/PackageTests/Check/NonConfCheck/PackageVersionsStraddle/pkg.cabal
  changelog.d/pr-10554
  doc/cabal-commands.rst
Labels: merge delay passed, merge+no rebase, ready and waiting

#10646 Deduplicate path separator duplicates
  CONTRIBUTING.md
  cabal-install-solver/src/Distribution/Solver/Types/ProjectConfigPath.hs
  cabal-testsuite/PackageTests/BuildDeps/InternalLibrary2/setup.test.hs
  cabal-testsuite/PackageTests/BuildDeps/InternalLibrary3/setup.test.hs
  cabal-testsuite/PackageTests/CheckSetup/setup.test.hs
  cabal-testsuite/PackageTests/ConditionalAndImport/cabal-missing-package.expect.txt
  cabal-testsuite/PackageTests/ConditionalAndImport/cabal.test.hs
  cabal-testsuite/PackageTests/ConditionalAndImport/hops.expect.txt
  cabal-testsuite/PackageTests/ConditionalAndImport/oops.expect.txt
  cabal-testsuite/PackageTests/NewBuild/T4288/cabal.test.hs
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/cabal.out
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/cabal.test.hs
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/errors.expect.txt
  cabal-testsuite/PackageTests/ProjectImport/ParseErrorProvenance/cabal.out
  cabal-testsuite/PackageTests/ProjectImport/ParseErrorProvenance/cabal.test.hs
  cabal-testsuite/PackageTests/ProjectImport/ParseErrorProvenance/dir-else/else.config
  cabal-testsuite/PackageTests/ProjectImport/ParseErrorProvenance/else.project
  cabal-testsuite/PackageTests/ProjectImport/ParseErrorProvenance/msg.expect.txt
  cabal-testsuite/PackageTests/Regression/T5409/use-different-versions-of-dependency-for-library-and-build-tool.test.hs
  cabal-testsuite/README.md
  cabal-testsuite/cabal-testsuite.cabal
  cabal-testsuite/src/Test/Cabal/NeedleHaystack.hs
  cabal-testsuite/src/Test/Cabal/Prelude.hs
  changelog.d/pr-10646.md
Labels: cabal-testsuite, merge delay passed, merge+no rebase, ready and waiting

#10716 Capitalize Cabal-hooks readme and changelog
  Cabal-hooks/CHANGELOG.md
  Cabal-hooks/README.md
Labels: merge me, merge delay passed, ready and waiting

#10710 Add since annotation for MHS
  Cabal-syntax/src/Distribution/Compiler.hs
Labels: merge me, merge delay passed, ready and waiting

#10719 Follow HLint suggestion: use fewer imports
  .hlint.yaml
  Cabal/src/Distribution/Compat/Internal/TempFile.hs
  Cabal/src/Distribution/Compat/Time.hs
  Cabal/src/Distribution/Simple/GHC.hs
  cabal-install/src/Distribution/Client/CmdTest.hs
  cabal-install/src/Distribution/Client/Config.hs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-install/src/Distribution/Client/SetupWrapper.hs
  cabal-install/src/Distribution/Client/Store.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-testsuite/src/Test/Cabal/Monad.hs
  cabal-testsuite/src/Test/Cabal/NeedleHaystack.hs
Labels: merge delay passed, merge+no rebase, ready and waiting

#10734 Ignore haddocks
  .gitignore
Labels: merge delay passed, merge+no rebase, ready and waiting

#9997 Suppress ghc-pkg warnings emitted when an empty packages is being registered
  Cabal/src/Distribution/Simple/Register.hs
  cabal-testsuite/PackageTests/HaddockEmptyLib/empty/empty.cabal
  cabal-testsuite/PackageTests/HaddockEmptyLib/setup.cabal.out
  cabal-testsuite/PackageTests/HaddockEmptyLib/setup.out
  cabal-testsuite/PackageTests/HaddockEmptyLib/setup.test.hs
  changelog.d/pr-9997
Labels: type: enhancement, Cabal: cmd/register, merge me, merge delay passed, ready and waiting, attention: needs-backport 3.14

#10725 Cabal: Honour -working-dir flag when running test executables
  Cabal/src/Distribution/Simple/Test/ExeV10.hs
  cabal-testsuite/PackageTests/TestChangeDir/cabal.project
  cabal-testsuite/PackageTests/TestChangeDir/cabal.test.hs
  cabal-testsuite/PackageTests/TestChangeDir/regression-simple/CHANGELOG.md
  cabal-testsuite/PackageTests/TestChangeDir/regression-simple/bench/Main.hs
  cabal-testsuite/PackageTests/TestChangeDir/regression-simple/do-i-exist.txt
  cabal-testsuite/PackageTests/TestChangeDir/regression-simple/regression-simple.cabal
  cabal-testsuite/PackageTests/TestChangeDir/regression-simple/test/Main.hs
  changelog.d/pr-10725
Labels: merge me, merge delay passed, ready and waiting, attention: needs-backport 3.14

#10728 Fix file+noindex URI usage on Windows
  Cabal-syntax/src/Distribution/Utils/Path.hs
  Makefile
  cabal-install/src/Distribution/Client/Config.hs
  cabal-install/src/Distribution/Client/GlobalFlags.hs
  cabal-install/src/Distribution/Client/IndexUtils.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
  cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
  cabal-testsuite/src/Test/Cabal/OutputNormalizer.hs
  cabal-testsuite/src/Test/Cabal/Prelude.hs
  changelog.d/pr-10728
  doc/config.rst
Labels: merge me, merge delay passed, ready and waiting, attention: needs-backport 3.14

#10705 Add support for Windows Aarch64
  Cabal/src/Distribution/Compat/Environment.hs
  Cabal/src/Distribution/Simple/Build/PathsModule.hs
  Cabal/src/Distribution/Simple/Build/PathsModule/Z.hs
  cabal-dev-scripts/src/GenPathsModule.hs
  cabal-install/src/Distribution/Client/Compat/ExecutablePath.hs
  changelog.d/pr-10705
  templates/Paths_pkg.template.hs
Labels: platform: windows, merge me, merge delay passed, ready and waiting

#10729 cabal-install.cabal: bump upper bound for random
  cabal-install/cabal-install.cabal
Labels: merge me, merge delay passed, ready and waiting, attention: needs-backport 3.14

#9508 Fix #9507 Describe accurately acceptable package names
  .typos.toml
  Cabal-described/src/Distribution/Described.hs
  Cabal-described/src/Distribution/Utils/CharSet.hs
  Cabal-described/src/Distribution/Utils/GrammarRegex.hs
  buildinfo-reference-generator/src/Main.hs
  buildinfo-reference-generator/template.zinza
  doc/buildinfo-fields-reference.rst
  doc/cabal-package-description-file.rst
  doc/package-concepts.rst
Labels: documentation, merge me, merge delay passed, ready and waiting

#9744 Add a cabal target command
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/CmdTarget.hs
  cabal-install/src/Distribution/Client/Main.hs
  cabal-install/src/Distribution/Client/ProjectOrchestration.hs
  cabal-install/src/Distribution/Client/Setup.hs
  cabal-testsuite/PackageTests/Target/cabal.all-benches.out
  cabal-testsuite/PackageTests/Target/cabal.all-enable-benches.out
  cabal-testsuite/PackageTests/Target/cabal.all-enable-tests.out
  cabal-testsuite/PackageTests/Target/cabal.all-exes.out
  cabal-testsuite/PackageTests/Target/cabal.all-tests.out
  cabal-testsuite/PackageTests/Target/cabal.component-target-bench.out
  cabal-testsuite/PackageTests/Target/cabal.component-target-exe.out
  cabal-testsuite/PackageTests/Target/cabal.component-target-lib.out
  cabal-testsuite/PackageTests/Target/cabal.component-target-test.out
  cabal-testsuite/PackageTests/Target/cabal.ctype-target.out
  cabal-testsuite/PackageTests/Target/cabal.default-all.out
  cabal-testsuite/PackageTests/Target/cabal.everything.out
  cabal-testsuite/PackageTests/Target/cabal.explicit-all.out
  cabal-testsuite/PackageTests/Target/cabal.missing-target.out
  cabal-testsuite/PackageTests/Target/cabal.package-target.out
  cabal-testsuite/PackageTests/Target/cabal.path-target.out
  cabal-testsuite/PackageTests/Target/cabal.project
  cabal-testsuite/PackageTests/Target/cabal.test.hs
  cabal-testsuite/PackageTests/Target/dir-a/a.cabal
  cabal-testsuite/PackageTests/Target/dir-b/b.cabal
  cabal-testsuite/PackageTests/Target/dir-c/c.cabal
  changelog.d/pr-9744.md
  doc/cabal-commands.rst
Labels: merge delay passed, merge+no rebase, ready and waiting

#10714 make formatting of `build-depends` consistent
  .git-blame-ignore-revs
  Cabal-hooks/Cabal-hooks.cabal
  Cabal-syntax/Cabal-syntax.cabal
  Cabal-tests/Cabal-tests.cabal
  Cabal/Cabal.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install/cabal-install.cabal
  solver-benchmarks/solver-benchmarks.cabal
Labels: merge delay passed, ready and waiting

#10287 Only munge internal dependencies when printing when there is no explicit syntax
  Cabal-syntax/src/Distribution/PackageDescription/PrettyPrint.hs
  Cabal-tests/tests/ParserTests/regressions/issue-6083-b.format
  cabal-validate/src/Main.hs
Labels: merge me, merge delay passed, ready and waiting

#10683 Add `make style-todo` and fourmolu on off comments
  Cabal-described/src/Distribution/Utils/CharSet.hs
  Cabal-tests/tests/HackageTests.hs
  Cabal-tests/tests/ParserTests.hs
  Cabal-tests/tests/custom-setup/CabalDoctestSetup.hs
  Cabal-tests/tests/custom-setup/IdrisSetup.hs
  Makefile
  cabal-install-solver/src/Distribution/Solver/Modular/Solver.hs
  cabal-testsuite/src/Test/Cabal/Server.hs
Labels: merge delay passed, merge+no rebase, ready and waiting, re: code formatting

#10709 cabal-install 3.14.1.1 release notes
  release-notes/cabal-install-3.14.1.1.md
Labels: priority: high :fire:, merge me, merge delay passed, ready and waiting, attention: needs-backport 3.14

#10644 Add source file to project parse errors and warnings
  cabal-install/cabal-install.cabal
  cabal-install/src/Distribution/Client/Errors.hs
  cabal-install/src/Distribution/Client/ProjectConfig.hs
  cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
  cabal-install/src/Distribution/Deprecated/ProjectParseUtils.hs
  cabal-testsuite/PackageTests/ConditionalAndImport/cabal.out
  cabal-testsuite/PackageTests/ProjectConfig/FieldStanzaConfusion/cabal.out
  cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromSimple/z-empty.config
  cabal-testsuite/PackageTests/ProjectImport/ParseErrorProvenance/cabal.out
  cabal-testsuite/PackageTests/ProjectImport/ParseErrorProvenance/cabal.project
  cabal-testsuite/PackageTests/ProjectImport/ParseErrorProvenance/cabal.test.hs
  cabal-testsuite/PackageTests/ProjectImport/ParseErrorProvenance/dir-elif/elif.config
  cabal-testsuite/PackageTests/ProjectImport/ParseErrorProvenance/dir-if/if.config
  cabal-testsuite/PackageTests/ProjectImport/ParseErrorProvenance/elif.project
  cabal-testsuite/PackageTests/ProjectImport/ParseErrorProvenance/if.project
  cabal-testsuite/PackageTests/ProjectImport/ParseErrorProvenance/with-ghc.config
  cabal-testsuite/PackageTests/ProjectImport/ParseWarningProvenance/cabal.out
  cabal-testsuite/PackageTests/ProjectImport/ParseWarningProvenance/cabal.project
  cabal-testsuite/PackageTests/ProjectImport/ParseWarningProvenance/cabal.test.hs
  cabal-testsuite/PackageTests/ProjectImport/ParseWarningProvenance/dir-x/a.config
  cabal-testsuite/PackageTests/ProjectImport/ParseWarningProvenance/dir-y/a.config
  cabal-testsuite/PackageTests/ProjectImport/ParseWarningProvenance/with-ghc.config
  cabal-testsuite/PackageTests/ProjectImport/ParseWarningProvenance/x.config
  cabal-testsuite/PackageTests/ProjectImport/ParseWarningProvenance/y.config
  cabal-testsuite/src/Test/Cabal/Prelude.hs
  changelog.d/pr-10644.md
Labels: merge delay passed, merge+no rebase, ready and waiting

#10731 cabal-install: Be less eager to configure external programs
  cabal-install/src/Distribution/Client/ProjectPlanning.hs
  cabal-testsuite/PackageTests/BuildToolDependsExternal/cabal.project
  cabal-testsuite/PackageTests/BuildToolDependsExternal/client/Hello.x
  cabal-testsuite/PackageTests/BuildToolDependsExternal/client/client.cabal
  cabal-testsuite/PackageTests/BuildToolDependsExternal/pre-proc/MyCustomPreprocessor.hs
  cabal-testsuite/PackageTests/BuildToolDependsExternal/pre-proc/pre-proc.cabal
  cabal-testsuite/PackageTests/BuildToolDependsExternal/scripts/alex
  cabal-testsuite/PackageTests/BuildToolDependsExternal/setup.out
  cabal-testsuite/PackageTests/BuildToolDependsExternal/setup.test.hs
  cabal-testsuite/PackageTests/ExtraProgPath/setup.out
  cabal-testsuite/PackageTests/ExtraProgPathLocal/cabal.project
  cabal-testsuite/PackageTests/ExtraProgPathLocal/client/Hello.x
  cabal-testsuite/PackageTests/ExtraProgPathLocal/client/client.cabal
  cabal-testsuite/PackageTests/ExtraProgPathLocal/scripts/alex
  cabal-testsuite/PackageTests/ExtraProgPathLocal/scripts/alex.exe
  cabal-testsuite/PackageTests/ExtraProgPathLocal/scripts/alex.shim
  cabal-testsuite/PackageTests/ExtraProgPathLocal/scripts2/alex
  cabal-testsuite/PackageTests/ExtraProgPathLocal/scripts2/alex.exe
  cabal-testsuite/PackageTests/ExtraProgPathLocal/scripts2/alex.shim
  cabal-testsuite/PackageTests/ExtraProgPathLocal/setup.out
  cabal-testsuite/PackageTests/ExtraProgPathLocal/setup.test.hs
  changelog.d/pr-10731
Labels: attention: needs-review, merge me, merge delay passed, ready and waiting

#10743 Use newer warning flags
  Cabal-QuickCheck/src/Test/QuickCheck/Instances/Cabal.hs
  Cabal-hooks/Cabal-hooks.cabal
  Cabal-syntax/Cabal-syntax.cabal
  Cabal-syntax/src/Distribution/PackageDescription/Configuration.hs
  Cabal-tests/tests/HackageTests.hs
  Cabal-tests/tests/Test/Laws.hs
  Cabal-tests/tests/UnitTests/Distribution/CabalSpecVersion.hs
  Cabal-tests/tests/UnitTests/Distribution/Compat/Graph.hs
  Cabal-tests/tests/UnitTests/Distribution/Described.hs
  Cabal-tests/tests/UnitTests/Distribution/SPDX.hs
  Cabal-tests/tests/UnitTests/Distribution/System.hs
  Cabal-tests/tests/UnitTests/Distribution/Types/GenericPackageDescription.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/Generic.hs
  Cabal-tests/tests/UnitTests/Distribution/Utils/NubList.hs
  Cabal-tests/tests/UnitTests/Distribution/Version.hs
  Cabal-tree-diff/src/Data/TreeDiff/Instances/Cabal.hs
  Cabal-tree-diff/src/Data/TreeDiff/Instances/CabalLanguage.hs
  Cabal-tree-diff/src/Data/TreeDiff/Instances/CabalSPDX.hs
  Cabal-tree-diff/src/Data/TreeDiff/Instances/CabalVersion.hs
  Cabal/Cabal.cabal
  Cabal/src/Distribution/Compat/FilePath.hs
  Cabal/src/Distribution/Simple.hs
  Cabal/src/Distribution/Simple/Build/PackageInfoModule/Z.hs
  Cabal/src/Distribution/Simple/Build/PathsModule/Z.hs
  Cabal/src/Distribution/Simple/ConfigureScript.hs
  cabal-benchmarks/bench/CabalBenchmarks.hs
  cabal-benchmarks/cabal-benchmarks.cabal
  cabal-install-solver/cabal-install-solver.cabal
  cabal-install-solver/src/Distribution/Solver/Compat/Prelude.hs
  cabal-install-solver/src/Distribution/Solver/Modular/Linking.hs
  cabal-install-solver/src/Distribution/Solver/Modular/Solver.hs
  cabal-install/src/Distribution/Client/BuildReports/Storage.hs
  cabal-install/src/Distribution/Client/Compat/Orphans.hs
  cabal-install/src/Distribution/Client/Compat/Prelude.hs
  cabal-install/src/Distribution/Client/Compat/Tar.hs
  cabal-install/src/Distribution/Client/Errors.hs
  cabal-install/src/Distribution/Client/FileMonitor.hs
  cabal-install/src/Distribution/Client/Tar.hs
  cabal-install/src/Distribution/Client/TargetSelector.hs
  cabal-install/tests/IntegrationTests2.hs
  cabal-install/tests/UnitTests/Distribution/Client/ArbitraryInstances.hs
  cabal-install/tests/UnitTests/Distribution/Client/DescribedInstances.hs
  cabal-install/tests/UnitTests/Distribution/Client/Glob.hs
  cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
  cabal-install/tests/UnitTests/Distribution/Client/TreeDiffInstances.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck.hs
  cabal-install/tests/UnitTests/Distribution/Solver/Modular/RetryLog.hs
  cabal-testsuite/cabal-testsuite.cabal
  cabal-testsuite/src/Test/Cabal/Plan.hs
  solver-benchmarks/solver-benchmarks.cabal
  templates/Paths_pkg.template.hs
Labels: merge delay passed, merge+no rebase, ready and waiting

#10756 ci: properly update metadata on nigthly releases
  .github/workflows/validate.yml
Labels: merge me, merge delay passed, ready and waiting
